-- Mada Trips app (Core API) tables. Generated by drizzle-kit from src/db/app-schema.ts.
-- drizzle-kit also emitted Ops statements already applied by hand-written migrations 0007-0014 (their snapshots were
-- never generated); those were removed here. meta/0015_snapshot.json is the full, current snapshot of both schemas.
CREATE TABLE "app_audit" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"actor_kind" text NOT NULL,
	"actor_id" text,
	"action" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" text,
	"summary" text NOT NULL,
	"data" jsonb,
	"ip_hash" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_circle_members" (
	"circle_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"role" text DEFAULT 'member' NOT NULL,
	"share_due" bigint DEFAULT 0 NOT NULL,
	"muted" boolean DEFAULT false NOT NULL,
	"last_read_at" timestamp with time zone,
	"joined_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "app_circle_members_circle_id_user_id_pk" PRIMARY KEY("circle_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "app_circles" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"image_url" text,
	"trip_id" uuid,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_credit_ledger" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"amount" bigint NOT NULL,
	"kind" text NOT NULL,
	"note" text,
	"refund_id" uuid,
	"payment_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_devices" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"session_id" uuid,
	"platform" text NOT NULL,
	"name" text,
	"push_token" text,
	"app_version" text,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"disabled_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_invoices" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"owner_id" uuid NOT NULL,
	"number" text NOT NULL,
	"trip_id" uuid,
	"payment_id" uuid,
	"total" bigint NOT NULL,
	"vat" bigint NOT NULL,
	"issued_at" timestamp with time zone DEFAULT now() NOT NULL,
	"zatca_status" text DEFAULT 'pending' NOT NULL,
	"pdf_path" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_messages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"thread_kind" text NOT NULL,
	"thread_id" uuid NOT NULL,
	"author_kind" text NOT NULL,
	"author_user_id" uuid,
	"author_ops_user_id" uuid,
	"author_name" text,
	"body" text NOT NULL,
	"card" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_notifications" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"kind" text NOT NULL,
	"level" text NOT NULL,
	"title" text NOT NULL,
	"body" text NOT NULL,
	"href" text,
	"data" jsonb,
	"pushed_at" timestamp with time zone,
	"read_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_otp" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"phone" text NOT NULL,
	"code_hash" text NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"consumed_at" timestamp with time zone,
	"ip_hash" text,
	"channel" text DEFAULT 'sms' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_payments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"owner_id" uuid NOT NULL,
	"request_id" uuid,
	"quote_id" uuid,
	"method" text NOT NULL,
	"status" text DEFAULT 'initiated' NOT NULL,
	"amount" bigint NOT NULL,
	"label" text,
	"instalments" integer DEFAULT 1 NOT NULL,
	"provider" text NOT NULL,
	"provider_ref" text,
	"idempotency_key" text NOT NULL,
	"ops_payment_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_people" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"owner_id" uuid NOT NULL,
	"is_self" boolean DEFAULT false NOT NULL,
	"given_names" text DEFAULT '' NOT NULL,
	"surname" text DEFAULT '' NOT NULL,
	"relation" text NOT NULL,
	"date_of_birth" date,
	"sex" text,
	"nationality" text,
	"passport_number_enc" text,
	"passport_number_masked" text,
	"passport_issuing_country" text,
	"passport_nationality" text,
	"passport_expiry" date,
	"passport_source" text,
	"passport_updated_at" timestamp with time zone,
	"deleted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_pickups" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"trip_id" uuid NOT NULL,
	"direction" text NOT NULL,
	"at" timestamp with time zone NOT NULL,
	"driver_name" text,
	"car" text,
	"plate" text,
	"meeting_point" text,
	"phone" text,
	"price" bigint DEFAULT 0 NOT NULL,
	"status" text DEFAULT 'held' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_quotes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"request_id" uuid NOT NULL,
	"lines" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"total" bigint NOT NULL,
	"cancellation" text,
	"expires_at" timestamp with time zone,
	"status" text DEFAULT 'open' NOT NULL,
	"offer_snapshot" jsonb,
	"created_by_ops_user_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_refunds" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"payment_id" uuid NOT NULL,
	"amount" bigint NOT NULL,
	"stage" text DEFAULT 'requested' NOT NULL,
	"destination" text DEFAULT 'original' NOT NULL,
	"reason" text,
	"expected_by" timestamp with time zone,
	"provider_ref" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_requests" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"owner_id" uuid NOT NULL,
	"kind" text NOT NULL,
	"status" text DEFAULT 'sent' NOT NULL,
	"summary" text NOT NULL,
	"traveller_ids" uuid[] DEFAULT '{}'::uuid[] NOT NULL,
	"trip_id" uuid,
	"agent_ops_user_id" uuid,
	"agent_name" text,
	"promised_by" timestamp with time zone,
	"details" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"ops_booking_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_segments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"trip_id" uuid NOT NULL,
	"direction" text NOT NULL,
	"sort" integer DEFAULT 0 NOT NULL,
	"carrier" text NOT NULL,
	"carrier_name" text NOT NULL,
	"flight_number" text NOT NULL,
	"from_airport" text NOT NULL,
	"to_airport" text NOT NULL,
	"depart_local" timestamp NOT NULL,
	"depart_tz" text NOT NULL,
	"arrive_local" timestamp NOT NULL,
	"arrive_tz" text NOT NULL,
	"duration_min" integer NOT NULL,
	"cabin" text DEFAULT 'economy' NOT NULL,
	"terminal" text,
	"gate" text,
	"seats" text[] DEFAULT '{}'::text[] NOT NULL,
	"baggage" text,
	"status" text DEFAULT 'scheduled' NOT NULL,
	"status_source" text,
	"pnr" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"refresh_hash" text NOT NULL,
	"previous_hash" text,
	"platform" text,
	"device_name" text,
	"app_version" text,
	"ip" text,
	"user_agent" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_used_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"revoked_at" timestamp with time zone,
	"revoked_reason" text
);
--> statement-breakpoint
CREATE TABLE "app_stays" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"trip_id" uuid NOT NULL,
	"name" text NOT NULL,
	"area" text,
	"address" text,
	"check_in" date NOT NULL,
	"nights" integer NOT NULL,
	"rooms" integer DEFAULT 1 NOT NULL,
	"price" bigint NOT NULL,
	"cancellation" text,
	"status" text DEFAULT 'held' NOT NULL,
	"confirmation" text,
	"supplier" text,
	"supplier_ref" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_tracked_flights" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"flight_number" text NOT NULL,
	"date" date NOT NULL,
	"carrier_name" text,
	"from_airport" text,
	"to_airport" text,
	"depart_local" timestamp,
	"arrive_local" timestamp,
	"status" text DEFAULT 'scheduled' NOT NULL,
	"gate" text,
	"terminal" text,
	"source" text,
	"provider_ref" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_trips" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"owner_id" uuid NOT NULL,
	"city" text NOT NULL,
	"country" text,
	"image_url" text,
	"start_date" date NOT NULL,
	"end_date" date,
	"traveller_ids" uuid[] DEFAULT '{}'::uuid[] NOT NULL,
	"status" text DEFAULT 'planning' NOT NULL,
	"booking_ref" text,
	"confirmed_by_name" text,
	"confirmed_by_ops_user_id" uuid,
	"ops_booking_id" uuid,
	"imported" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"phone" text,
	"name" text DEFAULT '' NOT NULL,
	"email" text,
	"email_relay" boolean DEFAULT false NOT NULL,
	"apple_sub" text,
	"google_sub" text,
	"locale" text DEFAULT 'en' NOT NULL,
	"alerts" text DEFAULT 'quiet' NOT NULL,
	"notifications" text DEFAULT 'unknown' NOT NULL,
	"onboarded_at" timestamp with time zone,
	"ops_client_id" uuid,
	"deleted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app_circle_members" ADD CONSTRAINT "app_circle_members_circle_id_app_circles_id_fk" FOREIGN KEY ("circle_id") REFERENCES "public"."app_circles"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_circle_members" ADD CONSTRAINT "app_circle_members_user_id_app_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_circles" ADD CONSTRAINT "app_circles_trip_id_app_trips_id_fk" FOREIGN KEY ("trip_id") REFERENCES "public"."app_trips"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_circles" ADD CONSTRAINT "app_circles_created_by_app_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."app_users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_credit_ledger" ADD CONSTRAINT "app_credit_ledger_user_id_app_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_users"("id") ON DELETE restrict ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_credit_ledger" ADD CONSTRAINT "app_credit_ledger_refund_id_app_refunds_id_fk" FOREIGN KEY ("refund_id") REFERENCES "public"."app_refunds"("id") ON DELETE restrict ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_credit_ledger" ADD CONSTRAINT "app_credit_ledger_payment_id_app_payments_id_fk" FOREIGN KEY ("payment_id") REFERENCES "public"."app_payments"("id") ON DELETE restrict ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_devices" ADD CONSTRAINT "app_devices_user_id_app_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_devices" ADD CONSTRAINT "app_devices_session_id_app_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."app_sessions"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_invoices" ADD CONSTRAINT "app_invoices_owner_id_app_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."app_users"("id") ON DELETE restrict ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_invoices" ADD CONSTRAINT "app_invoices_trip_id_app_trips_id_fk" FOREIGN KEY ("trip_id") REFERENCES "public"."app_trips"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_invoices" ADD CONSTRAINT "app_invoices_payment_id_app_payments_id_fk" FOREIGN KEY ("payment_id") REFERENCES "public"."app_payments"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_messages" ADD CONSTRAINT "app_messages_author_user_id_app_users_id_fk" FOREIGN KEY ("author_user_id") REFERENCES "public"."app_users"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_messages" ADD CONSTRAINT "app_messages_author_ops_user_id_users_id_fk" FOREIGN KEY ("author_ops_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_notifications" ADD CONSTRAINT "app_notifications_user_id_app_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_payments" ADD CONSTRAINT "app_payments_owner_id_app_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."app_users"("id") ON DELETE restrict ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_payments" ADD CONSTRAINT "app_payments_request_id_app_requests_id_fk" FOREIGN KEY ("request_id") REFERENCES "public"."app_requests"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_payments" ADD CONSTRAINT "app_payments_quote_id_app_quotes_id_fk" FOREIGN KEY ("quote_id") REFERENCES "public"."app_quotes"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_payments" ADD CONSTRAINT "app_payments_ops_payment_id_payments_id_fk" FOREIGN KEY ("ops_payment_id") REFERENCES "public"."payments"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_people" ADD CONSTRAINT "app_people_owner_id_app_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."app_users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_pickups" ADD CONSTRAINT "app_pickups_trip_id_app_trips_id_fk" FOREIGN KEY ("trip_id") REFERENCES "public"."app_trips"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_quotes" ADD CONSTRAINT "app_quotes_request_id_app_requests_id_fk" FOREIGN KEY ("request_id") REFERENCES "public"."app_requests"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_quotes" ADD CONSTRAINT "app_quotes_created_by_ops_user_id_users_id_fk" FOREIGN KEY ("created_by_ops_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_refunds" ADD CONSTRAINT "app_refunds_payment_id_app_payments_id_fk" FOREIGN KEY ("payment_id") REFERENCES "public"."app_payments"("id") ON DELETE restrict ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_requests" ADD CONSTRAINT "app_requests_owner_id_app_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."app_users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_requests" ADD CONSTRAINT "app_requests_trip_id_app_trips_id_fk" FOREIGN KEY ("trip_id") REFERENCES "public"."app_trips"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_requests" ADD CONSTRAINT "app_requests_agent_ops_user_id_users_id_fk" FOREIGN KEY ("agent_ops_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_requests" ADD CONSTRAINT "app_requests_ops_booking_id_bookings_id_fk" FOREIGN KEY ("ops_booking_id") REFERENCES "public"."bookings"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_segments" ADD CONSTRAINT "app_segments_trip_id_app_trips_id_fk" FOREIGN KEY ("trip_id") REFERENCES "public"."app_trips"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_sessions" ADD CONSTRAINT "app_sessions_user_id_app_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_stays" ADD CONSTRAINT "app_stays_trip_id_app_trips_id_fk" FOREIGN KEY ("trip_id") REFERENCES "public"."app_trips"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_tracked_flights" ADD CONSTRAINT "app_tracked_flights_user_id_app_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_trips" ADD CONSTRAINT "app_trips_owner_id_app_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."app_users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_trips" ADD CONSTRAINT "app_trips_confirmed_by_ops_user_id_users_id_fk" FOREIGN KEY ("confirmed_by_ops_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_trips" ADD CONSTRAINT "app_trips_ops_booking_id_bookings_id_fk" FOREIGN KEY ("ops_booking_id") REFERENCES "public"."bookings"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "app_users" ADD CONSTRAINT "app_users_ops_client_id_clients_id_fk" FOREIGN KEY ("ops_client_id") REFERENCES "public"."clients"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX "app_audit_entity_idx" ON "app_audit" USING btree ("entity_type","entity_id");
--> statement-breakpoint
CREATE INDEX "app_audit_created_idx" ON "app_audit" USING btree ("created_at");
--> statement-breakpoint
CREATE INDEX "app_circle_members_user_idx" ON "app_circle_members" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX "app_credit_user_idx" ON "app_credit_ledger" USING btree ("user_id","created_at");
--> statement-breakpoint
CREATE UNIQUE INDEX "app_devices_push_key" ON "app_devices" USING btree ("push_token") WHERE "app_devices"."push_token" IS NOT NULL;
--> statement-breakpoint
CREATE INDEX "app_devices_user_idx" ON "app_devices" USING btree ("user_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "app_invoices_number_key" ON "app_invoices" USING btree ("number");
--> statement-breakpoint
CREATE INDEX "app_invoices_owner_idx" ON "app_invoices" USING btree ("owner_id");
--> statement-breakpoint
CREATE INDEX "app_messages_thread_idx" ON "app_messages" USING btree ("thread_kind","thread_id","created_at");
--> statement-breakpoint
CREATE INDEX "app_notifications_user_idx" ON "app_notifications" USING btree ("user_id","created_at");
--> statement-breakpoint
CREATE INDEX "app_otp_phone_idx" ON "app_otp" USING btree ("phone","created_at");
--> statement-breakpoint
CREATE INDEX "app_otp_ip_idx" ON "app_otp" USING btree ("ip_hash","created_at");
--> statement-breakpoint
CREATE UNIQUE INDEX "app_payments_idem_key" ON "app_payments" USING btree ("idempotency_key");
--> statement-breakpoint
CREATE UNIQUE INDEX "app_payments_provider_ref_key" ON "app_payments" USING btree ("provider","provider_ref") WHERE "app_payments"."provider_ref" IS NOT NULL;
--> statement-breakpoint
CREATE INDEX "app_payments_owner_idx" ON "app_payments" USING btree ("owner_id");
--> statement-breakpoint
CREATE INDEX "app_people_owner_idx" ON "app_people" USING btree ("owner_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "app_people_one_self" ON "app_people" USING btree ("owner_id") WHERE "app_people"."is_self" AND "app_people"."deleted_at" IS NULL;
--> statement-breakpoint
CREATE INDEX "app_pickups_trip_idx" ON "app_pickups" USING btree ("trip_id");
--> statement-breakpoint
CREATE INDEX "app_quotes_request_idx" ON "app_quotes" USING btree ("request_id");
--> statement-breakpoint
CREATE INDEX "app_refunds_payment_idx" ON "app_refunds" USING btree ("payment_id");
--> statement-breakpoint
CREATE INDEX "app_requests_owner_idx" ON "app_requests" USING btree ("owner_id","created_at");
--> statement-breakpoint
CREATE INDEX "app_requests_status_idx" ON "app_requests" USING btree ("status","promised_by");
--> statement-breakpoint
CREATE INDEX "app_segments_trip_idx" ON "app_segments" USING btree ("trip_id","sort");
--> statement-breakpoint
CREATE INDEX "app_segments_flight_idx" ON "app_segments" USING btree ("flight_number","depart_local");
--> statement-breakpoint
CREATE UNIQUE INDEX "app_sessions_refresh_key" ON "app_sessions" USING btree ("refresh_hash");
--> statement-breakpoint
CREATE INDEX "app_sessions_previous_idx" ON "app_sessions" USING btree ("previous_hash");
--> statement-breakpoint
CREATE INDEX "app_sessions_user_idx" ON "app_sessions" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX "app_stays_trip_idx" ON "app_stays" USING btree ("trip_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "app_tracked_flights_key" ON "app_tracked_flights" USING btree ("user_id","flight_number","date");
--> statement-breakpoint
CREATE INDEX "app_trips_owner_idx" ON "app_trips" USING btree ("owner_id","start_date");
--> statement-breakpoint
CREATE UNIQUE INDEX "app_users_phone_key" ON "app_users" USING btree ("phone") WHERE "app_users"."phone" IS NOT NULL;
--> statement-breakpoint
CREATE UNIQUE INDEX "app_users_apple_key" ON "app_users" USING btree ("apple_sub") WHERE "app_users"."apple_sub" IS NOT NULL;
--> statement-breakpoint
CREATE UNIQUE INDEX "app_users_google_key" ON "app_users" USING btree ("google_sub") WHERE "app_users"."google_sub" IS NOT NULL;
