// Airports and airlines for the sale form pickers, so routes and carriers are always recorded the same way.
// Order matters: the first entries are shown before anyone types (Saudi and Gulf first).

export type Airport = { code: string; city: string; cityAr?: string; name: string; country: string };
export type Airline = { code: string; name: string; nameAr?: string; country: string };

export const AIRPORTS: Airport[] = [
  // Saudi Arabia
  { code: "RUH", city: "Riyadh", cityAr: "الرياض", name: "King Khalid International", country: "SA" },
  { code: "JED", city: "Jeddah", cityAr: "جدة", name: "King Abdulaziz International", country: "SA" },
  { code: "DMM", city: "Dammam", cityAr: "الدمام", name: "King Fahd International", country: "SA" },
  { code: "MED", city: "Madinah", cityAr: "المدينة المنورة", name: "Prince Mohammad bin Abdulaziz", country: "SA" },
  { code: "AHB", city: "Abha", cityAr: "أبها", name: "Abha International", country: "SA" },
  { code: "TIF", city: "Taif", cityAr: "الطائف", name: "Taif International", country: "SA" },
  { code: "TUU", city: "Tabuk", cityAr: "تبوك", name: "Prince Sultan bin Abdulaziz", country: "SA" },
  { code: "GIZ", city: "Jazan", cityAr: "جازان", name: "King Abdullah bin Abdulaziz", country: "SA" },
  { code: "ELQ", city: "Qassim", cityAr: "القصيم", name: "Prince Naif bin Abdulaziz", country: "SA" },
  { code: "HAS", city: "Hail", cityAr: "حائل", name: "Hail International", country: "SA" },
  { code: "AJF", city: "Al Jouf", cityAr: "الجوف", name: "Al Jouf", country: "SA" },
  { code: "ULH", city: "AlUla", cityAr: "العلا", name: "Prince Abdul Majeed bin Abdulaziz", country: "SA" },
  { code: "YNB", city: "Yanbu", cityAr: "ينبع", name: "Prince Abdul Mohsin bin Abdulaziz", country: "SA" },
  { code: "EAM", city: "Najran", cityAr: "نجران", name: "Najran", country: "SA" },
  { code: "RSI", city: "Red Sea", cityAr: "البحر الأحمر", name: "Red Sea International", country: "SA" },
  { code: "NUM", city: "NEOM", cityAr: "نيوم", name: "NEOM Bay", country: "SA" },
  { code: "BHH", city: "Bisha", cityAr: "بيشة", name: "Bisha", country: "SA" },
  { code: "RAE", city: "Arar", cityAr: "عرعر", name: "Arar", country: "SA" },
  { code: "AQI", city: "Hafr Al Batin", cityAr: "حفر الباطن", name: "Qaisumah", country: "SA" },
  { code: "URY", city: "Qurayyat", cityAr: "القريات", name: "Gurayat Domestic", country: "SA" },
  { code: "WAE", city: "Wadi Al Dawasir", cityAr: "وادي الدواسر", name: "Wadi Al Dawasir", country: "SA" },
  // Gulf
  { code: "DXB", city: "Dubai", cityAr: "دبي", name: "Dubai International", country: "AE" },
  { code: "DWC", city: "Dubai", cityAr: "دبي", name: "Al Maktoum International", country: "AE" },
  { code: "AUH", city: "Abu Dhabi", cityAr: "أبوظبي", name: "Zayed International", country: "AE" },
  { code: "SHJ", city: "Sharjah", cityAr: "الشارقة", name: "Sharjah International", country: "AE" },
  { code: "RKT", city: "Ras Al Khaimah", cityAr: "رأس الخيمة", name: "Ras Al Khaimah International", country: "AE" },
  { code: "DOH", city: "Doha", cityAr: "الدوحة", name: "Hamad International", country: "QA" },
  { code: "BAH", city: "Bahrain", cityAr: "البحرين", name: "Bahrain International", country: "BH" },
  { code: "KWI", city: "Kuwait", cityAr: "الكويت", name: "Kuwait International", country: "KW" },
  { code: "MCT", city: "Muscat", cityAr: "مسقط", name: "Muscat International", country: "OM" },
  { code: "SLL", city: "Salalah", cityAr: "صلالة", name: "Salalah", country: "OM" },
  // Middle East & North Africa
  { code: "CAI", city: "Cairo", cityAr: "القاهرة", name: "Cairo International", country: "EG" },
  { code: "HBE", city: "Alexandria", cityAr: "الإسكندرية", name: "Borg El Arab", country: "EG" },
  { code: "SSH", city: "Sharm El Sheikh", cityAr: "شرم الشيخ", name: "Sharm El Sheikh International", country: "EG" },
  { code: "HRG", city: "Hurghada", cityAr: "الغردقة", name: "Hurghada International", country: "EG" },
  { code: "LXR", city: "Luxor", cityAr: "الأقصر", name: "Luxor International", country: "EG" },
  { code: "AMM", city: "Amman", cityAr: "عمّان", name: "Queen Alia International", country: "JO" },
  { code: "BEY", city: "Beirut", cityAr: "بيروت", name: "Rafic Hariri International", country: "LB" },
  { code: "BGW", city: "Baghdad", cityAr: "بغداد", name: "Baghdad International", country: "IQ" },
  { code: "EBL", city: "Erbil", cityAr: "أربيل", name: "Erbil International", country: "IQ" },
  { code: "NJF", city: "Najaf", cityAr: "النجف", name: "Al Najaf International", country: "IQ" },
  { code: "BSR", city: "Basra", cityAr: "البصرة", name: "Basra International", country: "IQ" },
  { code: "IST", city: "Istanbul", cityAr: "إسطنبول", name: "Istanbul Airport", country: "TR" },
  { code: "SAW", city: "Istanbul", cityAr: "إسطنبول", name: "Sabiha Gökçen", country: "TR" },
  { code: "AYT", city: "Antalya", cityAr: "أنطاليا", name: "Antalya", country: "TR" },
  { code: "TZX", city: "Trabzon", cityAr: "طرابزون", name: "Trabzon", country: "TR" },
  { code: "ESB", city: "Ankara", cityAr: "أنقرة", name: "Esenboğa", country: "TR" },
  { code: "ADB", city: "Izmir", cityAr: "إزمير", name: "Adnan Menderes", country: "TR" },
  { code: "CMN", city: "Casablanca", cityAr: "الدار البيضاء", name: "Mohammed V International", country: "MA" },
  { code: "RAK", city: "Marrakech", cityAr: "مراكش", name: "Marrakech Menara", country: "MA" },
  { code: "TUN", city: "Tunis", cityAr: "تونس", name: "Tunis–Carthage", country: "TN" },
  { code: "ALG", city: "Algiers", cityAr: "الجزائر", name: "Houari Boumediene", country: "DZ" },
  { code: "KRT", city: "Khartoum", cityAr: "الخرطوم", name: "Khartoum International", country: "SD" },
  { code: "ADE", city: "Aden", cityAr: "عدن", name: "Aden International", country: "YE" },
  { code: "IKA", city: "Tehran", cityAr: "طهران", name: "Imam Khomeini International", country: "IR" },
  // South Asia
  { code: "KHI", city: "Karachi", cityAr: "كراتشي", name: "Jinnah International", country: "PK" },
  { code: "LHE", city: "Lahore", cityAr: "لاهور", name: "Allama Iqbal International", country: "PK" },
  { code: "ISB", city: "Islamabad", cityAr: "إسلام آباد", name: "Islamabad International", country: "PK" },
  { code: "PEW", city: "Peshawar", cityAr: "بيشاور", name: "Bacha Khan International", country: "PK" },
  { code: "MUX", city: "Multan", cityAr: "ملتان", name: "Multan International", country: "PK" },
  { code: "SKT", city: "Sialkot", cityAr: "سيالكوت", name: "Sialkot International", country: "PK" },
  { code: "LYP", city: "Faisalabad", cityAr: "فيصل آباد", name: "Faisalabad International", country: "PK" },
  { code: "DEL", city: "Delhi", cityAr: "دلهي", name: "Indira Gandhi International", country: "IN" },
  { code: "BOM", city: "Mumbai", cityAr: "مومباي", name: "Chhatrapati Shivaji Maharaj", country: "IN" },
  { code: "BLR", city: "Bengaluru", name: "Kempegowda International", country: "IN" },
  { code: "HYD", city: "Hyderabad", cityAr: "حيدر آباد", name: "Rajiv Gandhi International", country: "IN" },
  { code: "MAA", city: "Chennai", name: "Chennai International", country: "IN" },
  { code: "COK", city: "Kochi", name: "Cochin International", country: "IN" },
  { code: "CCJ", city: "Kozhikode", name: "Calicut International", country: "IN" },
  { code: "TRV", city: "Thiruvananthapuram", name: "Trivandrum International", country: "IN" },
  { code: "LKO", city: "Lucknow", name: "Chaudhary Charan Singh", country: "IN" },
  { code: "CCU", city: "Kolkata", name: "Netaji Subhas Chandra Bose", country: "IN" },
  { code: "DAC", city: "Dhaka", cityAr: "دكا", name: "Hazrat Shahjalal International", country: "BD" },
  { code: "CGP", city: "Chattogram", name: "Shah Amanat International", country: "BD" },
  { code: "ZYL", city: "Sylhet", name: "Osmani International", country: "BD" },
  { code: "KTM", city: "Kathmandu", cityAr: "كاتماندو", name: "Tribhuvan International", country: "NP" },
  { code: "CMB", city: "Colombo", cityAr: "كولومبو", name: "Bandaranaike International", country: "LK" },
  { code: "MLE", city: "Malé", cityAr: "المالديف", name: "Velana International (Maldives)", country: "MV" },
  // Africa
  { code: "ADD", city: "Addis Ababa", cityAr: "أديس أبابا", name: "Bole International", country: "ET" },
  { code: "NBO", city: "Nairobi", cityAr: "نيروبي", name: "Jomo Kenyatta International", country: "KE" },
  { code: "DAR", city: "Dar es Salaam", name: "Julius Nyerere International", country: "TZ" },
  { code: "ZNZ", city: "Zanzibar", cityAr: "زنجبار", name: "Abeid Amani Karume", country: "TZ" },
  { code: "JNB", city: "Johannesburg", name: "O. R. Tambo International", country: "ZA" },
  { code: "CPT", city: "Cape Town", name: "Cape Town International", country: "ZA" },
  { code: "LOS", city: "Lagos", name: "Murtala Muhammed International", country: "NG" },
  { code: "ACC", city: "Accra", name: "Kotoka International", country: "GH" },
  { code: "MRU", city: "Mauritius", cityAr: "موريشيوس", name: "Sir Seewoosagur Ramgoolam", country: "MU" },
  { code: "SEZ", city: "Seychelles", cityAr: "سيشل", name: "Seychelles International", country: "SC" },
  // Central Asia & Caucasus
  { code: "GYD", city: "Baku", cityAr: "باكو", name: "Heydar Aliyev International", country: "AZ" },
  { code: "TBS", city: "Tbilisi", cityAr: "تبليسي", name: "Tbilisi International", country: "GE" },
  { code: "EVN", city: "Yerevan", name: "Zvartnots International", country: "AM" },
  { code: "TAS", city: "Tashkent", cityAr: "طشقند", name: "Tashkent International", country: "UZ" },
  { code: "ALA", city: "Almaty", cityAr: "ألماتي", name: "Almaty International", country: "KZ" },
  { code: "NQZ", city: "Astana", name: "Nursultan Nazarbayev International", country: "KZ" },
  // East & Southeast Asia
  { code: "KUL", city: "Kuala Lumpur", cityAr: "كوالالمبور", name: "Kuala Lumpur International", country: "MY" },
  { code: "SIN", city: "Singapore", cityAr: "سنغافورة", name: "Changi", country: "SG" },
  { code: "BKK", city: "Bangkok", cityAr: "بانكوك", name: "Suvarnabhumi", country: "TH" },
  { code: "HKT", city: "Phuket", cityAr: "بوكيت", name: "Phuket International", country: "TH" },
  { code: "CGK", city: "Jakarta", cityAr: "جاكرتا", name: "Soekarno–Hatta International", country: "ID" },
  { code: "DPS", city: "Bali", cityAr: "بالي", name: "Ngurah Rai International", country: "ID" },
  { code: "MNL", city: "Manila", cityAr: "مانيلا", name: "Ninoy Aquino International", country: "PH" },
  { code: "HKG", city: "Hong Kong", cityAr: "هونغ كونغ", name: "Hong Kong International", country: "HK" },
  { code: "PEK", city: "Beijing", cityAr: "بكين", name: "Beijing Capital", country: "CN" },
  { code: "PKX", city: "Beijing", cityAr: "بكين", name: "Beijing Daxing", country: "CN" },
  { code: "PVG", city: "Shanghai", cityAr: "شنغهاي", name: "Shanghai Pudong", country: "CN" },
  { code: "CAN", city: "Guangzhou", cityAr: "قوانغتشو", name: "Guangzhou Baiyun", country: "CN" },
  { code: "ICN", city: "Seoul", cityAr: "سيول", name: "Incheon International", country: "KR" },
  { code: "NRT", city: "Tokyo", cityAr: "طوكيو", name: "Narita International", country: "JP" },
  { code: "HND", city: "Tokyo", cityAr: "طوكيو", name: "Haneda", country: "JP" },
  { code: "KIX", city: "Osaka", name: "Kansai International", country: "JP" },
  { code: "SGN", city: "Ho Chi Minh City", name: "Tan Son Nhat International", country: "VN" },
  { code: "HAN", city: "Hanoi", name: "Noi Bai International", country: "VN" },
  // Europe
  { code: "LHR", city: "London", cityAr: "لندن", name: "Heathrow", country: "GB" },
  { code: "LGW", city: "London", cityAr: "لندن", name: "Gatwick", country: "GB" },
  { code: "MAN", city: "Manchester", cityAr: "مانشستر", name: "Manchester", country: "GB" },
  { code: "CDG", city: "Paris", cityAr: "باريس", name: "Charles de Gaulle", country: "FR" },
  { code: "ORY", city: "Paris", cityAr: "باريس", name: "Orly", country: "FR" },
  { code: "NCE", city: "Nice", cityAr: "نيس", name: "Nice Côte d'Azur", country: "FR" },
  { code: "FRA", city: "Frankfurt", cityAr: "فرانكفورت", name: "Frankfurt", country: "DE" },
  { code: "MUC", city: "Munich", cityAr: "ميونخ", name: "Munich", country: "DE" },
  { code: "BER", city: "Berlin", cityAr: "برلين", name: "Berlin Brandenburg", country: "DE" },
  { code: "DUS", city: "Düsseldorf", name: "Düsseldorf", country: "DE" },
  { code: "AMS", city: "Amsterdam", cityAr: "أمستردام", name: "Schiphol", country: "NL" },
  { code: "BRU", city: "Brussels", cityAr: "بروكسل", name: "Brussels", country: "BE" },
  { code: "ZRH", city: "Zurich", cityAr: "زيورخ", name: "Zurich", country: "CH" },
  { code: "GVA", city: "Geneva", cityAr: "جنيف", name: "Geneva", country: "CH" },
  { code: "VIE", city: "Vienna", cityAr: "فيينا", name: "Vienna International", country: "AT" },
  { code: "FCO", city: "Rome", cityAr: "روما", name: "Fiumicino", country: "IT" },
  { code: "MXP", city: "Milan", cityAr: "ميلانو", name: "Malpensa", country: "IT" },
  { code: "MAD", city: "Madrid", cityAr: "مدريد", name: "Adolfo Suárez Madrid–Barajas", country: "ES" },
  { code: "BCN", city: "Barcelona", cityAr: "برشلونة", name: "Barcelona–El Prat", country: "ES" },
  { code: "LIS", city: "Lisbon", cityAr: "لشبونة", name: "Humberto Delgado", country: "PT" },
  { code: "ATH", city: "Athens", cityAr: "أثينا", name: "Athens International", country: "GR" },
  { code: "PRG", city: "Prague", cityAr: "براغ", name: "Václav Havel", country: "CZ" },
  { code: "BUD", city: "Budapest", name: "Budapest Ferenc Liszt", country: "HU" },
  { code: "WAW", city: "Warsaw", name: "Chopin", country: "PL" },
  { code: "CPH", city: "Copenhagen", name: "Copenhagen", country: "DK" },
  { code: "ARN", city: "Stockholm", name: "Arlanda", country: "SE" },
  { code: "OSL", city: "Oslo", name: "Gardermoen", country: "NO" },
  { code: "HEL", city: "Helsinki", name: "Helsinki-Vantaa", country: "FI" },
  { code: "DUB", city: "Dublin", name: "Dublin", country: "IE" },
  { code: "SVO", city: "Moscow", cityAr: "موسكو", name: "Sheremetyevo", country: "RU" },
  // Americas & Oceania
  { code: "JFK", city: "New York", cityAr: "نيويورك", name: "John F. Kennedy International", country: "US" },
  { code: "EWR", city: "New York", cityAr: "نيويورك", name: "Newark Liberty", country: "US" },
  { code: "IAD", city: "Washington", cityAr: "واشنطن", name: "Dulles International", country: "US" },
  { code: "ORD", city: "Chicago", cityAr: "شيكاغو", name: "O'Hare International", country: "US" },
  { code: "IAH", city: "Houston", cityAr: "هيوستن", name: "George Bush Intercontinental", country: "US" },
  { code: "DFW", city: "Dallas", name: "Dallas/Fort Worth International", country: "US" },
  { code: "LAX", city: "Los Angeles", cityAr: "لوس أنجلوس", name: "Los Angeles International", country: "US" },
  { code: "SFO", city: "San Francisco", name: "San Francisco International", country: "US" },
  { code: "BOS", city: "Boston", name: "Logan International", country: "US" },
  { code: "ATL", city: "Atlanta", name: "Hartsfield–Jackson", country: "US" },
  { code: "MIA", city: "Miami", name: "Miami International", country: "US" },
  { code: "YYZ", city: "Toronto", cityAr: "تورنتو", name: "Pearson International", country: "CA" },
  { code: "YUL", city: "Montreal", name: "Trudeau International", country: "CA" },
  { code: "MEX", city: "Mexico City", name: "Benito Juárez International", country: "MX" },
  { code: "GRU", city: "São Paulo", name: "Guarulhos International", country: "BR" },
  { code: "SYD", city: "Sydney", cityAr: "سيدني", name: "Kingsford Smith", country: "AU" },
  { code: "MEL", city: "Melbourne", cityAr: "ملبورن", name: "Melbourne", country: "AU" },
  { code: "PER", city: "Perth", name: "Perth", country: "AU" },
  { code: "AKL", city: "Auckland", name: "Auckland", country: "NZ" },
];

export const AIRLINES: Airline[] = [
  // Saudi & Gulf first
  { code: "SV", name: "Saudia", nameAr: "الخطوط السعودية", country: "SA" },
  { code: "XY", name: "flynas", nameAr: "طيران ناس", country: "SA" },
  { code: "F3", name: "flyadeal", nameAr: "طيران أديل", country: "SA" },
  { code: "RX", name: "Riyadh Air", nameAr: "طيران الرياض", country: "SA" },
  { code: "EK", name: "Emirates", nameAr: "طيران الإمارات", country: "AE" },
  { code: "FZ", name: "flydubai", nameAr: "فلاي دبي", country: "AE" },
  { code: "EY", name: "Etihad Airways", nameAr: "الاتحاد للطيران", country: "AE" },
  { code: "G9", name: "Air Arabia", nameAr: "العربية للطيران", country: "AE" },
  { code: "QR", name: "Qatar Airways", nameAr: "الخطوط الجوية القطرية", country: "QA" },
  { code: "GF", name: "Gulf Air", nameAr: "طيران الخليج", country: "BH" },
  { code: "KU", name: "Kuwait Airways", nameAr: "الخطوط الجوية الكويتية", country: "KW" },
  { code: "J9", name: "Jazeera Airways", nameAr: "طيران الجزيرة", country: "KW" },
  { code: "WY", name: "Oman Air", nameAr: "الطيران العماني", country: "OM" },
  { code: "OV", name: "SalamAir", nameAr: "طيران السلام", country: "OM" },
  // Middle East & Africa
  { code: "MS", name: "EgyptAir", nameAr: "مصر للطيران", country: "EG" },
  { code: "RJ", name: "Royal Jordanian", nameAr: "الملكية الأردنية", country: "JO" },
  { code: "ME", name: "Middle East Airlines", nameAr: "طيران الشرق الأوسط", country: "LB" },
  { code: "IA", name: "Iraqi Airways", nameAr: "الخطوط الجوية العراقية", country: "IQ" },
  { code: "TK", name: "Turkish Airlines", nameAr: "الخطوط الجوية التركية", country: "TR" },
  { code: "PC", name: "Pegasus Airlines", nameAr: "طيران بيغاسوس", country: "TR" },
  { code: "AT", name: "Royal Air Maroc", nameAr: "الخطوط الملكية المغربية", country: "MA" },
  { code: "TU", name: "Tunisair", nameAr: "الخطوط التونسية", country: "TN" },
  { code: "AH", name: "Air Algérie", nameAr: "الخطوط الجوية الجزائرية", country: "DZ" },
  { code: "ET", name: "Ethiopian Airlines", nameAr: "الخطوط الإثيوبية", country: "ET" },
  { code: "KQ", name: "Kenya Airways", country: "KE" },
  { code: "SA", name: "South African Airways", country: "ZA" },
  // South Asia
  { code: "PK", name: "PIA Pakistan International", nameAr: "الخطوط الباكستانية", country: "PK" },
  { code: "PA", name: "airblue", country: "PK" },
  { code: "ER", name: "SereneAir", country: "PK" },
  { code: "9P", name: "Fly Jinnah", country: "PK" },
  { code: "AI", name: "Air India", nameAr: "طيران الهند", country: "IN" },
  { code: "IX", name: "Air India Express", country: "IN" },
  { code: "6E", name: "IndiGo", country: "IN" },
  { code: "SG", name: "SpiceJet", country: "IN" },
  { code: "BG", name: "Biman Bangladesh", country: "BD" },
  { code: "BS", name: "US-Bangla Airlines", country: "BD" },
  { code: "UL", name: "SriLankan Airlines", country: "LK" },
  // Asia
  { code: "MH", name: "Malaysia Airlines", nameAr: "الخطوط الماليزية", country: "MY" },
  { code: "AK", name: "AirAsia", country: "MY" },
  { code: "D7", name: "AirAsia X", country: "MY" },
  { code: "SQ", name: "Singapore Airlines", nameAr: "الخطوط السنغافورية", country: "SG" },
  { code: "TG", name: "Thai Airways", nameAr: "الخطوط التايلاندية", country: "TH" },
  { code: "GA", name: "Garuda Indonesia", country: "ID" },
  { code: "PR", name: "Philippine Airlines", country: "PH" },
  { code: "CX", name: "Cathay Pacific", country: "HK" },
  { code: "CA", name: "Air China", country: "CN" },
  { code: "MU", name: "China Eastern", country: "CN" },
  { code: "CZ", name: "China Southern", country: "CN" },
  { code: "KE", name: "Korean Air", country: "KR" },
  { code: "OZ", name: "Asiana Airlines", country: "KR" },
  { code: "JL", name: "Japan Airlines", country: "JP" },
  { code: "NH", name: "ANA All Nippon Airways", country: "JP" },
  { code: "HY", name: "Uzbekistan Airways", country: "UZ" },
  { code: "KC", name: "Air Astana", country: "KZ" },
  { code: "J2", name: "Azerbaijan Airlines", country: "AZ" },
  // Europe, Americas, Oceania
  { code: "BA", name: "British Airways", nameAr: "الخطوط البريطانية", country: "GB" },
  { code: "VS", name: "Virgin Atlantic", country: "GB" },
  { code: "LH", name: "Lufthansa", nameAr: "لوفتهانزا", country: "DE" },
  { code: "AF", name: "Air France", nameAr: "الخطوط الفرنسية", country: "FR" },
  { code: "KL", name: "KLM", country: "NL" },
  { code: "LX", name: "Swiss", country: "CH" },
  { code: "OS", name: "Austrian Airlines", country: "AT" },
  { code: "SN", name: "Brussels Airlines", country: "BE" },
  { code: "AZ", name: "ITA Airways", country: "IT" },
  { code: "IB", name: "Iberia", country: "ES" },
  { code: "TP", name: "TAP Air Portugal", country: "PT" },
  { code: "A3", name: "Aegean Airlines", country: "GR" },
  { code: "LO", name: "LOT Polish Airlines", country: "PL" },
  { code: "SK", name: "SAS Scandinavian", country: "SE" },
  { code: "AY", name: "Finnair", country: "FI" },
  { code: "EI", name: "Aer Lingus", country: "IE" },
  { code: "SU", name: "Aeroflot", country: "RU" },
  { code: "W6", name: "Wizz Air", country: "HU" },
  { code: "U2", name: "easyJet", country: "GB" },
  { code: "FR", name: "Ryanair", country: "IE" },
  { code: "AA", name: "American Airlines", country: "US" },
  { code: "UA", name: "United Airlines", country: "US" },
  { code: "DL", name: "Delta Air Lines", country: "US" },
  { code: "AC", name: "Air Canada", country: "CA" },
  { code: "QF", name: "Qantas", country: "AU" },
];

export const AIRPORT_CODES = new Set(AIRPORTS.map((a) => a.code));
export const airlineLabel = (a: Airline) => `${a.name} (${a.code})`;
export const AIRLINE_LABELS = new Set(AIRLINES.map(airlineLabel));
