import type { authCopy } from './auth';

/*
 * Arabic for the sign-in section (same keys as auth.ts). A first draft for the native Saudi writer to transcreate
 * (COPY.md §7.4). The brand is written مادا. Codes, numbers and addresses stay left-to-right inside the sentence.
 */
export const authCopyAr: Record<keyof typeof authCopy, string> = {
  'auth.signin.email': 'المتابعة بالبريد الإلكتروني',
  'auth.signin.phone': 'المتابعة برقم الجوال',
  'auth.signin.busy': 'نسجّل دخولك',
  'auth.signin.cancelled': 'ألغيت تسجيل الدخول. لم نأخذ أي معلومة.',
  'auth.signin.unavailable': 'هذه الطريقة غير جاهزة على هذا الجوال. استخدم بريدك أو رقم جوالك.',

  'auth.email.title': 'بريدك الإلكتروني',
  'auth.email.body': 'نرسل لك رمزًا من 6 أرقام. بدون كلمة مرور.',
  'auth.email.label': 'البريد الإلكتروني',
  'auth.email.placeholder': 'you@example.com',
  'auth.email.problem': 'العنوان ناقص. يحتاج إلى @ واسم النطاق.',
  'auth.email.send': 'أرسلوا لي الرمز',
  'auth.email.codeTitle': 'افتح بريدك',
  'auth.email.sentTo': 'أرسلناه إلى {email}.',
  'auth.email.change': 'غيّر البريد',
  'auth.email.demo': 'رمز التجربة: 123456',

  'auth.code.wrong': 'الرمز غير مطابق. تأكد من آخر رمز أرسلناه.',
  'auth.code.expired': 'انتهت صلاحية الرمز. اطلب رمزًا جديدًا لتكمل.',
  'auth.code.wait': 'تقدر تطلب رمزًا جديدًا بعد {seconds} ثانية.',
  'auth.code.tooMany': 'طلبت رموزًا كثيرة. حاول بعد ساعة، أو تواصل مع مادا.',
  'auth.code.resendIn': 'رمز جديد بعد {time}',

  'auth.verifyPhone.title': 'وثّق رقم جوالك',
  'auth.verifyPhone.body': 'دخلت بحساب {provider}. قبل أول حجز نحتاج رقم جوال معك، لتغييرات البوابة ورسائل فيصل.',
  'auth.verifyPhone.bodyPlain': 'قبل أول حجز نحتاج رقم جوال معك، لتغييرات البوابة ورسائل فيصل.',
  'auth.verifyPhone.later': 'لاحقًا',
  'auth.verifyPhone.done': 'تم توثيق رقمك.',
  'auth.verifyPhone.needed': 'وثّق رقم جوالك لتحجز.',
  'auth.verifyPhone.neededBody': 'الخطوط السعودية وفريقنا يحتاجون رقمًا يوصل لك. تأخذ دقيقة.',
  'auth.verifyPhone.go': 'وثّق رقمي',
  'auth.verifyPhone.row': 'وثّق رقم جوالك',
  'auth.verifyPhone.rowSub': 'مطلوب قبل أول حجز',
  'auth.provider.apple': 'Apple',
  'auth.provider.google': 'Google',
  'auth.provider.email': 'بريدك الإلكتروني',

  'auth.methods.email': 'البريد الإلكتروني',
  'auth.methods.emailSub': 'رمز بالبريد',
  'auth.methods.addEmail': 'تضيف بريدك كطريقة دخول؟',
  'auth.methods.addEmailBody': 'نرسل رمزًا لنتأكد أنه بريدك.',
  'auth.methods.addPhoneBody': 'نرسل رمزًا لنتأكد أنه رقمك.',
  'auth.methods.addEmailGo': 'أضف بريدي',
  'auth.methods.addPhoneGo': 'أضف رقمي',
  'auth.methods.emailManage': 'تقدر تدخل برمز يصل إلى {email}.',
  'auth.methods.phoneKept': 'رقمك يبقى. به يتواصل معك فيصل أثناء الرحلة.',
  'auth.methods.changePhone': 'استخدم رقمًا آخر',
  'auth.methods.changeEmail': 'استخدم بريدًا آخر',
  'auth.methods.confirmFirst': 'سجّل دخولك من جديد لتغيير هذا.',
  'auth.methods.confirmFirstBody': 'لحمايتك، نتأكد أنك أنت قبل إضافة طريقة دخول. سجّل خروجك ثم ادخل كالمعتاد.',
  'auth.methods.taken': 'حساب {name} هذا مرتبط بحساب آخر في مادا.',
  'auth.methods.emailAdded': 'أضفنا بريدك. تقدر تدخل به الآن.',

  'auth.help.link': 'ما وصلك الرمز؟',
  'auth.help.title': 'ما وصلك الرمز؟',
  'auth.help.body': 'قد يتأخر الرمز دقيقة. وهذه خيارات أخرى.',
  'auth.help.resend': 'أرسلوا رمزًا جديدًا',
  'auth.help.resendIn': 'رمز جديد بعد {time}',
  'auth.help.spamTitle': 'افتح مجلد الرسائل غير المرغوب فيها',
  'auth.help.spamBody': 'يصلك من مادا للرحلات، من العنوان {address}.',
  'auth.help.changePhone': 'الرقم غير صحيح؟ غيّره',
  'auth.help.changeEmail': 'البريد غير صحيح؟ غيّره',
  'auth.help.otherWay': 'جرّب طريقة أخرى',
  'auth.help.useEmail': 'أرسلوا الرمز إلى بريدي',
  'auth.help.usePhone': 'أرسلوا الرمز برسالة نصية',
  'auth.help.lost': 'ما عاد عندي هذا الرقم أو البريد',
  'auth.help.lostSub': 'نتأكد أنك أنت، ثم ننقل حسابك.',
  'auth.code.resentTo': 'أرسلنا رمزًا جديدًا إلى {contact}.',
  'auth.email.openMail': 'افتح البريد',

  'auth.pause.title': 'لنأخذ استراحة قصيرة.',
  'auth.pause.body': 'كانت هناك محاولات كثيرة متتالية، فأوقفنا الرموز لحظة. هذا يحمي حسابك. لا شيء مقفل.',
  'auth.pause.wait': 'تقدر تحاول بعد',
  'auth.pause.ready': 'جاهزون متى ما كنت جاهزًا',
  'auth.pause.call': 'اتصل بمادا',

  'auth.signin.continueAs': 'المتابعة بـ {contact}',
  'auth.signin.another': 'استخدم طريقة أخرى',
  'auth.signin.last': 'دخلت بهذه الطريقة آخر مرة على هذا الجوال.',

  'recover.title': 'ما عاد عندك رقمك أو بريدك القديم؟',
  'recover.body': 'أخبرنا من أنت وكيف نوصل لك الآن. يتأكد شخص من مادا أنك أنت، ثم ينقل حسابك.',
  'recover.name': 'اسمك الكامل',
  'recover.nameNeeded': 'اسمك يساعدنا نلقى حسابك.',
  'recover.oldKind': 'كنت تدخل بـ',
  'recover.newKind': 'كيف نوصل لك الآن',
  'recover.kind.phone': 'رقم الجوال',
  'recover.kind.email': 'البريد الإلكتروني',
  'recover.oldPhone': 'رقمك القديم',
  'recover.oldEmail': 'بريدك القديم',
  'recover.newPhone': 'رقمك الجديد',
  'recover.newEmail': 'بريدك الجديد',
  'recover.note': 'أي شيء يساعدنا (اختياري)',
  'recover.notePlaceholder': 'مثلًا: آخر رحلة حجزتها معنا',
  'recover.same': 'الجديد لازم يختلف عن القديم.',
  'recover.privacy': 'نستخدم هذه التفاصيل فقط لنتأكد أنك أنت.',
  'recover.send': 'أرسل إلى مادا',
  'recover.tooMany': 'وصلتنا طلبات كثيرة من هنا اليوم. حاول غدًا، أو اتصل بمادا.',
  'recover.sent.title': 'وصلنا طلبك.',
  'recover.sent.body': 'يتأكد شخص من مادا أنك أنت، من بيانات الجواز المحفوظة وآخر حجز لك، ثم ينقل حسابك. عادةً خلال يوم.',
  'recover.sent.reach': 'نتواصل معك على {contact}.',
  'recover.sent.done': 'العودة لتسجيل الدخول',
  'recover.done.subject': 'نقلنا حسابك في مادا',
  'recover.done.body': 'مادا: صار حسابك على هذا {kind}. افتح مادا للرحلات وادخل برمز.',
  'recover.done.phone': 'الرقم',
  'recover.done.email': 'البريد',
  'recover.declined.subject': 'بخصوص حسابك في مادا',
  'recover.declined.body': 'مادا: ما قدرنا نتأكد أنك أنت، فبقي حسابك كما هو. اتصل بنا على {phone} ونحلها معًا.',

  'auth.error.phoneRequired': 'وثّق رقم جوالك لتحجز. تأخذ دقيقة.',
  'auth.error.identityTaken': 'طريقة الدخول هذه مرتبطة بحساب آخر.',
  'auth.error.signInAgain': 'سجّل دخولك من جديد لتكمل.',
};
