/*
 * Sign-in: Apple, Google, email code and phone code (identity through Supabase Auth, see docs/app/AUTH.md), the
 * "Verify your phone" step for accounts that started with Apple, Google or email, and Profile › Sign-in methods.
 * Spread into the catalogue in en.ts; held to the same COPY.md lint. Arabic: auth.ar.ts (same keys).
 */
export const authCopy = {
  // ───────────── sign-in choices ─────────────
  'auth.signin.email': 'Continue with email',
  'auth.signin.phone': 'Continue with phone number',
  'auth.signin.busy': 'Signing you in',
  'auth.signin.cancelled': 'Sign-in cancelled. Nothing was shared.',
  'auth.signin.unavailable': 'That way in isn’t ready on this phone. Use your email or phone number instead.',

  // ───────────── email code ─────────────
  'auth.email.title': 'Your email',
  'auth.email.body': 'We’ll email a 6-digit code. No password to remember.',
  'auth.email.label': 'Email address',
  'auth.email.placeholder': 'you@example.com',
  'auth.email.problem': 'That address looks incomplete. It needs an @ and a domain.',
  'auth.email.send': 'Email me a code',
  'auth.email.codeTitle': 'Check your email',
  'auth.email.sentTo': 'Sent to {email}.',
  'auth.email.change': 'Change email',
  'auth.email.demo': 'Demo code: 123456',

  // ───────────── codes (phone and email) ─────────────
  'auth.code.wrong': 'That code doesn’t match. Check the latest one we sent.',
  'auth.code.expired': 'That code has expired. Get a new one to carry on.',
  'auth.code.wait': 'You can ask for a new code in {seconds} seconds.',
  'auth.code.tooMany': 'Too many codes for now. Try again in an hour, or talk to Mada.',
  'auth.code.resendIn': 'New code in {time}',

  // ───────────── verify your phone ─────────────
  'auth.verifyPhone.title': 'Verify your phone',
  'auth.verifyPhone.body': 'You’re signed in with {provider}. Before your first booking we need a mobile number that’s with you, for gate changes and Faisal’s messages.',
  'auth.verifyPhone.bodyPlain': 'Before your first booking we need a mobile number that’s with you, for gate changes and Faisal’s messages.',
  'auth.verifyPhone.later': 'Later',
  'auth.verifyPhone.done': 'Your number is verified.',
  'auth.verifyPhone.needed': 'Verify your phone to book.',
  'auth.verifyPhone.neededBody': 'Saudi airlines and our desk need a number that reaches you. It takes a minute.',
  'auth.verifyPhone.go': 'Verify my phone',
  'auth.verifyPhone.row': 'Verify your phone',
  'auth.verifyPhone.rowSub': 'Needed before your first booking',
  'auth.provider.apple': 'Apple',
  'auth.provider.google': 'Google',
  'auth.provider.email': 'your email',

  // ───────────── sign-in methods (Profile) ─────────────
  'auth.methods.email': 'Email',
  'auth.methods.emailSub': 'A code by email',
  'auth.methods.addEmail': 'Add your email as a way in?',
  'auth.methods.addEmailBody': 'We’ll email a code to check it’s yours.',
  'auth.methods.addPhoneBody': 'We’ll text a code to check it’s yours.',
  'auth.methods.addEmailGo': 'Add my email',
  'auth.methods.addPhoneGo': 'Add my number',
  'auth.methods.emailManage': 'You can sign in with a code sent to {email}.',
  'auth.methods.phoneKept': 'Your number stays. It’s how Faisal reaches you on a trip.',
  'auth.methods.changePhone': 'Use a different number',
  'auth.methods.changeEmail': 'Use a different email',
  'auth.methods.confirmFirst': 'Sign in again to change this.',
  'auth.methods.confirmFirstBody': 'For your safety, we check it’s you before adding a way in. Sign out, then sign back in the usual way.',
  'auth.methods.taken': 'That {name} account is already on another Mada account.',
  'auth.methods.emailAdded': 'Email added. You can sign in with it now.',

  // ───────────── didn't get the code? (every code screen) ─────────────
  'auth.help.link': 'Didn’t get the code?',
  'auth.help.title': 'Didn’t get the code?',
  'auth.help.body': 'Codes can take a minute to arrive. Here’s what else you can do.',
  'auth.help.resend': 'Send a new code',
  'auth.help.resendIn': 'Send a new code in {time}',
  'auth.help.spamTitle': 'Check your spam or junk folder',
  'auth.help.spamBody': 'It comes from Mada Trips, {address}.',
  'auth.help.changePhone': 'Wrong number? Change it',
  'auth.help.changeEmail': 'Wrong email? Change it',
  'auth.help.otherWay': 'Try another way',
  'auth.help.useEmail': 'Get a code by email',
  'auth.help.usePhone': 'Get a code by text',
  'auth.help.lost': 'I can’t use this number or email any more',
  'auth.help.lostSub': 'We’ll check it’s you and move your account.',
  'auth.code.resentTo': 'New code sent to {contact}.',
  'auth.email.openMail': 'Open Mail',

  // ───────────── a short pause after too many wrong codes ─────────────
  'auth.pause.title': 'Let’s take a short pause.',
  'auth.pause.body': 'There were a lot of tries in a row, so we’ve paused codes for a moment. It keeps your account safe. Nothing is locked.',
  'auth.pause.wait': 'You can try again in',
  'auth.pause.ready': 'Ready when you are',
  'auth.pause.call': 'Call Mada',

  // ───────────── the way in this phone used last time ─────────────
  'auth.signin.continueAs': 'Continue as {contact}',
  'auth.signin.another': 'Use another way',
  'auth.signin.last': 'You used this last time on this phone.',

  // ───────────── account recovery (signed out) ─────────────
  'recover.title': 'Can’t use your old number or email?',
  'recover.body': 'Tell us who you are and how to reach you now. A person at Mada checks it’s you, then moves your account.',
  'recover.name': 'Your full name',
  'recover.nameNeeded': 'Your name helps us find your account.',
  'recover.oldKind': 'You signed in with',
  'recover.newKind': 'How we can reach you now',
  'recover.kind.phone': 'Phone number',
  'recover.kind.email': 'Email',
  'recover.oldPhone': 'Your old number',
  'recover.oldEmail': 'Your old email',
  'recover.newPhone': 'Your new number',
  'recover.newEmail': 'Your new email',
  'recover.note': 'Anything that helps (optional)',
  'recover.notePlaceholder': 'For example, your last trip with us',
  'recover.same': 'The new one needs to be different from the old one.',
  'recover.privacy': 'We only use these details to check it’s you.',
  'recover.send': 'Send to Mada',
  'recover.tooMany': 'We’ve had a few of these from here today. Try again tomorrow, or call Mada.',
  'recover.sent.title': 'We have your request.',
  'recover.sent.body': 'A person at Mada will check it’s you, using the passport details on file and your last booking, then move your account. Usually within a day.',
  'recover.sent.reach': 'We’ll reach you at {contact}.',
  'recover.sent.done': 'Back to sign-in',
  // Sent by text or email to the new contact when the desk decides.
  'recover.done.subject': 'Your Mada account has moved',
  'recover.done.body': 'Mada: your account is now on this {kind}. Open Mada Trips and sign in with a code.',
  'recover.done.phone': 'number',
  'recover.done.email': 'email address',
  'recover.declined.subject': 'About your Mada account',
  'recover.declined.body': 'Mada: we couldn’t confirm it’s you, so your account stays as it was. Call us on {phone} and we’ll sort it out together.',

  // ───────────── optional password (with an email; codes stay the default) ─────────────
  'auth.password.use': 'Use my password instead',
  'auth.password.useCode': 'Email me a code instead',
  'auth.password.title': 'Your password',
  'auth.password.body': 'Only if you set one in Profile. Codes always work too.',
  'auth.password.label': 'Password',
  'auth.password.show': 'Show',
  'auth.password.hide': 'Hide',
  'auth.password.signIn': 'Sign in',
  'auth.password.forgot': 'Forgot password?',
  'auth.password.mismatch': 'That email and password don’t match.',
  'auth.password.wrong.one': 'That email and password don’t match. 1 try left before a short pause.',
  'auth.password.wrong.other': 'That email and password don’t match. {count} tries left before a short pause.',
  'auth.password.forgotTitle': 'Choose a new password',
  'auth.password.forgotBody': 'We’ll email a 6-digit code to {email}. Then you choose a new password.',
  'auth.password.newLabel': 'New password',
  'auth.password.newHint': 'A short sentence with a number and a symbol is easy to remember and hard to guess.',
  'auth.password.short.one': 'At least 8 characters, please. You have 1.',
  'auth.password.short.other': 'At least 8 characters, please. You have {count}.',
  'auth.password.strength.weak': 'Easy to guess',
  'auth.password.strength.fair': 'Getting there',
  'auth.password.strength.strong': 'Strong',
  'auth.password.leaked': 'This password has appeared in a leak elsewhere. Choose another one.',
  'auth.password.rules': 'Your password needs',
  'auth.password.rule.length': 'At least 8 characters',
  'auth.password.rule.lower': 'A lowercase letter',
  'auth.password.rule.upper': 'An uppercase letter',
  'auth.password.rule.digit': 'A number',
  'auth.password.rule.symbol': 'A symbol, like # or @',
  'auth.password.rule.done': 'Done',
  'auth.password.rule.todo': 'Still needed',
  'auth.password.weakServer': 'That password is too easy to guess. Try a longer one.',
  'auth.password.save': 'Save password',
  'auth.password.saveSignIn': 'Save and sign in',
  'auth.password.saved': 'Password saved. You can sign in with it or with a code.',
  'auth.password.removed': 'Password removed. Codes work as before.',

  // ───────────── Profile › Sign-in methods › Password ─────────────
  'auth.methods.password': 'Password',
  'auth.methods.passwordSub': 'Optional, with your email',
  'auth.methods.passwordOn': 'Set',
  'auth.methods.passwordBody': 'Codes always work. A password is an extra way in with your email.',
  'auth.methods.passwordNeedsEmail': 'Add your email first. A password goes with it.',
  'auth.methods.setPassword': 'Set a password',
  'auth.methods.changePassword': 'Change password',
  'auth.methods.removePassword': 'Remove password',
  'auth.methods.removePasswordBody': 'You’ll sign in with a code, Apple or Google, as before.',
  'auth.methods.reauth': 'First, a code to check it’s you.',
  'auth.methods.reauthBody': 'We’ll send a 6-digit code to {contact}.',
  'auth.methods.reauthSend': 'Send the code',
  'auth.methods.codeLabel': 'Code from {contact}',

  // ───────────── open Mada with Face ID (opt-in) ─────────────
  'auth.bio.title': 'Open Mada with Face ID?',
  'auth.bio.body': 'A glance or a touch opens the app on this phone. Face ID or fingerprint, whichever it has. You can turn it off in Profile.',
  'auth.bio.allow': 'Use Face ID',
  'auth.bio.later': 'Not now',
  'auth.bio.row': 'Open Mada with Face ID',
  'auth.bio.rowSub': 'Asks when the app has been away 5 minutes',
  'auth.bio.on': 'Mada opens with Face ID on this phone.',
  'auth.bio.off': 'Mada opens without Face ID.',
  'auth.bio.locked': 'Mada is locked',
  'auth.bio.lockedBody': 'Your trips and documents are safe on this phone.',
  'auth.bio.unlock': 'Open with Face ID',
  'auth.bio.prompt': 'Open Mada',
  'auth.bio.signOut': 'Sign out instead',

  // ───────────── errors from the Core API ─────────────
  'auth.error.phoneRequired': 'Verify your phone number to book. It takes a minute.',
  'auth.error.identityTaken': 'That sign-in is already on another account.',
  'auth.error.signInAgain': 'Please sign in again to carry on.',
} as const;
