import type { authCopy } from './auth';

/*
 * Arabic for the sign-in section (same keys as auth.ts). A first draft for the native Saudi writer to transcreate
 * (COPY.md §7.4). The brand is written مادا. Codes, numbers and addresses stay left-to-right inside the sentence.
 */
export const authCopyAr: Record<keyof typeof authCopy, string> & Record<string, string> = {
  'auth.signin.email': 'المتابعة بالبريد الإلكتروني',
  'auth.signin.phone': 'المتابعة برقم الجوال',
  'auth.signin.busy': 'نسجّل دخولك',
  'auth.signin.cancelled': 'ألغيت تسجيل الدخول. لم نأخذ أي معلومة.',
  'auth.signin.unavailable': 'هذه الطريقة غير جاهزة على هذا الجوال. استخدم بريدك أو رقم جوالك.',

  'auth.email.title': 'بريدك الإلكتروني',
  'auth.email.body': 'نرسل لك رمزًا من 6 أرقام. بدون كلمة مرور.',
  'auth.email.label': 'البريد الإلكتروني',
  'auth.email.placeholder': 'you@example.com',
  'auth.email.problem': 'العنوان ناقص. يحتاج إلى @ واسم النطاق.',
  'auth.email.send': 'أرسلوا لي الرمز',
  'auth.email.codeTitle': 'افتح بريدك',
  'auth.email.sentTo': 'أرسلناه إلى {email}.',
  'auth.email.change': 'غيّر البريد',
  'auth.email.demo': 'رمز التجربة: 123456',

  'auth.code.wrong': 'الرمز غير مطابق. تأكد من آخر رمز أرسلناه.',
  'auth.code.expired': 'انتهت صلاحية الرمز. اطلب رمزًا جديدًا لتكمل.',
  'auth.code.wait': 'تقدر تطلب رمزًا جديدًا بعد {seconds} ثانية.',
  'auth.code.tooMany': 'طلبت رموزًا كثيرة. حاول بعد ساعة، أو تواصل مع مادا.',
  'auth.code.resendIn': 'رمز جديد بعد {time}',

  'auth.verifyPhone.title': 'وثّق رقم جوالك',
  'auth.verifyPhone.body': 'دخلت بحساب {provider}. قبل أول حجز نحتاج رقم جوال معك، لتغييرات البوابة ورسائل فيصل.',
  'auth.verifyPhone.bodyPlain': 'قبل أول حجز نحتاج رقم جوال معك، لتغييرات البوابة ورسائل فيصل.',
  'auth.verifyPhone.later': 'لاحقًا',
  'auth.verifyPhone.done': 'تم توثيق رقمك.',
  'auth.verifyPhone.needed': 'وثّق رقم جوالك لتحجز.',
  'auth.verifyPhone.neededBody': 'الخطوط السعودية وفريقنا يحتاجون رقمًا يوصل لك. تأخذ دقيقة.',
  'auth.verifyPhone.go': 'وثّق رقمي',
  'auth.verifyPhone.row': 'وثّق رقم جوالك',
  'auth.verifyPhone.rowSub': 'مطلوب قبل أول حجز',
  'auth.provider.apple': 'Apple',
  'auth.provider.google': 'Google',
  'auth.provider.email': 'بريدك الإلكتروني',

  'auth.methods.email': 'البريد الإلكتروني',
  'auth.methods.emailSub': 'رمز بالبريد',
  'auth.methods.addEmail': 'تضيف بريدك كطريقة دخول؟',
  'auth.methods.addEmailBody': 'نرسل رمزًا لنتأكد أنه بريدك.',
  'auth.methods.addPhoneBody': 'نرسل رمزًا لنتأكد أنه رقمك.',
  'auth.methods.addEmailGo': 'أضف بريدي',
  'auth.methods.addPhoneGo': 'أضف رقمي',
  'auth.methods.emailManage': 'تقدر تدخل برمز يصل إلى {email}.',
  'auth.methods.phoneKept': 'رقمك يبقى. به يتواصل معك فيصل أثناء الرحلة.',
  'auth.methods.changePhone': 'استخدم رقمًا آخر',
  'auth.methods.changeEmail': 'استخدم بريدًا آخر',
  'auth.methods.confirmFirst': 'سجّل دخولك من جديد لتغيير هذا.',
  'auth.methods.confirmFirstBody': 'لحمايتك، نتأكد أنك أنت قبل إضافة طريقة دخول. سجّل خروجك ثم ادخل كالمعتاد.',
  'auth.methods.taken': 'حساب {name} هذا مرتبط بحساب آخر في مادا.',
  'auth.methods.emailAdded': 'أضفنا بريدك. تقدر تدخل به الآن.',

  'auth.help.link': 'ما وصلك الرمز؟',
  'auth.help.title': 'ما وصلك الرمز؟',
  'auth.help.body': 'قد يتأخر الرمز دقيقة. وهذه خيارات أخرى.',
  'auth.help.resend': 'أرسلوا رمزًا جديدًا',
  'auth.help.resendIn': 'رمز جديد بعد {time}',
  'auth.help.spamTitle': 'افتح مجلد الرسائل غير المرغوب فيها',
  'auth.help.spamBody': 'يصلك من مادا للرحلات، من العنوان {address}.',
  'auth.help.changePhone': 'الرقم غير صحيح؟ غيّره',
  'auth.help.changeEmail': 'البريد غير صحيح؟ غيّره',
  'auth.help.otherWay': 'جرّب طريقة أخرى',
  'auth.help.useEmail': 'أرسلوا الرمز إلى بريدي',
  'auth.help.usePhone': 'أرسلوا الرمز برسالة نصية',
  'auth.help.lost': 'ما عاد عندي هذا الرقم أو البريد',
  'auth.help.lostSub': 'نتأكد أنك أنت، ثم ننقل حسابك.',
  'auth.code.resentTo': 'أرسلنا رمزًا جديدًا إلى {contact}.',
  'auth.email.openMail': 'افتح البريد',

  'auth.pause.title': 'لنأخذ استراحة قصيرة.',
  'auth.pause.body': 'كانت هناك محاولات كثيرة متتالية، فأوقفنا الرموز لحظة. هذا يحمي حسابك. لا شيء مقفل.',
  'auth.pause.wait': 'تقدر تحاول بعد',
  'auth.pause.ready': 'جاهزون متى ما كنت جاهزًا',
  'auth.pause.call': 'اتصل بمادا',

  'auth.signin.continueAs': 'المتابعة بـ {contact}',
  'auth.signin.another': 'استخدم طريقة أخرى',
  'auth.signin.last': 'دخلت بهذه الطريقة آخر مرة على هذا الجوال.',

  'recover.title': 'ما عاد عندك رقمك أو بريدك القديم؟',
  'recover.body': 'أخبرنا من أنت وكيف نوصل لك الآن. يتأكد شخص من مادا أنك أنت، ثم ينقل حسابك.',
  'recover.name': 'اسمك الكامل',
  'recover.nameNeeded': 'اسمك يساعدنا نلقى حسابك.',
  'recover.oldKind': 'كنت تدخل بـ',
  'recover.newKind': 'كيف نوصل لك الآن',
  'recover.kind.phone': 'رقم الجوال',
  'recover.kind.email': 'البريد الإلكتروني',
  'recover.oldPhone': 'رقمك القديم',
  'recover.oldEmail': 'بريدك القديم',
  'recover.newPhone': 'رقمك الجديد',
  'recover.newEmail': 'بريدك الجديد',
  'recover.note': 'أي شيء يساعدنا (اختياري)',
  'recover.notePlaceholder': 'مثلًا: آخر رحلة حجزتها معنا',
  'recover.same': 'الجديد لازم يختلف عن القديم.',
  'recover.privacy': 'نستخدم هذه التفاصيل فقط لنتأكد أنك أنت.',
  'recover.send': 'أرسل إلى مادا',
  'recover.tooMany': 'وصلتنا طلبات كثيرة من هنا اليوم. حاول غدًا، أو اتصل بمادا.',
  'recover.sent.title': 'وصلنا طلبك.',
  'recover.sent.body': 'يتأكد شخص من مادا أنك أنت، من بيانات الجواز المحفوظة وآخر حجز لك، ثم ينقل حسابك. عادةً خلال يوم.',
  'recover.sent.reach': 'نتواصل معك على {contact}.',
  'recover.sent.done': 'العودة لتسجيل الدخول',
  'recover.done.subject': 'نقلنا حسابك في مادا',
  'recover.done.body': 'مادا: صار حسابك على هذا {kind}. افتح مادا للرحلات وادخل برمز.',
  'recover.done.phone': 'الرقم',
  'recover.done.email': 'البريد',
  'recover.declined.subject': 'بخصوص حسابك في مادا',
  'recover.declined.body': 'مادا: ما قدرنا نتأكد أنك أنت، فبقي حسابك كما هو. اتصل بنا على {phone} ونحلها معًا.',

  'auth.password.use': 'استخدم كلمة المرور بدلًا من ذلك',
  'auth.password.useCode': 'أرسلوا لي رمزًا بالبريد بدلًا من ذلك',
  'auth.password.title': 'كلمة المرور',
  'auth.password.body': 'فقط إذا أنشأتها من الملف الشخصي. الرموز تعمل دائمًا أيضًا.',
  'auth.password.label': 'كلمة المرور',
  'auth.password.show': 'إظهار',
  'auth.password.hide': 'إخفاء',
  'auth.password.signIn': 'تسجيل الدخول',
  'auth.password.forgot': 'نسيت كلمة المرور؟',
  'auth.password.mismatch': 'البريد وكلمة المرور غير متطابقين.',
  'auth.password.wrong.one': 'البريد وكلمة المرور غير متطابقين. بقيت محاولة واحدة قبل استراحة قصيرة.',
  'auth.password.wrong.two': 'البريد وكلمة المرور غير متطابقين. بقيت محاولتان قبل استراحة قصيرة.',
  'auth.password.wrong.few': 'البريد وكلمة المرور غير متطابقين. بقيت {count} محاولات قبل استراحة قصيرة.',
  'auth.password.wrong.other': 'البريد وكلمة المرور غير متطابقين. بقيت {count} محاولة قبل استراحة قصيرة.',
  'auth.password.forgotTitle': 'اختر كلمة مرور جديدة',
  'auth.password.forgotBody': 'نرسل رمزًا من 6 أرقام إلى {email}. ثم تختار كلمة مرور جديدة.',
  'auth.password.newLabel': 'كلمة المرور الجديدة',
  'auth.password.newHint': 'جملة قصيرة فيها رقم ورمز سهلة التذكر وصعبة التخمين.',
  'auth.password.short.one': '8 أحرف على الأقل من فضلك. عندك حرف واحد.',
  'auth.password.short.two': '8 أحرف على الأقل من فضلك. عندك حرفان.',
  'auth.password.short.few': '8 أحرف على الأقل من فضلك. عندك {count} أحرف.',
  'auth.password.short.other': '8 أحرف على الأقل من فضلك. عندك {count} حرفًا.',
  'auth.password.strength.weak': 'سهلة التخمين',
  'auth.password.strength.fair': 'قريبة',
  'auth.password.strength.strong': 'قوية',
  'auth.password.leaked': 'ظهرت كلمة المرور هذه في تسريب في مكان آخر. اختر غيرها.',
  'auth.password.rules': 'كلمة المرور تحتاج',
  'auth.password.rule.length': '8 أحرف على الأقل',
  'auth.password.rule.lower': 'حرفًا لاتينيًا صغيرًا',
  'auth.password.rule.upper': 'حرفًا لاتينيًا كبيرًا',
  'auth.password.rule.digit': 'رقمًا',
  'auth.password.rule.symbol': 'رمزًا، مثل # أو @',
  'auth.password.rule.done': 'تم',
  'auth.password.rule.todo': 'لم يكتمل بعد',
  'auth.password.weakServer': 'كلمة المرور هذه سهلة التخمين. جرّب أطول منها.',
  'auth.password.save': 'احفظ كلمة المرور',
  'auth.password.saveSignIn': 'احفظ وادخل',
  'auth.password.saved': 'حفظنا كلمة المرور. تقدر تدخل بها أو برمز.',
  'auth.password.removed': 'أزلنا كلمة المرور. الرموز تعمل كما كانت.',

  'auth.methods.password': 'كلمة المرور',
  'auth.methods.passwordSub': 'اختيارية، مع بريدك',
  'auth.methods.passwordOn': 'مفعّلة',
  'auth.methods.passwordBody': 'الرموز تعمل دائمًا. كلمة المرور طريقة دخول إضافية مع بريدك.',
  'auth.methods.passwordNeedsEmail': 'أضف بريدك أولًا. كلمة المرور تكون معه.',
  'auth.methods.setPassword': 'أنشئ كلمة مرور',
  'auth.methods.changePassword': 'غيّر كلمة المرور',
  'auth.methods.removePassword': 'أزل كلمة المرور',
  'auth.methods.removePasswordBody': 'تدخل برمز أو Apple أو Google كما كنت.',
  'auth.methods.reauth': 'أولًا، رمز لنتأكد أنك أنت.',
  'auth.methods.reauthBody': 'نرسل رمزًا من 6 أرقام إلى {contact}.',
  'auth.methods.reauthSend': 'أرسلوا الرمز',
  'auth.methods.codeLabel': 'الرمز المرسل إلى {contact}',

  'auth.bio.title': 'تفتح مادا ببصمة الوجه؟',
  'auth.bio.body': 'نظرة أو لمسة تفتح التطبيق على هذا الجوال، ببصمة الوجه أو الإصبع حسب جوالك. تقدر توقفها من الملف الشخصي.',
  'auth.bio.allow': 'استخدم بصمة الوجه',
  'auth.bio.later': 'ليس الآن',
  'auth.bio.row': 'افتح مادا ببصمة الوجه',
  'auth.bio.rowSub': 'نطلبها إذا غاب التطبيق 5 دقائق',
  'auth.bio.on': 'تفتح مادا ببصمة الوجه على هذا الجوال.',
  'auth.bio.off': 'تفتح مادا بدون بصمة الوجه.',
  'auth.bio.locked': 'مادا مقفل',
  'auth.bio.lockedBody': 'رحلاتك ووثائقك محفوظة على هذا الجوال.',
  'auth.bio.unlock': 'افتح ببصمة الوجه',
  'auth.bio.prompt': 'افتح مادا',
  'auth.bio.signOut': 'سجّل الخروج بدلًا من ذلك',

  'auth.error.phoneRequired': 'وثّق رقم جوالك لتحجز. تأخذ دقيقة.',
  'auth.error.identityTaken': 'طريقة الدخول هذه مرتبطة بحساب آخر.',
  'auth.error.signInAgain': 'سجّل دخولك من جديد لتكمل.',
};
