/**
 * Strings for booking (M2): Ask, search, entry checks, requests, plans, the order sheet, payment, the wait for the
 * desk and the confirmation. Lifted from the prototype (Ask.jsx, Pay.jsx, Plan.jsx) with COPY.md applied, including
 * §1 "Mada and Faisal": buttons say Mada; the agent's name ({agent}) comes from the server and appears only as
 * presence or as the person who acted. Spread into the catalogue in en.ts, so the copy lint covers every line here.
 * Lines reworded from the prototype for the lint ("Data for the trip" → eSIM) are listed in the M2 report.
 */
export const bookingCopy = {
  // ───────────── ask: start ─────────────
  'ask.close': 'Close',
  'ask.title': 'Where to?',
  'ask.intro': "Say it any way you like. A place, dates, who's going. We'll ask only what we need.",
  'ask.composer': 'Where to? Say it any way you like',
  'ask.composerMore': 'Anything else?',
  'ask.a11y.input': 'Ask Mada',
  'ask.a11y.send': 'Send',
  'ask.a11y.talk': 'Hold to talk',
  'ask.voice': 'Voice comes in the app. Type here for now.',
  'ask.somethingElse': 'Ask something else',
  'ask.idea.familyEid': 'Istanbul for Eid, all {count} of us',
  'ask.idea.sameAgain': 'Same as last Eid',
  'ask.idea.hotel': 'A hotel in Istanbul',
  'ask.idea.visaFor': 'Schengen visa for {name}',
  'ask.idea.visa': 'A Schengen visa',
  'ask.idea.umrah': 'Umrah in Ramadan',
  'ask.idea.flights': 'Flights to Istanbul',
  'ask.idea.dubai': 'Flights to Dubai next weekend',
  'ask.idea.alula': 'A weekend in AlUla',
  'ask.idea.tripHotel': 'Add a hotel in {city}',
  'ask.idea.tripDinner': 'Dinner on the first night',
  'ask.idea.tripCar': 'A car for a day trip',
  'ask.idea.tripEsim': 'An eSIM for the trip',
  'ask.prompt.flight': 'Flights',
  'ask.prompt.stay': 'A place to stay',
  'ask.prompt.visa': 'A visa',
  'ask.prompt.umrah': 'An Umrah trip',
  'ask.prompt.car': 'A car',
  'ask.prompt.food': 'A table somewhere good',
  'ask.prompt.todo': 'Things to do',
  'ask.prompt.esim': 'An eSIM for the trip',
  'ask.offline.title': "You're offline.",
  'ask.offline.body': "Searching needs a connection. Everything for your trips is still on this phone, and requests to Mada send once you're back.",
  'ask.signin.title': 'Sign in to book',
  'ask.signin.body': 'Booking needs an account, so Mada can confirm with your details and your tickets land in your Wallet.',
  'ask.signin.go': 'Sign in',
  'ask.resume': 'We’re booking {place} for you. See where it is.',
  'ask.demo.title': 'Make it go wrong',
  'ask.demo.body': 'Demo switches for the mock suppliers. Nothing here is real.',
  'ask.demo.open': 'Demo',

  // ───────────── ask: one question at a time ─────────────
  'ask.q.where': 'Where to?',
  'ask.q.whichCity': 'Which city?',
  'ask.q.cityHint': 'Tbilisi, Baku, Abha…',
  'ask.q.go': 'Go',
  'ask.q.elsewhere': 'Somewhere else',
  'ask.q.when': 'When?',
  'ask.q.whenIn': 'When in {month}?',
  'ask.q.pickDates': 'I’ll pick dates',
  'ask.q.return': 'Leaving {day}. Coming back when?',
  'ask.q.after3': 'After 3 nights · {day}',
  'ask.q.afterWeek': 'After a week · {day}',
  'ask.q.oneWay': 'One way',
  'ask.q.who': "Who's going?",
  'ask.q.whoSaid': 'You said {count}. Add the others so we have their names as on their passports.',
  'ask.q.just': 'Just {name}',
  'ask.q.these': 'These {count}',
  'ask.q.addSomeone': 'Add someone',
  'ask.q.helper': '{name} (helper)',

  'person.add.body': 'Names exactly as on their passport. You can scan it later from the Wallet.',
  'person.add.given': 'Given names',
  'person.add.surname': 'Surname',
  'person.add.helperNote': "We'll ask for their iqama and exit and re-entry visa before any trip abroad.",
  'person.add.button': 'Add {name}',
  'person.add.them': 'them',
  'person.added': '{name} added. Scan their passport from the Wallet when you can.',
  'person.rel.family': 'Family',
  'person.rel.friend': 'Friend',
  'person.rel.helper': 'Helper',
  'person.rel.colleague': 'Colleague',

  // ───────────── search ─────────────
  'search.working.checking': 'Checking flights to {city}',
  'search.working.holding': 'Holding seats at this price',
  'search.working.matching': 'Matching seats and meals for {count}',
  'search.working.stays': 'Checking 120 places near your plans',
  'search.working.together': 'Keeping rooms side by side',
  'search.working.quiet': 'Picking the quiet rooms',
  'search.checked': 'Checked {count} flights · holding seats for {people}',
  'search.ways.one': 'One way to get there.',
  'search.ways.two': 'Two ways to get there.',
  'search.ways.three': 'Three ways to get there.',
  'search.summary': '{from} → {to} · {dates}',
  'search.summaryOneWay': '{date}, one way',
  'search.people.one': '1 adult',
  'search.people.other': '{count} people',
  'search.lap': '+ {count} on a lap',
  'search.flex': '±2 days',
  'search.edit': 'Edit',
  'search.a11y.edit': 'Edit search',
  'search.sort.best': 'Best',
  'search.sort.cheapest': 'Cheapest',
  'search.sort.fastest': 'Fastest',
  'search.sort.earliest': 'Earliest',
  'search.label.best': 'Best for you',
  'search.label.lowest': 'Lowest price',
  'search.label.earliest': 'Earliest',
  'search.label.fastest': 'Fastest',
  'search.label.bags': 'Two bags each',
  'search.label.quiet': 'Most quiet',
  'search.label.water': 'On the water',
  'search.direct': '{duration} · direct',
  'search.oneStop': '{duration} · 1 stop, IST',
  'search.tapAgain': 'Tap again for bags and change rules',
  'search.rule.bags': 'Bags',
  'search.rule.change': 'Change',
  'search.rule.cancel': 'Cancel',
  'search.rule.return': 'Return',
  'search.rule.lap': 'Lap infant',
  'search.rule.lapValue': '{price} each · bassinet on request',
  'search.travellers': 'Travellers',
  'search.staying': "Who's staying",
  'search.blocking.one': 'One thing to sort out before booking. It’s below the flights.',
  'search.blocking.other': '{count} things to sort out before booking. They’re below the flights.',
  'search.review': 'Review · {price}',
  'search.sortOut': 'Sort out {name}’s {thing} first',
  'search.bundle.family': 'Add connecting rooms near Galata Tower and airport pickup?',
  'search.bundle.two': 'Add a room for two near Galata Tower and airport pickup?',
  'search.bundle.one': 'Add a room near Galata Tower and airport pickup?',
  'search.bundle.helper': 'Add rooms near Galata Tower and airport pickup?',
  'search.bundle.nights.one': '1 night · {price}',
  'search.bundle.nights.other': '{count} nights · {price}',
  'search.bundle.add': 'Add',
  'search.bundle.added': 'Added',
  'search.cabinNoFirst': 'First isn’t sold on these routes. Business is the best cabin.',
  'search.rooms.connecting': '2 connecting rooms',
  'search.rooms.forTwo': '1 room for 2',
  'search.rooms.one': '1 room',
  'search.none.title': 'Nothing direct on those dates.',
  'search.none.body': 'Seats to {city} are gone on {day}. There’s room a day either side, or with one short stop.',
  'search.none.flex': 'Try a day either side',
  'search.none.stop': 'Allow one stop',
  'search.down.title': '{airline}’s system isn’t answering.',
  'search.down.body': 'The other airlines are fine. Or Mada can search {airline} by hand and come back within 20 minutes.',
  'search.down.others': 'Show the others',
  'search.down.byHand': 'Ask Mada',
  'search.down.note': 'We’ll search {airline} by hand and send you the options here within 20 minutes.',
  'search.stays.title': "Three places you'd like.",
  'search.stays.sub': '{dates} · {nights} nights · {rooms}',
  'search.stays.none.title': 'No rooms free on those dates.',
  'search.stays.none.body': 'Everything near Galata is taken for {rooms}. Mada knows places that never show online, and can look by hand.',
  'search.stays.byHand': 'Ask Mada to find rooms',
  'search.byHand.title': 'We’re searching {city} for you.',
  'search.byHand.stayTitle': 'We’re finding rooms in {city} for you.',
  'search.byHand.queued': 'Saved. We start on {city} when you’re back online.',
  'search.byHand.body': 'Options here within 20 minutes. You don’t need to stay on this screen.',
  'search.seeInTrips': 'See it in Trips',

  // ───────────── calendar ─────────────
  'cal.title': 'Your search',
  'cal.from': 'Flying from',
  'cal.type': 'Trip type',
  'cal.return': 'Return',
  'cal.oneway': 'One way',
  'cal.pickBoth': 'Pick the day you leave, then the day back',
  'cal.pickOut': 'Pick the day you leave',
  'cal.leaving': 'Leaving {day}',
  'cal.pickReturn': 'Leaving {day} · now pick the return',
  'cal.range.one': '{from} → {to} · 1 night',
  'cal.range.other': '{from} → {to} · {count} nights',
  'cal.months': 'Months',
  'cal.prev': 'Previous month',
  'cal.next': 'Next month',
  'cal.flexible': 'Flexible ±2 days',
  'cal.cabin': 'Cabin',
  'cal.cabin.economy': 'Economy',
  'cal.cabin.premium': 'Premium',
  'cal.cabin.business': 'Business',
  'cal.cabin.first': 'First',
  'cal.babies': 'Babies on a lap',
  'cal.babiesNote': 'Under 2 on the day you fly back. One per adult.',
  'cal.fewer': 'One fewer baby',
  'cal.more': 'One more baby',
  'cal.search': 'Search',
  'cal.pickDate': 'Pick a date',
  'cal.pickReturnDate': 'Pick a return date',

  // ───────────── entry checks ─────────────
  'entry.checked': 'Rules checked today · {what}',
  'entry.domestic': 'a flight inside Saudi Arabia',
  'entry.for': '{country}, for {nationalities} passports',
  'entry.forYour': '{country}, for your passports',
  'entry.passport.title': '{name} can’t travel on this passport.',
  'entry.passport.days': '{name}’s passport expires on {date}. {country} needs {days} days after you land, so it must be valid until {until}.',
  'entry.passport.trip': '{name}’s passport expires on {date}, before you’re back. It must be valid for the whole trip.',
  'entry.visa.title': '{name} needs a visa for {country}.',
  'entry.visa.has': '{name} already has the {need}.',
  'entry.visa.asked': 'Mada is getting {name}’s {need}. We check it before you fly.',
  'entry.manual': 'We don’t have {name}’s passport country yet. Mada checks the rules for {country} by hand before booking.',
  'entry.iqama.title': '{name}’s iqama runs out during the trip.',
  'entry.iqama.text': 'It expires {date}, before you’re back on {back}. It must be valid for the whole trip.',
  'entry.reentry.title': '{name} needs an exit and re-entry visa.',
  'entry.reentry.text': 'Anyone on an iqama needs one to leave Saudi Arabia and come back. It’s issued on Absher by the sponsor, usually the same day.',
  'entry.reentry.has': '{name} has an exit and re-entry visa.',
  'entry.reentry.asked': 'Mada is arranging {name}’s exit and re-entry visa. We check it before you fly.',
  'entry.eta.text': 'Each Saudi passport needs a UK ETA. It’s online, GBP 16, usually ready in 3 days.',
  'entry.eta.asked': 'Mada is applying for everyone’s UK ETA. We check them before you fly.',
  'entry.eta.ask': 'Ask Mada to apply',
  'entry.visa.ask': 'Ask Mada to get it',
  'entry.reentry.ask': 'Ask Mada to arrange it',
  'entry.reentry.hasOne': '{name} already has one',
  'entry.iqama.renewed': 'It’s been renewed',
  'entry.passport.renew': 'Renew it first',
  'entry.passport.onIt': 'Mada is on it',
  'entry.without': 'Book without {name}',
  'entry.thing.passport': 'passport',
  'entry.thing.visa': 'visa',
  'entry.thing.iqama': 'iqama',
  'entry.thing.reentry': 'exit and re-entry visa',

  // ───────────── plans ─────────────
  'plan.working.open': 'Looking at what’s open that weekend',
  'plan.working.prayer': 'Fitting it around prayer times',
  'plan.working.prayerKids': 'Fitting it around prayer times and the kids',
  'plan.working.tables': 'Holding tables and tour slots',
  'plan.ready': "We've planned it. Change anything you like.",
  'plan.stops': '{days} days · {count} stops',
  'plan.see': 'See the plan',
  'plan.by': 'Planned by Mada · {days} days',
  'plan.yours.title': 'Make it yours',
  'plan.yours.body': "Change a day, swap a stop, or add your own. Ask, and we'll rework the plan.",
  'plan.change': 'Change something',
  'plan.changePrefill': 'Change the {title} plan',
  'plan.book': 'Book it all · {price}',
  'plan.save': 'Save for later',
  'plan.saved': 'Saved. Tap to remove',
  'plan.savedToast': 'Saved. It’s in Circles → Your circles → Saved.',
  'plan.removedToast': 'Removed from your saves.',

  // ───────────── eSIM ─────────────
  'esim.title': 'An eSIM for Türkiye, ready on landing.',
  'esim.plan': '10 GB for 7 days',
  'esim.each': '{price} each',
  'esim.body': 'Installs on each phone before you fly. Turns on when you land. Your Saudi number keeps working for calls.',

  // ───────────── requests ─────────────
  'request.q.whichVisa': 'Which visa?',
  'request.q.forWho': 'For who?',
  'request.q.whenTravel': 'When do you travel?',
  'request.q.when': 'When?',
  'request.q.whoGoing': 'Who’s going?',
  'request.q.needs': 'Anything we should arrange for each person?',
  'request.q.makkahStay': 'Where to stay in Makkah?',
  'request.q.where': 'Where?',
  'request.q.size': 'What size?',
  'request.q.howLong': 'For how long?',
  'request.q.matters': 'What matters?',
  'request.q.pick': 'Pick what you like',
  'request.done': 'Done',
  'request.nothingNeeded': 'Nothing needed',
  'request.helperVisa': "For {names} we'll also need the iqama and an exit and re-entry visa.",
  'request.mentioned': 'You mentioned {needs}. Tap it for the right person.',
  'request.oxygen': 'We’ll arrange airline approval. We need a doctor’s form 7 days before you fly.',
  'request.umrahNusuk': "Every traveller needs their own Nusuk permit. We'll remind you to get them once dates are set.",
  'request.note.label': 'Anything else we should know?',
  'request.note.hint': 'Times that suit you, a hotel you like, anyone’s health',
  'request.willVisa': 'Mada will find the earliest appointment, prepare the forms and reply here.',
  'request.willPrice': 'Mada will price it for each person and reply here.',
  'request.send': 'Send to Mada',
  'request.sent': 'Sent to Mada.',
  'request.queued': 'Saved. It sends when you’re back online.',
  'request.sentBody': 'Usually within 2 hours, any time of day.',
  'request.replied': 'Here’s the price for each of you.',
  'request.pay': 'Pay {price}',
  'request.total': 'Total',
  'request.a11y.breakdown': 'Price for each person',
  'request.a11y.thread': 'Replies',
  'request.reply': 'Reply to Mada',
  'request.a11y.send': 'Send reply',
  'request.switch': 'Switch it',
  'request.switchYes': 'Yes, switch it.',
  'request.sendsOnline': 'Sends when you’re back online',
  'request.suggest.closer': 'Can we stay closer to the Haram?',
  'request.suggest.later': 'Can we leave a day later?',
  'request.suggest.laterFlight': 'Is there a later flight?',
  'request.suggest.less': 'Can we pay less?',
  'request.suggest.dates': 'Can we change the dates?',
  'request.status.queued': 'Saved, sends when online',
  'request.status.sent': 'Sent',
  'request.status.reviewing': 'Being looked at',
  'request.status.quoted': 'Price ready',
  'request.status.paid': 'Paid',
  'request.status.done': 'Done',
  'request.status.cancelled': 'Cancelled',
  'request.title.eta': 'UK ETA for everyone',
  'request.title.evisa': '{need} for {name}',
  'request.title.reentry': 'Exit and re-entry visa for {name}',
  'request.title.renewal': 'Passport renewal for {name}',
  'request.title.flightsTo': 'Flights to {city} · {dates}',
  'request.title.staysIn': 'A place to stay in {city}',
  'request.title.airlineByHand': '{airline} flights to {city} · {dates}',
  'request.title.package': 'Booked: {title}',
  'request.paidToast': 'Paid. We’ll take it from here.',
  'request.datesLater': 'Dates to agree',

  // ───────────── the order sheet ─────────────
  'pay.back': 'Back',
  'pay.held': 'Held {time}',
  'pay.holdEnded': 'Hold ended',
  'pay.edit': 'Edit',
  'pay.justYou': 'Just you',
  'pay.promo.open': 'Have a promo code?',
  'pay.promo.label': 'Promo code',
  'pay.promo.apply': 'Apply',
  'pay.promo.line': 'Code {code} · 10% off',
  'pay.promo.remove': 'Remove',
  'pay.promo.unknown': 'We don’t know that code. Check the spelling.',
  'pay.promo.ended': 'That code ended on {date}.',
  'pay.promo.demo': 'Demo: EID10',
  'pay.credit': 'Mada credit · {price}',
  'pay.credit.use': 'Use Mada credit',
  'pay.credit.first': 'You have {price} Mada credit. It’s used first.',
  'pay.passports.title': 'Passports for {names}',
  'pay.passports.body': 'Book now and add them after. Mada holds the seats and issues the tickets once they’re in, any time in the next 48 hours.',
  'pay.passports.scanYours': 'Scan yours now',
  'pay.passports.scan': 'Scan {name}’s now',
  'pay.allIn': 'Everything included. No fees later.',
  'pay.change': 'Change',
  'pay.paidCredit': 'Paid with Mada credit',
  'pay.plan.a11y': 'How to pay',
  'pay.plan.full': 'Pay in full',
  'pay.plan.tabby': 'Tabby · 4 × {price}',
  'pay.plan.tamara': 'Tamara · 3 × {price}',
  'pay.slide': 'Slide to book · {price}',
  'pay.slideCredit': 'Slide to book · paid with credit',
  'pay.slideTabby': 'Slide to book · 4 × {price}',
  'pay.slideTamara': 'Slide to book · 3 × {price}',
  'pay.slidePay': 'Slide to pay · {price}',
  'pay.busy': 'Checking with your bank',
  'pay.agentNote': 'You’re only charged once it’s confirmed.',
  'pay.nowNote': 'Charged now.',
  'pay.demoHold': '(demo: end the hold)',
  'pay.recheck': 'Check the price again',
  'pay.recheckSame': 'Price checked again. Same price, held for 20 minutes.',
  'pay.recheckMoved': 'Price checked again. It moved by {price}, held for 20 minutes.',
  'pay.missing': 'This price is no longer here. Go back and pick again.',
  'pay.line.flight.one': '1 traveller · {airline}, {how}',
  'pay.line.flight.other': '{count} travellers · {airline}, {how}',
  'pay.line.direct': 'direct',
  'pay.line.oneStop': 'one stop',
  'pay.line.oneWay': 'one way',
  'pay.line.infants.one': '1 baby on a lap',
  'pay.line.infants.other': '{count} babies on a lap',
  'pay.line.stay': '{rooms} near Galata Tower · {count} nights',
  'pay.line.connecting': 'Connecting rooms',
  'pay.line.aRoom': 'A room',
  'pay.line.pickupBoth': 'Airport pickup both ways',
  'pay.line.pickupOut': 'Airport pickup on the way there',
  'pay.line.hotel': '{rooms} · {dates} · {count} nights',
  'pay.line.planFlights': 'Flights for {count} · Riyadh ⇄ {city}',
  'pay.line.planStay.one': '{rooms} · 1 night',
  'pay.line.planStay.other': '{rooms} · {count} nights',
  'pay.line.planTours': 'Tickets, tours and tables for {count}',
  'pay.line.quoteVisa': 'Appointment, forms and checklist',
  'pay.line.quote': 'As agreed with Mada',
  'pay.line.esim': '10 GB for 7 days × {count}',
  'pay.rule.refund': 'If you cancel, the flights come back minus {fee}.',
  'pay.rule.noRefund': 'Flights can’t be refunded, only the airport taxes. Changes cost {fee}.',
  'pay.rule.rooms': 'Rooms and pickups are free to cancel until {date}.',
  'pay.rule.stay': 'Free to cancel until {date}. After that, the first night.',
  'pay.rule.package': 'Free to cancel until 7 days before. Tours refunded in full until 48 hours before.',
  'pay.rule.quote': 'Refunded in full if we can’t deliver it.',
  'pay.rule.esim': 'Refundable until it’s installed.',
  'pay.title.esim': 'An eSIM for Türkiye',
  'pay.title.share': 'Your share · {circle}',
  'pay.line.share': '{what}, your share',
  'pay.rule.share': 'Paid to the group by card. Mada keeps a record so everyone sees it’s settled.',
  'pay.shareToast': 'Paid. Your circle can see it.',
  'pay.shareGone': 'This share is already settled.',
  'pay.people.title': "Who's travelling?",
  'pay.people.note': 'The price updates as you change it.',
  'pay.people.done': 'Done · {price}',
  'pay.offline.title': "You're offline.",
  'pay.offline.body': "Nothing was charged. Your price stays held while the timer runs. Try again once you're connected.",
  'pay.declined.title': 'Your bank said no.',
  'pay.declined.body': 'Nothing was charged. Banks sometimes block large travel payments. Try another card, or call your bank and come back. The price stays held.',
  'pay.declined.other': 'Use another card',
  'pay.price.title': 'The price went up {price} while we checked.',
  'pay.price.body': 'Airlines change fares minute to minute. Nothing was charged.',
  'pay.price.accept': 'Book at {price}',
  'pay.price.other': 'See other options',
  'pay.blocked.title': 'One thing to sort out first.',
  'pay.cancelled': 'Cancelled. Nothing was charged.',
  'pay.paidToast': 'Paid. We’ll take it from here.',
  'pay.esimToast': 'Done. The eSIMs install before you fly.',

  // ───────────── cards and the bank ─────────────
  'pay.cards.title': 'Pay with',
  'pay.cards.expires': 'Expires {date}',
  'pay.cards.add': 'Add a card',
  'pay.card.label': '{brand} ending {last}',
  'pay.card.number': 'Card number',
  'pay.card.expiry': 'Expiry',
  'pay.card.cvv': 'Security code',
  'pay.card.cvvHint': '3 digits',
  'pay.card.name': 'Name on the card',
  'pay.card.save': 'Save this card for next time',
  'pay.card.note': 'Card details go straight to the payment provider. Mada never sees the full number.',
  'pay.card.test': 'Test card: 4242 4242 4242 4242.',
  'pay.card.use': 'Use this card',
  'pay.card.amex': 'We can’t take American Express yet. Use Visa, Mastercard or mada.',
  'pay.card.luhn': 'That number doesn’t look right. Check each digit.',
  'pay.card.short': 'Card numbers have 16 digits.',
  'pay.card.brands': 'We take Visa, Mastercard and mada.',
  'pay.card.expired': 'This card has expired.',
  'pay.card.expiryShape': 'Use MM/YY, like 08/28.',
  'pay.card.provider': 'The payment provider didn’t take the card. Check the details and try once more.',
  'pay.3ds.title': 'Your bank wants to check it’s you',
  'pay.3ds.body': 'They sent a code to the number your bank has. It isn’t from Mada.',
  'pay.3ds.label': 'Code from your bank',
  'pay.3ds.wrong.one': 'That code doesn’t match. 1 try left.',
  'pay.3ds.wrong.other': 'That code doesn’t match. {count} tries left.',
  'pay.3ds.stopped': 'Your bank stopped this payment. Nothing was charged. Use another card or call your bank.',
  'pay.3ds.demo': 'Demo code: 123456',
  'pay.apple.inWallet': '{card} · in Wallet',
  'pay.apple.to': 'Pay Mada Trips for {what}',
  'pay.apple.double': 'Double-click to pay',
  'pay.apple.done': 'Done',
  'pay.apple.failed': 'Face not recognised',
  'pay.apple.passcode': 'Pay with passcode',
  'pay.apple.card': 'Your card',

  // ───────────── with Mada: the wait ─────────────
  'wait.title': 'Mada',
  'wait.live.line': '{agent} is on the line with {with}',
  'wait.live.question': '{agent} has a question for you',
  'wait.live.almost': 'Almost done',
  'wait.with.hotel': 'the hotel',
  'wait.with.guides': 'the hotel and guides',
  'wait.with.airline': 'the airline',
  'wait.a11y.time': 'Time so far',
  'wait.close': 'Close',
  'wait.eyebrow': 'Booking now',
  'wait.sub': '{day} · {time} from {from}',
  'wait.subOneWay': '{day} · {time} from {from} · one way',
  'wait.row.seats.one': 'Holding your seat',
  'wait.row.seats.other': 'Holding {count} seats together',
  'wait.row.seatsDone.one': 'Held: your seat',
  'wait.row.seatsDone.other': 'Held: {count} seats together',
  'wait.row.seatsDetail.one': 'Seat {seats}',
  'wait.row.seatsDetail.other': 'Seats {seats}',
  'wait.row.price': 'Locking the price',
  'wait.row.priceDone': 'Price locked',
  'wait.row.priceDetail': '{price}, it can’t go up now',
  'wait.row.issue.one': 'Issuing your ticket',
  'wait.row.issue.other': 'Issuing {count} tickets',
  'wait.row.issueDone.one': 'Issued: your ticket',
  'wait.row.issueDone.other': 'Issued: {count} tickets',
  'wait.row.issueDetail': '{flight} · e-tickets in your Wallet',
  'wait.row.hotel': 'Asking the hotel',
  'wait.row.hotelDone': 'Hotel said yes',
  'wait.row.hotelDetail': 'Connecting rooms, quiet side',
  'wait.row.rooms': 'Confirming rooms',
  'wait.row.roomsDone': 'Rooms confirmed',
  'wait.row.roomsDetail': 'Early check-in requested',
  'wait.row.tours': 'Booking tours and tables',
  'wait.row.toursDone': 'Tours and tables booked',
  'wait.row.toursDetail': 'Times in your plan',
  'wait.row.request': 'Arranging it',
  'wait.row.requestDone': 'Arranged',
  'wait.says': '{agent} says',
  'wait.asks': '{agent} asks',
  'wait.fare.text': '{airline} sold the last seats at that price a minute ago. The same flight is now {each} more each, {total} in all. Nothing has been charged.',
  'wait.fare.accept': 'Book at {price}',
  'wait.fare.other': 'See other flights',
  'wait.fare.stop': 'Stop',
  'wait.ticket.title': 'The airline didn’t issue the tickets',
  'wait.ticket.text': '{airline}’s system timed out. Nothing was charged and the hold on your card is released. Your seats are still held for 2 hours.',
  'wait.ticket.phone': 'Mada tries by phone',
  'wait.ticket.cancel': 'Cancel the booking',
  'wait.ticket.note': 'By phone usually takes 15 minutes. You can close the app.',
  'wait.slow': 'Taking longer than usual. {airline}’s system is slow today. You can close the app; we’ll tell you the moment it’s done.',
  'wait.question.names': '{name}’s passport has more than one given name: “{given}”. Should the ticket say exactly that?',
  'wait.question.namesYours': 'Your passport has more than one given name: “{given}”. Should the ticket say exactly that?',
  'wait.question.yes': 'Yes, as on the passport',
  'wait.question.call': 'Call me',
  'wait.question.calling': '{agent} is calling you now',
  'wait.question.thanks': 'Thanks. Carrying on.',
  'wait.note': 'Nothing leaves your card until it’s confirmed. You can close the app; we’ll tell you the moment it’s done.',
  'wait.cancelled': 'Cancelled. Nothing was charged.',
  'wait.background': 'We’re finishing it. We’ll tell you the moment it’s confirmed.',
  'wait.confirmedToast': 'Confirmed by {agent} at Mada. Booking {ref}.',

  'notify.replied.title': 'Mada replied',
  'notify.replied.body': '{agent}: your {what} is ready. Tap to see it.',

  // ───────────── confirmed ─────────────
  'done.going': "You're going to {city}.",
  'done.rooms': 'Your rooms are booked.',
  'done.paid': 'Paid.',
  'done.tickets': 'Tickets in your Wallet',
  'done.roomsBooked': 'Rooms booked',
  'done.tabby': 'Tabby: first of 4 paid',
  'done.tamara': 'Tamara: first of 3 paid',
  'done.paidWith': 'Paid with {card}',
  'done.credit': '{price} from credit',
  'done.invoice': 'VAT invoice in Trips',
  'done.watching': "We're watching the flight",
  'done.alerts.title': 'Want gate changes on this phone?',
  'done.alerts.body': 'Only things you need to act on: gate changes, delays, the moment your driver arrives. Never offers.',
  'done.alerts.allow': 'Allow alerts',
  'done.alerts.on': 'Alerts are on for this trip.',
  'done.seeTrip': 'See the trip',
  'done.done': 'Done',
} as const;
