/**
 * Circles, Discover and people (M4). Spread into the catalogue in en.ts; held to the same COPY.md lint.
 * Lifted from the prototype (Circles.jsx, Social.jsx) wherever it has the words.
 */
export const enCircles = {
  // ───────────── shared words ─────────────
  'circles.and': 'and',
  'circles.others': '{count} others',
  'circles.you': 'You',
  'circles.youLower': 'you',
  'circles.someone': 'Someone',
  'circles.mada': 'Mada',
  'circles.back': 'Circles',
  'circles.cancel': 'Cancel',
  'circles.save': 'Save',
  'circles.saved': 'Saved',
  'circles.remove': 'Remove',
  'circles.keep': 'Keep',
  'circles.keepIt': 'Keep it',
  'circles.planIt': 'Plan it',
  'circles.bookTable': 'Book a table',
  'circles.tableAsk': 'A table at {place}',
  'circles.people.one': '{count} person',
  'circles.people.other': '{count} people',
  'circles.requests.one': '{count} request',
  'circles.requests.other': '{count} requests',
  'circles.places.one': '{count} place',
  'circles.places.other': '{count} places',
  'circles.ago.now': 'just now',
  'circles.ago.min': '{n} min ago',
  'circles.ago.hours': '{n}h ago',
  'circles.ago.days.one': '{count} day ago',
  'circles.ago.days.other': '{count} days ago',
  'circles.when.today': 'Today',
  'circles.when.yesterday': 'Yesterday',
  'circles.when.days': '{n} days ago',
  'circles.when.lastWeek': 'Last week',
  'circles.when.weeks': '{n} weeks ago',
  'circles.when.lastMonth': 'Last month',
  'circles.when.months': '{n} months ago',

  // ───────────── the Circles tab ─────────────
  'circles.a11y.views': 'Circles views',
  'circles.a11y.people': 'Your people',
  'circles.a11y.peopleRequests': 'Your people, {count} request',
  'circles.a11y.new': 'New circle',
  'circles.a11y.postTip': 'Post a tip',
  'circles.new': 'New circle',
  'circles.unread': '{count} new',
  'circles.muted': 'Muted',
  'circles.friends.seeAll': 'See all',
  'circles.friends.requestsSeeAll': '{count} request · See all',
  'circles.friends.invited': 'Invited',
  'circles.known.title': 'From people you know',
  'circles.known.newest': 'Newest first',
  'circles.known.emptyTitle': 'Nothing from friends yet.',
  'circles.known.emptyBody': 'When a friend posts a tip, it shows here first, before anyone else’s.',
  'circles.known.emptyAction': 'See what’s on in Discover',
  'circles.post.checking': 'being checked',
  'circles.post.justNow': 'Just now',
  'circles.saved.title': 'Saved',
  'circles.saved.emptyTitle': 'Nothing saved yet.',
  'circles.saved.emptyBody': 'Tap the bookmark on any tip or plan in Discover. It lands here, sorted by city.',
  'circles.saved.emptyAction': 'Look around Discover',
  'circles.saved.planDays': 'Plan · {days} days',
  'circles.passport.title': 'Your passport',
  'circles.passport.none': 'No stamps yet',
  'circles.passport.countries.one': '{count} country',
  'circles.passport.countries.other': '{count} countries',
  'circles.passport.withPlaces': '{countries} · {places} Saudi places',
  'circles.passport.a11y': 'An empty passport page',
  'circles.passport.head': 'Visas · Stamps',
  'circles.passport.next': 'NEXT',
  'circles.passport.firstTrip': 'Your first stamp lands when you’re home from {city}.',
  'circles.passport.every': 'Every trip home adds a stamp.',
  'circles.passport.fills': 'It fills in by itself. Nothing to do.',
  'circles.passport.book': 'Book your first trip and this page starts to fill.',
  'circles.passport.plan': 'Plan a trip',
  'circles.passport.rank': 'You’re {position} among friends for places explored. {leader} leads with {places}.',
  'circles.passport.lead': 'You lead your friends for places explored, with {places}.',
  'circles.passport.stamp': '{city} stamp',
  'circles.passport.stampNext': '{city} stamp, after this trip',
  'circles.incoming.title': '{name} invited you to {circle}',
  'circles.incoming.sub': 'You join when you say yes.',
  'circles.incoming.join': 'Join',
  'circles.incoming.declined': 'Declined. {name} isn’t told.',

  // ───────────── who's around ─────────────
  'circles.around.here': '{name} is in {city} when you are.',
  'circles.around.shared': '{dates} · {name} shared it with you',
  'circles.around.sharedNoDates': '{name} shared it with you',
  'circles.around.more': 'More options for {name}',
  'circles.around.helloSent': 'Sent. {name} will see it next time they open Mada.',
  'circles.around.notNowDone': 'Okay. We won’t mention it again for this trip.',
  'circles.around.sayHello': 'Say hello',
  'circles.around.helloText': 'Salam. I see you’re in {city} too.',
  'circles.around.tell': 'Tell friends you’re in {city}',
  'circles.around.on': 'On for {who} · city only · ends when you fly home',
  'circles.around.whoClose': 'close friends',
  'circles.around.whoFamily': 'family only',
  'circles.around.off': 'Off. Only people you choose, city only, and it ends when you fly home.',
  'circles.around.hidden': 'Hidden. Nobody can see where you are.',
  'circles.around.sheetLabel': 'Who can see you',
  'circles.around.sheetTitle': 'Who can see you’re in {city}?',
  'circles.around.sheetBody': 'City only. Never a map, a hotel or a live location. It turns off by itself when you fly home.',
  'circles.around.picked': 'Friends I pick',
  'circles.around.close': 'Close friends',
  'circles.around.family': 'Family only',
  'circles.around.nobody': 'Nobody yet',
  'circles.around.turnOn': 'Turn on',
  'circles.around.hide': 'Don’t show me {name} here',
  'circles.around.hideSub': 'They aren’t told.',
  'circles.around.hideDone': 'Hidden. You won’t see {name} here, and they aren’t told.',

  // ───────────── reports ─────────────
  'circles.report': 'Report',
  'circles.report.sub': 'A person reviews every report.',
  'circles.report.label': 'Report',
  'circles.report.title': 'What’s wrong?',
  'circles.report.unwanted': 'Unwanted messages',
  'circles.report.impostor': 'Not who they say',
  'circles.report.unsafe': 'Something unsafe',
  'circles.report.other': 'Something else',
  'circles.report.send': 'Send report',
  'circles.report.done': 'Thanks. A person will look at this within 24 hours.',
  'circles.report.andBlock': 'Report and block',
  'circles.report.blockedDone': 'Reported and blocked. A person will look at it within 24 hours.',

  // ───────────── Discover ─────────────
  'circles.discover.on': 'On this week in',
  'circles.discover.cityA11y': '{city}. Choose a city',
  'circles.discover.whileThere': 'While you’re there, {dates}',
  'circles.discover.book': 'Book with Mada',
  'circles.discover.eventAsk': '{title} in {city}',
  'circles.discover.plans': 'Trips we’ve planned',
  'circles.discover.planPill': '{days} days · planned by Mada',
  'circles.discover.tips': 'From people who went',
  'circles.discover.filterA11y': 'Filter tips',
  'circles.discover.all': 'All',
  'circles.discover.food': 'Food',
  'circles.discover.todo': 'To do',
  'circles.discover.empty.all': 'No tips from {city} yet.',
  'circles.discover.empty.food': 'No food tips in {city} yet.',
  'circles.discover.empty.todo': 'No tips on things to do in {city} yet.',
  'circles.discover.empty.body': 'People who went share the places they loved. Been there? Yours would be the first.',
  'circles.discover.empty.action': 'Post a tip',
  'circles.discover.empty.allTips': 'All tips',
  'circles.tip.profileA11y': '{name}’s profile',
  'circles.tip.saveA11y': 'Save {place}',
  'circles.kind.food': 'Food',
  'circles.kind.todo': 'Things to do',
  'circles.rel.you': 'You',
  'circles.rel.family': 'Family',
  'circles.rel.friend': 'Friend',
  'circles.rel.following': 'You follow them',
  'circles.rel.mada': 'Mada traveller · {count} trips',
  'circles.rel.madaNew': 'On Mada',
  'circles.city.label': 'Choose a city',
  'circles.city.title': 'What’s on where?',
  'circles.city.search': 'Search a city',
  'circles.city.here': 'Where you are',
  'circles.city.trips': 'Your trips',
  'circles.city.worth': 'Worth a look',
  'circles.city.hereNow': 'Here now',
  'circles.city.planned': 'A trip we’ve planned',
  'circles.city.popular': 'Popular this month',
  'circles.city.none': 'We don’t cover {city} yet.',
  'circles.city.noneBody': 'We can still plan it with you, and we’ll tell you when Discover reaches it.',
  'circles.city.tellMe': 'Tell me when it’s here',
  'circles.city.told': 'We’ll tell you when {city} is on Discover.',

  // ───────────── post a tip, and one tip opened ─────────────
  'circles.postTip.title': 'Post a tip',
  'circles.postTip.place': 'Place',
  'circles.postTip.placeHint': 'Künefe near Galata Tower',
  'circles.postTip.tip': 'Your tip',
  'circles.postTip.tipHint': 'What should people know? When to go, what to order, who it suits.',
  'circles.postTip.photo': 'Photo (optional)',
  'circles.postTip.addPhoto': 'Add a photo',
  'circles.postTip.changePhoto': 'Change photo',
  'circles.postTip.consent': 'Everyone in this photo agreed to it being shared.',
  'circles.postTip.who': 'Who sees it',
  'circles.postTip.friends': 'Friends',
  'circles.postTip.everyone': 'Everyone on Mada',
  'circles.postTip.note': 'Tips are checked before they show. No faces of strangers, no addresses of people.',
  'circles.postTip.post': 'Post',
  'circles.postTip.postedFriends': 'Posted to your friends. It shows once it’s checked, usually within a minute.',
  'circles.postTip.postedEveryone': 'Posted to everyone on Mada. It shows once it’s checked, usually within a minute.',
  'circles.postTip.photoTooBig': 'That photo is too big. Pick one under 2 MB.',
  'circles.tipDetail.planWith': 'Plan it with Mada',
  'circles.tipDetail.thank': 'Thank {name}',
  'circles.tipDetail.thanked': '{name} will see your thanks',
  'circles.tipDetail.delete': 'Delete tip',
  'circles.tipDetail.report': 'Report this tip',
  'circles.tipDetail.reported': 'Thanks. A person will look at this tip within 24 hours.',
  'circles.tipDetail.deleteLabel': 'Delete tip',
  'circles.tipDetail.deleteTitle': 'Delete this tip?',
  'circles.tipDetail.deleteBody': 'It goes for everyone, including people who saved it.',
  'circles.tipDetail.deleteYes': 'Delete',
  'circles.tipDetail.deleted': 'Tip deleted.',
  'circles.tipDetail.gone': 'This tip is gone. The person who posted it took it down.',
  'circles.saveToast.post': 'Saved to {city}. Find it in Circles → Saved.',
  'circles.saveToast.plan': 'Saved. It’s in Circles → Saved.',
  'circles.saveToast.removed': 'Removed from Saved.',

  // ───────────── new circle ─────────────
  'circles.newCircle.step': '{n} of 2',
  'circles.newCircle.yours': 'Your circle',
  'circles.newCircle.justYou': 'Just you, for now',
  'circles.newCircle.andMore': 'You and {count} more',
  'circles.newCircle.cover': 'Cover',
  'circles.newCircle.plain': 'Plain green',
  'circles.newCircle.name': 'Name it',
  'circles.newCircle.nameHint': 'Summer in Baku',
  'circles.newCircle.dupe': 'You already have a circle called {name}.',
  'circles.newCircle.next': 'Next',
  'circles.newCircle.who': 'Who’s in {name}?',
  'circles.newCircle.whoSub': 'They get an invite and join when they say yes.',
  'circles.newCircle.picked': 'Invited so far',
  'circles.newCircle.removeA11y': 'Remove {name}',
  'circles.newCircle.search': 'Search anyone on Mada, by name or number',
  'circles.newCircle.searchA11y': 'Search people on Mada',
  'circles.newCircle.noNumber': 'That number isn’t on Mada yet.',
  'circles.newCircle.noName': 'Nobody called “{q}” on Mada yet.',
  'circles.newCircle.sendLink': 'Send them an invite link',
  'circles.newCircle.family': 'Family',
  'circles.newCircle.friends': 'Friends',
  'circles.newCircle.nobody': 'Search for anyone already on Mada above, or send a link to people who aren’t.',
  'circles.newCircle.inviteLink': 'Invite someone not on Mada',
  'circles.newCircle.make': 'Make {name}',
  'circles.newCircle.makeLater': 'Make {name}, invite later',
  'circles.newCircle.tagFriend': 'Friend',
  'circles.newCircle.tagFamily': 'Family',
  'circles.newCircle.tagMada': 'On Mada · {count} friends in common',
  'circles.newCircle.made': 'Circle made. Invite sent to {names}.',
  'circles.newCircle.madeAlone': 'Circle made. Share the link to bring people in.',

  // ───────────── invite links ─────────────
  'circles.invite.label': 'Invite with a link',
  'circles.invite.title': 'Invite to {what}',
  'circles.invite.body': 'They open the link, add their own passport and can pay their own share. Nothing is shared until they join.',
  'circles.invite.linkA11y': 'Invite link',
  'circles.invite.copy': 'Copy invite link',
  'circles.invite.shareNative': 'Share invite link',
  'circles.invite.copied': 'Link copied. Paste it in WhatsApp.',
  'circles.invite.copyRefused': 'Select the link above to copy it.',
  'circles.invite.shareText': 'Join me on Mada Trips: {url}',
  'circles.invite.mada': 'Mada',
  'circles.invite.list': 'your {city} list',
  'circles.invite.yourCircle': 'your circle',
  'circles.invite.cancelled': 'Invite cancelled. {name} isn’t told.',
  'circles.invite.reminded': 'Reminder sent to {name}.',

  // ───────────── a circle's chat ─────────────
  'circles.chat.settingsA11y': '{name} settings and people',
  'circles.chat.invited': '{count} invited',
  'circles.chat.muted': 'muted',
  'circles.chat.openVote': 'Open vote',
  'circles.chat.pinnedPlan': 'Pinned plan',
  'circles.chat.voted': '{q} · {n} of {total} voted',
  'circles.chat.startsHere': '{name} starts here.',
  'circles.chat.startsBody': 'Every vote, plan and split you make together lives here, in order.',
  'circles.chat.dmTitle': 'Say salam to {name}.',
  'circles.chat.dmBody': 'Just you two. A hello, a place you saved, a plan for the weekend.',
  'circles.chat.ideasA11y': 'Ideas',
  'circles.chat.idea.salam': 'Salam',
  'circles.chat.idea.free': 'Free this weekend?',
  'circles.chat.gone': 'This circle is gone.',
  'circles.chat.goneBody': 'You left it, or the admin deleted it. Bookings you made are still in Trips.',
  'circles.chat.startedVote': '{who} started a vote',
  'circles.chat.splitCost': '{who} split a cost',
  'circles.chat.sharedPlan': '{who} shared a plan',
  'circles.chat.sharedPlace': '{who} shared a place',
  'circles.chat.invitePeople': 'Invite people',
  'circles.chat.startVote': 'Start a vote',
  'circles.chat.split': 'Split a cost',
  'circles.chat.seen': 'Seen',
  'circles.chat.seenBy': 'Seen by {names}',
  'circles.chat.madaTyping': 'Mada is looking into it',
  'circles.chat.tools': 'Circle tools: vote, split, share, ask Mada',
  'circles.chat.input': 'Message the group',
  'circles.chat.placeholder': 'Message, or @Mada',
  'circles.chat.placeholderDm': 'Message {name}',
  'circles.chat.send': 'Send',
  'circles.chat.older': 'Earlier messages',
  'circles.chat.notSent': 'Not sent. Tap send to try again.',
  'circles.tools.title': 'Add to the circle',
  'circles.tools.voteSub': 'Dates, places, anything. Everyone taps once.',
  'circles.tools.splitSub': 'Who paid, who owes. Pay your share here.',
  'circles.tools.splitSubAlone': 'Works once someone joins.',
  'circles.tools.share': 'Share a plan or place',
  'circles.tools.shareSub': 'From our plans and your saves.',
  'circles.tools.askSub': 'Ideas, flights, stays and visas for {dest}.',
  'circles.tools.askSubAny': 'Ideas, flights, stays and visas.',
  'circles.vote.closedWon': 'Closed · {label} won',
  'circles.vote.closedTie': 'Closed · a tie',
  'circles.vote.count': '{n} of {total} voted',
  'circles.vote.youPicked': 'you picked {label}',
  'circles.vote.close': 'Close vote',
  'circles.vote.opt.one': '{label}, {count} vote',
  'circles.vote.opt.other': '{label}, {count} votes',
  'circles.split.paidBy': 'Paid by {who} · {mode}',
  'circles.split.modeFamily': 'split by family',
  'circles.split.modeCustom': 'custom amounts',
  'circles.split.modeEqual': 'split equally',
  'circles.split.settled': 'Settled',
  'circles.split.paidBill': 'Paid the bill',
  'circles.split.paid': 'Paid',
  'circles.split.yourShare': 'Your share',
  'circles.split.owes': 'Owes {who}',
  'circles.split.markPaid': 'Mark paid',
  'circles.split.payMine': 'Pay my share · {amount}',
  'circles.split.cash': 'I paid in cash',
  'circles.split.reminded': 'Reminded today',
  'circles.split.remind': 'Remind {names}',
  'circles.split.allPaid': 'Everyone’s paid. Nothing to chase.',
  'circles.split.remindToast': 'Reminder sent to {names}.',
  'circles.split.yourFamily': 'Your family',
  'circles.split.family': '{name}’s family',
  'circles.share.plan': 'Plan · {days} days',
  'circles.share.pin': 'Pin',
  'circles.share.yourTip': 'your tip',
  'circles.share.tipOf': '{name}’s tip',
  'circles.voteSheet.q': 'Question',
  'circles.voteSheet.qPlaces': 'Where should we go?',
  'circles.voteSheet.qDates': 'Which evening for dinner?',
  'circles.voteSheet.qAny': 'Shall we book the van?',
  'circles.voteSheet.dates': 'Dates',
  'circles.voteSheet.places': 'Places',
  'circles.voteSheet.any': 'Anything',
  'circles.voteSheet.kindA11y': 'Kind of vote',
  'circles.voteSheet.choice': 'Choice {n}',
  'circles.voteSheet.removeChoice': 'Remove choice {n}',
  'circles.voteSheet.add': 'Add a choice',
  'circles.voteSheet.quick': 'Quick choices',
  'circles.voteSheet.yes': 'Yes',
  'circles.voteSheet.no': 'No',
  'circles.voteSheet.maybe': 'Maybe',
  'circles.voteSheet.needQ': 'Add a question.',
  'circles.voteSheet.dup': 'Two choices are the same.',
  'circles.voteSheet.need2': 'Add at least 2 choices.',
  'circles.voteSheet.post': 'Post the vote',
  'circles.splitSheet.what': 'What for',
  'circles.splitSheet.whatHint': 'Dinner on the Bosphorus',
  'circles.splitSheet.dinner': 'Dinner',
  'circles.splitSheet.hotel': 'Hotel',
  'circles.splitSheet.van': 'Airport van',
  'circles.splitSheet.tickets': 'Tickets',
  'circles.splitSheet.total': 'Total',
  'circles.splitSheet.totalHint': '1,200',
  'circles.splitSheet.paidBy': 'Paid by',
  'circles.splitSheet.between': 'Between',
  'circles.splitSheet.how': 'How to split',
  'circles.splitSheet.equally': 'Equally',
  'circles.splitSheet.byFamily': 'By family',
  'circles.splitSheet.custom': 'Custom',
  'circles.splitSheet.shareA11y': '{name}’s share',
  'circles.splitSheet.addsUp': 'Adds up to {amount}.',
  'circles.splitSheet.left': '{amount} still to share out.',
  'circles.splitSheet.over': '{amount} more than the total.',
  'circles.splitSheet.pick2': 'Pick at least 2 people.',
  'circles.splitSheet.go': 'Split {amount}',
  'circles.splitSheet.idle': 'Split it',
  'circles.shareSheet.plans': 'Plans we’ve made',
  'circles.shareSheet.planSub': '{days} days · {city}',
  'circles.shareSheet.pin': 'Pin the plan to the top of the circle',
  'circles.shareSheet.saves': 'Your saved places',
  'circles.shareSheet.none': 'Nothing saved yet. Bookmark a tip in Discover and you can share it here.',
  'circles.shareSheet.from': '{city} · from {name}',

  // ───────────── what Mada says in a circle ─────────────
  'circles.mada.where': 'Where are you thinking? Tell us a place and we’ll bring ideas for all {n}.',
  'circles.mada.where.one': 'Where are you thinking? Tell us a place and we’ll bring ideas for you.',
  'circles.mada.you': 'you',
  'circles.mada.all': 'all {n}',
  'circles.mada.planIt': 'Plan it',
  'circles.mada.planAsk': 'Plan a trip to {dest} for {n}',
  'circles.mada.unknown': 'We don’t have ready ideas for {dest} yet. We can plan it with you from scratch, for {who}.',
  'circles.mada.visaCheck': 'We check every passport in the circle before anything is booked.',
  'circles.mada.flights': '{dest} is {fly}. Flights from {from} a person. We can hold seats for {who}, together.',
  'circles.mada.findFlights': 'Find flights',
  'circles.mada.flightsAsk': 'Flights to {dest} for {n}',
  'circles.mada.home': '{dest} is home. No flights needed.',
  'circles.mada.stay': 'Where to stay in {dest}: {stay}',
  'circles.mada.seeStays': 'See stays',
  'circles.mada.staysAsk': 'A place to stay in {dest} for {n}',
  'circles.mada.when': 'Best time for {dest}: {when}',
  'circles.mada.onePerson': 'one person',
  'circles.mada.people': '{n} people',
  'circles.mada.cost': 'For {people}, 4 nights in {dest} is usually {lo}–{hi} with flights and a hotel. We price it exactly when you ask.',
  'circles.mada.ideas': 'Three ideas for {dest}, for {who}:',
  'circles.mada.ideasFoot': '{fly}, from {from} a person.',
  'circles.mada.seePlan': 'See our plan',
  'circles.mada.result': '{phrase} it is. Want us to book it?',
  'circles.mada.bookIt': 'Book it',
  'circles.mada.notNow': 'Not now',
  'circles.mada.tie': 'It’s a tie between {options}. Pick one and we’ll take it from there.',
  'circles.mada.welcomeOthers': 'This is {name}. Plan here, vote on choices and split costs. Type @Mada to ask us anything. Your Mada agent confirms anything you book.',
  'circles.mada.welcomeInvited.one': 'This is {name}. {names} is invited. Start planning while you wait.',
  'circles.mada.welcomeInvited.other': 'This is {name}. {names} are invited. Start planning while you wait.',
  'circles.mada.welcomeAlone': 'This is {name}. It’s just you so far. Share the link and people join when they open it.',
  'circles.mada.ideasFor': 'Ideas for {dest}',
  'circles.mada.aTrip': 'a trip',
  'circles.mada.ideasMsg': '@Mada ideas for {dest}',
  'circles.mada.fallback': 'We’ll answer that one in Ask. Send it to Mada from there.',

  // ───────────── system lines in a chat ─────────────
  'circles.sys.created.you': 'You made the circle',
  'circles.sys.created': '{name} made the circle',
  'circles.sys.invited.you': 'You invited {names}',
  'circles.sys.invited': '{name} invited {names}',
  'circles.sys.joined.you': 'You joined',
  'circles.sys.joined': '{name} joined',
  'circles.sys.joinedByLink.you': 'You joined from {name}’s link',
  'circles.sys.joinedByLink': '{name} joined from a link',
  'circles.sys.left.you': 'You left the circle',
  'circles.sys.left': '{name} left the circle',
  'circles.sys.removed.you': 'You removed {names}',
  'circles.sys.removed': '{name} removed {names}',
  'circles.sys.renamed.you': 'You renamed the circle to {text}',
  'circles.sys.renamed': '{name} renamed the circle to {text}',
  'circles.sys.admin.you': 'You’re the admin now',
  'circles.sys.admin': '{names} is the admin now',
  'circles.sys.pinned.you': 'You pinned {text}',
  'circles.sys.pinned': '{name} pinned {text}',
  'circles.sys.cancelledInvite.you': 'You cancelled {names}’s invite',
  'circles.sys.cancelledInvite': '{name} cancelled an invite',
  'circles.sys.paid.you': 'You paid your share · {amount}',
  'circles.sys.paid': '{name} paid their share · {amount}',
  'circles.sys.markedPaid.self': 'You marked your share as paid · {amount}',
  'circles.sys.markedPaid.you': 'You marked {names} as paid',
  'circles.sys.markedPaid.theirs': '{name} marked their share as paid · {amount}',
  'circles.sys.markedPaid': '{name} marked {names} as paid',
  'circles.sys.reminded.you': 'You reminded {names}',
  'circles.sys.reminded': '{name} sent a reminder to {names}',
  'circles.sys.dm': 'Messages with {name} stay between you two.',
  'circles.last.nothing': 'Nothing yet',
  'circles.last.vote': 'Vote: {q}',
  'circles.last.voteClosed': 'Vote closed: {q}',
  'circles.last.split': 'Split: {what}',
  'circles.last.settled': 'Settled: {what}',
  'circles.last.shared': '{who} shared {what}',
  'circles.last.line': '{who}: {text}',

  // ───────────── circle settings ─────────────
  'circles.settings.label': 'Circle settings',
  'circles.settings.rename': 'Rename',
  'circles.settings.adminYou': 'you’re the admin',
  'circles.settings.admin': '{name} is the admin',
  'circles.settings.roleAdmin': 'Admin',
  'circles.settings.roleFamily': 'Family',
  'circles.settings.invitedPill': 'Invited',
  'circles.settings.invitedA11y': '{name}, invited',
  'circles.settings.sent': 'Sent {ago}',
  'circles.settings.remindedTag': 'reminded',
  'circles.settings.noAnswer': 'no answer yet',
  'circles.settings.remind': 'Remind',
  'circles.settings.reminded': 'Reminded',
  'circles.settings.cancelInvite': 'Cancel invite',
  'circles.settings.addPeople': 'Add people',
  'circles.settings.mute': 'Mute',
  'circles.settings.muteSub': 'Bookings and votes still reach you.',
  'circles.settings.muteA11y': 'Mute this circle',
  'circles.settings.mutedToast': 'Muted.',
  'circles.settings.unmutedToast': 'Unmuted.',
  'circles.settings.leave': 'Leave the circle',
  'circles.settings.delete': 'Delete the circle',
  'circles.settings.deleteAll': 'Delete for everyone',
  'circles.rename.title': 'Rename the circle',
  'circles.rename.a11y': 'Circle name',
  'circles.rename.note': 'Everyone in the circle sees the new name.',
  'circles.rename.done': 'Renamed.',
  'circles.add.title': 'Invite people',
  'circles.add.none': 'Everyone you know on Mada is already here or invited. Invite others with a link.',
  'circles.add.go': 'Invite {count}',
  'circles.add.idle': 'Invite',
  'circles.add.sent': 'Invite sent to {names}.',
  'circles.member.member': 'Member',
  'circles.member.makeAdmin': 'Make {name} the admin',
  'circles.member.makeAdminSub': 'You stay in the circle.',
  'circles.member.adminDone': '{name} is the admin now.',
  'circles.member.remove': 'Remove from the circle',
  'circles.member.removeSub': 'Their messages stay. They lose access to shared plans.',
  'circles.member.removed': '{name} is out of the circle.',
  'circles.member.onlyAdmin': 'Only the admin, {name}, can add or remove people.',
  'circles.member.profile': 'See profile',
  'circles.leave.title': 'Leave {name}?',
  'circles.leave.deleteTitle': 'Delete {name}?',
  'circles.leave.bodyAdmin': '{name} becomes the admin. Bookings you made stay yours.',
  'circles.leave.body': 'You won’t see new messages. Bookings you made stay yours.',
  'circles.leave.bodyInvited': 'Nobody has joined yet, so the circle and its invites are deleted.',
  'circles.leave.bodyAlone': 'You’re the only one here, so the circle is deleted.',
  'circles.leave.leave': 'Leave',
  'circles.leave.delete': 'Delete',
  'circles.leave.stay': 'Stay',
  'circles.leave.left': 'You left {name}.',
  'circles.leave.deleted': '{name} is deleted.',
  'circles.deleteAll.title': 'Delete it for everyone?',
  'circles.deleteAll.body': 'Messages, votes and shared plans go for all {count}. Bookings stay with whoever made them.',

  // ───────────── your people ─────────────
  'circles.people.title': 'Your people',
  'circles.people.tabsA11y': 'People',
  'circles.people.friends': 'Friends',
  'circles.people.following': 'Following',
  'circles.people.invited': 'Invited',
  'circles.people.requests': 'Requests',
  'circles.people.going': 'Going to {going}',
  'circles.people.explored': '{count} places explored',
  'circles.people.friendsEmptyTitle': 'No friends here yet.',
  'circles.people.friendsEmptyBody': 'Add the people you travel with. Only they see your trips, tips and plans.',
  'circles.people.followingSub': '{count} trips · public tips',
  'circles.people.followingEmptyTitle': 'You don’t follow anyone yet.',
  'circles.people.followingEmptyBody': 'Follow people whose taste you trust. Their public tips show up first in Discover.',
  'circles.people.followingEmptyAction': 'Find people in Discover',
  'circles.people.joined': 'Joined',
  'circles.people.expired': 'Link expired',
  'circles.people.notYet': 'Not yet',
  'circles.people.sentBy': 'Sent by {channel} · {when}',
  'circles.people.remindedToday': 'reminded today',
  'circles.people.channel.link': 'link',
  'circles.people.channel.sms': 'SMS',
  'circles.people.channel.whatsapp': 'WhatsApp',
  'circles.people.remindToast': 'Reminder sent to {name} by {channel}.',
  'circles.people.cancelToast': 'Invite cancelled. The link no longer works.',
  'circles.people.see': 'See {name}',
  'circles.people.invitedEmptyTitle': 'Nobody invited yet.',
  'circles.people.invitedEmptyBody': 'Send your link on WhatsApp. It lasts 14 days, and you’ll see here the moment someone joins.',
  'circles.people.shareLink': 'Share your invite link',
  'circles.people.requestSub': '{trips} trips · {mutual} friends in common',
  'circles.people.accept': 'Accept',
  'circles.people.decline': 'Decline',
  'circles.people.block': 'Block',
  'circles.people.friendsNow': 'You and {name} are friends.',
  'circles.people.declined': 'Declined. {name} isn’t told.',
  'circles.people.blocked': 'Blocked. {name} can’t find or message you.',
  'circles.people.requestsEmptyTitle': 'No requests.',
  'circles.people.requestsEmptyBody': 'When someone asks to be your friend, it shows here. You decide, and they aren’t told if you say no.',
  'circles.addFriends.title': 'Add friends',
  'circles.addFriends.contacts': 'From your contacts',
  'circles.addFriends.contactsSub': 'See who’s already on Mada. Your contacts aren’t uploaded.',
  'circles.addFriends.byPhone': 'By phone number',
  'circles.addFriends.phoneHint': '5X XXX XXXX',
  'circles.addFriends.phoneBad': 'Saudi mobile numbers start with 5 and have 9 digits.',
  'circles.addFriends.already': '{name} is already your friend.',
  'circles.addFriends.onMada': 'On Mada',
  'circles.addFriends.add': 'Add',
  'circles.addFriends.sent': 'Sent',
  'circles.addFriends.requestSent': 'Request sent.',
  'circles.addFriends.notOnMada': 'Not on Mada yet.',
  'circles.addFriends.inviteSms': 'Invite them by SMS',
  'circles.addFriends.smsSent': 'Invite sent by SMS.',
  'circles.contacts.askLabel': 'Contacts access',
  'circles.contacts.askTitle': 'See which of your contacts are on Mada?',
  'circles.contacts.askBody': 'To show who’s already on Mada. Numbers are matched on this phone and never stored.',
  'circles.contacts.allow': 'Allow',
  'circles.contacts.deny': 'Don’t allow',
  'circles.contacts.deniedLabel': 'No contacts',
  'circles.contacts.deniedTitle': 'That’s fine.',
  'circles.contacts.deniedBody': 'Add friends by phone number or send your link instead. You can allow contacts later in Settings.',
  'circles.contacts.foundLabel': 'Contacts on Mada',
  'circles.contacts.foundTitle': 'On Mada from your contacts',
  'circles.contacts.mutual': '{count} friends in common',
  'circles.contacts.allFriends': 'Everyone in your contacts on Mada is already your friend.',
  'circles.contacts.none': 'Nobody in your contacts is on Mada yet. Send them your link.',

  // ───────────── a friend's page ─────────────
  'circles.friend.gone': 'This person isn’t on Mada any more.',
  'circles.friend.more': 'More options for {name}',
  'circles.friend.since': 'Friends since {year}',
  'circles.friend.sinceToday': 'Friends since today',
  'circles.friend.youFollow': 'You follow them',
  'circles.friend.tripsWith': '{count} trips with Mada',
  'circles.friend.stats': '{lead} · {places} places · {followers} followers',
  'circles.friend.inCity': 'In {city} when you are',
  'circles.friend.inCitySub': '{dates} · {name} shared it with you',
  'circles.friend.message': 'Message',
  'circles.friend.follow': 'Follow',
  'circles.friend.following': 'Following',
  'circles.friend.followToast': 'Following {name}. Their public tips show in your feed.',
  'circles.friend.unfollowToast': 'Unfollowed {name}.',
  'circles.friend.acceptRequest': 'Accept friend request',
  'circles.friend.add': 'Add friend',
  'circles.friend.asked': 'Asked',
  'circles.friend.askedToast': 'Asked {name}. Friends see each other’s trips and private tips.',
  'circles.friend.planTogether': 'Plan a trip together',
  'circles.friend.followNote': 'Following shows you {name}’s public tips. Only friends see each other’s trips and where they are.',
  'circles.friend.circlesTogether': 'Circles together',
  'circles.friend.tips': '{name}’s tips',
  'circles.friend.noTips': '{name} hasn’t posted a tip yet.',
  'circles.friend.hideAround': 'Hide from Who’s around',
  'circles.friend.hideAroundSub': 'They aren’t told.',
  'circles.friend.hideAroundToast': 'You won’t see {name} in Who’s around. They aren’t told.',
  'circles.friend.remove': 'Remove friend',
  'circles.friend.removeSub': 'You stay in circles you share.',
  'circles.friend.reportBlock': 'Report or block',
  'circles.friend.reportBlockSub': 'A person reviews every report within 24 hours.',
  'circles.friend.removeTitle': 'Remove {name}?',
  'circles.friend.removeBody': 'They won’t see your tips or where you are. They aren’t told.',
  'circles.friend.removed': 'Removed {name}.',
  'circles.friend.blockedTitle': 'You blocked {name}.',
  'circles.friend.blockedBody': 'They can’t find or message you. Unblock to see their page again.',
  'circles.friend.unblock': 'Unblock',
  'circles.friend.unblocked': 'Unblocked {name}.',

  // ───────────── saved ─────────────
  'circles.savedScreen.inCity': 'Saved in {city}',
  'circles.savedScreen.emptyBody': 'Tap the bookmark on any tip or plan. It lands here, sorted by city, ready to plan or share with a circle.',
  'circles.savedScreen.dayFrom': 'Plan a day from these',
  'circles.savedScreen.dayAsk': 'Plan a day in {city} around {places}',
  'circles.savedScreen.share': 'Share',
  'circles.savedScreen.from': 'From {name} · {kind}',
  'circles.savedScreen.map': 'Map',
  'circles.savedScreen.plans': 'Saved plans',

  // ───────────── joining from a link ─────────────
  'circles.join.expiredTitle': 'This invite has expired.',
  'circles.join.expiredBody': 'Invite links last 14 days. Ask {name} to send a new one. It takes them two taps.',
  'circles.join.cancelledTitle': 'This invite no longer works.',
  'circles.join.cancelledBody': '{name} cancelled it. Ask them for a new link if you still want to join.',
  'circles.join.askOnWhatsApp': 'Ask {name} on WhatsApp',
  'circles.join.backToMada': 'Back to Mada',
  'circles.join.lookAround': 'Look around Mada',
  'circles.join.invitedYou': '{name} invited you',
  'circles.join.areIn': '{names} are in',
  'circles.join.isIn': '{names} is in',
  'circles.join.theySee': 'If you join, they see',
  'circles.join.theySeeBody': 'Your name, photo and what you post in the circle. Never your passport, payments or where you are.',
  'circles.join.join': 'Join the circle',
  'circles.join.joinWithMada': 'Join with Mada',
  'circles.join.takesAMinute': 'Takes a minute. Your passport can wait.',
  'circles.join.joined': 'You’re in. {name} can see you joined.',
  'circles.join.already': 'You’re already in {name}.',
  'circles.join.madaTitle': 'Travel with {name}.',
  'circles.join.madaBody': 'Plan trips together, vote on dates and split the costs. Only friends see your trips.',
  'circles.join.addFriend': 'Add {name} as a friend',
  'circles.join.notFound': 'We can’t find that invite.',

  // ───────────── problems the server reports ─────────────
  'circles.err.notMember': 'You’re not in this circle.',
  'circles.err.adminOnly': 'Only the admin can do that.',
  'circles.err.blocked': 'You can’t reach this person on Mada.',
  'circles.err.inviteExpired': 'This invite has expired.',
  'circles.err.voteClosed': 'This vote is closed.',
  'circles.err.splitSum': 'The shares don’t add up to the total.',
  'circles.err.self': 'That’s you.',
  'circles.err.alreadyReminded': 'You already sent a reminder today.',
  'circles.err.dupeName': 'You already have a circle with that name.',

  // ───────────── messages that leave the app ─────────────
  'sms.circles.invite': '{name} invited you to Mada Trips: {url}',
  'sms.circles.remind': '{name} is waiting for you on Mada Trips: {url}',
  'notify.circles.invite.title': '{name} invited you',
  'notify.circles.invite.body': '{circle}. You join when you say yes.',
  'notify.circles.share.title': 'A share to settle',
  'notify.circles.share.body': '{name} reminded you: {what}, {amount}.',
  'notify.circles.friend.title': '{name} wants to be friends',
  'notify.circles.friend.body': 'Accept or decline in Circles. They aren’t told if you say no.',
  'notify.circles.thanks.title': '{name} thanked you',
  'notify.circles.thanks.body': 'For your tip on {place}.',
  'notify.circles.hello.title': '{name} said hello',
  'notify.circles.hello.body': 'You’re both in {city}.',
} as const;
