/**
 * The trip companion's words (M3): Today's phases, Trips, trip management, refunds, invoices, disruption and the inbox.
 * Lifted from the prototype (docs/app/prototype-app/src/screens/Today.jsx, Trips.jsx, TripManage.jsx, Disruption.jsx),
 * with the COPY.md §1 rule: buttons say Mada, a person is named only as presence or when they acted ({agent}).
 * Spread into the main catalogue in ./en.ts, so the same lint applies.
 */
import { enTripsToday } from './en-trips-today';
import { enTripsUi } from './en-trips-ui';
import { enTripsUi2 } from './en-trips-ui2';

export const enTrips = {
  ...enTripsToday,
  ...enTripsUi,
  ...enTripsUi2,
  // ───────────── trip: shared words ─────────────
  'trip.and': 'and',
  'trip.ofYou.one': 'you',
  'trip.ofYou.two': 'you two',
  'trip.ofYou.many': 'the {n} of you',
  'trip.oneWay': 'one way',
  'trip.yourDriver': 'Your driver',
  'trip.yourName': 'your name',
  'trip.theAirline': 'the airline',
  'trip.aRoom': 'A room',
  'trip.aRoomCap': 'Room',
  'trip.connectingRooms': 'Connecting rooms',
  'trip.cabin.economy': 'Economy',
  'trip.cabin.premium': 'Premium',
  'trip.cabin.business': 'Business',
  'trip.cabin.first': 'First',
  'trip.with.airline': 'the airline',
  'trip.with.hotel': 'the hotel',
  'trip.with.faisal': 'Mada',
  'trip.legs.flight': 'the flight',
  'trip.legs.back': 'the way back',
  'trip.legs.both': 'both flights',

  // fare and refund rules
  'trip.rule.flight.flown': 'The flight is flown.',
  'trip.rule.flights.flown': 'Both flights are flown.',
  'trip.rule.flight.nothingLeft': 'There’s nothing left on the tickets to refund.',
  'trip.rule.airlineCancelled': '{airline} cancelled this flight.',
  'trip.rule.gaca': 'Under GACA rules you get the full price back, fees and all.',
  'trip.rule.refundable': '{airline} fare: refund minus SAR {fee} per person.',
  'trip.rule.refundable.used': '{airline} fare: refund minus SAR {fee} per person, for the unused way back.',
  'trip.rule.refundable.why': 'Fee for {n}: {fee}. Refunds {legs}.',
  'trip.rule.refundable.usedWhy': 'You’ve flown the way there. The way back is unused, so that half comes back, minus the fee.',
  'trip.rule.taxesOnly': 'This {airline} fare can’t be refunded. Airport taxes can: SAR {tax} per person.',
  'trip.rule.taxesOnly.used': 'This {airline} fare can’t be refunded. Airport taxes can: SAR {tax} per person for the return.',
  'trip.rule.taxesOnly.why': 'The airline never pays those taxes if you don’t fly, so they come back to you. The fare itself doesn’t.',
  'trip.rule.stay.over': 'Your stay is over.',
  'trip.rule.stay.overWhy': 'Every night was used.',
  'trip.rule.freeCancelled': 'Free, because the flight was cancelled.',
  'trip.rule.stay.waived': 'The hotel waives its rule when the airline cancels. We already told them.',
  'trip.rule.stay.used': 'Tonight is used. The hotel keeps one more night as its fee.',
  'trip.rule.stay.usedWhy': '{nights} unused nights, minus one night ({night}).',
  'trip.rule.stay.free': 'Free to cancel until {day}.',
  'trip.rule.stay.freeWhy': 'Every riyal comes back.',
  'trip.rule.stay.late': 'After {day} the hotel keeps the first night, {night}.',
  'trip.rule.stay.lateWhy': 'The other nights come back.',
  'trip.rule.pickup.bothDone': 'Both rides are done.',
  'trip.rule.pickup.allDone': 'All four rides are done.',
  'trip.rule.pickup.half': 'The rides there are done. The rides home aren’t.',
  'trip.rule.pickup.halfWhy': 'Half comes back.',
  'trip.rule.pickup.inside24': 'Inside 24 hours, the driver is paid in full.',
  'trip.rule.pickup.inside24Why': '{driver} is booked for the morning. Mada can still ask.',
  'trip.rule.pickup.free': 'Free to cancel until 24 hours before.',
  'trip.rule.extra.free': 'Free to cancel until 48 hours before.',
  'trip.rule.extra.inside48': 'Inside 48 hours this can’t be refunded.',
  'trip.rule.extra.inside48Why': 'The place is holding it for you. Mada can still ask.',
  'trip.rule.change': 'A flight change is paid to the airline and can’t come back.',

  // changing a flight
  'trip.change.backOn': 'Back on {day}.',
  'trip.change.oneWay': 'One way.',
  'trip.change.dayEarlier': 'A day earlier.',
  'trip.change.dayLater': 'A day later.',
  'trip.change.noSeats': 'No {n} seats left on this flight.',
  'trip.change.flyOn': 'You fly on {day}',
  'trip.change.onFlight': 'You’re on {code} at {time}',
  'trip.change.early': 'Earliest, and the lowest price. Lands in time for lunch.',
  'trip.change.evening': 'Evening. A slow morning at home.',
  'trip.change.homeOn': 'You come home on {day}',
  'trip.change.homeAt': 'You come home at {time} instead',
  'trip.change.sooner': 'A day sooner. The hotel keeps one night as its fee.',
  'trip.change.longer': 'A day longer. Add a night at the hotel too.',
  'trip.change.later': 'Same day, later. Lands 01:50.',
  'trip.change.oneSooner': 'A day sooner.',
  'trip.change.twoSooner': 'Two days sooner.',

  // ───────────── requests ─────────────
  'rq.queued': 'Waiting for a connection',
  'rq.sent': 'Sent to Mada',
  'rq.onIt': '{agent} is on it',
  'rq.asking': '{agent} is asking {who}',
  'rq.needsAnswer': 'Mada has a question',
  'rq.priceReady': 'Price ready',
  'rq.confirmedBy': 'Confirmed by {who}',
  'rq.done': 'Done',
  'rq.cant': 'Can’t do it',
  'rq.cancelled': 'Cancelled',

  // ───────────── special requests ─────────────
  'sr.everyone': 'everyone',
  'sr.bothFlights': 'Both flights',
  'sr.theFlight': 'The flight',
  'sr.hotel': 'Hotel',
  'sr.noFlights': 'There are no flights on this trip, so there’s nothing to ask {airline} for.',
  'sr.wheelchair.title.gate': 'Wheelchair to the gate',
  'sr.wheelchair.title.seat': 'Wheelchair to the seat',
  'sr.wheelchair.title.own': 'Wheelchair (own chair)',
  'sr.wheelchair.short': 'Wheelchair · {who}',
  'sr.meal.child': 'Child meal',
  'sr.meal.veg': 'Vegetarian meal',
  'sr.meal.diabetic': 'Diabetic meal',
  'sr.meal.gluten': 'Gluten-free meal',
  'sr.meal.childOnly': 'Child meals are only for children under 12.',
  'sr.bassinet.none': 'Bassinets are for babies under 2 and under 11 kg. No one on this trip is that young.',
  'sr.bassinet.title': 'Bassinet seat',
  'sr.bassinet.short': 'Bassinet',
  'sr.bassinet.alt': 'The bassinet row is taken on the way there. Faisal moved you to row 14 with a spare seat beside you instead.',
  'sr.seats.keep': 'Seats together',
  'sr.seats.keepBoth': 'Seats together, both ways',
  'sr.seats.kids': 'Children beside a parent',
  'sr.seats.short': 'Seats together',
  'sr.seats.alt': 'flynas only guarantees seats together with paid seat selection, SAR 35 each. Mada can add it.',
  'sr.celebration.birthday': 'Birthday',
  'sr.celebration.anniversary': 'Anniversary',
  'sr.celebration.else': 'Something else',
  'sr.celebration.note': 'A note to the hotel',
  'sr.prayer.title': 'Prayer mats and qibla in the room',
  'sr.prayer.short': 'Prayer mats',
  'sr.bags.title.one': '1 extra bag',
  'sr.bags.title.other': '{count} extra bags',
  'sr.bags.bothWays': 'both ways',
  'sr.bags.short': 'extra bags',
  'sr.bags.quote.one': '{airline} has added 1 extra bag of {kg} kg{both}. {price}.',
  'sr.bags.quote.other': '{airline} has added {count} extra bags of {kg} kg{both}. {price}.',
  'sr.sports.golf': 'Golf clubs',
  'sr.sports.bike': 'A bike',
  'sr.sports.ski': 'Skis',
  'sr.sports.short.golf': 'Golf clubs',
  'sr.sports.short.bike': 'Bike box',
  'sr.sports.short.ski': 'Skis',
  'sr.sports.alt': 'The bike box is too long for {airline}’s hold on this plane. Mada can send it by air cargo for SAR 410; it arrives a day before you.',
  'sr.pet.no': 'Pets can’t fly with you on {airline}, in the cabin or the hold, and Mada can’t book pet travel.',

  // ───────────── hotel options ─────────────
  'ho.none': 'No hotel on this trip.',
  'ho.pickRoom': 'Pick a room',
  'ho.room.family': 'Family suite',
  'ho.room.view': 'Rooms with a Bosphorus view',
  'ho.room.two': 'Two standard rooms',
  'ho.room.familySub': 'One big room, two bathrooms',
  'ho.room.viewSub': 'Two rooms side by side, 7th floor',
  'ho.room.twoSub': 'Not connecting, on the same floor',
  'ho.instead': '{title} instead',
  'ho.nightsAt': '{name} · {nights} nights',
  'ho.room.quote': 'The hotel has the {room} for all {nights} nights. {price} more. Pay and we’ll swap it.',
  'ho.backOnce': '{amount} back once confirmed',
  'ho.refundOnWay': '{amount} refund on its way',
  'ho.nights.addTitle': 'One more night, until {day}',
  'ho.nights.quote': 'The hotel can keep your rooms one more night, until {day}. Same rooms, {price}.',
  'ho.nights.cutHere': 'Shortening a stay goes through Hotel options.',
  'ho.short.room': 'room change',
  'ho.short.night': 'extra night',
  'ho.short.early': 'Early check-in',
  'ho.short.late': 'Late checkout {time}',
  'ho.short.bed': 'extra bed',
  'ho.times.earlyFree': 'Early check-in, if a room is ready',
  'ho.times.earlyPaid': 'Early check-in at 10:00, guaranteed',
  'ho.times.lateFree': 'Late checkout until 14:00',
  'ho.times.latePaid': 'Late checkout until 18:00',
  'ho.times.earlyNo': 'Rooms are full the night before. Leave your bags at the desk; the hotel has a family lounge with prayer space.',
  'ho.times.quote': 'The hotel says yes: {what}. {price}.',
  'ho.bed.cot': 'A cot',
  'ho.bed.cotShort': 'Cot in the room',
  'ho.bed.extra': 'An extra bed',
  'ho.bed.noBaby': 'For babies under 2. No one on this trip is that young.',
  'ho.bed.quote': 'The hotel will set up an extra bed in the second room. {price} for {nights} nights.',
  'ho.connecting': 'Connecting rooms',

  // ───────────── change flight asks ─────────────
  'cf.callTitle': 'Call me about a flight change',
  'cf.callShort': 'Call about a change',
  'cf.callDetail': '{code} · less than a day to go',
  'cf.callYes': 'Mada is calling you',
  'cf.widerTitle': 'Find another flight',
  'cf.widerShort': 'Wider search',
  'cf.widerDetail': '{code} · any day near {day}',
  'cf.widerYes': 'Two options sent to your chat',

  // ───────────── itinerary ─────────────
  'itin.pickupHome': '{driver} picks you up at home',
  'itin.flight': '{from} → {to} · {code}',
  'itin.flightSub': '{airline} · {from} {terminal} · lands {arr} at {to}',
  'itin.flightBackSub': '{airline} · lands {arr} at {to}',
  'itin.fact.seats': 'Seats',
  'itin.fact.bags': 'Bags',
  'itin.fact.bagsEach': '{bags} each',
  'itin.fact.boarding': 'Boarding',
  'itin.meets': '{driver} meets you at {door}',
  'itin.meetsSub': '{airport} · sign with your name · {drive} to {place}',
  'itin.meetsSubNoStay': '{airport} · sign with your name · tell us where you’re staying',
  'itin.theHotel': 'the hotel',
  'itin.yourPlace': 'where you’re staying',
  'itin.noStay': 'No hotel booked. Where are you staying?',
  'itin.noStaySub': 'Tell us, so the driver and Mada know where you are.',
  'itin.own': 'Staying with {label}',
  'itin.checkIn': 'Check in · {name}',
  'itin.checkInSub': '{room} · {nights} nights',
  'itin.earlyCheckIn': '· early check-in',
  'itin.checkOut': 'Check out',
  'itin.checkOutSub': 'Leave bags at the desk if you want to walk',
  'itin.lateCheckout': 'Late checkout, confirmed',
  'itin.toAirport': '{driver} takes you to the airport',
  'itin.toAirportSub': 'From {place} · {drive}',
  'itin.aboutHour': 'about an hour',
  'itin.drivesHome': '{driver} drives you home',
  'itin.drivesHomeSub': 'Meets you at arrivals, Door 2',
  'itin.pickPending': 'Booking when you land',
  'itin.heldPay': 'Held · pay to confirm',
  'itin.celebrationSub': 'The hotel knows. Something small in the room.',
  'itin.kidsFish': 'Kids love the fish.',
  'itin.packTonight': 'Pack tonight',
  'itin.packTonightPickup': '{driver} picks you up at {time} tomorrow.',
  'itin.packTonightCheckout': 'Check-out is at 12:00 tomorrow.',
  'itin.day.fly': 'You fly to {city}',
  'itin.day.home': 'Home',
  'itin.day.free': 'A free day',
  'itin.day.in': 'In {city}',
  'itin.docs.passport.one': 'Your passport',
  'itin.docs.passport.other': 'Passports for all {n}',
  'itin.docs.passes': 'Boarding passes, in your Wallet',
  'itin.docs.hotel': 'Hotel booking, shown at check-in',
  'itin.docs.copies': 'Passport copies are in your Wallet. Originals stay in the room safe.',
  'itin.warn.pickupOld': 'Still booked for {day}. Your flight is {flight}.',
  'itin.warn.noStay': 'No hotel booked. Where are you staying?',
  'itin.warn.emptyNight': 'You land on {day}. This night is paid for but empty.',
  'itin.warn.noRoom.one': 'Your flight home is {day}. No room for the last night.',
  'itin.warn.noRoom.other': 'Your flight home is {day}. No room for the last {count} nights.',
  'itin.share.head': '{city}, {dates}. The plan, from Mada Trips.',
  'itin.share.hotel': 'Staying at {name}, {address}',
  'itin.share.foot': 'Times are local.',

  // ───────────── invoices ─────────────
  'inv.kind.simplified': 'Simplified tax invoice',
  'inv.kind.tax': 'Tax invoice',
  'inv.kind.credit_note': 'Credit note',
  'inv.kindAr.simplified': 'فاتورة ضريبية مبسطة',
  'inv.kindAr.tax': 'فاتورة ضريبية',
  'inv.kindAr.credit_note': 'إشعار دائن',
  'inv.draft': 'draft',
  'inv.vatNo': 'VAT',
  'inv.no': 'Invoice no.',
  'inv.cnNo': 'Credit note no.',
  'inv.against': 'Against invoice',
  'inv.buyer': 'Buyer:',
  'inv.customer': 'Customer:',
  'inv.traveller': 'Traveller:',
  'inv.paidWith': 'Paid with',
  'inv.col.item': 'What',
  'inv.col.rate': 'VAT rate',
  'inv.col.net': 'Net',
  'inv.col.vat': 'VAT',
  'inv.col.total': 'Total',
  'inv.beforeVat': 'Total before VAT',
  'inv.vat15': 'VAT 15%',
  'inv.total': 'Total',
  'inv.foot': 'Prices include VAT. International flights are zero-rated.',
  'inv.line.tickets': 'Air tickets {from}–{to} {ways}, {cabin}{n} × {each}',
  'inv.return': 'return',
  'inv.oneWay': 'one way',
  'inv.zeroRated': 'International transport, zero-rated',
  'inv.line.fee': 'Mada service fee',
  'inv.line.discount': 'Discount',
  'inv.discountNote': 'Taken off the price',
  'inv.line.room': '{room}, {nights} nights × {each}',
  'inv.line.transfer.one': 'Private transfer, 1 ride',
  'inv.line.transfer.other': 'Private transfers, {count} rides',
  'inv.changeNote': 'Price difference and change fee',
  'inv.reissueTitle': 'Reissue the tax invoice',
  'inv.reissueShort': 'Invoice reissued',
  'inv.reissueYes': 'New tax invoice in Payments',

  // ───────────── disruption options ─────────────
  'dz.opt.direct': '{airline} {code} · direct',
  'dz.opt.tomorrow': '{airline} {code} · tomorrow',
  'dz.opt.times': 'Leaves {dep} · lands {arr} at {airport}',
  'dz.opt.stay': 'Stay on {code}',
  'dz.opt.stayTimes': 'Likely leaves {dep} · lands {arr}',
  'dz.opt.refund': 'Get a refund instead',
  'dz.opt.home': 'Go home and get a refund',
  'dz.opt.refundTimes': '{amount} back to your card',
  'dz.opt.refundNote': 'Your stay and pickup are cancelled for free too.',
  'dz.opt.homeNote': 'Your stay and pickup are cancelled for free too. The airline pays the taxi home.',
  'dz.opt.morningNote': 'The first flight out. Same seats together. A hotel near the airport tonight, paid by the airline.',
  'dz.opt.xyNightNote': 'A longer sleep. Same hotel tonight. Your pickup moves with you.',
  'dz.opt.nextNote': 'Same seats together. No extra cost.',
  'dz.opt.xyEarlierNote': 'Earlier. No extra cost to you. Your pickup moves with you.',
  'dz.opt.xyNote': 'No extra cost to you. Your pickup moves with you.',
  'dz.opt.stayNote': 'Same seats, same airport. You land 3 hours later.',

  // ───────────── Today: readiness bits the server words ─────────────
  'td.pp.blocking': '{name}’s passport expires on {date}. {country} needs {days} days after you land, so it must be valid until {need}.',
  'td.pp.fine': 'Fine for {city}: {country} asks for {days} days after you land, {name} has {left}.',
  'td.esim.title': 'eSIM for {country}',
  'td.esim.short.one': 'eSIM for 1',
  'td.esim.short': 'eSIM for {count}',
  'td.esim.detail': '10 GB each for 7 days',
  'td.esim.quote': 'eSIMs for {count}, 10 GB each for 7 days. {price}. They install before you fly.',

  // ───────────── disruption (server words) ─────────────
  'dz.you': 'you',
  'dz.allOf': 'all {n} of you',
  'dz.delay.headline': '{code} will likely leave 3 hours late.',
  'dz.delay.sub': 'The plane coming from Cairo landed late. {airline} hasn’t announced it yet. We’re holding seats for {everyone} on an earlier flight.',
  'dz.delay.source': 'Predicted from the inbound plane at 08:02',
  'dz.cancel.headline': '{airline} cancelled {code}.',
  'dz.cancel.sub': 'You’re owed a full refund. We’re holding seats for {everyone} on two other flights today.',
  'dz.cancel.source': '{airline} confirmed the cancellation at 06:12',
  'dz.night.headline': '{airline} cancelled {code} at 23:40.',
  'dz.night.sub': 'You don’t need to sort tonight out yourself. We’ve held a room near the airport and seats for {everyone} on the first flight tomorrow.',
  'dz.night.source': '{airline} confirmed the cancellation at 23:40',
  'dz.night.hotel': 'Hotel near the airport tonight',
  'dz.night.hotelBody': 'The airline pays. Your voucher goes to your Wallet. Shuttle from Door 4 every 20 minutes.',
  'dz.night.meals': 'Meal vouchers',
  'dz.night.mealsBody': 'SAR 75 each for {everyone}, at any café in the terminal or at the hotel.',
  'dz.night.next': 'Next flight {time}',
  'dz.night.nextBody': '{airline} {code}, seats held together. Or pick another below.',
  'dz.agent.day': '{agent} at Mada is on this with you.',
  'dz.agent.night': '{agent} on the night desk is on this with you.',
  'dz.refundTitle': '{code} cancelled · flights, stay and pickup',
  'dz.done.refund': 'Refund on its way: {amount}.',
  'dz.done.refundBody': 'Usually 7–14 days back to your {card}. Track it in Trips → Requests.',
  'dz.done.refundBodyNight': 'Usually 7–14 days back to your {card}. Track it in Trips → Requests. {airline} pays the taxi home: keep the receipt.',
  'dz.done.refundLine': '“I’ve asked {airline} for the refund and cancelled the rest. I’ll tell you when it’s sent.”',
  'dz.done.stay': 'Done. You’re staying on {code}.',
  'dz.done.stayBody': 'We’ll keep watching the plane. If it gets later, we’ll have another option ready before {airline} announces it.',
  'dz.done.rebook.one': 'Done. You’re on {flight}.',
  'dz.done.rebook.other': 'Done. All {n} of you are on {flight}.',
  'dz.done.rebookBody': '{driver} now collects you at {time}. Your pickup at the other end moves too. New boarding passes are in your Wallet.',
  'dz.done.rebookBodyNoCar': 'New boarding passes are in your Wallet.',
  'dz.done.nightBody': 'Your room is booked at the airport hotel, 8 minutes on the shuttle from Door 4. The hotel and meal vouchers are in your Wallet. We’ll message you at {time} to get up.',
  'dz.done.line': '“I’ve moved everything. Have a good trip.”',
  'dz.done.nightLine': '“I’ve moved your tickets and booked the room. Get some sleep.”',
  'dz.voucher.hotel': 'Hotel tonight · airport hotel',
  'dz.voucher.hotelBody': 'Paid by {airline}. Shuttle from Door 4 every 20 minutes.',
  'dz.voucher.meal': 'Meal vouchers · SAR 75 each × {n}',
  'dz.voucher.mealBody': 'Any café in the terminal or at the hotel. Valid until 10:00.',

  // Lock-screen notifications from the trip (title ≤ 32, body ≤ 90). Sender: Mada.
  'notify.trip.price.title': 'A price from Mada',
  'notify.trip.price.body': '{what}: {amount}. Pay in Trips to confirm.',
  'notify.trip.credit.title': 'Refund in your Mada credit',
  'notify.trip.credit.body': '{amount} is ready to use now, on any booking.',
  'notify.trip.rebooked.title': 'Your new flight is booked',
  'notify.trip.rebooked.body': '{agent}: You’re on {what} at {time}. Pickups moved too.',
  'notify.trip.cancelled.title': '{flight} is cancelled',
  'notify.trip.cancelled.body': 'We’re holding seats on other flights. Tap to choose.',
  'notify.trip.delayed.title': '{flight} is late',
  'notify.trip.delayed.body': 'About {minutes} minutes late. We’re holding an earlier option.',
} as const;
