/** Trip screens, part one: trip detail, the Trips tab, payments, invoices, refunds and flight changes (prototype TripManage). */
export const enTripsUi = {
  /* trip detail */
  'tm.detail.gone': 'This trip has ended.',
  'tm.detail.booking': 'booking {ref}',
  'tm.detail.going': 'Going',
  'tm.detail.oneWay': 'One way',
  'tm.detail.back': 'Back',
  'tm.detail.refunded': 'Refunded',
  'tm.detail.change': 'Change',
  'tm.detail.noHome': 'No flight home booked. {agent} can add one any time.',
  'tm.detail.nights': '{n} nights',
  'tm.detail.cancelled': 'Cancelled',
  'tm.detail.stayed': 'Stayed',
  'tm.detail.refundOnWay': 'Refund on its way. Track it in Trips, under Requests.',
  'tm.detail.stayingWith': 'Staying with {label}',
  'tm.detail.takesYou': '{driver} takes you there.',
  'tm.detail.tellUs': 'Tell us',
  'tm.detail.pickBoth': 'Airport pickup both ways',
  'tm.detail.pickThere': 'Airport pickups on the way there',
  'tm.detail.pickArrival': 'Airport pickup on arrival',
  'tm.detail.inCity': '{driver} in {city}',
  'tm.detail.needsAddr': 'needs your address',
  'tm.detail.manage': 'Manage',
  'tm.detail.travellers': 'Travellers',
  'tm.detail.you': '{name} (you)',
  'tm.detail.open.one': '1 request with Mada. See where it is.',
  'tm.detail.open.other': '{n} requests with Mada. See where each one is.',
  'tm.m.itinerary': 'Full itinerary',
  'tm.m.itinerarySub': 'Day by day, with times and documents',
  'tm.m.payments': 'Payments and invoices',
  'tm.m.paymentsSub': 'VAT invoices for every payment',
  'tm.m.nextPayment': 'Next payment {amount} on {day}',
  'tm.m.change': 'Change flight',
  'tm.m.changeSub': 'Date, time, way back, a name spelling',
  'tm.m.changeCall': 'Less than a day to go: {agent} calls you',
  'tm.m.hotel': 'Hotel options',
  'tm.m.hotelSub': 'Room, nights, check-in and checkout',
  'tm.m.hotelFind': 'Find a place to stay',
  'tm.m.special': 'Special requests',
  'tm.m.specialSub': 'Wheelchair, meals, bags, a celebration',
  'tm.m.refund': 'Ask for a refund',
  'tm.m.refundSub': 'See exactly what comes back first',
  'tm.cancel.title': 'Cancel the stay?',
  'tm.cancel.body': 'You’ll get {amount} back.',
  'tm.cancel.flightsStay': 'Your flights stay as they are.',
  'tm.cancel.instalments': 'That’s what you’ve paid so far with {provider}. The {n} payments left ({amount}) are cancelled.',
  'tm.cancel.paid': 'You paid {amount}.',
  'tm.cancel.confirm': 'Cancel the stay',
  'tm.cancel.keep': 'Keep it',
  'tm.cancel.done': 'Cancelled. Your refund is on its way.',
  'tm.nostay.body': '{driver} meets you at the airport on {day}. Tell us where to take you.',

  /* Trips tab */
  'tr.tripA11y': '{city} trip',
  'tr.justYou': 'Just you',
  'tr.booked': 'Booked',
  'tr.itinerary': 'Itinerary',
  'tr.payments': 'Payments',
  'tr.tracking': 'Flights you’re tracking',
  'tr.import.title': 'Booked somewhere else?',
  'tr.import.body': 'Upload the PDF and we’ll watch it like any Mada trip.',
  'tr.import.upload': 'Upload a booking',
  'tr.req.send': 'Send Mada a request',
  'tr.req.pay': 'Pay {amount}',
  'tr.req.confirmedToday': 'Confirmed today',
  'tr.req.cantDefault': 'They can’t do it. Talk to Mada and we’ll find another way.',
  'tr.req.queuedChoice': 'Your choice for the flight',
  'tr.req.savedPhone': 'Saved on this phone. It sends when you’re back online.',
  'tr.refund': 'Refund · {amount}',
  'tr.ref.notApproved': 'Not approved',
  'tr.ref.withMada': 'With Mada',
  'tr.ref.inCredit': 'In your credit',
  'tr.ref.sent': 'Sent',
  'tr.ref.onWay': 'On its way',
  'tr.sameAgain': 'Same again',
  'tr.sameAgainAsk': '{city} again, like {when}',
  'rq.tr.savedPhone': 'Saved on this phone',
  'rq.tr.withinHour': 'Usually within the hour',

  /* payments */
  'pay.title': 'Payments',
  'pay.emptyTitle': 'Nothing paid yet.',
  'pay.emptyBody': 'Every payment on this trip lands here with its VAT invoice.',
  'pay.plan': 'Plan a trip',
  'pay.eyebrow': '{city} · booking {ref}',
  'pay.total': 'The trip in total. Tap any payment for its VAT invoice.',
  'pay.totalRefunded': 'The trip in total, with {amount} refunded. Tap any payment for its VAT invoice.',
  'pay.next': 'Next payment: {amount} on {day}',
  'pay.nextBody': '{what}. {n} left, taken from {card}. No interest, no fees.',
  'pay.a11y': '{title}, {amount}, open the invoice',
  'pay.andCredit': 'and {amount} Mada credit',
  'pay.credited': 'Credited {amount} · credit note',
  'pay.ofPaid': '{n} of {total} paid',
  'pay.invoice': 'Invoice',
  'pay.plan.title': 'Payment plan',
  'pay.atBooking': 'At booking',
  'pay.payment': 'Payment {n}',
  'pay.paid': 'Paid',
  'pay.due': 'Due',
  'pay.plan.foot': 'If you cancel, the payments left are cancelled too. Nothing more is taken.',
  'pay.tabby4': 'Tabby · 4 payments',
  'pay.tamara3': 'Tamara · 3 payments',

  /* invoices */
  'inv.title': 'Invoice',
  'inv.gone': 'This payment isn’t on the trip any more.',
  'inv.goneBody': 'Mada can send you a copy of any invoice.',
  'inv.tab.invoice': 'Invoice',
  'inv.tab.tax': 'Tax invoice',
  'inv.tab.credit': 'Credit note',
  'inv.draft.title': 'Draft. Check the company details.',
  'inv.draft.body': 'Once it’s issued it can’t be edited. Only {agent} can reissue it.',
  'inv.qr': 'ZATCA QR code',
  'inv.f.seller': 'Seller',
  'inv.f.vat': 'VAT number',
  'inv.f.no': 'Invoice no.',
  'inv.f.cnNo': 'Credit note no.',
  'inv.f.onIssue': 'On issue',
  'inv.f.date': 'Date',
  'inv.f.buyer': 'Buyer',
  'inv.f.buyerVat': 'Buyer VAT · CR',
  'inv.f.traveller': 'Traveller',
  'inv.f.customer': 'Customer',
  'inv.f.against': 'Against invoice',
  'inv.f.paidWith': 'Paid with',
  'inv.vatRate': 'VAT {rate}%',
  'inv.seeCredit': 'See the credit note for the refund',
  'inv.co.title': 'Invoice for a company',
  'inv.co.row': 'A full tax invoice with your company’s VAT number',
  'inv.co.body': 'We issue a full tax invoice with your company’s details, for every payment on this trip. Check them before you issue it.',
  'inv.co.name': 'Company name',
  'inv.co.namePh': 'As on the commercial registration',
  'inv.co.vat': 'VAT number',
  'inv.co.cr': 'CR number',
  'inv.co.crPh': '10 digits',
  'inv.co.address': 'Address',
  'inv.co.addressPh': 'Street, district, city',
  'inv.co.save': 'Save company details',
  'inv.co.saved': 'Saved. Check it, then issue the tax invoice.',
  'inv.co.errName': 'Add the company name as it’s registered.',
  'inv.co.errVat': 'Add the company’s VAT number.',
  'inv.co.errVatLen': 'A Saudi VAT number has 15 digits (this has {n}).',
  'inv.co.errVat3': 'It starts and ends with 3, like 300000000000003.',
  'inv.co.errCr': 'Add the commercial registration number.',
  'inv.co.errCrLen': 'A CR number has 10 digits (this has {n}).',
  'inv.co.errAddr': 'Add the street, the district and the city.',
  'inv.issue': 'Issue the tax invoice',
  'inv.issued': 'Issued. The tax invoice is final now.',
  'inv.editCo': 'Edit company details',
  'inv.share': 'Share PDF',
  'inv.saved': 'Saved. Choose “Save as PDF” to keep a copy.',
  'inv.cantShare': 'Couldn’t share it here. Ask Mada to email it.',
  'inv.issuedTo': 'Issued to {name}, {day}',
  'inv.cantEdit': 'A tax invoice can’t be edited once it’s issued. {agent} can cancel it with a credit note and issue a new one.',
  'inv.askReissue': 'Ask Mada to reissue',
  'inv.reissueSent': 'Sent to Mada. Say what to change in the chat.',

  /* refunds */
  'rf.title': 'Refund',
  'rf.askTitle': 'Ask for a refund',
  'rf.emptyTitle': 'Nothing to refund yet.',
  'rf.emptyBody': 'Once you’ve paid for a trip, you can see here exactly what would come back.',
  'rf.seeTrips': 'See it in Trips',
  'rf.done': 'Done',
  'rf.sent.anyway': 'Sent to Mada.',
  'rf.sent.credit': '{amount} is in your Mada credit.',
  'rf.sent.card': '{amount} is on its way back.',
  'rf.sent.anywayBody': 'The rule says nothing comes back, but {agent} will ask. You’ll hear within a day.',
  'rf.sent.creditBody': 'Ready to use now, on any booking. It doesn’t expire.',
  'rf.sent.tabbyBody': 'We tell {provider} today. What you paid goes back to your card, and the payments left are cancelled.',
  'rf.sent.cardBody': 'Back to your {card}, usually in 5–10 working days.',
  'rf.sent.line': '“I’ll keep an eye on it until it’s in your account.”',
  'rf.sent.lineAnyway': '“I’ll ask, and tell you either way.”',
  'rf.sent.lineCredit': '“Done. It’s there now.”',
  'rf.doneTitle': 'Your trip is done.',
  'rf.doneBody': 'Every flight and night was used, so nothing is left to refund. If anything on the trip let you down, tell {agent}. He’ll take it up with the airline or hotel.',
  'rf.slide.pick': 'Pick what to refund',
  'rf.slide.reason': 'Pick a reason',
  'rf.slide.anyway': 'Slide to ask Mada anyway',
  'rf.slide.ask': 'Slide to ask for {amount}',
  'rf.what': 'What should we refund?',
  'rf.cancelled': '{airline} cancelled {code}.',
  'rf.cancelledBody': 'Under GACA rules you get the full price of the flights back, fees and all. Your stay and pickup are free to cancel too.',
  'rf.used': 'Part of the trip is used.',
  'rf.usedBody': 'Only what you haven’t used yet can come back.',
  'rf.already': 'Already refunded',
  'rf.refunded': 'Refunded',
  'rf.paymentsStop': 'Payments stop',
  'rf.nothingBack': 'Nothing back',
  'rf.youPaid': 'You paid {amount}.',
  'rf.instNote': 'You’ve paid {paid} so far, and that comes back. The {n} {provider} payments left ({left}) are cancelled.',
  'rf.owe': '{provider} still takes {amount} for the hotel’s fee.',
  'rf.why': 'Why?',
  'rf.reason.plans': 'Plans changed',
  'rf.reason.ill': 'Someone is ill',
  'rf.reason.docs': 'Visa or passport problem',
  'rf.reason.airline': 'The airline changed it',
  'rf.reason.else': 'Found something else',
  'rf.reason.other': 'Other',
  'rf.illNote': 'Send Mada a doctor’s note. Some airlines waive the fee with one, and we’ll ask.',
  'rf.airlineNote': 'If {airline} moved your flight by more than 3 hours, GACA rules give you a full refund. Mada will check the schedule.',
  'rf.where': 'Where should it go?',
  'rf.backThrough': 'Back through {provider}',
  'rf.backThroughBody': 'You paid with instalments, so the refund goes the way you paid: what you’ve paid so far back to your card, and the payments left cancelled.',
  'rf.toCard': 'Back to your {card}',
  'rf.toCardSub': '5–10 working days',
  'rf.toCredit': 'Mada credit',
  'rf.toCreditSub': 'Instant · the same amount · for any booking, no expiry',
  'rf.mixed': 'The part paid with {provider} goes back through them, and the payments left are cancelled.',
  'rf.sumAnyway': 'The rules say nothing comes back. {agent} can ask anyway.',
  'rf.youGet': 'You get back',
  'rf.sumInst': 'and {left} of payments you won’t make. {all} in all.',
  'rf.tr.requested': 'Requested',
  'rf.tr.today': 'Today',
  'rf.tr.asking': '{agent} is asking',
  'rf.tr.couldnt': '{agent} couldn’t get it approved',
  'rf.tr.withinDay': 'Usually within a day',
  'rf.tr.approvedBy': 'Approved by {agent}',
  'rf.tr.approvedByAirline': 'Approved by {airline}',
  'rf.tr.inCredit': 'Added to your Mada credit · {amount}',
  'rf.tr.readyNow': 'Ready to use now',
  'rf.tr.days13': 'Usually 1–3 days',
  'rf.tr.sentProvider': 'Sent to {provider}',
  'rf.tr.sentCard': 'Sent to your {card}',
  'rf.tr.cancelledLeft': '{n} payments left cancelled',
  'rf.tr.law': 'Within 7 days, by law',
  'rf.tr.days714': 'Usually 7–14 days',
  'rf.tr.backOnCard': 'Back on your card',
  'rf.tr.inBank': 'In your bank',
  'rf.tr.arrived': 'Arrived',
  'rf.tr.afterSent': '5–10 working days after it’s sent, in riyals',

  /* change flight */
  'cf.title': 'Change flight',
  'cf.noFlights': 'No flights on this trip.',
  'cf.noFlightsBody': 'Mada can add flights any time.',
  'cf.cancelledBody': 'You don’t pay anything to change. We’re holding seats on two other flights for all {n} of you.',
  'cf.flown': 'Both flights are flown.',
  'cf.flownBody': 'Welcome home. Nothing left to change.',
  'cf.flownOne': 'You’ve flown this one already.',
  'cf.callMe': 'Ask Mada to call me',
  'cf.within24': 'Less than a day to go.',
  'cf.within24Body': 'Inside 24 hours, {airline} only changes tickets by phone. {agent} calls you, then calls them, and stays on until it’s done.',
  'cf.rulesApply': 'The rules still apply',
  'cf.rulesBody': 'Change fee {fee}, plus any difference in fare. You see the price before anything changes.',
  'cf.feePp': 'SAR {fee} per person',
  'cf.feePpShort': 'SAR {fee} pp',
  'cf.free': 'Free',
  'cf.minusPp': 'Minus SAR {fee} pp',
  'cf.taxesOnly': 'Taxes only',
  'cf.r.fee': 'Change fee',
  'cf.r.refund': 'Refund',
  'cf.r.bags': 'Bags',
  'cf.working': '{agent} is changing it.',
  'cf.step.held': 'New seats held',
  'cf.step.changing': 'Changing the tickets with {airline}',
  'cf.step.pickups': 'Moving your pickups',
  'cf.backToTrip': 'Back to the trip',
  'cf.done': 'Done. {say}.',
  'cf.doneCredit': 'The fare is lower, so {amount} is in your Mada credit now.',
  'cf.doneNoCost': 'No cost to you.',
  'cf.donePasses': 'New boarding passes reach your Wallet when check-in opens.',
  'cf.doneLine': '“Changed with {airline}. {seats}”',
  'cf.sameSeats': 'Same seats together.',
  'cf.sameSeat': 'Same seat.',
  'cf.backLine': 'Back {code} · {day} · {time}',
  'cf.oneWayLine': 'One way',
  'cf.travellers.one': '1 traveller',
  'cf.travellers.other': '{n} travellers',
  'cf.whatChange': 'What would you like to change?',
  'cf.k.date': 'Another day',
  'cf.k.dateSub': 'Same airline. Your seats move with you.',
  'cf.k.time': 'Another time, same day',
  'cf.k.timeSub': 'Earlier or later on {day}.',
  'cf.k.return': 'Only the way back',
  'cf.k.returnSub': 'Stay longer, or come home sooner.',
  'cf.k.one': 'Just one traveller',
  'cf.k.oneSub': 'One of you flies home on another day.',
  'cf.k.airline': 'Another airline',
  'cf.k.airlineSub': 'A new ticket, not a change.',
  'cf.k.name': 'Fix a name spelling',
  'cf.k.nameSub': 'Small fixes, so the ticket matches the passport.',
  'cf.onlyHome': 'You’re in {city}, so only the way home can change.',
  'cf.else': 'Something else',
  'cf.whoHome': 'Who flies home on another day?',
  'cf.under12': '{name} is under 12.',
  'cf.escort': 'Children under 12 fly alone only with {airline}’s escort, who stays with them door to door. SAR 350, included below.',
  'cf.pickHome': 'Pick the flight home',
  'cf.pickNew': 'Pick the new flight',
  'cf.noSeats': 'No seats for {who} on those flights.',
  'cf.one': 'one',
  'cf.allN': 'all {n}',
  'cf.wider': '{agent} can look wider: other airports, or a waitlist on the day you want.',
  'cf.askWider': 'Ask Mada to look wider',
  'cf.full': 'Full',
  'cf.b.fee': 'Change fee',
  'cf.b.freeFare': 'free on this fare',
  'cf.b.escort': 'Escort for {name}, door to door',
  'cf.b.diff': 'Fare difference',
  'cf.b.same': 'Same fare',
  'cf.b.pay': 'You pay',
  'cf.b.back': 'You get back',
  'cf.b.total': 'Total',
  'cf.b.creditNote': 'The fare is lower than the fee, so the difference comes back as Mada credit, straight away.',
  'cf.b.nextMove': 'Next, we’ll ask if your hotel and pickup move too.',
  'cf.b.oneMore': 'You’ll need one more night. Add it in Hotel options.',
  'cf.b.rules': 'The new tickets keep the same rules. {agent} confirms with {airline}.',
  'cf.review': 'Review · {amount}',
  'cf.pickFlight': 'Pick a flight',
  'cf.slideBack': 'Slide to change · {amount} back',
  'cf.slideFree': 'Slide to change · no cost',
  'cf.quoted': 'Sent to Mada. The price is in Trips, under Requests.',
  'cf.sent': 'Sent to Mada. Track it in Trips, under Requests.',
  'cf.sw.cant': 'Tickets can’t move to another airline.',
  'cf.sw.body': 'We’d refund your {airline} tickets under their rules and buy new ones.',
  'cf.sw.back': 'You’d get {amount} back.',
  'cf.sw.taxes': 'This fare isn’t refundable, so only taxes come back: {amount}. Changing the day on {airline} costs less: SAR {fee} per person.',
  'cf.sw.foot': 'Price after your refund, for all {n}. {agent} checks seats before you pay anything.',
  'cf.sw.ask': 'Ask Mada to swap it',
  'cf.n.whose': 'Whose name?',
  'cf.n.now': 'On the ticket now',
  'cf.n.given': 'Given names',
  'cf.n.sur': 'Surname',
  'cf.n.same': 'Type it exactly as on the passport. Airlines allow small fixes only: up to 3 letters.',
  'cf.n.ok.one': 'A small fix (1 letter). {airline} does this free. Mada sends it with a photo of the passport page.',
  'cf.n.ok.other': 'A small fix ({n} letters). {airline} does this free. Mada sends it with a photo of the passport page.',
  'cf.n.too': 'That’s more than a spelling fix. Airlines allow up to 3 letters changed. A different name means a new ticket, so the fare rules apply.',
  'cf.n.askCost': 'Ask Mada what it would cost',
} as const;
