/** Trip screens, part two: hotel options, special requests, the itinerary and disruptions (prototype TripManage, Disruption). */
export const enTripsUi2 = {
  /* hotel options */
  'ho.title': 'Hotel options',
  'ho.cancelled': 'The stay is cancelled.',
  'ho.ownPlace': 'You’re staying at {address}.',
  'ho.sameDates': 'Rooms near the centre, for the same dates?',
  'ho.free': 'Free to change until {day}.',
  'ho.r.room': 'Change the room',
  'ho.r.roomSub': 'A suite, a view, or two rooms',
  'ho.r.nights': 'Add or remove nights',
  'ho.r.nightsSub': 'Now {n} nights, out on {day}',
  'ho.r.times': 'Check-in and checkout',
  'ho.r.timesSub': 'Early check-in, late checkout',
  'ho.r.bed': 'A cot or an extra bed',
  'ho.r.bedSub': 'For a baby, or one more person',
  'ho.connecting': 'Connecting rooms',
  'ho.r.inBooking': 'In your booking',
  'ho.r.askHotel': 'Ask the hotel',
  'ho.r.switch': 'A different hotel',
  'ho.r.switchSub': 'Mada finds one for the same dates',
  'ho.switchAsk': 'A different hotel in {city}, {dates}',
  'ho.aNight': 'a night',
  'ho.room.more': '{amount} more for {n} nights. You pay once the hotel says yes.',
  'ho.room.less': '{amount} back to your card once the hotel confirms.',
  'ho.askPrice': 'Ask the hotel · +SAR {amount}',
  'ho.ask': 'Ask the hotel',
  'ho.pickOne': 'Pick one',
  'ho.n.until': 'Stay until {day}',
  'ho.n.oneMore': 'One more night · {amount}',
  'ho.n.leave': 'Leave on {day}',
  'ho.n.lessFree': 'One night less · free to shorten until {day}',
  'ho.n.lessKept': 'After {day} the hotel keeps the night you drop',
  'ho.n.flightStill': 'Your flight home is still on {day}. Change it in Change flight.',
  'ho.n.needPlace': 'Your flight home is on {day}, so you’ll need somewhere for that night.',
  'ho.n.cutBtn': 'Leave a night sooner',
  'ho.times.earlyFree': 'Early check-in, if a room is ready',
  'ho.times.earlyPaid': 'Early check-in at 10:00, guaranteed',
  'ho.times.lateFree': 'Late checkout until 14:00',
  'ho.times.latePaid': 'Late checkout until 18:00',
  'ho.t.earlyFreeSub': 'Free. The hotel decides on the morning.',
  'ho.t.lateFreeSub': 'Free, if the hotel has space',
  'ho.t.half': 'Half a night, {amount}',
  'ho.t.free': 'Free',
  'ho.t.intro': 'You land at {arr} and reach the hotel around {reach}.',
  'ho.t.mayNot': 'Check-in is 14:00, so you may not need it.',
  'ho.t.foot': 'Subject to the hotel having rooms. You only pay if they say yes.',
  'ho.bed.cot': 'A cot',
  'ho.bed.noBaby': 'For babies under 2. No one on this trip is that young.',
  'ho.bed.extra': 'An extra bed',
  'ho.b.cotSub': 'Free, set up before you arrive',
  'ho.b.bedSub': 'SAR 150 a night · {n} nights',
  'ho.c.has': 'Already in your booking. The hotel confirmed two connecting rooms.',
  'ho.c.not': 'Your rooms aren’t connecting now. The hotel can try; it depends on who checks out before you.',
  'ho.c.good': 'Good',

  /* special requests */
  'sr.title': 'Special requests',
  'sr.anything': 'Anything you need?',
  'sr.intro': 'Mada asks {airline} and the hotel for you, and you watch each one move.',
  'sr.everyoneCap': 'Everyone',
  'sr.emptyTitle': 'No trip to ask for.',
  'sr.emptyBody': 'Special requests open once a trip is booked.',
  'sr.t.wheelchair': 'Wheelchair',
  'sr.t.meal': 'A special meal',
  'sr.t.bassinet': 'A bassinet',
  'sr.t.seats': 'Seats together',
  'sr.t.celebration': 'A celebration',
  'sr.t.prayer': 'Prayer mat and qibla in the room',
  'sr.t.bags': 'Extra bags',
  'sr.t.sports': 'Sports equipment',
  'sr.t.pet': 'Travelling with a pet',
  'sr.s.wheelchair': 'To the gate, or to the seat',
  'sr.s.meal': 'Halal on every flight. Child, vegetarian, diabetic.',
  'sr.s.bassinet': 'For a baby under 2',
  'sr.s.seats': 'Keep the family side by side',
  'sr.s.celebration': 'Birthday or anniversary, a note to the hotel',
  'sr.s.prayer': 'With prayer times for the city',
  'sr.s.bags': 'Cheaper now than at the airport',
  'sr.s.sports': 'Golf, bikes, skis',
  'sr.s.pet': 'What’s allowed',
  'sr.asked': 'Asked so far',
  'sr.else': 'Something else? Talk to Mada',
  'sr.close': 'Close',
  'sr.queued': 'Saved on this phone. It sends when you’re back online.',
  'sr.sentToast': 'Sent to Mada. Track it in Trips, under Requests.',
  'sr.bags.toast': 'Sent to Mada. The price is in Trips, under Requests.',
  'sr.w.intro': 'For {who}. {airline} meets you at the check-in desk and takes you through.',
  'sr.w.gate': 'To the gate',
  'sr.w.gateSub': 'You can walk to the seat',
  'sr.w.seat': 'To the seat',
  'sr.w.seatSub': 'Help up the steps and to the seat',
  'sr.w.own': 'Own wheelchair',
  'sr.w.ownSub': 'It flies free in the hold',
  'sr.m.intro': 'Every meal on {airline} is halal. A special one for {who}:',
  'sr.m.for': 'For {names}',
  'sr.m.vegSub': 'No meat or fish',
  'sr.m.diabeticSub': 'Low sugar, measured carbs',
  'sr.m.glutenSub': 'No wheat, barley or rye',
  'sr.m.childSub': 'For children under 12',
  'sr.m.foot': 'Free. Needs 24 hours before the flight.',
  'sr.b.intro': 'A bassinet clips to the wall in front of the first row. For babies under 11 kg. Free, but there are only a few on each plane.',
  'sr.b.addBaby': 'Travelling with a baby after all? Add them in the Wallet first, then come back.',
  'sr.se.intro': 'You’re in {out} now.',
  'sr.se.introBack': 'You’re in {out} now, and {back} coming back.',
  'sr.se.side': 'side by side',
  'sr.se.keep': 'Seats together',
  'sr.se.keepSub': 'Everyone in one row, or two rows one behind the other',
  'sr.se.kids': 'Children beside a parent',
  'sr.se.kidsSub': 'At least one adult next to each child',
  'sr.c.intro': 'The hotel will do something small in the room. What exactly is up to them.',
  'sr.c.note': 'A note for the hotel (optional)',
  'sr.c.notePh': 'Who, and what for',
  'sr.c.notePhOne': '{name} turns …',
  'sr.p.times': 'Prayer times in {city}: {times}.',
  'sr.p.qibla': 'The hotel marks the qibla in the room.',
  'sr.bg.intro': 'Your fare has {bags}. Each extra bag on {airline} is up to {kg} kg, {fee} each way.',
  'sr.bg.fewer': 'One bag fewer',
  'sr.bg.more': 'One bag more',
  'sr.bg.total': 'Extra bags',
  'sr.bg.for': 'Extra bags for {who}',
  'sr.bg.twoFlights': '2 flights',
  'sr.bg.ask': 'Ask for it · {amount}',
  'sr.sp.intro': 'Sports bags count as one bag up to {kg} kg. Mada checks the size with the airline.',
  'sr.sp.golf': 'Golf clubs',
  'sr.sp.golfSub': 'Usually 15–20 kg',
  'sr.sp.bike': 'A bike in a box',
  'sr.sp.bikeSub': 'Usually 25–32 kg',
  'sr.sp.ski': 'Skis or a snowboard',
  'sr.sp.skiSub': 'Usually 8–12 kg',
  'sr.pet.guide': 'Guide and assistance dogs are the exception. They fly free in the cabin with the right papers. Tell Mada and we’ll arrange it.',

  /* itinerary */
  'itin.title': 'Itinerary',
  'itin.heading': '{city}, day by day',
  'itin.offTitle': 'The itinerary isn’t on this phone yet.',
  'itin.offBody': 'Open it once with signal and it stays here for the whole trip.',
  'itin.retry': 'Try again',
  'itin.eyebrow': '{dates} · {n} days',
  'itin.saved': 'Saved on this phone. Works without signal.',
  'itin.lastUpdated': 'Offline · last updated at {time}',
  'itin.addCal': 'Add to calendar',
  'itin.share': 'Share',
  'itin.sameTime': 'Times are local. {city} is on the same time as Riyadh.',
  'itin.localTimes': 'Times are local to where you are that day.',
  'itin.cancelledAirline': 'Cancelled by the airline',
  'itin.carry': 'Carry:',
  'itin.askedFor': 'Asked for: {what}.',
  'itin.checkInNote': 'Check-in opens 24 hours before. We do it for you and the boarding passes appear in your Wallet.',
  'itin.changeFlight': 'Change this flight',
  'itin.special': 'Special requests',
  'itin.passes': 'Boarding passes',
  'itin.theDriver': 'The driver',
  'itin.driverWaits': '{driver} tracks your flight. If it’s late, he waits, at no cost.',
  'itin.callDriver': 'Call {driver}',
  'itin.yourName': 'your name',
  'itin.hotelTimes': 'Check-in from 14:00, checkout by 12:00. Your booking is under {name}.',
  'itin.hotelOptions': 'Hotel options',
  'itin.heldNote': '{what}. Mada holds it until then.',
  'itin.bookedNote': 'Booked. Your confirmation is in your Wallet.',
  'itin.payConfirm': 'Pay to confirm',
  'itin.ideaNote': 'Just an idea. Nothing is booked.',
  'itin.askBook': 'Ask Mada to book it',
  'itin.leaveFree': 'Leave the day free',
  'itin.close': 'Close',
  'itin.shareTitle': 'Share the itinerary',
  'itin.shareBody': 'Send the plan as a message. It shows times and places, nothing private.',
  'itin.theySee': 'What they see',
  'itin.theyDont': 'What they don’t',
  'itin.sees.flights': 'Flight times and numbers',
  'itin.sees.hotel': 'Hotel name and address',
  'itin.sees.drivers': 'Driver names and pickup times',
  'itin.sees.tables': 'Booked tables and tours',
  'itin.hidden.passports': 'Passport numbers',
  'itin.hidden.paid': 'What you paid, and how',
  'itin.hidden.code': 'Your booking code',
  'itin.shareBtn': 'Share the plan',
  'itin.copied': 'Copied. Paste it in WhatsApp.',
  'itin.cantShare': 'Couldn’t share from here. Try again.',
  'itin.calTitle': 'Add to your calendar',
  'itin.calBody': 'The {n} moments that matter. Free-day ideas stay out.',
  'itin.add': 'Add',
  'itin.added': 'Added',
  'itin.allFile': 'Add all as a file',
  'itin.fileSaved': 'Saved. Open it and your calendar adds all {n}.',
  'itin.fileFailed': 'Your calendar app can’t take a file here. Add them one by one above.',

  /* disruption */
  'dz.call': 'Call',
  'dz.callA11y': 'Call the Mada desk on {phone}',
  'dz.callNumber': 'Call the Mada desk on {phone}.',
  'dz.callDesk': 'Call the desk',
  'dz.offTitle': 'No signal to load the options.',
  'dz.offBody': 'Call the desk and we’ll sort it by phone. {phone}, any hour.',
  'dz.working': 'Mada is on it.',
  'dz.step.held': 'Seats held',
  'dz.step.refund': 'Asking {airline} for the refund',
  'dz.theAirline': 'the airline',
  'dz.step.tickets': 'Moving your tickets',
  'dz.step.vouchers': 'Booking the hotel and meal vouchers',
  'dz.step.pickup': 'Moving the pickup',
  'dz.chooseAgain': 'Choose again',
  'dz.q.title': 'Saved on your phone. It sends when you’re back online.',
  'dz.q.body': 'Your choice: {choice}. Nothing has reached us yet. The moment your phone reconnects, it goes to {who} and we make the change. Seats stay held until {until}.',
  'dz.q.nightDesk': 'the night desk',
  'dz.q.waiting': 'Waiting for a connection',
  'dz.q.hurry': 'Need it sooner? Call the desk and we’ll do it by phone. {phone}, any hour.',
  'dz.backToday': 'Back to today',
  'dz.sentTitle': 'Sent. Mada made the change.',
  'dz.sentBody': 'Your choice reached us once you were back online. The trip shows the new plan.',
  'dz.today': 'Today',
  'dz.tonight': 'Tonight',
  'dz.chooseA11y': 'Choose what to do',
  'dz.rights.title': 'What the rules give you',
  'dz.rights.sub': 'Saudi aviation rules (GACA), in plain words',
  'dz.rights.care': 'Care while you wait.',
  'dz.rights.careBody': 'Meals and drinks, a hotel room when it runs overnight, and the ride there and back. The airline pays.',
  'dz.rights.choice': 'Your choice of the next flight or your money back.',
  'dz.rights.choiceBody': 'A full refund, even on a fare that says non-refundable.',
  'dz.rights.comp': 'Compensation on top',
  'dz.rights.compBody': 'when the airline cancels with less than 14 days’ notice. We claim it for you. You don’t need to fill in anything.',
  'dz.rather': 'Rather talk? Call {phone}',
  'dz.offlineNote': 'You’re offline. We’ll save your choice and send it the moment you’re back.',
  'dz.getRefund': 'Get the refund',
  'dz.stayOn': 'Stay on {code}',
  'dz.take': 'Take the {time}',
} as const;
