/**
 * Today's moments (M3), from the prototype's Today.jsx. Buttons say Mada; a person is named only as presence or when
 * they acted (COPY.md §1). Spread into ./en-trips.ts.
 */
export const enTripsToday = {
  'trip.direct': 'direct',
  'td.justYou': 'just you',
  'td.travellers': '{n} travellers',
  'td.openTrip': 'Open the trip',
  'td.lastTrip': '{when}, {you} went to {city}.',
  'td.lastTime': 'Last time',
  'td.tile.circle': 'Start a circle',
  'td.tile.circleBody': 'Plan the next trip together',
  'td.banner.now': 'now',

  // when
  'td.when.tomorrow': 'Tomorrow',
  'td.when.tomorrowAt': 'Tomorrow · {time}',
  'td.when.today': 'Today',
  'td.when.todayAt': 'Today · {time}',
  'td.when.thisWeek': 'This week',
  'td.when.inDays': 'In {n} days',
  'td.when.inWeeks': 'In {n} weeks',

  // demo panel
  'td.demo.title': 'Show a moment of the trip',
  'td.demo.body': 'For review builds. The trip clock jumps there; nothing real changes.',
  'td.demo.real': 'Real time',
  'td.demo.offline': 'Offline',
  'td.demo.showing': 'Showing: {phase}',
  'td.demo.phase.none': 'Nothing planned',
  'td.demo.phase.booked': 'Weeks before',
  'td.demo.phase.daybefore': 'Day before',
  'td.demo.phase.travelday': 'Travel day',
  'td.demo.phase.delayed': 'Delay predicted',
  'td.demo.phase.cancelled': 'Flight cancelled',
  'td.demo.phase.inair': 'In the air',
  'td.demo.phase.landed': 'Landed',
  'td.demo.phase.home': 'Back home',

  // requests card
  'td.req.answer': 'Mada has an answer on your {what}',
  'td.req.working': 'Mada is working on your {what}',
  'td.req.tap': 'Tap to see it',
  'td.req.queued': 'Sends when you’re back online',
  'td.req.usually': 'Usually within 2 hours',

  // tracking a flight
  'td.guest.title': 'Track any flight.',
  'td.guest.emptyTitle': 'Nothing tracked yet.',
  'td.guest.emptyBody': 'Add a flight number and we’ll watch the gate and the time for you. No account needed.',
  'td.guest.cardTitle': 'Want us to book and look after the whole trip?',
  'td.guest.cardBody': 'Sign in to book flights, stays and visas with a named agent behind every booking.',
  'td.guest.comeWith': 'Your tracked flights come with you.',
  'td.guest.signIn': 'Sign in',
  'td.track.label': 'Flight number',
  'td.track.when': 'When does it fly?',
  'td.track.today': 'Today',
  'td.track.tomorrow': 'Tomorrow',
  'td.track.pick': 'Pick a date',
  'td.track.date': 'Flight date',
  'td.track.pickDay': 'Pick the day it flies.',
  'td.track.submit': 'Track it',
  'td.track.errNumber': 'Add the number after the airline code, like SV263.',
  'td.track.errAirline': 'Start with the airline’s two-letter code, like SV or EK.',
  'td.track.errShape': 'Two letters or a letter and a number, then up to 4 digits. Like SV263 or F3101.',
  'td.track.askTitle': 'Want an alert if {code} changes?',
  'td.track.askBody': 'Gate changes, delays and cancellations for this flight. Nothing else. Your phone asks next.',
  'td.track.allow': 'Yes, alert me',
  'td.track.tracking': 'Tracking {code}.',
  'td.track.trackingAlerts': 'Tracking {code}. We’ll alert you if it changes.',
  'td.track.saved': 'Saved. We’ll find {code} when it’s in the air.',
  'td.track.onTime': 'On time',
  'td.track.late': 'Late',
  'td.track.waiting': 'Waiting',
  'td.track.unknown': 'We’ll find it when it’s in the air. Most airlines share a flight’s route a day before it leaves.',
  'td.track.alerts': 'We’ll alert you if it changes',
  'td.track.alertsOff': 'Alerts are off on this phone',
  'td.track.noAlerts': 'No alerts for this one',
  'td.track.fromTo': '{from} to {to}',
  'td.track.stop': 'Stop',
  'td.track.stopped': 'Stopped tracking {code}.',

  // weeks before: readiness
  'td.ready.count': '{done} of {total} ready',
  'td.ready.allSet': 'All set.',
  'td.ready.last': '{k} is the last thing.',
  'td.ready.left': '{n} things left. Each takes a minute.',
  'td.ready.nothing': 'Nothing needs you until the day before.',
  'td.ready.doneList': '{n} done: {list}',
  'td.ready.flight': 'Flight',
  'td.ready.flights': 'Flights',
  'td.ready.seatsTogether': 'seats {seats}, together',
  'td.ready.seat': 'seat {seat}',
  'td.ready.noFlights': 'No flights yet',
  'td.ready.noFlightsBody': 'The stay is booked. Add flights when you’re ready.',
  'td.ready.findFlights': 'Find flights',
  'td.ready.noStay': 'No stay yet',
  'td.ready.staysCancelled': 'The rooms were cancelled. We can find another.',
  'td.ready.noStayBody': 'Want rooms for the same dates? We can hold some.',
  'td.ready.findStay': 'Find a stay',
  'td.ready.whereStaying': 'Where you’re staying',
  'td.ready.stay': 'Stay',
  'td.ready.stayV': '{name} · {nights} nights',
  'td.ready.ppOf': '{name}’s passport',
  'td.ready.fixPp': 'Fix {name}’s passport',
  'td.ready.passport': 'Passport',
  'td.ready.passports': 'Passports',
  'td.ready.ppMissing': 'Not in the Wallet yet: {names}',
  'td.ready.addPp': 'Add it',
  'td.ready.ppValid': 'Valid for {country}',
  'td.ready.ppValidAll': 'All {n} valid for {country}',
  'td.ready.entry': 'Entry rules',
  'td.ready.entryV': 'Checked for you',
  'td.ready.entryAll': 'Checked for all {n}',
  'td.ready.data': 'Phone signal on landing',
  'td.ready.dataOne': 'Your phone works the minute you land. {price}.',
  'td.ready.dataMany': 'Phones work the minute you land. {price} each.',
  'td.ready.setUp': 'Set it up',
  'td.ready.esimDone': 'eSIM for {n} · installs before you fly',
  'td.ready.esimWaiting': 'With Mada. Pay once the price is ready.',
  'td.ready.esimPay': 'See it',
  'td.ready.pickups': 'Airport pickups',
  'td.ready.bothWays': 'Both ways · driver waits {wait}',
  'td.ready.oneWay': 'On the way there · driver waits {wait}',
  'td.ready.noPickup': 'No airport pickup',
  'td.ready.noPickupBody': 'A driver at arrivals with your name.',
  'td.ready.addPickup': 'Add a pickup',
  'td.esim.sheetTitle': 'Phone signal in {country}',
  'td.esim.sheetBody': '10 GB each for 7 days. It installs before you fly and switches on when you land. Refundable until it’s installed.',
  'td.esim.send': 'Send to Mada · {price}',
  'td.esim.sent': 'Sent to Mada. You pay once the eSIMs are ready.',
  'td.esim.offline': 'Connect to send it. Everything else is saved.',
  'td.offline.title': 'You’re offline.',
  'td.rel.self': 'You',
  'td.rel.spouse': 'Spouse',
  'td.rel.child': 'Child',
  'td.rel.parent': 'Parent',
  'td.rel.sibling': 'Sibling',
  'td.rel.helper': 'Helper',
  'td.rel.other': 'Family',

  // weeks before: next
  'td.next.title': 'Next for {city}',
  'td.next.cruise': 'Bosphorus dinner cruise',
  'td.next.cruiseMany': 'Dinner on the water for {n}. From Kabataş pier.',
  'td.next.cruiseOne': 'Dinner on the water. From Kabataş pier.',
  'td.next.anyEvening': 'Any evening',
  'td.next.kids': 'Three easy days with kids',
  'td.next.kidsNote': 'Palaces, ferries and the best künefe.',
  'td.next.plan': 'A plan for you',
  'td.next.walk': 'Galata to Karaköy on foot',
  'td.next.walkNote': 'Coffee, the tower and the water. A slow morning.',
  'td.next.walkAsk': 'A walk from Galata to Karaköy',
  'td.next.half': 'Half a day',
  'td.next.table': 'A table in Karaköy',
  'td.next.tableFamily': 'Halal, family seating, by the water.',
  'td.next.tableHalal': 'Halal, by the water.',
  'td.next.anyNight': 'Any night',
  'td.circleTips': 'Tips from people who’ve been',
  'td.circleTipsBody': 'See what travellers saved in {city}, in Circles.',

  // the day before
  'td.db.allSet': 'All set for tomorrow.',
  'td.db.oncePacked': 'All set, once you’ve packed.',
  'td.db.checkedIn': 'Checked in',
  'td.db.seat': 'Seat',
  'td.db.seats': 'Seats',
  'td.db.bags': '{bags} each',
  'td.db.pass': '1 boarding pass',
  'td.db.passes': '{n} boarding passes',
  'td.db.offline': 'Ready offline',
  'td.db.openPass': 'Open pass',
  'td.db.openPasses': 'Open passes',
  'td.plan.title': 'The plan',
  'td.plan.tonight': 'Tonight',
  'td.plan.pack': 'Pack the bags',
  'td.plan.packed': 'Packed',
  'td.plan.packSub': '{n} of {total} done',
  'td.plan.packedSub': 'All in. Nothing left for the morning.',
  'td.plan.seeList': 'See the list',
  'td.plan.lights': 'Lights out',
  'td.plan.lightsSub': '{n} hours before the alarm',
  'td.plan.wake': 'We wake your phone',
  'td.plan.wakeSub': 'A soft alarm, with the weather and the drive time',
  'td.plan.atDoor': '{driver} at your door',
  'td.plan.atDoorSub': '{car} · he waits {waits}',
  'td.plan.changePickup': 'Change pickup time',
  'td.plan.leave': 'Leave for the airport',
  'td.plan.leaveSub': '31 min to {airport}. No car booked.',
  'td.plan.airportSub': 'Bag drop closes {time}. You’re already checked in.',
  'td.plan.boarding': 'Boarding, gate {gate}',
  'td.plan.seats': 'Seats {seats}, together',
  'td.plan.seat': 'Seat {seat}',
  'td.plan.fly': '{code} to {city}',
  'td.plan.flySub': 'Lands {time}, local time',
  'td.plan.tomorrow': 'Tomorrow, {day}',
  'td.weather.onLanding': '{city} on landing',
  'td.weather.a11y': '{city} when you land: {temp} degrees. {summary}',
  'td.pack.title': 'Pack tonight',
  'td.pack.done': 'Packed. Sleep well.',
  'td.pack.doneBody': 'Everything’s in. We’ll handle the morning.',
  'td.pack.count': '{n} of {total} in the bags. Ticks stay on this phone.',
  'td.pack.passport': 'Your passport',
  'td.pack.passports': 'Passports ×{n}',
  'td.pack.ppFix': '{name}’s needs fixing first.',
  'td.pack.ppOk': 'Valid for {country}. Checked against the Wallet.',
  'td.pack.ppOkAll': 'All {n} valid for {country}. Checked against the Wallet.',
  'td.pack.chargers': 'Chargers and a power bank',
  'td.pack.chargersSub': 'Power banks go in hand luggage.',
  'td.pack.adapter': 'Plug adapter, {plug}',
  'td.pack.adapterSub': 'Round two-pin plugs in {country}, 230 V.',
  'td.pack.umbrella': 'An umbrella',
  'td.pack.umbrellaSub': 'Light rain when you land.',
  'td.pack.layer': 'A warm layer',
  'td.pack.layerEach': 'A warm layer each',
  'td.pack.layerSub': '{temp}° in {city}. About 28° here.',
  'td.pack.mat': 'Prayer mat',
  'td.pack.matHotel': 'The hotel is 2 minutes from a mosque.',
  'td.pack.matCity': 'Mosques are never far in {city}.',
  'td.pack.snacks': 'Snacks for {names}',
  'td.pack.snacksSub': '{dur} in the air.',
  'td.pack.meds': 'Medicines',
  'td.pack.medsSub': 'In hand luggage, with the prescriptions.',
  'td.pack.yours': 'Added by you',
  'td.pack.add': 'Add something to pack',
  'td.pack.addBtn': 'Add',
  'td.pack.remove': 'Remove {what}',
  'td.pickup.label': 'Change pickup time',
  'td.pickup.when': 'When should {driver} come?',
  'td.pickup.body': '31 min to {airport} at that hour. Bag drop for {code} closes at {time}.',
  'td.pickup.atBy': 'At {t} by {time}',
  'td.pickup.spare': '{n} min to spare',
  'td.pickup.tight': 'Only {n} min before bag drop closes',
  'td.pickup.suggest': 'what we suggest',
  'td.pickup.wake': 'We’ll wake your phone at {time}.',
  'td.pickup.stays': 'Pickup stays at {time}',
  'td.pickup.move': 'Move pickup to {time}',
  'td.pickup.told': 'We’ve told {driver}. Pickup at {time}.',
  'td.pickup.tightNote': 'That’s tight on a weekday morning. We’d go earlier.',

  // travel day
  'td.tv.allSet': 'All set.',
  'td.tv.oneThing': 'One thing to look at.',
  'td.tv.newFlight': 'All set on the new flight.',
  'td.tv.driverWaits': '{car}. He’ll wait at your door.',
  'td.tv.leaveBy': 'Leave by {time}',
  'td.tv.driveTo': '31 min to {airport}, {terminal}.',
  'td.tv.passes': 'Boarding passes',
  'td.leave.in': 'Leave home in',
  'td.leave.min': 'min',
  'td.leave.driver': '{driver} at {time}',
  'td.leave.noCar': 'No car booked',
  'td.leave.drive': '31 min to {airport}',
  'td.fc.onTime': 'On time',
  'td.fc.mayBeLate': 'May leave late',
  'td.fc.late': '{n} min late',
  'td.fc.gate': 'Gate',
  'td.fc.boards': 'Boards',
  'td.fc.seat': 'Seat',
  'td.fc.seats': 'Seats',
  'td.fc.live': 'Live from the airline · updated just now',
  'td.fc.offline': 'Offline · last update from the airline at {time}',
  'td.fc.gateChanged': 'Gate changed to {gate} · {min}-minute walk · live from the airline',
  'td.fc.inbound': 'The plane coming from Cairo is late.',
  'td.fc.predicted': 'Mada predicts a delay. {airline} hasn’t said yet.',
  'td.fc.seePlan': 'See the plan',
  'td.dw.title': 'What happens next',
  'td.dw.held': 'Seats held on the 10:25',
  'td.dw.heldAll': 'For all {n}, together. No cost to hold.',
  'td.dw.heldOne': 'A seat for you. No cost to hold.',
  'td.dw.watching': 'Watching the plane from Cairo',
  'td.dw.watchingSub': 'It should land in Riyadh by 08:30. We check every 5 minutes.',
  'td.dw.driver': '{driver} hears from us',
  'td.dw.driverSub': 'If you move flights, he comes later. Stay home until then.',
  'td.cx.title': '{airline} cancelled your flight.',
  'td.cx.bodyAll': 'You’re owed a full refund. We’re already holding seats on the next flight for all {n} of you.',
  'td.cx.bodyOne': 'You’re owed a full refund. We’re already holding a seat for you on the next flight.',
  'td.cx.options': 'See your options',
  'td.cx.taken': 'Already taken care of',
  'td.cx.hotel': 'The hotel knows',
  'td.cx.hotelRoom': '{name}: your room is held, even if you land late.',
  'td.cx.hotelRooms': '{name}: your rooms are held, even if you land late.',
  'td.cx.pickups': 'Pickups move with you',
  'td.cx.pickupsSub': '{a} and {b} follow whichever flight you choose.',
  'td.cx.money': 'Or your money back',
  'td.cx.moneySub': '{amount} for the {what}, to your card in about 7 days.',
  'td.cx.flight': 'flight',
  'td.cx.flights': 'flights',

  // presence lines (COPY.md §1: the person is presence; the action says Mada)
  'td.talk.today': '{agent} is with you today.',
  'td.talk.tonight': '{agent} is on call tonight.',
  'td.talk.watching': '{agent} is watching the plane from Cairo.',
  'td.talk.onPhone': '{agent} is already on the phone with {airline}.',
  'td.talk.wifi': 'On-board Wi-Fi? {agent} can still reach you.',
  'td.talk.arrival': '{agent} is watching your arrival.',

  // in the air
  'td.air.estimated': 'In the air · estimated, no signal needed',
  'td.air.live': 'In the air · {alt} ft, seen just now',
  'td.air.to': 'to {city}',
  'td.air.lookLeft': 'Look left in about 40 minutes: the Taurus Mountains.',
  'td.deck.title': 'Plan your first evening',
  'td.deck.body': 'Swipe right on what sounds good. We’ll book it when you land.',
  'td.deck.of': '{i} of {n}',
  'td.deck.yes': 'Yes, book it',
  'td.deck.yesA11y': 'Yes, book it when I land',
  'td.deck.skip': 'Skip',
  'td.deck.picks.one': 'Your first evening: 1 pick.',
  'td.deck.picks.other': 'Your first evening: {n} picks.',
  'td.deck.free': 'A free evening it is.',
  'td.deck.saved': 'Saved. We’ll book them the moment you land and have signal.',
  'td.deck.nothing': 'Nothing booked. You can always ask once you’re there.',
  'td.deck.again': 'Start over',
  'td.words.title': 'Five words for {city}',
  'td.words.body': 'For the taxi, the café and the kids.',
  'td.words.in': 'In {lang}',
  'td.words.english': 'In English',
  'td.words.say': 'say “{say}”',
  'td.words.tapFlip': 'Tap to flip',
  'td.words.tap': 'Tap to see it in the local language',
  'td.words.next': 'Next word',
  'td.words.again': 'Start again',
  'td.land.title': 'When you land',
  'td.land.passport': 'Passport control, then bags',
  'td.land.carousel': 'The carousel shows here as you land',
  'td.land.driver': '{driver} meets you at {door} with your name',
  'td.land.noCar': 'No car booked yet. Your options are below.',
  'td.land.where': 'Where are you staying?',
  'td.land.forDriver': 'The address for the driver',
  'td.land.gettingThere': 'Getting there',

  // landed
  'td.arr.landed': 'Landed {time} · {to}',
  'td.arr.sameTime': 'Same time as Riyadh',
  'td.arr.welcome': 'Welcome to {city}.',
  'td.arr.weather': '{temp}° and {summary}.',
  'td.arr.booking.one': 'Booking your pick for tonight',
  'td.arr.booking.other': 'Booking your {n} picks for tonight',
  'td.arr.bookingSub': 'The ones you chose in the air. Confirmation in about 5 minutes.',
  'td.arr.now': 'Now',
  'td.arr.through': 'You’re through.',
  'td.arr.count': '{n} of {total}',
  'td.arr.phone': 'Phone on',
  'td.arr.phoneSub': 'Free airport Wi-Fi for 1 hour. Turn on roaming only if you need it.',
  'td.arr.passport': 'Passport control',
  'td.arr.passportMany': 'Foreign passports lane. Keep all {n} together.',
  'td.arr.passportOne': 'Foreign passports lane. About 20 minutes.',
  'td.arr.kids': 'Children stay with you.',
  'td.arr.bags': 'Bags on {carousel}',
  'td.arr.theCarousel': 'the carousel',
  'td.arr.bagsSub': 'About 20 minutes after you land.',
  'td.arr.bagMissing': 'Bag reported missing',
  'td.arr.bagRef': 'Reference {ref}. {agent} is chasing it with {airline}.',
  'td.arr.money': 'Money',
  'td.arr.moneySub': 'Cards work almost everywhere. For small cash, {atm}.',
  'td.arr.moneyGeneric': 'Cards work almost everywhere. For small cash, use an ATM, not the exchange desk.',
  'td.arr.driverAt': '{driver} at {door}',
  'td.arr.toHotel': 'Getting to the hotel',
  'td.arr.gettingThere': 'Getting there',
  'td.arr.sign': 'Sign says {name}. He waits {waits} at no cost.',
  'td.arr.tellUs': 'Tell us where you’re staying.',
  'td.arr.noCar': 'No car booked. A pickup, a taxi or the metro.',
  'td.arr.room': 'Room ready at 14:00',
  'td.arr.rooms': 'Rooms ready at 14:00',
  'td.arr.roomSub': '{name}. {drive} drive.',
  'td.arr.toYours': 'To where you’re staying',
  'td.arr.noHotel': 'No hotel booked. Tell us, so the driver and Mada know.',
  'td.arr.hotelAddress': 'Hotel address',
  'td.arr.theAddress': 'The address',
  'td.arr.gotBags': 'Got the bags',
  'td.arr.bagDidnt': 'A bag didn’t arrive',
  'td.arr.withDriver': 'With the driver',
  'td.arr.atHotel': 'At the hotel',
  'td.arr.there': 'I’m there',
  'td.arr.done': 'Done',
  'td.arr.rest': 'Rest first. When you want dinner, ask us.',
  'td.arr.restPicks': 'Rest first. Your picks for tonight are being booked.',
  'td.arr.again': 'Start the list again',
  'td.bag.label': 'Missing bag',
  'td.bag.title': 'Before you leave the baggage hall',
  'td.bag.s1': 'Go to the {airline} baggage desk next to {carousel}.',
  'td.bag.s2': 'Show your bag tag (it’s on your boarding pass in the Wallet).',
  'td.bag.s3': 'They give you a reference that looks like ISTSV12345. Type it below.',
  'td.bag.ref': 'Reference from the desk',
  'td.bag.err': 'It’s 5 letters then 5 numbers, like ISTSV12345.',
  'td.bag.chase': 'Let Mada chase it',
  'td.bag.toast': '{agent} is chasing it with {airline}. Keep receipts for essentials, up to SAR 375 a day.',
  'td.bag.foot': 'Bags usually arrive within 48 hours. {airline} pays for essentials while you wait.',

  // address sheet
  'as.whereTitle': 'No hotel booked. Where are you staying?',
  'as.driverNeeds': '{driver} needs an address after the airport.',
  'as.soMada': 'So Mada knows where to reach you.',
  'as.address': 'Address',
  'as.hotelInstead': 'Want a hotel instead? Ask Mada for rooms for tonight.',
  'as.hotelAddress': 'Hotel address',
  'as.theAddress': 'The address',
  'as.checkIn': 'check-in from 14:00',
  'as.with': 'With {label}',
  'as.youGave': 'the address you gave us',
  'as.fullScreen': 'Show the address full screen',
  'as.tapFull': 'Tap to show it full screen to the driver',
  'as.google': 'Google Maps',
  'as.apple': 'Apple Maps',
  'as.copy': 'Copy',
  'as.copied': 'Address copied.',
  'as.holdCopy': 'Press and hold the address to copy it.',
  'as.callHotel': 'Call the hotel',
  'as.cantOpen': 'That didn’t open on this phone.',
  'as.meeting': '{driver} is meeting you',
  'as.meetingBody': '{door}, arrivals hall, with a sign saying {sign}. {car}. He waits {waits} after you land, at no cost.',
  'as.call': 'Call {driver}',
  'as.message': 'Message',
  'as.noCar': 'No car booked. Three ways there',
  'as.opt.pickup': 'A Mada pickup',
  'as.opt.pickupSub': 'SAR 220 {all}· driver waits 60 min',
  'as.forAll': 'for all of you',
  'as.opt.taxi': 'Taxi from the rank',
  'as.opt.taxiGeneric': 'From the official rank outside arrivals. Ask for the meter.',
  'as.opt.metro': 'Metro',
  'as.opt.metroGeneric': 'Cheapest, and hard with big bags.',
  'as.bookPickup': 'Ask Mada for the pickup · SAR 220',
  'as.pickupAsked': 'Sent to Mada. You pay once the driver is confirmed.',
  'as.taxiTip': 'Only take taxis from the rank. If a driver won’t use the meter, take the next one. Show them the address above.',
  'as.directions': 'Directions in Google Maps',
  'as.offline': 'Saved on this phone. Works without signal.',
  'as.forDriver': 'Address for the driver',
  'as.takeMe': 'Please take me here',
  'as.tapClose': 'Tap anywhere to close',
  'as.pickupTitle': 'Airport pickup on arrival',
  'as.pickupShort': 'pickup',
  'as.pickupDetail': '{airport} · a driver at arrivals with your name',
  'as.pickupQuote': 'A driver at arrivals with your name, waiting 60 minutes. {price}.',

  // move the hotel and pickup
  'mv.both': 'Your hotel and pickup are',
  'mv.hotel': 'Your hotel is',
  'mv.pickup': 'Your pickup is',
  'mv.stillOn': '{what} still on {day}.',
  'mv.flightNow': 'Your flight is now {day}.',
  'mv.moveThem': 'Move them to {day}',
  'mv.moveIt': 'Move it to {day}',
  'mv.titleBoth': 'Move the hotel and pickup to {day} too?',
  'mv.titleHotel': 'Move the hotel to {day} too?',
  'mv.titlePickup': 'Move the pickup to {day} too?',
  'mv.flightIs': 'Your flight is now {day} at {time}.',
  'mv.checkIn': 'Check in {from} → {to} · {n} nights',
  'mv.atDoor': '{driver} at your door',
  'mv.noCost': 'No cost',
  'mv.nothingBack': 'Nothing back',
  'mv.keepsNight': 'After the free window the hotel keeps the night you drop.',
  'mv.extraNight': 'The hotel needs to say yes to the extra night. You pay once they do.',
  'mv.both.btn': 'Move both',
  'mv.it.btn': 'Move it',
  'mv.back': '{amount} back',
  'mv.keep': 'Keep them as they are',
  'mv.familyFriends': 'family or friends',
  'mv.whereStaying': 'Where are you staying?',
  'mv.addrPh': 'Street, area, city',
  'mv.addrErr': 'Add the street and the area.',
  'mv.saveAddr': 'Save the address',
  'mv.saved': 'Saved. The driver has the address.',
  'mv.findHotel': 'Find a hotel',
  'mv.sameDates': 'For the same dates',
  'mv.withFamily': 'With family or friends',
  'mv.addAddr': 'Add the address for the driver',
  'mv.later': 'Decide later',

  // back home
  'td.home.title': 'Welcome home.',
  'td.home.noLag': '{city} runs on Riyadh time, so no jet lag. Rest tonight. Nothing needs you.',
  'td.home.rest': 'Rest tonight. Nothing needs you.',
  'td.home.oneWay': 'You flew one way, so there’s no flight home on this trip. Tell Mada if you want one.',
  'td.home.stampA11y': 'New passport stamp: {label} {day}',
  'td.home.night': '1 night in {city}',
  'td.home.nights': '{n} nights in {city}',
  'td.home.newStamp': 'New stamp: {country}.',
  'td.home.countries': '{n} countries now.',
  'td.home.first': 'Your first with Mada.',
  'td.home.km': 'km flown',
  'td.home.nightWord': 'night',
  'td.home.nightsWord': 'nights',
  'td.home.traveller': 'traveller',
  'td.home.ofYou': 'of you',
  'td.home.whole': 'The whole trip',
  'td.home.noExtra': 'No extra charges',
  'td.home.flight': 'Flight',
  'td.home.flights': 'Flights',
  'td.home.stay': 'Stay',
  'td.home.pickups': 'Pickups',
  'td.home.refund': 'Refund on its way · {amount}',
  'td.home.refundAsked': 'Requested from {airline}',
  'td.home.refundApproved': 'Approved. Sent to {card} next.',
  'td.home.credit': '{amount} Mada credit',
  'td.home.creditSub': 'Unused. It comes off your next booking by itself.',
  'td.home.receipts': 'Receipts in Trips',
  'td.home.planNext': 'Plan the next one',
  'td.home.good.winter': 'Good this winter',
  'td.home.good.spring': 'Good this spring',
  'td.home.good.summer': 'Good this summer',
  'td.rate.how': 'How was it',
  'td.rate.q.hotel': 'Same hotel next time?',
  'td.rate.q.driver': 'How were the drivers?',
  'td.rate.q.agent': 'And {agent}?',
  'td.rate.agentWho': 'Your agent for this trip',
  'td.rate.drivers': '{a} in Riyadh, {b} in {city}',
  'td.rate.yes': 'Yes, remember it',
  'td.rate.no': 'Not this one',
  'td.rate.great': 'Great',
  'td.rate.fine': 'Fine',
  'td.rate.poor': 'Not good',
  'td.rate.hotelYes': 'Saved. We’ll suggest it first next time.',
  'td.rate.hotelNo': 'Got it. We won’t suggest it again.',
  'td.rate.anything': 'Anything {agent} should know?',
  'td.rate.notePh': 'Optional. The kids loved the ferry…',
  'td.rate.noteA11y': 'A note for {agent}',
  'td.rate.sent': 'Sent to Mada.',
  'td.rate.thanks': 'Thank you. {agent} reads every one.',
  'td.rate.noteWent': 'Your note went with it.',
  'td.rate.change': 'Change my answers',
  'td.mem.add': 'Add 3 favourite photos',
  'td.mem.three': 'Three to remember it by.',
  'td.mem.go': 'They go on the trip card, to find them later.',
  'td.mem.goMany': 'They go on the trip card, so {you} can find them.',
  'td.mem.onTrip': 'They’re on the trip card now.',
  'td.mem.onTripMany': 'They’re on the trip now, for {you}.',
  'td.mem.added': 'Added to the {city} trip.',
  'td.mem.cant': 'That one didn’t open. Try another photo.',
  'td.mem.addOne': 'Add a photo',
  'td.mem.remove': 'Remove photo {n}',
  'td.ideas.forUs': 'for the {n} of us',
  'td.ideas.forMe': 'for me',
  'td.ideas.alula': 'AlUla',
  'td.ideas.alulaWinter': 'Cool nights, warm days. 1h 20m away.',
  'td.ideas.alulaSpring': 'The last cool weeks before summer.',
  'td.ideas.alulaAsk': 'Two days in AlUla',
  'td.ideas.alulaOct': 'AlUla in October',
  'td.ideas.alulaOctNote': 'Book now, the season fills fast.',
  'td.ideas.season': 'Riyadh Season',
  'td.ideas.seasonNote': 'A weekend at home, done properly.',
  'td.ideas.seasonAsk': 'A weekend at Riyadh Season {us}',
  'td.ideas.snow': 'Somewhere with snow',
  'td.ideas.snowNote': 'Gudauri or Erzurum, 4h away.',
  'td.ideas.snowAsk': 'Somewhere with snow in January {us}',
  'td.ideas.abha': 'Abha',
  'td.ideas.abhaSpring': 'Green mountains, 20° in May.',
  'td.ideas.abhaSummer': 'Escape the heat, 1h 40m away.',
  'td.ideas.abhaAsk': 'A long weekend in Abha',
  'td.ideas.riyadh': 'Riyadh',
  'td.ideas.riyadhNote': 'Staycation while it’s still mild.',
  'td.ideas.riyadhAsk': 'A staycation in Riyadh',
  'td.ideas.baku': 'Back to Baku',
  'td.ideas.bakuNote': 'You loved it last Eid. 24° in July.',
  'td.ideas.bakuAsk': 'Baku again this summer {us}',
  'td.ideas.tbilisi': 'Tbilisi',
  'td.ideas.tbilisiNote': '24° in July. 3h 30m away.',
  'td.ideas.tbilisiAsk': 'Tbilisi this summer {us}',
} as const;
