/*
 * Places: worldwide city search, the city page and "Plan it with Mada" (any city, planned by hand when we don't sell
 * it in the app). Spread into the catalogue in en.ts; held to the same COPY.md lint.
 */
export const placesCopy = {
  // ───────────── search ─────────────
  'places.search.title': 'Where to?',
  'places.search.placeholder': 'A city or an airport code',
  'places.search.label': 'Search cities and airports',
  'places.search.recent': 'Recent',
  'places.search.near': 'Near you',
  'places.search.popular': 'Where people go',
  'places.search.clearRecent': 'Clear',
  'places.search.clear': 'Clear the search',
  'places.search.none': 'No city called ‘{q}’.',
  'places.search.noneBody': 'Try a city or an airport code.',
  'places.search.closest': 'Closest we know',
  'places.search.offline': 'You’re offline. Search works again the moment you’re back.',
  'places.search.retry': 'Search again',
  'places.hit.alsoCalled': 'Also called {name}',
  'places.hit.airport': '{label}',

  // ───────────── the city page ─────────────
  'places.city.timeThere': '{time} there',
  'places.city.sameTime': 'Same time as you',
  'places.city.ahead': '{hours} ahead of you',
  'places.city.behind': '{hours} behind you',
  'places.city.hour.one': '1 hour',
  'places.city.hour.other': '{count} hours',
  'places.city.weather': 'The forecast shows here 10 days before you go.',
  'places.city.airports': 'Airports',
  'places.city.airportKm': '{km} km from the centre',
  'places.city.money': 'Money',
  'places.city.guide': 'The guide',
  'places.city.readOn': 'Read on at Wikivoyage',
  'places.city.wikipedia': 'Read on at Wikipedia',
  'places.city.sources': 'Sources',
  'places.city.section.understand': 'Understand',
  'places.city.section.getIn': 'Getting there',
  'places.city.section.see': 'See',
  'places.city.section.do': 'Do',
  'places.city.section.eat': 'Eat',
  'places.city.section.staySafe': 'Stay safe',
  'places.city.trimmed': 'Shortened from the original.',
  'places.city.plan': 'Plan it with Mada',
  'places.city.planServed': 'Flights and rooms for {city} are right here. Tell us who’s going and when.',
  'places.city.localTime': 'Local time',
  'places.city.nearest': 'Nearest airport',
  'places.city.planByHandAway': 'We’ll put it together by hand. Mada replies here within 10 minutes, any hour.',
  'places.city.planByHand': 'We’ll put it together by hand. {agent} replies here, usually within 20 minutes.',
  'places.city.notFound': 'We can’t find that city.',
  'places.city.notFoundBody': 'Search again by its name or its airport code.',
  'places.city.search': 'Search cities',
  'places.city.loadingGuide': 'Opening the guide…',
  'places.city.a11yHero': '{city}, {country}',

  // ───────────── plan it with Mada ─────────────
  'places.plan.title': 'Plan {city} with Mada',
  'places.plan.who': 'How many of you',
  'places.plan.when': 'When',
  'places.plan.month': 'Pick a month',
  'places.plan.undecided': 'Not sure yet',
  'places.plan.message': 'Your message',
  'places.plan.send': 'Send to Mada',
  'places.plan.sending': 'Sending…',
  'places.plan.offline': 'You’re offline. It sends the moment you’re back.',
  'places.request.title': 'A trip to {city}',
  'places.request.detail': '{city}, {country}',
} as const;
