/**
 * When things go wrong (FLOWS.md §12): no connection, a weak one, a slow or busy server, a supplier that isn't
 * answering, an update that's needed, maintenance, a crash. COPY.md §5.6 is the standard: say what happened, what
 * still works, and the one thing to do. Calm, no alarm words, nothing that sounds like a system.
 */
export const resilienceCopy = {
  // ───────────── connection ─────────────
  'net.offline.title': 'You’re offline.',
  'net.offline.body': 'This needs a connection. Everything for your trips is still on this phone.',
  'net.offline.retryOnline': 'We’ll load it the moment you’re back.',
  'net.offline.queued': 'You’re offline. We’ll send it the moment you’re back.',
  'net.back': 'Back online.',
  'net.back.sending.one': 'Back online. Sent 1 thing you did offline.',
  'net.back.sending.other': 'Back online. Sent {count} things you did offline.',
  'net.weak': 'Your connection is slow right now.',

  // ───────────── freshness ─────────────
  'fresh.justNow': 'Updated just now',
  'fresh.minutes': 'Updated {minutes} min ago',
  'fresh.hours': 'Updated {hours}h ago',
  'fresh.date': 'Updated {date}',
  'fresh.offline': 'Saved on this phone · updated {when}',
  'fresh.last': 'Last updated {when}',

  // ───────────── waiting ─────────────
  'slow.title': 'Still working… slower than usual',
  'slow.body': 'Nothing you did is lost.',
  'slow.bodyWeak': 'Your connection is weak. Nothing you did is lost.',
  'slow.cancel': 'Cancel',
  'timeout.title': 'This is taking too long.',
  'timeout.body': 'The connection may be weak. Nothing you did was lost.',
  'busy.wait': 'We’re busy for a moment. Trying again in {seconds} seconds.',
  'busy.title': 'Let’s take a short pause.',
  'busy.body': 'There were a lot of tries in a row. We’ll try again in {seconds} seconds. Nothing is locked.',

  // ───────────── our side ─────────────
  'problem.inline': 'This didn’t load.',
  'problem.title': 'That didn’t work, and it’s on us.',
  'problem.body': 'Your trips and documents are safe on this phone. Try once more, or talk to Mada.',
  'problem.ref': 'Reference {ref}',
  'problem.partial.title': 'Part of this didn’t load.',
  'problem.partial.body': 'Updating Mada usually fixes it. Everything else works as normal.',
  'crash.eyebrow': 'Holding pattern',
  'crash.title': 'We’re circling for a moment. Your trips are safe.',
  'crash.body': 'Something on our side stopped. Your bookings, payments and documents are untouched. Restart and you’ll land back on Today.',
  'crash.note': 'Our team already knows. No personal details were sent.',
  'crash.restart': 'Restart Mada',

  // ───────────── suppliers ─────────────
  'supplierDown.title': '{supplier}’s system isn’t answering.',
  'supplierDown.body': 'We try again every minute. Talk to Mada and we’ll book it by hand.',
  'supplierDown.bodyBooking': '{agent} is booking this by hand. You don’t need to do anything.',
  'supplierDown.generic': 'The airline',
  'supplierDown.status': '{supplier} is slow to answer right now.',
  // The names suppliers go by on screen (GET /status labels), written to read well in "{supplier}’s system isn’t answering."
  'supplier.flights': 'The airline',
  'supplier.hotels': 'The hotel',
  'supplier.payments': 'The bank',
  'supplier.sms': 'The text message service',
  'supplier.whatsapp': 'WhatsApp',
  'supplier.email': 'The email service',
  'supplier.flightStatus': 'The flight tracker',
  'supplier.flightPositions': 'The flight map',
  'supplier.ai': 'The instant answers service',
  'supplier.identity': 'Apple or Google',

  // ───────────── sessions ─────────────
  'session.expired.title': 'Sign back in to carry on.',
  'session.expired.body': 'You’ve been signed out to keep your account safe. What you typed is still here.',
  'session.expired.action': 'Sign in',
  'session.expired.to': 'We’ll text a code to {phone}.',

  // ───────────── versions and maintenance ─────────────
  'update.title': 'Update Mada to keep booking.',
  'update.body': 'This version can’t reach bookings any more. Your trips and documents are safe, and they’re all here after the update.',
  'update.note': 'Usually under a minute on Wi-Fi.',
  'update.action': 'Update Mada',
  'update.offline': 'Open my trips',
  'update.soft': 'A new version of Mada is ready.',
  'update.softAction': 'Update',
  'maintenance.title': 'Mada is being updated.',
  'maintenance.titleUntil': 'Mada is being updated until {time}.',
  'maintenance.body': 'Booking, changes and payments pause for now. It’s planned, and nothing you’ve booked is affected.',
  'maintenance.bodyUntil': 'Booking, changes and payments pause until {time} Riyadh time. It’s planned, and nothing you’ve booked is affected.',
  'maintenance.works': 'Your trips and Wallet still work offline, with boarding passes and the hotel address.',
  'maintenance.call': 'Talk to Mada by phone',
  'maintenance.note': 'The desk answers any hour on {phone}.',
  'maintenance.until': 'Back by {time}.',
  'maintenance.banner': 'Maintenance · booking paused',
  'maintenance.bannerUntil': 'Maintenance until {time} · booking paused',
  'maintenance.trips': 'Open my trips',
  'maintenance.retry': 'Check again',

  // ───────────── money and orders ─────────────
  'net.pay.offlineTitle': 'You’re offline, so we stopped before paying.',
  'pay.dropped.title': 'The connection dropped while paying.',
  'net.pay.held': 'Nothing was charged. Your price is held for {minutes} more minutes.',
  'pay.already': 'Already paying. You can only be charged once.',
  'net.pay.offlineBody': 'Nothing was charged. We’ll pick up right where you left off.',
  'pay.offline.resume': 'Resume',
  'pay.unknown.title': 'We’re checking with your bank.',
  'pay.unknown.body': 'You won’t be charged twice. We’ll show the answer here.',
  'order.resumed': 'Your {place} booking is still with {agent}.',

  // ───────────── outbox ─────────────
  'outbox.queued': 'Queued',
  'outbox.queuedLine': 'Sends when you’re online',
  'outbox.sending': 'Sending',
  'outbox.stuck': 'Didn’t send',
  'outbox.why': 'It didn’t reach Mada. Nothing is lost.',
  'outbox.retry': 'Send again',
  'outbox.discard': 'Discard',
  'outbox.discarded': 'Discarded. Nothing was sent.',
  'outbox.empty': 'Nothing waiting to send',
  'outbox.offline': 'You’re offline. These go the moment you’re back.',
  'outbox.down': 'Mada isn’t answering right now. These go the moment it does.',
  'outbox.allSent': 'Everything you did has reached Mada.',
  'outbox.works': 'Works without a connection',
  'outbox.worksBody': 'Trips, Wallet, boarding passes, your itinerary and the hotel address in the local language.',
  'outbox.call': 'Call Mada · {phone}',
  'pill.offline': 'Offline · your trips are on this phone',
  'pill.offlineWaiting': 'Offline · {count} waiting to send',
  'pill.down': 'Can’t reach Mada right now',
  'pill.downWaiting': 'Can’t reach Mada · {count} waiting',
  'pill.weak': 'Weak connection · loading slowly',
  'pill.sending.one': 'Sending 1 thing…',
  'pill.sending.other': 'Sending {count} things…',
  'pill.held': '{count} didn’t send · open the Outbox',
  'pill.a11y': '{text}. Open the Outbox.',
  'outbox.title': 'Waiting to send',

  // ───────────── things that aren't there ─────────────
  'gone.title': 'This link doesn’t go anywhere now.',
  'gone.body': 'What it pointed to was removed, or it was shared with someone else. Nothing of yours has changed.',
  'gone.trips': 'See your trips',
  'gone.home': 'Go to Today',
  'gone.inviteTitle': 'This invite has expired.',
  'gone.inviteBody': 'Invites last 7 days. Ask whoever sent it for a new link.',

  // ───────────── the phone itself ─────────────
  'storage.full.title': 'Your phone is almost full.',
  'storage.full.body': 'We couldn’t save your trips for offline use. Free up some space and we’ll try again.',
  'perm.settings': 'Open Settings',
  'perm.camera.title': 'The camera is off for Mada.',
  'perm.camera.body': 'We use it to read passports and documents. Nothing is saved until you check it. Turn it on in Settings › Mada, or carry on without it.',
  'perm.camera.manual': 'Upload a photo instead',
  'perm.contacts.title': 'Contacts are off for Mada.',
  'perm.contacts.body': 'We match numbers on this phone to show who’s already on Mada. They’re never uploaded. Turn it on in Settings › Mada, or carry on without it.',
  'perm.contacts.manual': 'Share your invite link',
  'perm.location.title': 'Location is off for Mada.',
  'perm.location.body': 'We use your city, never your street, so friends you chose can see you’re nearby. Turn it on in Settings › Mada, or carry on without it.',
  'perm.location.manual': 'Choose your city instead',
  'perm.notifications.title': 'Alerts are off for Mada.',
  'perm.notifications.body': 'Gate changes, delays and your driver arriving. Never offers. Turn it on in Settings › Mada, or carry on without it.',
  'perm.notifications.manual': 'Get them by SMS instead',
  'perm.photos.title': 'Photos are off for Mada.',
  'perm.photos.body': 'We use them to add a document from your photos. Turn it on in Settings › Mada, or carry on without it.',
  'perm.photos.manual': 'Choose a file instead',

  // ───────────── server-side codes (errors.ts) ─────────────
  'error.supplierDown': 'That supplier isn’t answering. Talk to Mada and we’ll do it by hand.',
  'error.maintenance': 'Booking is paused for a few minutes while we make Mada better.',
  'error.upgradeRequired': 'This version of Mada needs an update.',
  'error.idempotencyConflict': 'That was already sent with different details. Check it and send again.',
  'error.inProgress': 'We’re still on the first try. Give it a few seconds.',
  'error.timeout': 'This is taking too long. Nothing you did was lost.',
} as const;
