/**
 * Strings for the Wallet, passports, documents, money, the account screens, Help and support (M1).
 * Lifted from the prototype (Wallet.jsx, Onboarding.jsx, Account.jsx, Profile.jsx, Support.jsx) with COPY.md applied:
 * where the prototype used a banned word ("unlock", "data", "soon") the line was reworded and is listed in the
 * M1 report for the writer's review. Spread into the catalogue in en.ts, so the copy lint covers every line here.
 */
export const walletCopy = {
  // ───────────── wallet: lock ─────────────
  'wallet.lock.title': 'Wallet is locked',
  'wallet.lock.body': 'Passports and visas for the whole family. Stored encrypted, and they work offline.',
  'wallet.lock.checking': 'Checking Face ID',
  'wallet.lock.open': 'Open with Face ID',
  'wallet.lock.failed': "Face ID didn't match. Use your passcode.",
  'wallet.lock.passcode': 'Passcode',
  'wallet.lock.usePasscode': 'Use passcode',
  'wallet.lock.openWallet': 'Open the Wallet',
  'wallet.lock.wrong.one': "That passcode doesn't match. 1 try left.",
  'wallet.lock.wrong.other': "That passcode doesn't match. {count} tries left.",
  'wallet.lock.lockedOut': 'Too many tries. Try again in {minutes} min, or open it with Face ID.',
  'wallet.lock.demo': 'Demo passcode: 123456',
  'wallet.lock.prompt': 'Open your Wallet',
  'wallet.lock.lockedWith': 'Locked with Face ID · works offline',
  'wallet.lock.notLocked': 'Opens without Face ID · works offline',

  // ───────────── wallet: passport card ─────────────
  'wallet.add': 'Add a document',
  'wallet.whose': 'Whose documents',
  'wallet.signedOut.title': 'Add a passport and we’ll keep an eye on it.',
  'wallet.signedOut.body': 'Expiry dates, visas and entry rules, checked against every trip.',
  'wallet.signedOut.action': 'Sign in to add one',
  'wallet.passport.waitingOther': '{name}’s passport isn’t here yet.',
  'wallet.passport.number': 'Number',
  'wallet.passport.born': 'Born',
  'wallet.passport.expires': 'Expires',
  'wallet.passport.issuedBy': 'Issued by {country}',
  'wallet.chip.valid': 'Valid',
  'wallet.chip.ready': 'Ready for {city}',
  'wallet.chip.spare': 'Ready · {days} days to spare',
  'wallet.chip.notValid': 'Not valid for {city}',
  'wallet.chip.expired': 'Expired',
  'wallet.validity.validUntil': 'Valid until {date}.',
  'wallet.validity.validUntilBody': 'We’ll check it against every trip you plan.',
  'wallet.validity.expired': 'This passport expired on {date}.',
  'wallet.validity.expiredBody': 'It can’t be used to travel. Mada can help you renew it.',
  'wallet.validity.ready': 'Ready for {city}.',
  'wallet.validity.readyBody': 'Valid well beyond the {days} days {country} asks for after you land.',
  'wallet.validity.spare': 'Fine for {city}, with {days} days to spare.',
  'wallet.validity.spareBody': 'Fine for {city}: {country} asks for {need} days after you land, {name} has {left}.',
  'wallet.validity.blockedYou': 'You can’t travel to {city} on this passport.',
  'wallet.validity.blocked': '{name} can’t travel to {city} on this passport.',
  'wallet.validity.blockedBody': '{name}’s passport expires on {date}. {country} needs {need} days after you land, so it must be valid until {until}.',
  'wallet.validity.notOnTrip': '{name} isn’t on the {city} trip.',
  'wallet.validity.trip': 'Trip · {date}',
  'wallet.validity.until': 'Needed until {date}',
  'wallet.renew': 'Book a renewal',
  'wallet.renew.sent': 'Sent to Mada. We’ll find the earliest renewal slot for {name}.',
  'wallet.copyNumber': 'Copy number',
  'wallet.copyNumber.done': 'Number copied.',
  'wallet.copyNumber.masked': 'We only keep the last digits on this phone: {number}. The full number is with Mada, encrypted.',
  'wallet.docs.eyebrowOther': '{name}’s other documents',
  'wallet.docs.emptyTitleOther': 'No other documents yet',
  'wallet.docs.emptyBodyOther': 'A visa, a national ID or travel insurance for {name}. We’ll watch the dates.',
  'wallet.docs.addFor': 'Add a document for {name}',
  'wallet.docs.iqama': 'Iqama',
  'wallet.docs.exitVisa': 'Exit and re-entry visa',
  'wallet.docs.notAdded': 'Not added',
  'wallet.docs.exitNeeded': 'Needed before each trip abroad',
  'wallet.docs.addIt': 'Add it',
  'wallet.docs.replace': 'Replace with a newer one',
  'wallet.docs.replaceBody': 'Scan or upload it. The old one is removed once the new one is saved.',
  'wallet.docs.share': 'Share with Mada',
  'wallet.docs.shareBody': 'For a visa or a booking. Faisal can see it until the trip ends.',
  'wallet.docs.shared': 'Shared with Mada for this trip only. Faisal can see it, not download it.',
  'wallet.docs.sharedUntil': 'Faisal can see it until {date}.',
  'wallet.docs.stopSharing': 'Stop sharing',
  'wallet.docs.stopped': 'Faisal can’t see it any more.',
  'wallet.docs.view': 'See the file',
  'wallet.docs.delete': 'Delete',
  'wallet.docs.deleted': 'Deleted from this phone and from Mada.',
  'wallet.docs.setup': 'Added when you set up Mada. To remove it, talk to Mada.',
  'wallet.docs.added': 'Added just now',
  'wallet.docs.validUntil': 'Valid until {date}',
  'wallet.docs.expiresOn': '{number} · expires {date}',
  'wallet.passes.title': 'Boarding passes',
  'wallet.passes.row': '{flight} · {count} boarding passes',
  'wallet.passes.rowOne': '{flight} · 1 boarding pass',
  'wallet.passes.rowSub': '{date} · {terminal} · seats {seats}',
  'wallet.passes.rowSubOne': '{date} · {terminal} · seat {seats}',
  'wallet.passes.notYet': 'For {flight} on {date}. They open at check-in, 24 hours before you fly.',
  'wallet.passes.noFlights': 'No flights on this trip.',
  'wallet.pass.seat': 'Seat {seat}',
  'wallet.pass.terminal': 'Terminal',
  'wallet.pass.gate': 'Gate',
  'wallet.pass.boards': 'Boards',
  'wallet.pass.previous': 'Previous',
  'wallet.pass.next': 'Next',
  'wallet.pass.of': '{n} of {count}',
  'wallet.pass.code': 'Boarding pass code',
  'wallet.pass.bright': 'Turn the brightness up at the gate.',
  'wallet.pass.appleWallet': 'Add to Apple Wallet',
  'wallet.vouchers': 'Vouchers from the airline',

  // ───────────── wallet: money ─────────────
  'money.eyebrow': 'Money',
  'money.credit': 'Mada credit',
  'money.credit.used': 'Used first at checkout. Never expires.',
  'money.credit.zero': 'Refunds can land here instantly instead of waiting for the bank.',
  'money.credit.title': 'Mada credit · {amount}',
  'money.credit.body': 'Money Mada holds for you. It comes from refunds you chose to take as credit, and it’s used first whenever you pay. It never expires, and you can move it to your card at any time.',
  'money.credit.emptyTitle': 'Nothing has moved yet.',
  'money.credit.emptyBody': 'Refunds you take as credit show here, with the date. They come off your next booking first.',
  'money.credit.move': 'Move it to my card',
  'money.credit.moved': '{amount} is on its way to your {card}. 5 to 10 working days.',
  'money.credit.movedTo': 'Moved to {card}',
  'money.credit.refund': 'Refund as credit',
  'money.credit.goodwill': 'From Mada',
  'money.credit.spend': 'Used on a booking',
  'money.credit.adjustment': 'Adjustment',
  'money.credit.expiry': 'Expired',
  'money.credit.notEnough': 'There isn’t that much Mada credit. Your balance is {amount}.',
  'money.credit.nothing': 'There’s no Mada credit to move.',
  'money.cards': 'Cards and Apple Pay',
  'money.cards.sub': '{count} saved · default {label}',
  'money.cards.subOne': '1 saved · default {label}',
  'money.cards.none': 'No cards yet · Apple Pay is ready on this phone',

  // ───────────── cards ─────────────
  'cards.title': 'Pay with',
  'cards.creditNote': 'You have {amount} Mada credit. It’s used first.',
  'cards.expires': 'Expires {exp}',
  'cards.applePay': 'Apple Pay',
  'cards.add': 'Add a card',
  'cards.number': 'Card number',
  'cards.expiry': 'Expiry',
  'cards.cvv': 'Security code',
  'cards.cvvHint': '3 digits',
  'cards.name': 'Name on the card',
  'cards.save': 'Save this card for next time',
  'cards.note': 'Card details go straight to the payment provider. Mada never sees the full number.',
  'cards.test': 'Test card: 4242 4242 4242 4242.',
  'cards.use': 'Use this card',
  'cards.problem.amex': 'We can’t take American Express yet. Use Visa, Mastercard or mada.',
  'cards.problem.luhn': 'That number doesn’t look right. Check each digit.',
  'cards.problem.short': 'Card numbers have 16 digits.',
  'cards.problem.brand': 'We take Visa, Mastercard and mada.',
  'cards.problem.expired': 'This card has expired.',
  'cards.problem.format': 'Use MM/YY, like 08/28.',
  'cards.label': '{brand} ending {last}',
  'cards.default.applePay': 'Apple Pay is your default.',
  'cards.default.changed': '{label} is your default now.',
  'cards.default.same': 'That’s already your default.',
  'cards.default.updated': 'Default card updated.',
  'cards.default': 'Default',
  'cards.remove': 'Remove',
  'cards.removeLabel': 'Remove {label}',
  'cards.removed': 'Card removed.',
  'cards.removedApplePay': 'Card removed. Apple Pay is your default.',
  'cards.removeDefault.title': 'That’s your default card.',
  'cards.removeDefault.body': 'Pick what to use from now on, then we’ll remove it.',
  'cards.removeDefault.use': 'Use {label}',
  'cards.removeLast.title': 'Remove your only card?',
  'cards.removeLast.body': 'You can still pay with Apple Pay. Add a card any time when you book.',
  'cards.removeLast.confirm': 'Remove card',
  'cards.keep': 'Keep it',
  'cards.pickDefault': 'Choose the new default first.',

  // ───────────── adding a document ─────────────
  'docs.add.title': 'What are you adding?',
  'docs.kind.passport': 'Passport',
  'docs.kind.visa': 'Visa',
  'docs.kind.id': 'National ID or iqama',
  'docs.kind.insurance': 'Travel insurance',
  'docs.kind.other': 'Something else',
  'docs.title.passport': 'Passport',
  'docs.title.visa': 'Visa',
  'docs.title.national_id': 'National ID',
  'docs.title.iqama': 'Iqama',
  'docs.title.exit_reentry': 'Exit and re-entry visa',
  'docs.title.insurance': 'Travel insurance',
  'docs.title.other': 'Document',
  'docs.upload.for': 'Add {what} for {name}',
  'docs.upload.aDocument': 'a document',
  'docs.upload.scan': 'Scan with the camera',
  'docs.upload.scanSub': 'Best for passports and printed visas',
  'docs.upload.photo': 'Take a photo of the photo page',
  'docs.upload.photoSub': 'We read the two lines at the bottom',
  'docs.upload.file': 'Upload a photo or PDF',
  'docs.upload.fileSub': 'From your files or photos · up to 10 MB',
  'docs.upload.choosePhoto': 'Choose a photo',
  'docs.upload.choosePhotoSub': 'From your photos · up to 10 MB',
  'docs.upload.reading': 'Reading {name}…',
  'docs.upload.readingPage': 'Reading the page…',
  'docs.upload.failed': "We couldn't read it.",
  'docs.upload.failedBody': 'Try a sharper photo, flat and without glare, or a PDF straight from the issuer.',
  'docs.upload.failedPassport': 'Lay it flat on a table, away from glare, with the whole photo page in the shot, including the two lines at the bottom.',
  'docs.upload.found': 'We found this. Check it before saving.',
  'docs.upload.foundPhoto': 'Read from your photo. Check every letter before saving.',
  'docs.upload.checkThis': 'Check this',
  'docs.upload.save': 'Save',
  'docs.upload.wrong': "Something's wrong",
  'docs.upload.saved': 'Saved to the Wallet.',
  'docs.upload.sending': 'Saving it, encrypted…',
  'docs.field.type': 'Type',
  'docs.field.valid': 'Valid',
  'docs.field.name': 'Name',
  'docs.field.insurer': 'Insurer',
  'docs.field.covers': 'Covers',
  'docs.field.policy': 'Policy',
  'docs.field.document': 'Document',
  'docs.field.number': 'Number',
  'docs.field.expires': 'Expires',
  'docs.field.validUntil': 'Valid until (DD/MM/YYYY)',
  'docs.field.validUntilHint': 'So we can remind you before it runs out.',
  'wallet.upload.wrongType': 'That file type won’t work. Use a photo or a PDF.',
  'wallet.upload.tooBig': 'That file is over 10 MB. Try a photo of the page instead.',
  'wallet.upload.photoOnly': 'We read passports from a photo, not a PDF. Take a photo of the photo page instead.',

  // ───────────── passport: add, scan, confirm ─────────────
  'passport.later': 'Later',
  'passport.title': 'Scan it once. Never type it again.',
  'passport.body': 'Every flight, hotel and visa fills itself in from now on, for you and everyone you travel with.',
  'passport.lock': 'Encrypted, and opened only when Mada books for you.',
  'passport.titleFor': 'Scan {name}’s passport once.',
  'passport.scan': 'Scan passport',
  'passport.byHand': 'Enter it by hand',
  'passport.demo.head': 'Kingdom of Saudi Arabia',
  'passport.demo.type': 'Passport · P',
  'passport.demo.surname': 'Surname',
  'passport.demo.given': 'Given names',
  'passport.demo.no': 'No.',
  'passport.demo.expires': 'Expires',
  'passport.demo.form': 'Saudia · Passenger 1',
  'passport.demo.filled': 'Filled by your scan',
  'passport.demo.nameOnTicket': 'Name on ticket',
  'passport.demo.passport': 'Passport',
  'passport.demo.valid': 'Valid for this trip',
  'passport.camera.title': '“Mada” would like to use the camera',
  'passport.camera.body': 'To read your passport. Nothing is uploaded until you check the details.',
  'passport.camera.allow': 'Allow',
  'passport.camera.deny': "Don't allow",
  'passport.camera.deniedTitle': 'No camera, no problem.',
  'passport.camera.deniedBody': 'Enter the details by hand now. You can allow the camera later in Settings.',
  'passport.camera.doLater': 'Do it later',
  'passport.camera.settings': 'Open Settings',
  'passport.camera.cancel': 'Cancel',
  'passport.camera.hold': 'Photograph the photo page',
  'passport.camera.holdBody': 'Flat on a table, no glare, with the two lines at the bottom in the shot.',
  'passport.camera.take': 'Take a photo',
  'passport.camera.choose': 'Choose a photo',
  'passport.camera.useDemo': 'Use the demo passport',
  'passport.camera.private': 'Read on this phone. The photo isn’t uploaded or kept.',
  'passport.camera.demoTitle': 'Hold the photo page in the frame',
  'passport.camera.demoBody': 'Reading the two lines at the bottom…',
  'passport.camera.reading': 'Reading your passport…',
  'passport.camera.warming': 'Getting ready. The first scan takes a few seconds longer.',
  'passport.camera.looking': 'Looking for the two lines at the bottom.',
  'passport.camera.failed': "We couldn't read it.",
  'passport.camera.tip1': 'Lay the passport flat on a table.',
  'passport.camera.tip2': 'No glare. Turn away from lamps and windows.',
  'passport.camera.tip3': 'Get the whole photo page in, including the two lines at the bottom.',
  'passport.camera.readerMissing': 'The passport reader didn’t load. Check your connection and try again.',
  'passport.camera.notPhoto': 'That isn’t a photo. Choose a JPG or PNG of the photo page.',
  'passport.camera.tooBig': 'That photo is over 10 MB. Try a smaller one, or take a new photo.',
  'passport.camera.cantOpen': 'That photo couldn’t be opened. Try a JPG or PNG.',
  'passport.confirm.title': 'Is this right?',
  'passport.confirm.titleManual': 'Exactly as on the photo page.',
  'passport.confirm.bar': 'Passport details',
  'passport.confirm.body': 'Airlines need names to match the passport letter for letter, including every given name.',
  'passport.confirm.fromPhoto': 'Read from your photo. Check every letter.',
  'passport.confirm.doubt.one': 'One detail may not have read right.',
  'passport.confirm.doubt.other': '{count} details may not have read right.',
  'passport.field.given': 'Given names',
  'passport.field.surname': 'Surname',
  'passport.field.number': 'Passport number',
  'passport.field.nationality': 'Nationality',
  'passport.field.dob': 'Date of birth (DD/MM/YYYY)',
  'passport.field.expiry': 'Expiry date (DD/MM/YYYY)',
  'passport.field.check': 'Check this. It may not have read right.',
  'passport.field.badDate': 'Use the format DD/MM/YYYY, for example 22/06/2031.',
  'passport.field.badNumber': 'Letters and digits only, as on the photo page.',
  'passport.field.badCountry': 'Write the country as on the passport, like Saudi Arabia.',
  'passport.expired.title': 'This passport has expired.',
  'passport.expired.body': "We'll save it, but it can't be used to travel. Mada can help you renew it.",
  'passport.fillMore.one': 'Fill in 1 more',
  'passport.fillMore.other': 'Fill in {count} more',
  'passport.save': 'Save passport',
  'passport.saveScanned': 'Yes, save it',
  'passport.saved': 'Passport saved. It fills in every booking from now on.',
  'passport.savedFor': '{name}’s passport is saved.',

  // ───────────── profile ─────────────
  'profile.guest.title': 'You’re tracking a flight.',
  'profile.guest.body': 'Sign in to book, keep your trips and add your family’s passports.',
  'profile.guest.signIn': 'Sign in',
  'profile.yourAccount': 'Your account',
  'profile.addPhone': 'Add a mobile number',
  'profile.addPassport': 'Add your passport to fill in your name',
  'profile.details': 'Your details',
  'profile.detailsSub': 'Name, email, phone, home airport',
  'profile.account': 'Account',
  'profile.signin': 'Sign-in methods',
  'profile.signinNone': 'None',
  'profile.prefs': 'Travel preferences',
  'profile.prefsNoLoyalty': 'no loyalty numbers yet',
  'profile.prefsLoyalty.one': '1 loyalty number',
  'profile.prefsLoyalty.other': '{count} loyalty numbers',
  'profile.household': 'Household',
  'profile.justYou': 'Just you',
  'profile.household.youNoPassport': 'Your passport isn’t scanned yet · add your family',
  'profile.household.addFamily': 'Add your family to book for everyone',
  'profile.household.needs.one': '1 passport needs a look',
  'profile.household.needs.other': '{count} passports need a look',
  'profile.household.allGood': 'Everyone’s passport is scanned',
  'profile.paying': 'Paying',
  'profile.noCards': 'No cards saved',
  'profile.noCardsSub': 'Add one when you book, or now.',
  'profile.noCardsApplePay': 'No cards saved. Apple Pay works on this phone.',
  'profile.credit': '{amount} Mada credit',
  'profile.creditSub': 'Used first on your next booking.',
  'profile.changeCard': 'Change default or add a card',
  'profile.addCard': 'Add a card',
  'profile.alerts': 'Alerts',
  'profile.alerts.quiet': 'Quiet',
  'profile.alerts.everything': 'Everything',
  'profile.alerts.label': 'How often we alert you',
  'profile.alerts.quietBody': 'Only when you need to act: gate changes, delays, leave-now, documents. Everything else waits for the evening digest.',
  'profile.alerts.everythingBody': 'Every update about your trips as it happens. Still never offers.',
  'profile.alerts.off': 'Alerts are off for Mada on this phone. Turn them on in Settings to get gate changes.',
  'profile.app': 'App',
  'profile.language': 'Language',
  'profile.languageSub': 'English · العربية is on its way',
  'profile.languageSubNotify': 'English · we’ll tell you when العربية is ready',
  'profile.security': 'Security',
  'profile.securitySub.one': '{face} · 1 device',
  'profile.securitySub.other': '{face} · {count} devices',
  'profile.faceOn': 'Face ID on',
  'profile.faceOff': 'Face ID off',
  'profile.privacy': 'Privacy',
  'profile.privacySub': 'Download, delete, what we keep',
  'profile.privacySubPending': 'Your copy is on its way by email',
  'profile.help': 'Help',
  'profile.helpSub': 'Questions, talk to Mada, terms',
  'profile.inbox': 'Updates',
  'profile.inboxSub.zero': 'Nothing new',
  'profile.inboxSub.one': '1 new',
  'profile.inboxSub.other': '{count} new',
  'profile.signOut': 'Sign out',
  'profile.version': 'Mada Trips {version}',
  'profile.photoChange': 'Change photo',
  'profile.photoAdd': 'Add a photo',

  // ───────────── account: details ─────────────
  'account.title': 'Your details',
  'account.intro': 'Each detail shows where it came from. Mada uses these on every booking.',
  'account.name': 'Name',
  'account.passportName': 'Name on your passport',
  'account.notScanned': 'Not scanned yet',
  'account.calledYou': 'What Mada calls you',
  'account.addName': 'Add a name',
  'account.nameWait': 'We’ll use your first name once your passport is in',
  'account.contact': 'Contact',
  'account.email': 'Email',
  'account.notAdded': 'Not added',
  'account.emailWarn': 'Add one to get tickets and receipts',
  'account.mobile': 'Mobile',
  'account.mobileWarn': 'Add one for gate changes and Faisal’s messages',
  'account.fromPassport': 'From your passport',
  'account.dob': 'Date of birth',
  'account.nationality': 'Nationality',
  'account.forBookings': 'For bookings',
  'account.home': 'Home airport',
  'account.language': 'Language',
  'account.currency': 'Prices shown in',
  'account.src.passport': 'From your passport scan',
  'account.src.typed': 'You typed it',
  'account.src.apple': 'From Apple sign-in',
  'account.src.google': 'From Google sign-in',
  'account.src.signup': 'Verified by text when you signed up',
  'account.src.verified': 'Verified',
  'account.src.verifiedOn': 'Verified on {date}',
  'account.src.default': 'Mada default',
  'account.src.none': 'Not scanned yet',
  'account.src.added': 'Set when you added them',
  'account.locked.nameTitle': 'Comes from your passport.',
  'account.locked.fieldTitle': 'Read from your passport.',
  'account.locked.nameBody': 'Airlines need it letter for letter. To change it, scan a new passport.',
  'account.locked.fieldBody': 'It always matches your passport. To change it, scan a new passport.',
  'account.locked.notYet': 'You haven’t scanned yours yet.',
  'account.locked.scanNew': 'Scan a new passport',
  'account.locked.scanMine': 'Scan my passport',
  'account.preferred.title': 'What should we call you?',
  'account.preferred.body': 'Used in messages from Mada and Faisal. Tickets always use your passport name.',
  'account.preferred.empty': 'Add the name you’d like us to use.',
  'account.preferred.long': 'Keep it under 30 letters.',
  'account.preferred.letters': 'Use letters only.',
  'account.preferred.save': 'Save name',
  'account.preferred.saved': 'We’ll call you {name}.',
  'account.preferred.usePassport': 'Use my passport name',
  'account.preferred.reset': 'We’ll use the name on your passport.',
  'account.email.yours': 'Your email',
  'account.email.new': 'New email',
  'account.email.add': 'Add your email',
  'account.email.body': 'Tickets, receipts and visa letters go here. We send a code to check it’s yours.',
  'account.email.bad': 'That doesn’t look like an email address. Check for an @ and a dot.',
  'account.email.same': 'That’s already your email.',
  'account.email.send': 'Send me a code',
  'account.email.relayTitle': 'A private address from Apple',
  'account.email.relayBody': 'You chose Hide My Email when you signed in. Mail we send here is forwarded to your Apple ID inbox. You can keep it, or use your own address.',
  'account.email.useOwn': 'Use my own email',
  'account.email.change': 'Change email',
  'account.email.keep': 'Keep this one',
  'account.email.verified': 'Email verified. Tickets and receipts go there now.',
  'account.code.title': 'Enter the code',
  'account.code.sentTo': 'Sent to {to}.',
  'account.code.change': 'Change',
  'account.code.label': '6-digit code',
  'account.code.wrong.one': "That code doesn't match. 1 try left.",
  'account.code.wrong.other': "That code doesn't match. {count} tries left.",
  'account.code.locked': 'Too many tries. Get a new code to carry on.',
  'account.code.newIn': 'New code in 0:{seconds}',
  'account.code.resend': 'Send a new code',
  'account.code.resent': 'New code sent.',
  'account.code.offline': 'You’re offline. We’ll send it once you’re connected.',
  'account.code.demo': 'Demo code: 123456',
  'account.phone.change': 'Change your number',
  'account.phone.add': 'Add your number',
  'account.phone.now': 'Now {phone}.',
  'account.phone.body': 'We’ll text a code to the new number to check it’s yours.',
  'account.phone.label': 'New mobile number',
  'account.phone.same': 'That’s the number you already use.',
  'account.phone.taken': 'That number is on another Mada account. Sign in with it there, or ask Mada to move it to this one.',
  'account.phone.switchTo': 'Switch to {phone}?',
  'account.phone.use': 'Use {phone}?',
  'account.phone.stops': 'Stops working',
  'account.phone.fromNow': 'From now on',
  'account.phone.confirmBody': 'Your old number stops working for sign-in straight away. Trip texts and calls from Faisal go to the new one. Airlines on booked trips get it too.',
  'account.phone.useNew': 'Use the new number',
  'account.phone.keepOld': 'Keep my old number',
  'account.phone.changed': 'Number changed. Use it next time you sign in.',
  'account.phone.added': 'Added. You can sign in with it too.',
  'account.offline': 'You’re offline. We’ll be able to send the code once you’re connected.',
  'account.home.title': 'Where do you usually fly from?',
  'account.home.main': 'Main airports',
  'account.home.other': 'Another airport',
  'account.home.placeholder': 'City or 3-letter code',
  'account.home.none': 'No Saudi airport matches “{q}”. Try the city or the 3-letter code. For airports abroad, ask Mada.',
  'account.home.saved': 'Flights start from {code} unless you say otherwise.',
  'account.language.title': 'Language',
  'account.language.arabicSub': 'On its way. Written by a Saudi writer, not translated by a machine.',
  'account.language.next': 'Next',
  'account.language.notify': 'Tell me when Arabic is ready',
  'account.language.notifySub': 'One alert, then never again.',
  'account.language.notifyOn': 'We’ll tell you when العربية is ready.',
  'account.language.done': 'Done',
  'account.currency.title': 'Show prices in',
  'account.currency.note': 'You’re always charged in SAR. Other currencies are a guide, at today’s rate.',
  'account.currency.sar': 'Prices in SAR.',
  'account.currency.other': 'Prices shown in {code} too. You’re still charged in SAR.',
  'account.photo.title': 'Your photo',
  'account.photo.added': 'Added {date}. Faisal and your circles see it.',
  'account.photo.body': 'Faisal and your circles see it. It’s never on a booking.',
  'account.photo.take': 'Take a photo',
  'account.photo.choose': 'Choose a photo',
  'account.photo.remove': 'Remove photo',
  'account.photo.removed': 'Photo removed.',
  'account.photo.updated': 'Photo updated.',
  'account.photo.rules': 'JPEG or PNG, up to 10 MB.',
  'account.photo.notPhoto': 'That file isn’t a photo. Choose a JPEG or PNG.',
  'account.photo.tooBig': 'That photo is over 10 MB. Choose one under 10 MB.',

  // ───────────── account: sign-in methods ─────────────
  'signinMethods.title': 'Sign-in methods',
  'signinMethods.body': 'Ways into your account. Keep at least two, so losing one never locks you out.',
  'signinMethods.apple': 'Apple',
  'signinMethods.appleSub': 'Face ID or your Apple password',
  'signinMethods.google': 'Google',
  'signinMethods.googleSub': 'Your Google account',
  'signinMethods.phone': 'Phone number',
  'signinMethods.phoneSub': 'A code by text',
  'signinMethods.hideOn': 'Hide My Email is on',
  'signinMethods.notLinked': 'Not linked',
  'signinMethods.linked': 'Linked',
  'signinMethods.add': 'Add',
  'signinMethods.onlyOne': 'Only one way in.',
  'signinMethods.onlyOneBody': 'Add another method so you can still sign in if you lose this one.',
  'signinMethods.hideTitle': 'About Hide My Email',
  'signinMethods.hideBody': 'When you sign in with Apple you can hide your real address. Apple gives us a private one that forwards to you. You can turn it off any time in your iPhone’s Settings, under Apple ID, Sign in with Apple.',
  'signinMethods.addTitle': 'Add {name} as a way in?',
  'signinMethods.addApple': 'Apple shares your name and an email. You can hide your real address.',
  'signinMethods.addGoogle': 'Google shares your name and email address. Nothing else.',
  'signinMethods.continue': 'Continue with {name}',
  'signinMethods.offline': 'You’re offline. Connect to add a sign-in method.',
  'signinMethods.added': '{name} added. You can sign in with it now.',
  'signinMethods.phoneManage': 'You sign in with a code sent to {phone}. To use a different number, change it in Your details.',
  'signinMethods.canSignIn': 'You can sign in with {name}.',
  'signinMethods.onlyWay': 'This is your only way in.',
  'signinMethods.onlyWayBody': 'Add another method before you remove this one.',
  'signinMethods.relayNote': 'Your email is Apple’s private address. Mail to it still reaches you, but we’d suggest adding your own email in Your details.',
  'signinMethods.remove': 'Remove {name}',
  'signinMethods.removed': '{name} removed. You can’t sign in with it now.',
  'signinMethods.keep': 'Keep it',
  'signinMethods.taken': 'That {name} account is already on another Mada account.',

  // ───────────── account: travel preferences ─────────────
  'prefs.title': 'Travel preferences',
  'prefs.body': 'Faisal uses these on every booking for you. Change them any time. Trips already booked keep what was asked for.',
  'prefs.seats': 'Seats',
  'prefs.seat.window': 'Window',
  'prefs.seat.aisle': 'Aisle',
  'prefs.seat.any': 'No preference',
  'prefs.seat.anyShort': 'Any seat',
  'prefs.together': 'Seat us together with family',
  'prefs.togetherSub': 'We pay for seat selection when an airline charges for it, and tell you first.',
  'prefs.meal': 'Meal',
  'prefs.meal.halal': 'Halal',
  'prefs.meal.veg': 'Vegetarian',
  'prefs.meal.vegan': 'Vegan',
  'prefs.meal.child': 'Child meal',
  'prefs.meal.diabetic': 'Diabetic',
  'prefs.meal.gluten': 'Gluten-free',
  'prefs.meal.lowsalt': 'Low salt',
  'prefs.meal.halalNote': 'Every meal on Saudi airlines is halal. On other airlines we ask for it.',
  'prefs.meal.childNote': 'Child meals are for ages 2 to 11. For adults we’ll ask for a light meal.',
  'prefs.meal.otherNote': 'Asked for at booking. Airlines need it 24 hours before the flight.',
  'prefs.assist': 'Help at the airport',
  'prefs.assist.wchr': 'Wheelchair to the gate',
  'prefs.assist.wchrSub': 'You can walk short distances and climb steps.',
  'prefs.assist.wchc': 'Wheelchair to the seat',
  'prefs.assist.wchcSub': 'Help all the way to your seat on board.',
  'prefs.assist.infant': 'Travelling with an infant',
  'prefs.assist.infantSub': 'Under 2, on a lap. Airlines need to know when we book.',
  'prefs.assist.bassinet': 'Bassinet',
  'prefs.assist.bassinetSub': 'A cot fixed to the wall in front. Limited, so we ask early.',
  'prefs.assist.bassinetOff': 'Turn on “Travelling with an infant” first.',
  'prefs.loyalty': 'Loyalty numbers',
  'prefs.loyalty.emptyTitle': 'No loyalty numbers yet',
  'prefs.loyalty.emptyBody': 'Add Alfursan, or a hotel programme, and every booking we make earns you points.',
  'prefs.loyalty.add': 'Add a loyalty number',
  'prefs.loyalty.edit': 'Edit {name}',
  'prefs.loyalty.airlines': 'Airlines',
  'prefs.loyalty.hotels': 'Hotels',
  'prefs.loyalty.number': 'Membership number',
  'prefs.loyalty.dup': 'You already have a {name} number. Edit that one instead.',
  'prefs.loyalty.bad': 'That doesn’t look like a {name} number. It’s {hint}.',
  'prefs.loyalty.save': 'Save number',
  'prefs.loyalty.saved': '{name} saved. We add it to every booking that earns.',
  'prefs.loyalty.remove': 'Remove',
  'prefs.loyalty.removedAirline': '{name} removed. Points already earned stay with the airline.',
  'prefs.loyalty.removedHotel': '{name} removed. Points already earned stay with the hotel.',
  'prefs.notes': 'Notes for Faisal',
  'prefs.notesHint': 'Anything that helps, like “Hessa prefers early flights” or “Ahmed gets travel sick.”',
  'prefs.notesSaved': 'Saved for Faisal.',

  // ───────────── household ─────────────
  'household.title': 'Household',
  'household.body': 'Everyone you book for. Their passports and preferences fill in every trip.',
  'household.you': '{name} (you)',
  'household.youPlain': 'You',
  'household.holder': 'Account holder',
  'household.emptyTitle': 'Just you so far.',
  'household.emptyBody': 'Add the people you book for. Their names and passports fill in every trip, so nobody types them twice.',
  'household.note': 'Passports are scanned in the Wallet and stay encrypted.',
  'household.add': 'Add someone',
  'household.status.none': 'Not scanned',
  'household.status.problem': 'Needs renewing',
  'household.status.expired': 'Expired',
  'household.status.soon': 'Expiring',
  'household.status.ok': 'Scanned',
  'household.status.expiredText': 'Expired on {date}. It can’t be used to travel.',
  'household.status.soonText': 'Expires {date}. Many countries want 6 months left when you land.',
  'household.age.infant': 'Infant · under 2',
  'household.age.child': 'Child · {age}',
  'household.age.teen': 'Teen · {age}',
  'household.age.adult': 'Adult · {age}',
  'household.age.infantNote': 'Flies on a lap or in a bassinet. Needs their own passport.',
  'household.age.childNote': 'Child fare on most airlines, from 2 to 11.',
  'household.age.teenNote': 'Adult fare from 12. Still a minor for visas and consent letters.',
  'household.gone': 'No longer in your household.',
  'household.youHolder': 'You · account holder',
  'household.passport': 'Passport',
  'household.notScannedYou': 'Your passport isn’t scanned yet.',
  'household.notScanned': '{name}’s passport isn’t scanned yet.',
  'household.expiresLine': '{number} · expires {date}',
  'household.scanMine': 'Scan my passport',
  'household.scanTheirs': 'Scan their passport',
  'household.scanNew': 'Scan the new passport',
  'household.details': 'Details',
  'household.relation': 'Relation',
  'household.yourDetails': 'Your details and preferences',
  'household.yourDetailsSub': 'Name, contact, seats, meals',
  'household.residency': 'Residency',
  'household.iqama': 'Iqama number',
  'household.iqamaLength': 'An iqama number has 10 digits (this has {count}).',
  'household.iqamaPrefix': 'Iqama numbers start with 2. Saudi ID numbers start with 1.',
  'household.iqamaSaved': 'Iqama number saved.',
  'household.exit': 'Exit and re-entry visa',
  'household.exit.none': 'None yet',
  'household.exit.single': 'Single',
  'household.exit.multiple': 'Multiple',
  'household.exit.useBy': 'Use by (DD/MM/YYYY)',
  'household.exit.needed': 'Needed before {name} travels abroad. You issue it on Absher as the sponsor.',
  'household.exit.addDate': 'Add the date it must be used by.',
  'household.exit.expired': 'Expired on {date}. Issue a new one on Absher before any trip.',
  'household.exit.valid': 'Valid until {date} · {days} days left.',
  'household.remove': 'Remove {name} from household',
  'household.remove.title': 'Remove {name}?',
  'household.remove.body': '{name}’s passport and preferences are deleted. Bookings already made stay as they are. You can add them again any time.',
  'household.remove.confirm': 'Remove {name}',
  'household.remove.keep': 'Keep {name}',
  'household.removed': '{name} removed from your household.',
  'household.relation.title': '{name} is your…',
  'household.relation.note': 'Some visas and consent letters ask how you’re related.',
  'household.saved': 'Saved.',
  'household.addTitle': 'Add someone',
  'household.addBody': 'Names exactly as on their passport. You can scan it later from the Wallet.',
  'household.addGiven': 'Given names',
  'household.addSurname': 'Surname',
  'household.addHelperNote': "We'll ask for their iqama and exit and re-entry visa before any trip abroad.",
  'household.addButton': 'Add {name}',
  'household.addThem': 'Add them',
  'household.added': '{name} added. Scan their passport from the Wallet when you can.',
  'household.relation.Spouse': 'Spouse',
  'household.relation.Son': 'Son',
  'household.relation.Daughter': 'Daughter',
  'household.relation.Parent': 'Parent',
  'household.relation.Sibling': 'Sibling',
  'household.relation.Relative': 'Relative',
  'household.relation.Friend': 'Friend',
  'household.relation.Helper': 'Helper',
  'household.relation.Colleague': 'Colleague',
  'household.relation.Family': 'Family',

  // ───────────── security ─────────────
  'security.title': 'Security',
  'security.wallet': 'Wallet',
  'security.faceId': 'Face ID for the Wallet',
  'security.checking': 'Checking Face ID…',
  'security.on': 'Passports open only after Face ID or your passcode.',
  'security.off': 'Off. Anyone with your unlocked phone can open passports.',
  'security.faceFailed': 'Face ID didn’t match. Try again, or set it up in your iPhone’s Settings.',
  'security.faceOnToast': 'Wallet locks with Face ID.',
  'security.signedInOn': 'Signed in on',
  'security.thisPhone': 'This phone',
  'security.signOut': 'Sign out',
  'security.onlyThis': 'Only this phone is signed in.',
  'security.onlyThisBody': 'If you sign in on an iPad or the web, it shows here, and you can sign it out from this phone.',
  'security.unknown': 'Don’t recognise a device? Sign it out, then tell Mada.',
  'security.everywhere': 'Sign out everywhere',
  'security.faceOff.title': 'Turn off Face ID for the Wallet?',
  'security.faceOff.body': 'Passports and visas will open without a check. Anyone holding your unlocked phone could see them.',
  'security.faceOff.confirm': 'Turn it off',
  'security.faceOff.keep': 'Keep Face ID',
  'security.faceOff.done': 'Face ID off for the Wallet.',
  'security.device.title': 'Sign out of {name}?',
  'security.device.body': 'It will need Apple, Google or a code to get back in. Anything saved only on that device is removed from it.',
  'security.device.confirm': 'Sign out of {name}',
  'security.device.offline': 'You’re offline. Connect to sign out another device.',
  'security.device.done': 'Signed out of {name}.',
  'security.device.sub': '{platform} · {when}',
  'security.device.now': 'now',
  'security.device.web': 'madatrips.sa on the web',
  'security.device.unknown': 'A phone',

  // ───────────── sign out ─────────────
  'signout.title': 'Sign out?',
  'signout.titleEverywhere': 'Sign out everywhere?',
  'signout.body': 'Your trips stay in your account either way. What should stay on this phone?',
  'signout.bodyEverywhere': 'Every device, this phone included. Your trips stay in your account either way. What should stay on this phone?',
  'signout.keep': 'Keep my trips on this phone',
  'signout.keepBody': 'Faster to sign back in. Your passport stays encrypted and locked until you sign in.',
  'signout.keepBodyFamily.one': 'Faster to sign back in. Passports for you and 1 other stay encrypted and locked until you sign in.',
  'signout.keepBodyFamily.other': 'Faster to sign back in. Passports for you and {count} others stay encrypted and locked until you sign in.',
  'signout.remove': 'Remove everything from this phone',
  'signout.removeBody': 'For a shared or borrowed phone. Trips, passports, cards and photos are wiped from it. Sign in again to get them back.',

  // ───────────── privacy ─────────────
  'privacy.title': 'Privacy',
  'privacy.yours': 'Your copy',
  'privacy.export': 'Download everything',
  'privacy.exportSub': 'Trips, documents, payments and messages, as one file.',
  'privacy.exportPending': 'Copy on its way',
  'privacy.exportPendingSub': 'Asked for {date} at {time}. A link goes to {email} within 24 hours.',
  'privacy.pending': 'Pending',
  'privacy.keep': 'What we keep, and why',
  'privacy.keep.passports': 'Passports and IDs',
  'privacy.keep.passportsWhy': 'To book flights, hotels and visas. Encrypted. Sent only to the airline, hotel or embassy when we book.',
  'privacy.keep.contact': 'Name, phone and email',
  'privacy.keep.contactWhy': 'To sign you in and reach you about your trips.',
  'privacy.keep.trips': 'Trips and payments',
  'privacy.keep.tripsWhy': 'So you can see and change them. Card numbers are held by our payment provider, not by Mada.',
  'privacy.keep.prefs': 'Preferences',
  'privacy.keep.prefsWhy': 'Seats, meals and loyalty numbers, to fill in bookings.',
  'privacy.keep.location': 'Location',
  'privacy.keep.locationWhy': 'Only on travel days, to time your drive. And for Who’s around, when it’s on.',
  'privacy.keep.usage': 'App usage',
  'privacy.keep.usageWhy': 'If you allow it. To find what’s slow. Never sold, never used for ads.',
  'privacy.choose': 'You choose',
  'privacy.marketing': 'Offers by email',
  'privacy.marketingSub': 'Never on unless you ask. At most one email a month.',
  'privacy.analytics': 'Help us improve the app',
  'privacy.analyticsSub': 'Anonymous usage, like which screens are slow.',
  'privacy.delete': 'Delete my account',
  'privacy.footer': 'We never sell what you share with us. Questions go to privacy@madatrips.sa.',
  'privacy.export.title': 'Get a copy of everything?',
  'privacy.export.body': 'We’ll email a download link within 24 hours. The link works for 7 days.',
  'privacy.export.bodyTo': 'We’ll email a download link to {email} within 24 hours. The link works for 7 days.',
  'privacy.export.needEmail': 'Add an email in Your details first, so we have somewhere to send it.',
  'privacy.export.confirm': 'Email me my copy',
  'privacy.export.offline': 'You’re offline. Ask again once you’re connected.',
  'privacy.export.done': 'Requested. We’ll email a link within 24 hours.',
  'privacy.delete.title': 'Delete your account?',
  'privacy.delete.body': 'In 30 days we delete your trips, documents, household and preferences. Until then you can change your mind.',
  'privacy.delete.bookings': 'Bookings already made stay with the airline and hotel.',
  'privacy.delete.bookingsTrip': 'Bookings already made stay with the airline and hotel, including {city} on {date}.',
  'privacy.delete.refunds': 'Refunds still in progress still reach your card.',
  'privacy.delete.receipts': 'We keep receipts for 5 years, because the law asks us to.',
  'privacy.delete.type': 'Type DELETE to confirm',
  'privacy.delete.typeWord': 'Type the word DELETE.',
  'privacy.delete.confirm': 'Delete in 30 days',
  'privacy.delete.keep': 'Keep my account',
  'privacy.delete.scheduled': 'Scheduled for {date}.',
  'privacy.banner.title': 'Scheduled for deletion on {date}.',
  'privacy.banner.body': 'Everything stays until then. Bookings stay with the airlines.',
  'privacy.banner.cancel': 'Cancel deletion',
  'privacy.banner.cancelled': 'Deletion cancelled. Your account stays.',
  'privacy.exportEmail.subject': 'Your Mada Trips copy',
  'privacy.exportEmail.body': 'Here is everything Mada Trips keeps for you, as you asked. The link works for 7 days: {link}',

  // ───────────── help and legal ─────────────
  'help.title': 'Help',
  'help.talk': 'Talk to Mada',
  'help.talkBody': 'A person answers, day and night. Usually within 5 minutes.',
  'help.whatsapp': 'WhatsApp',
  'help.call': 'Call',
  'help.faq': 'Questions people ask',
  'help.q1': 'Who books my trip?',
  'help.a1': 'A person at Mada, usually Faisal. Every booking is checked and confirmed by hand, and you see the name of whoever confirmed it.',
  'help.q2': 'Can I change or cancel a booking?',
  'help.a2': 'Yes. Open the trip and tap Change. We show the airline’s fee before anything happens, and nothing changes until you say so.',
  'help.q3': 'When does a refund reach my card?',
  'help.a3': 'We send it the day the airline or hotel releases it. Banks then take 5 to 14 days to show it. You can follow each step in Trips.',
  'help.q4': 'Is my passport safe in the app?',
  'help.a4': 'It’s encrypted and locked with Face ID. We open it only to book for you, and we never sell it.',
  'help.q5': 'Can I book for my family and our helper?',
  'help.a5': 'Yes. Add them to your household once. Their passports fill in every booking, and for a helper we check the iqama and exit and re-entry visa first.',
  'help.q6': 'What happens if my flight is delayed or cancelled?',
  'help.a6': 'We watch every flight. If it changes, we hold seats on other flights and tell you the options. Faisal and the team are there day and night.',
  'help.legal': 'Legal',
  'help.terms': 'Terms of use',
  'help.privacy': 'Privacy policy',
  'help.version': 'Mada Trips {version}',
  'help.callTitle': 'Call Mada',
  'help.callBody': '{phone}. Day and night, in Arabic or English. Have your booking code ready if it’s about a trip.',
  'help.callNow': 'Call now',
  'help.opening': 'Opening WhatsApp: {phone}',
  'legal.updated': 'Updated 1 Oct 2026',
  'legal.terms.1h': 'Who we are',
  'legal.terms.1b': 'Mada Trips is run by Mada Travel and Tourism, a licensed travel agency in Riyadh. People at Mada book every trip.',
  'legal.terms.2h': 'Bookings',
  'legal.terms.2b': 'When you confirm, we book with the airline, hotel or supplier in your name. Their fare rules apply, and we show them before you pay.',
  'legal.terms.3h': 'Payment',
  'legal.terms.3b': 'Prices are in SAR and include every fee we know of. If a price changes before we book, we ask you first.',
  'legal.terms.4h': 'Changes and refunds',
  'legal.terms.4b': 'We pass on the supplier’s fees and add none of our own for changes you make in the app.',
  'legal.terms.5h': 'Your account',
  'legal.terms.5b': 'Keep your sign-in to yourself. You’re responsible for bookings made from your account.',
  'legal.privacy.1h': 'What we collect',
  'legal.privacy.1b': 'Your details, your household’s passports, your trips and payments, and, if you allow it, location on travel days.',
  'legal.privacy.2h': 'Why',
  'legal.privacy.2b': 'To book and look after your trips. Nothing else.',
  'legal.privacy.3h': 'Who sees it',
  'legal.privacy.3b': 'People at Mada who work on your trips, and the airlines, hotels and embassies we book with. We never sell it.',
  'legal.privacy.4h': 'Where it’s kept',
  'legal.privacy.4b': 'Passports are encrypted. Everything is stored in Saudi Arabia, under the PDPL, Saudi Arabia’s privacy law.',
  'legal.privacy.5h': 'Your rights',
  'legal.privacy.5b': 'Download it, correct it or delete it, any time, from Privacy in the app.',

  // ───────────── support with Faisal ─────────────
  'support.presenceLine': '{presence} · {replies}',
  'support.pronoun.she': 'She',
  'support.pronoun.he': 'He',
  'support.about': 'About: {about}',
  'support.aboutAccount': 'Your account',
  'support.aboutTrip': '{city} trip',
  'support.disclosure': 'Instant answers from Mada. Faisal and the team confirm anything you book.',
  'support.hiNamed': 'Hi {name}. I have your {what} open. What can I do?',
  'support.hi': 'Hi. I have your {what} open. What can I do?',
  'support.account': 'account',
  'support.topics': 'Topics',
  'support.topic.change': 'Change my booking',
  'support.topic.refund': 'A refund',
  'support.topic.bag': 'A missing bag',
  'support.topic.docs': 'Documents or a visa',
  'support.topic.airport': 'Help at the airport',
  'support.topic.other': 'Something else',
  'support.placeholder': 'Write to Mada',
  'support.send': 'Send',
  'support.attach': 'Send a photo',
  'support.call': 'Call Mada on {phone}',
  'support.whatsapp': 'WhatsApp Mada',
  'support.callDesk': 'Call the desk now',
  'support.read': 'read',
  'support.queued': 'sends when you’re online',
  'support.sending': 'sending',
  'support.typingLabel': 'Typing',
  'support.photoAlt': 'Photo you sent',
  'support.pdf': 'PDF · {name}',
  'support.tooBig': 'That file is over 10 MB. Send a smaller photo, or a screenshot of the page.',
  'support.offline.title': "You're offline.",
  'support.offline.queued.one': 'Your message sends the moment you’re back.',
  'support.offline.queued.other': 'Your {count} messages send the moment you’re back.',
  'support.offline.none': 'Messages you write now send the moment you’re back.',
  'support.offline.desk': 'Need us now? The desk answers any hour.',
  'support.offline.call': 'Call the desk',
  'support.offline.sms': 'Send an SMS',
  'support.offline.smsBody': 'Hi Faisal, I need help with my trip.',
  'support.rate.title': 'Did that sort it?',
  'support.rate.yes': 'Yes, thanks',
  'support.rate.no': 'Not yet',
  'support.rate.yesSaid': 'Yes, thanks.',
  'support.rate.noSaid': 'Not yet.',
  'support.bag.ref': 'Bag tag or baggage desk reference',
  'support.bag.refHint': 'SV 482913 or RUHSV12345',
  'support.bag.what': 'What does it look like?',
  'support.bag.black': 'Black suitcase',
  'support.bag.coloured': 'Coloured suitcase',
  'support.bag.box': 'A bag or box',
  'support.bag.to': 'Deliver it to',
  'support.bag.hotel': 'Our hotel',
  'support.bag.home': 'Home',
  'support.bag.none': 'I don’t have a reference yet',
  'support.bag.summary': '{ref} · {kind} · deliver to {to}',
  'support.refund.sent': 'Sent',
  'support.refund.withFaisal': 'With Faisal',
  'support.refund.onWay': 'On its way',
  'support.refund.to': 'To {card}.',
  'support.refund.stage.requested': 'Asked the airline. They usually answer within 3 days',
  'support.refund.stage.approved': 'Approved. It’s being sent to your card',
  'support.refund.stage.sent': 'Sent. Banks take up to 5 working days to show it',
  'support.refund.stage.rejected': 'Faisal is checking it with the airline',
  'support.reply.urgent': 'Call the desk now: {phone}. Someone answers any hour, usually within a minute. If anyone is hurt, call 997 for an ambulance in Saudi Arabia, or 112 abroad.',
  'support.reply.airport': 'Calling is quickest at the airport. Tap call and you reach the desk straight away, any hour.',
  'support.reply.bag': 'Sorry about the bag. Let’s find it. Send us the bag tag number from the sticker on your boarding pass, or the reference the baggage desk gave you.',
  'support.reply.missedTrip': 'We’re on it. We’re holding seats on two flights today. Which one?',
  'support.reply.missed': 'We’re on it. Send us the flight number or a photo of the booking, and we’ll rebook you on the next flight with seats.',
  'support.reply.refundTwice': 'We can see one payment. A second charge is usually a hold from the bank that drops off within 3 days. Send us a screenshot of the statement and we’ll check it today.',
  'support.reply.refundTwiceRef': 'We can see one payment for booking {ref}. A second charge is usually a hold from the bank that drops off within 3 days. Send us a screenshot of the statement and we’ll check it today.',
  'support.reply.refundLatest': 'Here’s where your refund is.',
  'support.reply.refundNone': 'No refunds in progress. Pick what you want refunded and you’ll see exactly what comes back before anything happens.',
  'support.reply.refundStart': 'Start a refund',
  'support.reply.refundAnother': 'Start another refund',
  'support.reply.seatNoTrip': 'Once you’ve booked, we’ll seat you together. There’s nothing to change yet.',
  'support.reply.seat': 'We’ve asked {airline} for {seat}{next}, on both flights. We’ll confirm here, and the seat goes on the boarding pass in your Wallet.',
  'support.reply.seatWindow': 'a window seat',
  'support.reply.seatAisle': 'an aisle seat',
  'support.reply.seatNext': ', next to {name}',
  'support.reply.change': 'What would you like to change: the flight, the hotel, or who’s travelling? You can also do it yourself and we’ll confirm it.',
  'support.reply.changeFlight': 'Change the flight',
  'support.reply.docs': 'Send us a photo of the document, or tell us which country. We’ll check what each of you needs.',
  'support.reply.other': 'Go ahead. We’re here.',
  'support.reply.photo': 'Got it. We’ll look at it and reply here within 5 minutes.',
  'support.reply.free': 'We’ll look and reply here within 5 minutes.',
  'support.reply.picked': 'We’re holding {flight} for you now. Faisal confirms it with the airline, and the new boarding passes land in your Wallet.',
  'support.reply.pickedRefund': 'Your seats are released and the full fare comes back. Pick what to refund and you’ll see the amount first.',
  'support.reply.bagFiled': 'Thanks. We’ll file it with the airline under {ref} now. Here’s what happens next.',
  'support.reply.bagStep1': 'They trace it now. Most bags turn up within 24 hours.',
  'support.reply.bagStep2Hotel': 'When it’s found, it’s delivered to your hotel at no cost. We’ll tell you here.',
  'support.reply.bagStep2Home': 'When it’s found, it’s delivered to your home at no cost. We’ll tell you here.',
  'support.reply.bagStep3': 'Until then, buy what you need. The airline pays back reasonable costs: keep the receipts and send photos here.',
  'support.reply.bagStep4': 'If it isn’t found in 21 days, we’ll claim its full value for you.',
  'support.reply.bagNone': 'That’s fine. Before you leave the airport, go to the baggage desk in arrivals and report it. They’ll give you a reference on a form. Send us a photo of it and we’ll take it from there.',
  'support.reply.bagNoneSaid': 'I don’t have a reference yet.',
  'support.reply.leaveLater': 'A refund instead',
  'notify.supportReply.title': 'Mada',
  'notify.supportReply.body': '{name}: {text}',

  // ───────────── inbox ─────────────
  'inbox.title': 'Updates',
  'inbox.markRead': 'Mark all read',
  'inbox.filter': 'Filter updates',
  'inbox.all': 'All',
  'inbox.trips': 'Trips',
  'inbox.money': 'Money',
  'inbox.circles': 'Circles',
  'inbox.empty.title': 'All quiet.',
  'inbox.empty.money': 'Payments, refunds and Mada credit land here the moment they move.',
  'inbox.empty.circles': 'Votes, splits and new people in your circles land here.',
  'inbox.empty.watching': 'We’re watching your flights. The moment a gate, a time or a reply changes, it lands here.',
  'inbox.empty.body': 'Gate changes, replies from Faisal, refunds and circle news land here, so nothing gets lost.',
  'inbox.empty.plan': 'Plan a trip',
  'inbox.justNow': 'Just now',
  'inbox.minAgo': '{n} min ago',
  'inbox.hAgo': '{n} h ago',
  'inbox.unread': 'Unread',

  // ───────────── server problems in this area ─────────────
  'error.documentType': 'That file type won’t work. Use a photo or a PDF.',
  'error.documentSize': 'That file is over 10 MB. Try a photo of the page instead.',
  'error.lastMethod': 'This is your only way in. Add another method before you remove this one.',
  'error.emailNeeded': 'Add an email in Your details first, so we have somewhere to send it.',
  'error.emailCodeWrong.one': "That code doesn't match. 1 try left.",
  'error.emailCodeWrong.other': "That code doesn't match. {count} tries left.",
  'error.defaultCard': 'That’s your default card. Pick what to use from now on, then we’ll remove it.',
  'error.creditShort': 'There isn’t that much Mada credit. Your balance is {amount}.',
  'error.storageMissing': 'Documents can’t be saved on this server yet. Faisal can take them by hand.',
} as const;
