/**
 * Arabic: Booking: Ask, search, requests, plans, the order sheet, payment and the wait (booking.ts).
 * A first draft in warm, plain Modern Standard Arabic for the native Saudi writer to transcreate (COPY.md §7.4).
 * Same keys as the English; Arabic's extra plural forms are `.two`, `.few` and `.zero`. The brand is مادا.
 * Generated once from the translation sheet; edit here from now on.
 */
import type { bookingCopy } from '../booking';
import type { ArSection } from './types';

export const arBooking: ArSection<typeof bookingCopy> = {
  'ask.close': 'أغلق',
  'ask.title': 'إلى أين؟',
  'ask.intro': 'قلها كما تحب. مكان، تواريخ، ومن معك. ولن نسأل إلا عما نحتاجه.',
  'ask.composer': 'إلى أين؟ قلها كما تحب',
  'ask.composerMore': 'شيء آخر؟',
  'ask.a11y.input': 'اسأل مادا',
  'ask.a11y.send': 'أرسل',
  'ask.a11y.talk': 'اضغط مطولًا لتتحدث',
  'ask.voice': 'الصوت يصل في التطبيق. اكتب هنا حاليًا.',
  'ask.somethingElse': 'اسأل عن شيء آخر',
  'ask.idea.familyEid': 'إسطنبول في العيد، كلنا الـ {count}',
  'ask.idea.sameAgain': 'مثل العيد الماضي',
  'ask.idea.hotel': 'فندق في إسطنبول',
  'ask.idea.visaFor': 'تأشيرة شنغن لـ {name}',
  'ask.idea.visa': 'تأشيرة شنغن',
  'ask.idea.umrah': 'عمرة في رمضان',
  'ask.idea.flights': 'رحلات إلى إسطنبول',
  'ask.idea.dubai': 'رحلات إلى دبي الويكند الجاي',
  'ask.idea.alula': 'ويكند في العُلا',
  'ask.idea.tripHotel': 'أضف فندقًا في {city}',
  'ask.idea.tripDinner': 'عشاء أول ليلة',
  'ask.idea.tripCar': 'سيارة لرحلة يوم',
  'ask.idea.tripEsim': 'شريحة eSIM للرحلة',
  'ask.prompt.flight': 'طيران',
  'ask.prompt.stay': 'مكان للإقامة',
  'ask.prompt.visa': 'تأشيرة',
  'ask.prompt.umrah': 'رحلة عمرة',
  'ask.prompt.car': 'سيارة',
  'ask.prompt.food': 'طاولة في مكان مميز',
  'ask.prompt.todo': 'أنشطة',
  'ask.prompt.esim': 'شريحة eSIM للرحلة',
  'ask.offline.title': 'أنت غير متصل.',
  'ask.offline.body': 'البحث يحتاج إلى اتصال. كل ما يخص رحلاتك موجود على هذا الجوال، وطلباتك إلى مادا تُرسل حين يعود الاتصال.',
  'ask.signin.title': 'سجّل دخولك لتحجز',
  'ask.signin.body': 'الحجز يحتاج حسابًا، لتؤكد مادا ببياناتك وتصل تذاكرك إلى محفظتك.',
  'ask.signin.go': 'سجّل الدخول',
  'ask.resume': 'نحجز {place} لك. شاهد أين وصلنا.',
  'ask.demo.title': 'اجعلها تتعثر',
  'ask.demo.body': 'مفاتيح تجربة للمزوّدين الوهميين. لا شيء هنا حقيقي.',
  'ask.demo.open': 'تجربة',
  'ask.q.where': 'إلى أين؟',
  'ask.q.whichCity': 'أي مدينة؟',
  'ask.q.cityHint': 'تبليسي، باكو، أبها…',
  'ask.q.go': 'انطلق',
  'ask.q.elsewhere': 'مكان آخر',
  'ask.q.when': 'متى؟',
  'ask.q.whenIn': 'متى في {month}؟',
  'ask.q.pickDates': 'أختار التواريخ بنفسي',
  'ask.q.return': 'المغادرة {day}. والعودة متى؟',
  'ask.q.after3': 'بعد 3 ليالٍ · {day}',
  'ask.q.afterWeek': 'بعد أسبوع · {day}',
  'ask.q.oneWay': 'ذهاب فقط',
  'ask.q.who': 'من معك؟',
  'ask.q.whoSaid': 'قلت {count}. أضف البقية لتكون أسماؤهم لدينا كما في جوازاتهم.',
  'ask.q.just': '{name} فقط',
  'ask.q.these': 'هؤلاء الـ {count}',
  'ask.q.addSomeone': 'أضف شخصًا',
  'ask.q.helper': '{name} (عاملة منزلية)',
  'person.add.body': 'الأسماء كما في الجواز تمامًا. وتقدر تمسحه لاحقًا من المحفظة.',
  'person.add.given': 'الاسم الأول والأسماء الأخرى',
  'person.add.surname': 'اسم العائلة',
  'person.add.helperNote': 'نطلب رقم الإقامة وتأشيرة الخروج والعودة قبل أي سفر للخارج.',
  'person.add.button': 'أضف {name}',
  'person.add.them': 'الشخص',
  'person.added': 'أُضيف {name}. امسح جوازه من المحفظة حين تتمكن.',
  'person.rel.family': 'العائلة',
  'person.rel.friend': 'صديق',
  'person.rel.helper': 'عاملة منزلية',
  'person.rel.colleague': 'زميل',
  'search.working.checking': 'نبحث في الرحلات إلى {city}',
  'search.working.holding': 'نحجز المقاعد بهذا السعر',
  'search.working.matching': 'ننسّق المقاعد والوجبات لـ {count}',
  'search.working.stays': 'نبحث في 120 مكانًا قرب خططك',
  'search.working.together': 'نُبقي الغرف متجاورة',
  'search.working.quiet': 'نختار الغرف الهادئة',
  'search.checked': 'راجعنا {count} رحلة · نحجز مقاعد لـ {people}',
  'search.ways.one': 'طريقة واحدة للوصول.',
  'search.ways.two': 'طريقتان للوصول.',
  'search.ways.three': 'ثلاث طرق للوصول.',
  'search.summary': '{from} → {to} · {dates}',
  'search.summaryOneWay': '{date}، ذهاب فقط',
  'search.people.one': 'بالغ واحد',
  'search.people.two': 'شخصان',
  'search.people.few': '{count} أشخاص',
  'search.people.other': '{count} شخصًا',
  'search.lap': '+ {count} في الحضن',
  'search.flex': '±2 يوم',
  'search.edit': 'عدّل',
  'search.a11y.edit': 'عدّل البحث',
  'search.sort.best': 'الأفضل',
  'search.sort.cheapest': 'الأرخص',
  'search.sort.fastest': 'الأسرع',
  'search.sort.earliest': 'الأبكر',
  'search.label.best': 'الأنسب لك',
  'search.label.lowest': 'أقل سعر',
  'search.label.earliest': 'الأبكر',
  'search.label.fastest': 'الأسرع',
  'search.label.bags': 'حقيبتان لكل مسافر',
  'search.label.quiet': 'الأهدأ',
  'search.label.water': 'على الماء',
  'search.direct': '{duration} · مباشرة',
  'search.oneStop': '{duration} · توقف واحد، IST',
  'search.tapAgain': 'اضغط مرة أخرى لترى الحقائب وقواعد التغيير',
  'search.rule.bags': 'الحقائب',
  'search.rule.change': 'التغيير',
  'search.rule.cancel': 'الإلغاء',
  'search.rule.return': 'العودة',
  'search.rule.lap': 'رضيع في الحضن',
  'search.rule.lapValue': '{price} للواحد · سرير أطفال عند الطلب',
  'search.travellers': 'المسافرون',
  'search.staying': 'من سيقيم',
  'search.blocking.one': 'شيء واحد يحتاج حلًّا قبل الحجز. تجده تحت الرحلات.',
  'search.blocking.two': 'شيئان يحتاجان حلًّا قبل الحجز. تجدهما تحت الرحلات.',
  'search.blocking.few': '{count} أشياء تحتاج حلًّا قبل الحجز. تجدها تحت الرحلات.',
  'search.blocking.other': '{count} شيئًا يحتاج حلًّا قبل الحجز. تجدها تحت الرحلات.',
  'search.review': 'راجع · {price}',
  'search.sortOut': 'حلّ مسألة {thing} لـ {name} أولًا',
  'search.bundle.family': 'نضيف غرفًا متصلة قرب برج غلطة واستقبالًا من المطار؟',
  'search.bundle.two': 'نضيف غرفة لشخصين قرب برج غلطة واستقبالًا من المطار؟',
  'search.bundle.one': 'نضيف غرفة قرب برج غلطة واستقبالًا من المطار؟',
  'search.bundle.helper': 'نضيف غرفًا قرب برج غلطة واستقبالًا من المطار؟',
  'search.bundle.nights.one': 'ليلة واحدة · {price}',
  'search.bundle.nights.two': 'ليلتان · {price}',
  'search.bundle.nights.few': '{count} ليالٍ · {price}',
  'search.bundle.nights.other': '{count} ليلة · {price}',
  'search.bundle.add': 'أضف',
  'search.bundle.added': 'أُضيف',
  'search.cabinNoFirst': 'الدرجة الأولى غير متاحة على هذه الخطوط. درجة الأعمال هي الأفضل.',
  'search.rooms.connecting': 'غرفتان متصلتان',
  'search.rooms.forTwo': 'غرفة لشخصين',
  'search.rooms.one': 'غرفة واحدة',
  'search.none.title': 'لا رحلات مباشرة في هذه التواريخ.',
  'search.none.body': 'نفدت المقاعد إلى {city} يوم {day}. تتوفر أماكن قبله أو بعده بيوم، أو مع توقف قصير.',
  'search.none.flex': 'جرّب قبلها أو بعدها بيوم',
  'search.none.stop': 'اسمح بتوقف واحد',
  'search.down.title': 'نظام {airline} لا يستجيب.',
  'search.down.body': 'شركات الطيران الأخرى تعمل. أو تبحث مادا في {airline} يدويًا وترجع لك خلال 20 دقيقة.',
  'search.down.others': 'اعرض البقية',
  'search.down.byHand': 'اسأل مادا',
  'search.down.note': 'نبحث في {airline} يدويًا ونرسل لك الخيارات هنا خلال 20 دقيقة.',
  'search.stays.title': 'ثلاثة أماكن ستعجبك.',
  'search.stays.sub': '{dates} · {nights} ليالٍ · {rooms}',
  'search.stays.none.title': 'لا غرف متاحة في هذه التواريخ.',
  'search.stays.none.body': 'كل ما حول غلطة محجوز لـ {rooms}. تعرف مادا أماكن لا تظهر على الإنترنت، وتقدر تبحث يدويًا.',
  'search.stays.byHand': 'اطلب من مادا إيجاد غرف',
  'search.byHand.title': 'نبحث لك في {city}.',
  'search.byHand.stayTitle': 'نبحث لك عن غرف في {city}.',
  'search.byHand.queued': 'حُفظ. نبدأ في {city} حين يعود اتصالك.',
  'search.byHand.body': 'الخيارات هنا خلال 20 دقيقة. لا داعي لأن تبقى في هذه الشاشة.',
  'search.seeInTrips': 'اعرضها في «الرحلات»',
  'cal.title': 'بحثك',
  'cal.from': 'المغادرة من',
  'cal.type': 'نوع الرحلة',
  'cal.return': 'ذهاب وعودة',
  'cal.oneway': 'ذهاب فقط',
  'cal.pickBoth': 'اختر يوم المغادرة، ثم يوم العودة',
  'cal.pickOut': 'اختر يوم المغادرة',
  'cal.leaving': 'المغادرة {day}',
  'cal.pickReturn': 'المغادرة {day} · اختر الآن يوم العودة',
  'cal.range.one': '{from} → {to} · ليلة واحدة',
  'cal.range.two': '{from} → {to} · ليلتان',
  'cal.range.few': '{from} → {to} · {count} ليالٍ',
  'cal.range.other': '{from} → {to} · {count} ليلة',
  'cal.months': 'الأشهر',
  'cal.prev': 'الشهر السابق',
  'cal.next': 'الشهر التالي',
  'cal.flexible': 'مرن ±2 يوم',
  'cal.cabin': 'الدرجة',
  'cal.cabin.economy': 'السياحية',
  'cal.cabin.premium': 'السياحية المميزة',
  'cal.cabin.business': 'الأعمال',
  'cal.cabin.first': 'الأولى',
  'cal.babies': 'رضّع في الحضن',
  'cal.babiesNote': 'دون السنتين في يوم العودة. واحد لكل بالغ.',
  'cal.fewer': 'رضيع أقل',
  'cal.more': 'رضيع إضافي',
  'cal.search': 'ابحث',
  'cal.pickDate': 'اختر تاريخًا',
  'cal.pickReturnDate': 'اختر تاريخ العودة',
  'entry.checked': 'راجعنا الشروط اليوم · {what}',
  'entry.domestic': 'رحلة داخل السعودية',
  'entry.for': '{country}، لجوازات {nationalities}',
  'entry.forYour': '{country}، لجوازاتكم',
  'entry.passport.title': 'لا يمكن لـ {name} السفر بهذا الجواز.',
  'entry.passport.days': 'جواز {name} ينتهي في {date}. تطلب {country} صلاحية {days} يومًا بعد الوصول، فيجب أن يكون ساريًا حتى {until}.',
  'entry.passport.trip': 'جواز {name} ينتهي في {date}، قبل عودتكم. يجب أن يكون ساريًا طوال الرحلة.',
  'entry.visa.title': '{name} يحتاج تأشيرة لـ {country}.',
  'entry.visa.has': 'لدى {name} {need} أصلًا.',
  'entry.visa.asked': 'تستخرج مادا {need} لـ {name}. ونتحقق منها قبل سفرك.',
  'entry.manual': 'لا نعرف دولة جواز {name} بعد. تراجع مادا شروط {country} يدويًا قبل الحجز.',
  'entry.iqama.title': 'إقامة {name} تنتهي أثناء الرحلة.',
  'entry.iqama.text': 'تنتهي في {date}، قبل عودتكم في {back}. يجب أن تكون سارية طوال الرحلة.',
  'entry.reentry.title': '{name} يحتاج تأشيرة خروج وعودة.',
  'entry.reentry.text': 'كل مقيم يحتاجها ليغادر السعودية ويعود. يصدرها الكفيل من أبشر، عادةً في اليوم نفسه.',
  'entry.reentry.has': 'لدى {name} تأشيرة خروج وعودة.',
  'entry.reentry.asked': 'ترتّب مادا تأشيرة الخروج والعودة لـ {name}. ونتحقق منها قبل سفرك.',
  'entry.eta.text': 'كل جواز سعودي يحتاج تصريح ETA البريطاني. يُطلب إلكترونيًا، بـ 16 جنيهًا، ويجهز عادةً خلال 3 أيام.',
  'entry.eta.asked': 'تتقدّم مادا بطلبات ETA للجميع. ونتحقق منها قبل سفرك.',
  'entry.eta.ask': 'اطلب من مادا التقديم',
  'entry.visa.ask': 'اطلب من مادا استخراجها',
  'entry.reentry.ask': 'اطلب من مادا ترتيبها',
  'entry.reentry.hasOne': 'لدى {name} واحدة أصلًا',
  'entry.iqama.renewed': 'جُدّدت',
  'entry.passport.renew': 'جدّده أولًا',
  'entry.passport.onIt': 'مادا تتابعه',
  'entry.without': 'احجز بدون {name}',
  'entry.thing.passport': 'الجواز',
  'entry.thing.visa': 'التأشيرة',
  'entry.thing.iqama': 'الإقامة',
  'entry.thing.reentry': 'تأشيرة الخروج والعودة',
  'plan.working.open': 'نبحث عما هو مفتوح ذلك الويكند',
  'plan.working.prayer': 'نرتّبها حول أوقات الصلاة',
  'plan.working.prayerKids': 'نرتّبها حول أوقات الصلاة والأطفال',
  'plan.working.tables': 'نحجز الطاولات ومواعيد الجولات',
  'plan.ready': 'خطّطناها لك. غيّر ما تشاء.',
  'plan.stops': '{days} أيام · {count} محطات',
  'plan.see': 'اعرض الخطة',
  'plan.by': 'من تخطيط مادا · {days} أيام',
  'plan.yours.title': 'اجعلها على ذوقك',
  'plan.yours.body': 'غيّر يومًا، أو بدّل محطة، أو أضف ما تحب. اطلب، ونعيد ترتيب الخطة.',
  'plan.change': 'غيّر شيئًا',
  'plan.changePrefill': 'غيّر خطة {title}',
  'plan.book': 'احجز الكل · {price}',
  'plan.save': 'احفظها لاحقًا',
  'plan.saved': 'محفوظة. اضغط لإزالتها',
  'plan.savedToast': 'حُفظت. تجدها في المجموعات ← مجموعاتك ← المحفوظات.',
  'plan.removedToast': 'أُزيلت من محفوظاتك.',
  'esim.title': 'شريحة eSIM لتركيا، جاهزة عند الهبوط.',
  'esim.plan': '10 جيجابايت لـ 7 أيام',
  'esim.each': '{price} للواحد',
  'esim.body': 'تُثبّت على كل جوال قبل السفر. وتعمل حين تهبط. ويبقى رقمك السعودي يعمل للمكالمات.',
  'request.q.whichVisa': 'أي تأشيرة؟',
  'request.q.forWho': 'لمن؟',
  'request.q.whenTravel': 'متى تسافر؟',
  'request.q.when': 'متى؟',
  'request.q.whoGoing': 'من مسافر؟',
  'request.q.needs': 'أي شيء نرتّبه لكل شخص؟',
  'request.q.makkahStay': 'أين تقيم في مكة؟',
  'request.q.where': 'أين؟',
  'request.q.size': 'أي حجم؟',
  'request.q.howLong': 'لكم من الوقت؟',
  'request.q.matters': 'ما الذي يهمك؟',
  'request.q.pick': 'اختر ما يعجبك',
  'request.done': 'تم',
  'request.nothingNeeded': 'لا شيء',
  'request.helperVisa': 'لـ {names} نحتاج أيضًا الإقامة وتأشيرة خروج وعودة.',
  'request.mentioned': 'ذكرت {needs}. اضغطها للشخص المعني.',
  'request.oxygen': 'نرتّب موافقة شركة الطيران. نحتاج نموذجًا من الطبيب قبل السفر بـ 7 أيام.',
  'request.umrahNusuk': 'كل مسافر يحتاج تصريحه في نسك. نذكّرك بإصداره حين تتحدد التواريخ.',
  'request.note.label': 'شيء آخر نحتاج نعرفه؟',
  'request.note.hint': 'أوقات تناسبك، فندق تحبه، صحة أحدكم',
  'request.willVisa': 'تبحث مادا عن أقرب موعد، وتجهّز النماذج، وترد هنا.',
  'request.willPrice': 'تحسب مادا السعر لكل شخص وترد هنا.',
  'request.send': 'أرسل إلى مادا',
  'request.sent': 'وصل إلى مادا.',
  'request.queued': 'حُفظ. يُرسل حين يعود اتصالك.',
  'request.sentBody': 'عادةً خلال ساعتين، في أي وقت.',
  'request.replied': 'هذا سعر كل واحد منكم.',
  'request.pay': 'ادفع {price}',
  'request.total': 'المجموع',
  'request.a11y.breakdown': 'السعر لكل شخص',
  'request.a11y.thread': 'الردود',
  'request.reply': 'رد على مادا',
  'request.a11y.send': 'أرسل الرد',
  'request.switch': 'بدّلها',
  'request.switchYes': 'نعم، بدّلها.',
  'request.sendsOnline': 'يُرسل حين يعود اتصالك',
  'request.suggest.closer': 'نقدر نسكن أقرب إلى الحرم؟',
  'request.suggest.later': 'نقدر نغادر بعد يوم؟',
  'request.suggest.laterFlight': 'فيه رحلة لاحقة؟',
  'request.suggest.less': 'نقدر ندفع أقل؟',
  'request.suggest.dates': 'نقدر نغيّر التواريخ؟',
  'request.status.queued': 'محفوظ، يُرسل حين تتصل',
  'request.status.sent': 'أُرسل',
  'request.status.reviewing': 'قيد المراجعة',
  'request.status.quoted': 'السعر جاهز',
  'request.status.paid': 'مدفوع',
  'request.status.done': 'تم',
  'request.status.cancelled': 'ملغى',
  'request.title.eta': 'تصريح ETA البريطاني للجميع',
  'request.title.evisa': '{need} لـ {name}',
  'request.title.reentry': 'تأشيرة خروج وعودة لـ {name}',
  'request.title.renewal': 'تجديد جواز {name}',
  'request.title.flightsTo': 'رحلات إلى {city} · {dates}',
  'request.title.staysIn': 'مكان للإقامة في {city}',
  'request.title.airlineByHand': 'رحلات {airline} إلى {city} · {dates}',
  'request.title.package': 'محجوز: {title}',
  'request.paidToast': 'دُفع. علينا الباقي.',
  'request.datesLater': 'تواريخ نتفق عليها',
  'pay.back': 'رجوع',
  'pay.held': 'محجوز {time}',
  'pay.holdEnded': 'انتهى الحجز المؤقت',
  'pay.edit': 'عدّل',
  'pay.justYou': 'أنت فقط',
  'pay.promo.open': 'لديك رمز خصم؟',
  'pay.promo.label': 'رمز الخصم',
  'pay.promo.apply': 'طبّق',
  'pay.promo.line': 'الرمز {code} · خصم 10%',
  'pay.promo.remove': 'أزل',
  'pay.promo.unknown': 'لا نعرف هذا الرمز. راجع كتابته.',
  'pay.promo.ended': 'انتهى هذا الرمز في {date}.',
  'pay.promo.demo': 'للتجربة: EID10',
  'pay.credit': 'رصيد مادا · {price}',
  'pay.credit.use': 'استخدم رصيد مادا',
  'pay.credit.first': 'لديك {price} رصيد مادا. يُستخدم أولًا.',
  'pay.passports.title': 'جوازات {names}',
  'pay.passports.body': 'احجز الآن وأضفها بعدها. تحجز مادا المقاعد وتصدر التذاكر حين تصل الجوازات، في أي وقت خلال 48 ساعة.',
  'pay.passports.scanYours': 'امسح جوازك الآن',
  'pay.passports.scan': 'امسح جواز {name} الآن',
  'pay.allIn': 'كل شيء مشمول. لا رسوم لاحقة.',
  'pay.change': 'غيّر',
  'pay.paidCredit': 'دُفع برصيد مادا',
  'pay.plan.a11y': 'طريقة الدفع',
  'pay.plan.full': 'ادفع كامل المبلغ',
  'pay.plan.tabby': 'تابي · 4 × {price}',
  'pay.plan.tamara': 'تمارا · 3 × {price}',
  'pay.slide': 'اسحب للحجز · {price}',
  'pay.slideCredit': 'اسحب للحجز · مدفوع بالرصيد',
  'pay.slideTabby': 'اسحب للحجز · 4 × {price}',
  'pay.slideTamara': 'اسحب للحجز · 3 × {price}',
  'pay.slidePay': 'اسحب للدفع · {price}',
  'pay.busy': 'نتحقق مع بنكك',
  'pay.agentNote': 'لا يُخصم المبلغ إلا بعد التأكيد.',
  'pay.nowNote': 'يُخصم الآن.',
  'pay.demoHold': '(تجربة: أنهِ الحجز المؤقت)',
  'pay.recheck': 'راجع السعر مرة أخرى',
  'pay.recheckSame': 'راجعنا السعر. نفس السعر، محجوز لمدة 20 دقيقة.',
  'pay.recheckMoved': 'راجعنا السعر. تغيّر بمقدار {price}، ومحجوز لمدة 20 دقيقة.',
  'pay.missing': 'هذا السعر لم يعد متاحًا. ارجع واختر من جديد.',
  'pay.line.flight.one': 'مسافر واحد · {airline}، {how}',
  'pay.line.flight.two': 'مسافران · {airline}، {how}',
  'pay.line.flight.few': '{count} مسافرين · {airline}، {how}',
  'pay.line.flight.other': '{count} مسافرًا · {airline}، {how}',
  'pay.line.direct': 'مباشرة',
  'pay.line.oneStop': 'توقف واحد',
  'pay.line.oneWay': 'ذهاب فقط',
  'pay.line.infants.one': 'رضيع واحد في الحضن',
  'pay.line.infants.two': 'رضيعان في الحضن',
  'pay.line.infants.few': '{count} رضّع في الحضن',
  'pay.line.infants.other': '{count} رضيعًا في الحضن',
  'pay.line.stay': '{rooms} قرب برج غلطة · {count} ليالٍ',
  'pay.line.connecting': 'غرف متصلة',
  'pay.line.aRoom': 'غرفة',
  'pay.line.pickupBoth': 'استقبال من المطار وتوصيل إليه',
  'pay.line.pickupOut': 'استقبال من المطار عند الوصول',
  'pay.line.hotel': '{rooms} · {dates} · {count} ليالٍ',
  'pay.line.planFlights': 'طيران لـ {count} · الرياض ⇄ {city}',
  'pay.line.planStay.one': '{rooms} · ليلة واحدة',
  'pay.line.planStay.two': '{rooms} · ليلتان',
  'pay.line.planStay.few': '{rooms} · {count} ليالٍ',
  'pay.line.planStay.other': '{rooms} · {count} ليلة',
  'pay.line.planTours': 'تذاكر وجولات وطاولات لـ {count}',
  'pay.line.quoteVisa': 'الموعد والنماذج وقائمة المتطلبات',
  'pay.line.quote': 'كما اتفقنا مع مادا',
  'pay.line.esim': '10 جيجابايت لـ 7 أيام × {count}',
  'pay.rule.refund': 'إن ألغيت، يُسترد سعر الطيران بعد خصم {fee}.',
  'pay.rule.noRefund': 'تذاكر الطيران غير مستردة، عدا ضرائب المطار. والتغيير بـ {fee}.',
  'pay.rule.rooms': 'الغرف والاستقبال إلغاؤها مجاني حتى {date}.',
  'pay.rule.stay': 'الإلغاء مجاني حتى {date}. بعدها، تُحتسب الليلة الأولى.',
  'pay.rule.package': 'الإلغاء مجاني حتى 7 أيام قبل الموعد. والجولات تُسترد كاملة حتى 48 ساعة قبلها.',
  'pay.rule.quote': 'يُسترد كاملًا إن لم نتمكن من تنفيذه.',
  'pay.rule.esim': 'قابلة للاسترداد حتى تثبيتها.',
  'pay.title.esim': 'شريحة eSIM لتركيا',
  'pay.title.share': 'حصتك · {circle}',
  'pay.line.share': '{what}، حصتك',
  'pay.rule.share': 'تُدفع للمجموعة بالبطاقة. تحتفظ مادا بسجل ليرى الجميع أنها سُدّدت.',
  'pay.shareToast': 'دُفعت. مجموعتك تقدر تراها.',
  'pay.shareGone': 'هذه الحصة مسدّدة.',
  'pay.people.title': 'من المسافرون؟',
  'pay.people.note': 'السعر يتحدّث مع كل تغيير.',
  'pay.people.done': 'تم · {price}',
  'pay.offline.title': 'أنت غير متصل.',
  'pay.offline.body': 'لم يُخصم شيء. سعرك محجوز ما دام العدّاد يعمل. حاول مرة أخرى حين يعود الاتصال.',
  'pay.declined.title': 'بنكك رفض العملية.',
  'pay.declined.body': 'لم يُخصم شيء. أحيانًا تمنع البنوك مدفوعات السفر الكبيرة. جرّب بطاقة أخرى، أو اتصل ببنكك وارجع. السعر يبقى محجوزًا.',
  'pay.declined.other': 'استخدم بطاقة أخرى',
  'pay.price.title': 'ارتفع السعر {price} أثناء المراجعة.',
  'pay.price.body': 'شركات الطيران تغيّر أسعارها من دقيقة لأخرى. لم يُخصم شيء.',
  'pay.price.accept': 'احجز بـ {price}',
  'pay.price.other': 'اعرض خيارات أخرى',
  'pay.blocked.title': 'شيء واحد يحتاج حلًّا أولًا.',
  'pay.cancelled': 'أُلغي. لم يُخصم شيء.',
  'pay.paidToast': 'دُفع. علينا الباقي.',
  'pay.esimToast': 'تم. تُثبَّت الشرائح قبل سفرك.',
  'pay.cards.title': 'ادفع بـ',
  'pay.cards.expires': 'تنتهي {date}',
  'pay.cards.add': 'أضف بطاقة',
  'pay.card.label': '{brand} المنتهية بـ {last}',
  'pay.card.number': 'رقم البطاقة',
  'pay.card.expiry': 'تاريخ الانتهاء',
  'pay.card.cvv': 'رمز الأمان',
  'pay.card.cvvHint': '3 أرقام',
  'pay.card.name': 'الاسم على البطاقة',
  'pay.card.save': 'احفظ البطاقة للمرة القادمة',
  'pay.card.note': 'بيانات البطاقة تذهب مباشرة إلى مزوّد الدفع. لا ترى مادا الرقم الكامل أبدًا.',
  'pay.card.test': 'بطاقة تجربة: 4242 4242 4242 4242.',
  'pay.card.use': 'استخدم هذه البطاقة',
  'pay.card.amex': 'لا نقبل American Express بعد. استخدم Visa أو Mastercard أو مدى.',
  'pay.card.luhn': 'الرقم لا يبدو صحيحًا. راجع كل رقم.',
  'pay.card.short': 'رقم البطاقة من 16 رقمًا.',
  'pay.card.brands': 'نقبل Visa وMastercard ومدى.',
  'pay.card.expired': 'انتهت صلاحية هذه البطاقة.',
  'pay.card.expiryShape': 'اكتبه بصيغة MM/YY، مثل 08/28.',
  'pay.card.provider': 'لم يقبل مزوّد الدفع البطاقة. راجع البيانات وحاول مرة أخرى.',
  'pay.3ds.title': 'بنكك يريد التأكد أنه أنت',
  'pay.3ds.body': 'أرسل رمزًا إلى الرقم المسجّل لديه. الرمز ليس من مادا.',
  'pay.3ds.label': 'الرمز من بنكك',
  'pay.3ds.wrong.one': 'الرمز غير مطابق. بقيت محاولة واحدة.',
  'pay.3ds.wrong.two': 'الرمز غير مطابق. بقيت محاولتان.',
  'pay.3ds.wrong.few': 'الرمز غير مطابق. بقيت {count} محاولات.',
  'pay.3ds.wrong.other': 'الرمز غير مطابق. بقيت {count} محاولة.',
  'pay.3ds.stopped': 'أوقف بنكك هذه العملية. لم يُخصم شيء. استخدم بطاقة أخرى أو اتصل ببنكك.',
  'pay.3ds.demo': 'رمز التجربة: 123456',
  'pay.apple.inWallet': '{card} · في المحفظة',
  'pay.apple.to': 'ادفع لمادا للرحلات مقابل {what}',
  'pay.apple.double': 'اضغط مرتين للدفع',
  'pay.apple.done': 'تم',
  'pay.apple.failed': 'لم يُتعرَّف على الوجه',
  'pay.apple.passcode': 'ادفع برمز المرور',
  'pay.apple.card': 'بطاقتك',
  'wait.title': 'مادا',
  'wait.live.line': '{agent} يتواصل الآن مع {with}',
  'wait.live.question': 'لدى {agent} سؤال لك',
  'wait.live.almost': 'اقتربنا',
  'wait.with.hotel': 'الفندق',
  'wait.with.guides': 'الفندق والمرشدين',
  'wait.with.airline': 'شركة الطيران',
  'wait.a11y.time': 'الوقت حتى الآن',
  'wait.close': 'أغلق',
  'wait.eyebrow': 'نحجز الآن',
  'wait.sub': '{day} · {time} من {from}',
  'wait.subOneWay': '{day} · {time} من {from} · ذهاب فقط',
  'wait.row.seats.one': 'نحجز مقعدك',
  'wait.row.seats.two': 'نحجز مقعدين متجاورين',
  'wait.row.seats.few': 'نحجز {count} مقاعد متجاورة',
  'wait.row.seats.other': 'نحجز {count} مقعدًا متجاورًا',
  'wait.row.seatsDone.one': 'محجوز: مقعدك',
  'wait.row.seatsDone.two': 'محجوز: مقعدان متجاوران',
  'wait.row.seatsDone.few': 'محجوز: {count} مقاعد متجاورة',
  'wait.row.seatsDone.other': 'محجوز: {count} مقعدًا متجاورًا',
  'wait.row.seatsDetail.one': 'المقعد {seats}',
  'wait.row.seatsDetail.other': 'المقاعد {seats}',
  'wait.row.price': 'نثبّت السعر',
  'wait.row.priceDone': 'ثبّتنا السعر',
  'wait.row.priceDetail': '{price}، ولن يرتفع الآن',
  'wait.row.issue.one': 'نصدر تذكرتك',
  'wait.row.issue.two': 'نصدر تذكرتين',
  'wait.row.issue.few': 'نصدر {count} تذاكر',
  'wait.row.issue.other': 'نصدر {count} تذكرة',
  'wait.row.issueDone.one': 'صدرت: تذكرتك',
  'wait.row.issueDone.two': 'صدرت: تذكرتان',
  'wait.row.issueDone.few': 'صدرت: {count} تذاكر',
  'wait.row.issueDone.other': 'صدرت: {count} تذكرة',
  'wait.row.issueDetail': '{flight} · التذاكر الإلكترونية في محفظتك',
  'wait.row.hotel': 'نسأل الفندق',
  'wait.row.hotelDone': 'الفندق وافق',
  'wait.row.hotelDetail': 'غرف متصلة، في الجهة الهادئة',
  'wait.row.rooms': 'نؤكد الغرف',
  'wait.row.roomsDone': 'تأكدت الغرف',
  'wait.row.roomsDetail': 'طلبنا تسجيل دخول مبكرًا',
  'wait.row.tours': 'نحجز الجولات والطاولات',
  'wait.row.toursDone': 'حُجزت الجولات والطاولات',
  'wait.row.toursDetail': 'المواعيد في خطتك',
  'wait.row.request': 'نرتّبها',
  'wait.row.requestDone': 'تم الترتيب',
  'wait.says': 'يقول {agent}',
  'wait.asks': 'يسأل {agent}',
  'wait.fare.text': 'باعت {airline} آخر المقاعد بذلك السعر قبل دقيقة. نفس الرحلة الآن أغلى بـ {each} للفرد، {total} للكل. لم يُخصم شيء.',
  'wait.fare.accept': 'احجز بـ {price}',
  'wait.fare.other': 'اعرض رحلات أخرى',
  'wait.fare.stop': 'أوقف',
  'wait.ticket.title': 'لم تصدر شركة الطيران التذاكر',
  'wait.ticket.text': 'انتهت مهلة نظام {airline}. لم يُخصم شيء وأُفرج عن التعليق على بطاقتك. ومقاعدك محجوزة لمدة ساعتين.',
  'wait.ticket.phone': 'تحاول مادا بالهاتف',
  'wait.ticket.cancel': 'ألغِ الحجز',
  'wait.ticket.note': 'بالهاتف يأخذ عادةً 15 دقيقة. تقدر تغلق التطبيق.',
  'wait.slow': 'يأخذ وقتًا أطول من المعتاد. نظام {airline} بطيء اليوم. تقدر تغلق التطبيق، ونخبرك لحظة الانتهاء.',
  'wait.question.names': 'في جواز {name} أكثر من اسم: «{given}». هل تُكتب التذكرة هكذا تمامًا؟',
  'wait.question.namesYours': 'في جوازك أكثر من اسم: «{given}». هل تُكتب التذكرة هكذا تمامًا؟',
  'wait.question.yes': 'نعم، كما في الجواز',
  'wait.question.call': 'اتصل بي',
  'wait.question.calling': '{agent} يتصل بك الآن',
  'wait.question.thanks': 'شكرًا. نكمل.',
  'wait.note': 'لا يُخصم شيء من بطاقتك قبل التأكيد. تقدر تغلق التطبيق، ونخبرك لحظة الانتهاء.',
  'wait.cancelled': 'أُلغي. لم يُخصم شيء.',
  'wait.background': 'نكمل الحجز. ونخبرك لحظة التأكيد.',
  'wait.confirmedToast': 'أكّدها {agent} من مادا. رمز الحجز {ref}.',
  'notify.replied.title': 'ردّت مادا',
  'notify.replied.body': '{agent}: {what} جاهز. اضغط لتراه.',
  'done.going': 'رحلتك إلى {city} مؤكدة.',
  'done.rooms': 'غرفكم محجوزة.',
  'done.paid': 'دُفع.',
  'done.tickets': 'التذاكر في محفظتك',
  'done.roomsBooked': 'الغرف محجوزة',
  'done.tabby': 'تابي: دُفعت الأولى من 4',
  'done.tamara': 'تمارا: دُفعت الأولى من 3',
  'done.paidWith': 'دُفع بـ {card}',
  'done.credit': '{price} من الرصيد',
  'done.invoice': 'فاتورة ضريبية في «الرحلات»',
  'done.watching': 'نراقب الرحلة',
  'done.alerts.title': 'تريد تغييرات البوابة على هذا الجوال؟',
  'done.alerts.body': 'فقط ما يحتاج منك فعلًا: تغيّر البوابة، التأخير، لحظة وصول سائقك. ولا عروض أبدًا.',
  'done.alerts.allow': 'اسمح بالتنبيهات',
  'done.alerts.on': 'التنبيهات مفعّلة لهذه الرحلة.',
  'done.seeTrip': 'اعرض الرحلة',
  'done.done': 'تم',
};
