/**
 * Arabic: Circles, Discover and people (en-circles.ts).
 * A first draft in warm, plain Modern Standard Arabic for the native Saudi writer to transcreate (COPY.md §7.4).
 * Same keys as the English; Arabic's extra plural forms are `.two`, `.few` and `.zero`. The brand is مادا.
 * Generated once from the translation sheet; edit here from now on.
 */
import type { enCircles } from '../en-circles';
import type { ArSection } from './types';

export const arCircles: ArSection<typeof enCircles> = {
  'circles.and': 'و',
  'circles.others': '{count} آخرين',
  'circles.you': 'أنت',
  'circles.youLower': 'أنت',
  'circles.someone': 'شخص ما',
  'circles.mada': 'مادا',
  'circles.back': 'المجموعات',
  'circles.cancel': 'إلغاء',
  'circles.save': 'احفظ',
  'circles.saved': 'محفوظ',
  'circles.remove': 'أزل',
  'circles.keep': 'أبقِ',
  'circles.keepIt': 'أبقِه',
  'circles.planIt': 'خطّط لها',
  'circles.bookTable': 'احجز طاولة',
  'circles.tableAsk': 'طاولة في {place}',
  'circles.people.one': 'شخص واحد',
  'circles.people.two': 'شخصان',
  'circles.people.few': '{count} أشخاص',
  'circles.people.other': '{count} شخصًا',
  'circles.requests.one': 'طلب واحد',
  'circles.requests.two': 'طلبان',
  'circles.requests.few': '{count} طلبات',
  'circles.requests.other': '{count} طلبًا',
  'circles.places.one': 'مكان واحد',
  'circles.places.two': 'مكانان',
  'circles.places.few': '{count} أماكن',
  'circles.places.other': '{count} مكانًا',
  'circles.ago.now': 'الآن',
  'circles.ago.min': 'قبل {n} د',
  'circles.ago.hours': 'قبل {n} س',
  'circles.ago.days.one': 'قبل يوم',
  'circles.ago.days.two': 'قبل يومين',
  'circles.ago.days.few': 'قبل {count} أيام',
  'circles.ago.days.other': 'قبل {count} يومًا',
  'circles.when.today': 'اليوم',
  'circles.when.yesterday': 'أمس',
  'circles.when.days': 'قبل {n} أيام',
  'circles.when.lastWeek': 'الأسبوع الماضي',
  'circles.when.weeks': 'قبل {n} أسابيع',
  'circles.when.lastMonth': 'الشهر الماضي',
  'circles.when.months': 'قبل {n} أشهر',
  'circles.a11y.views': 'عروض المجموعات',
  'circles.a11y.people': 'ناسك',
  'circles.a11y.peopleRequests': 'ناسك، {count} طلب',
  'circles.a11y.new': 'مجموعة جديدة',
  'circles.a11y.postTip': 'انشر نصيحة',
  'circles.new': 'مجموعة جديدة',
  'circles.unread': '{count} جديد',
  'circles.muted': 'مكتومة',
  'circles.friends.seeAll': 'عرض الكل',
  'circles.friends.requestsSeeAll': '{count} طلب · عرض الكل',
  'circles.friends.invited': 'مدعو',
  'circles.known.title': 'من أشخاص تعرفهم',
  'circles.known.newest': 'الأحدث أولًا',
  'circles.known.emptyTitle': 'لا شيء من الأصدقاء بعد.',
  'circles.known.emptyBody': 'حين ينشر صديق نصيحة، تظهر هنا أولًا، قبل غيرها.',
  'circles.known.emptyAction': 'شاهد الجديد في «اكتشف»',
  'circles.post.checking': 'قيد المراجعة',
  'circles.post.justNow': 'الآن',
  'circles.saved.title': 'المحفوظات',
  'circles.saved.emptyTitle': 'لا شيء محفوظ بعد.',
  'circles.saved.emptyBody': 'اضغط علامة الحفظ على أي نصيحة أو خطة في «اكتشف». تظهر هنا، مرتبة حسب المدينة.',
  'circles.saved.emptyAction': 'تجوّل في «اكتشف»',
  'circles.saved.planDays': 'خطة · {days} أيام',
  'circles.passport.title': 'جوازك',
  'circles.passport.none': 'لا أختام بعد',
  'circles.passport.countries.one': 'دولة واحدة',
  'circles.passport.countries.two': 'دولتان',
  'circles.passport.countries.few': '{count} دول',
  'circles.passport.countries.other': '{count} دولة',
  'circles.passport.withPlaces': '{countries} · {places} أماكن في السعودية',
  'circles.passport.a11y': 'صفحة جواز فارغة',
  'circles.passport.head': 'التأشيرات · الأختام',
  'circles.passport.next': 'التالي',
  'circles.passport.firstTrip': 'ختمك الأول يصل حين تعود من {city}.',
  'circles.passport.every': 'كل عودة من رحلة تضيف ختمًا.',
  'circles.passport.fills': 'يمتلئ وحده. لا شيء عليك.',
  'circles.passport.book': 'احجز رحلتك الأولى وتبدأ هذه الصفحة بالامتلاء.',
  'circles.passport.plan': 'خطّط لرحلة',
  'circles.passport.rank': 'أنت في المركز {position} بين أصدقائك في عدد الأماكن. يتصدّر {leader} بـ {places}.',
  'circles.passport.lead': 'تتصدّر أصدقاءك في عدد الأماكن، بـ {places}.',
  'circles.passport.stamp': 'ختم {city}',
  'circles.passport.stampNext': 'ختم {city}، بعد هذه الرحلة',
  'circles.incoming.title': '{name} دعاك إلى {circle}',
  'circles.incoming.sub': 'تنضم حين توافق.',
  'circles.incoming.join': 'انضم',
  'circles.incoming.declined': 'رفضت. لن نخبر {name}.',
  'circles.around.here': '{name} في {city} في نفس وقتك.',
  'circles.around.shared': '{dates} · شاركها {name} معك',
  'circles.around.sharedNoDates': 'شاركها {name} معك',
  'circles.around.more': 'خيارات أخرى لـ {name}',
  'circles.around.helloSent': 'أُرسلت. سيراها {name} حين يفتح مادا.',
  'circles.around.notNowDone': 'تمام. لن نذكرها مرة أخرى في هذه الرحلة.',
  'circles.around.sayHello': 'سلّم عليه',
  'circles.around.helloText': 'السلام عليكم. أشوفك في {city} أيضًا.',
  'circles.around.tell': 'أخبر أصدقاءك أنك في {city}',
  'circles.around.on': 'مفعّل لـ {who} · المدينة فقط · ينتهي حين تعود',
  'circles.around.whoClose': 'الأصدقاء المقرّبين',
  'circles.around.whoFamily': 'العائلة فقط',
  'circles.around.off': 'مغلق. لمن تختارهم فقط، المدينة فقط، وينتهي حين تعود.',
  'circles.around.hidden': 'مخفي. لا أحد يرى أين أنت.',
  'circles.around.sheetLabel': 'من يراك',
  'circles.around.sheetTitle': 'من يرى أنك في {city}؟',
  'circles.around.sheetBody': 'المدينة فقط. لا خريطة ولا فندق ولا موقع مباشر. ويُغلق وحده حين تعود.',
  'circles.around.picked': 'أصدقاء أختارهم',
  'circles.around.close': 'الأصدقاء المقرّبون',
  'circles.around.family': 'العائلة فقط',
  'circles.around.nobody': 'لا أحد بعد',
  'circles.around.turnOn': 'فعّل',
  'circles.around.hide': 'لا تُظهر لي {name} هنا',
  'circles.around.hideSub': 'لن نخبره.',
  'circles.around.hideDone': 'أُخفي. لن ترى {name} هنا، ولن نخبره.',
  'circles.report': 'بلّغ',
  'circles.report.sub': 'يراجع شخص كل بلاغ.',
  'circles.report.label': 'بلاغ',
  'circles.report.title': 'ما المشكلة؟',
  'circles.report.unwanted': 'رسائل غير مرغوبة',
  'circles.report.impostor': 'ينتحل شخصية غيره',
  'circles.report.unsafe': 'شيء غير آمن',
  'circles.report.other': 'شيء آخر',
  'circles.report.send': 'أرسل البلاغ',
  'circles.report.done': 'شكرًا. سيراجعه شخص خلال 24 ساعة.',
  'circles.report.andBlock': 'بلّغ واحظر',
  'circles.report.blockedDone': 'بلّغنا وحظرنا. سيراجعه شخص خلال 24 ساعة.',
  'circles.discover.on': 'هذا الأسبوع في',
  'circles.discover.cityA11y': '{city}. اختر مدينة',
  'circles.discover.whileThere': 'خلال وجودك هناك، {dates}',
  'circles.discover.book': 'احجز مع مادا',
  'circles.discover.eventAsk': '{title} في {city}',
  'circles.discover.plans': 'رحلات خطّطناها',
  'circles.discover.planPill': '{days} أيام · من تخطيط مادا',
  'circles.discover.tips': 'من أشخاص زاروها',
  'circles.discover.filterA11y': 'صفّ النصائح',
  'circles.discover.all': 'الكل',
  'circles.discover.food': 'أكل',
  'circles.discover.todo': 'أنشطة',
  'circles.discover.empty.all': 'لا نصائح من {city} بعد.',
  'circles.discover.empty.food': 'لا نصائح عن الأكل في {city} بعد.',
  'circles.discover.empty.todo': 'لا نصائح عن الأنشطة في {city} بعد.',
  'circles.discover.empty.body': 'من زاروها يشاركون الأماكن التي أحبوها. زرتها؟ نصيحتك ستكون الأولى.',
  'circles.discover.empty.action': 'انشر نصيحة',
  'circles.discover.empty.allTips': 'كل النصائح',
  'circles.tip.profileA11y': 'ملف {name}',
  'circles.tip.saveA11y': 'احفظ {place}',
  'circles.kind.food': 'أكل',
  'circles.kind.todo': 'أنشطة',
  'circles.rel.you': 'أنت',
  'circles.rel.family': 'العائلة',
  'circles.rel.friend': 'صديق',
  'circles.rel.following': 'تتابعه',
  'circles.rel.mada': 'مسافر مع مادا · {count} رحلات',
  'circles.rel.madaNew': 'على مادا',
  'circles.city.label': 'اختر مدينة',
  'circles.city.title': 'ماذا يحدث وأين؟',
  'circles.city.search': 'ابحث عن مدينة',
  'circles.city.here': 'حيث أنت',
  'circles.city.trips': 'رحلاتك',
  'circles.city.worth': 'تستحق نظرة',
  'circles.city.hereNow': 'هنا الآن',
  'circles.city.planned': 'رحلة خطّطناها',
  'circles.city.popular': 'الأكثر طلبًا هذا الشهر',
  'circles.city.guide': 'دليل المدينة',
  'circles.postTip.title': 'انشر نصيحة',
  'circles.postTip.place': 'المكان',
  'circles.postTip.placeHint': 'كنافة قرب برج غلطة',
  'circles.postTip.tip': 'نصيحتك',
  'circles.postTip.tipHint': 'ماذا يحتاج الناس أن يعرفوا؟ متى يذهبون، ماذا يطلبون، ولمن يناسب.',
  'circles.postTip.photo': 'صورة (اختيارية)',
  'circles.postTip.addPhoto': 'أضف صورة',
  'circles.postTip.changePhoto': 'غيّر الصورة',
  'circles.postTip.consent': 'كل من في الصورة وافق على نشرها.',
  'circles.postTip.who': 'من يراها',
  'circles.postTip.friends': 'الأصدقاء',
  'circles.postTip.everyone': 'كل من على مادا',
  'circles.postTip.note': 'نراجع النصائح قبل ظهورها. لا وجوه لغرباء، ولا عناوين لأشخاص.',
  'circles.postTip.post': 'انشر',
  'circles.postTip.postedFriends': 'نُشرت لأصدقائك. تظهر بعد المراجعة، عادةً خلال دقيقة.',
  'circles.postTip.postedEveryone': 'نُشرت لكل من على مادا. تظهر بعد المراجعة، عادةً خلال دقيقة.',
  'circles.postTip.photoTooBig': 'الصورة كبيرة. اختر صورة أقل من 2 ميجابايت.',
  'circles.tipDetail.planWith': 'خطّط لها مع مادا',
  'circles.tipDetail.thank': 'اشكر {name}',
  'circles.tipDetail.thanked': 'سيرى {name} شكرك',
  'circles.tipDetail.delete': 'احذف النصيحة',
  'circles.tipDetail.report': 'بلّغ عن هذه النصيحة',
  'circles.tipDetail.reported': 'شكرًا. سيراجع شخص هذه النصيحة خلال 24 ساعة.',
  'circles.tipDetail.deleteLabel': 'احذف النصيحة',
  'circles.tipDetail.deleteTitle': 'تحذف هذه النصيحة؟',
  'circles.tipDetail.deleteBody': 'تُحذف عند الجميع، ومنهم من حفظها.',
  'circles.tipDetail.deleteYes': 'احذف',
  'circles.tipDetail.deleted': 'حُذفت النصيحة.',
  'circles.tipDetail.gone': 'هذه النصيحة لم تعد موجودة. حذفها من نشرها.',
  'circles.saveToast.post': 'حُفظت في {city}. تجدها في المجموعات ← المحفوظات.',
  'circles.saveToast.plan': 'حُفظت. تجدها في المجموعات ← المحفوظات.',
  'circles.saveToast.removed': 'أُزيلت من المحفوظات.',
  'circles.newCircle.step': '{n} من 2',
  'circles.newCircle.yours': 'مجموعتك',
  'circles.newCircle.justYou': 'أنت فقط، حاليًا',
  'circles.newCircle.andMore': 'أنت و{count} آخرين',
  'circles.newCircle.cover': 'الغلاف',
  'circles.newCircle.plain': 'أخضر سادة',
  'circles.newCircle.name': 'سمّها',
  'circles.newCircle.nameHint': 'صيف في باكو',
  'circles.newCircle.dupe': 'لديك مجموعة باسم {name}.',
  'circles.newCircle.next': 'التالي',
  'circles.newCircle.who': 'من في {name}؟',
  'circles.newCircle.whoSub': 'تصلهم دعوة وينضمون حين يوافقون.',
  'circles.newCircle.picked': 'المدعوون حتى الآن',
  'circles.newCircle.removeA11y': 'أزل {name}',
  'circles.newCircle.search': 'ابحث عن أي شخص على مادا، بالاسم أو الرقم',
  'circles.newCircle.searchA11y': 'ابحث عن أشخاص على مادا',
  'circles.newCircle.noNumber': 'هذا الرقم ليس على مادا بعد.',
  'circles.newCircle.noName': 'لا أحد باسم «{q}» على مادا بعد.',
  'circles.newCircle.sendLink': 'أرسل لهم رابط دعوة',
  'circles.newCircle.family': 'العائلة',
  'circles.newCircle.friends': 'الأصدقاء',
  'circles.newCircle.nobody': 'ابحث في الأعلى عمن هم على مادا، أو أرسل رابطًا لمن ليسوا عليها.',
  'circles.newCircle.inviteLink': 'ادعُ شخصًا ليس على مادا',
  'circles.newCircle.make': 'أنشئ {name}',
  'circles.newCircle.makeLater': 'أنشئ {name}، وادعُ لاحقًا',
  'circles.newCircle.tagFriend': 'صديق',
  'circles.newCircle.tagFamily': 'العائلة',
  'circles.newCircle.tagMada': 'على مادا · {count} أصدقاء مشتركين',
  'circles.newCircle.made': 'أنشأنا المجموعة. أرسلنا الدعوة إلى {names}.',
  'circles.newCircle.madeAlone': 'أنشأنا المجموعة. شارك الرابط ليدخل ناسك.',
  'circles.invite.label': 'ادعُ برابط',
  'circles.invite.title': 'دعوة إلى {what}',
  'circles.invite.body': 'يفتحون الرابط، ويضيفون جوازاتهم، ويدفعون حصتهم بأنفسهم. لا يُشارك شيء حتى ينضموا.',
  'circles.invite.linkA11y': 'رابط الدعوة',
  'circles.invite.copy': 'انسخ رابط الدعوة',
  'circles.invite.shareNative': 'شارك رابط الدعوة',
  'circles.invite.copied': 'نُسخ الرابط. الصقه في واتساب.',
  'circles.invite.copyRefused': 'حدّد الرابط في الأعلى لتنسخه.',
  'circles.invite.shareText': 'انضم إلي في مادا للرحلات: {url}',
  'circles.invite.mada': 'مادا',
  'circles.invite.list': 'قائمتك في {city}',
  'circles.invite.yourCircle': 'مجموعتك',
  'circles.invite.cancelled': 'أُلغيت الدعوة. لن نخبر {name}.',
  'circles.invite.reminded': 'أرسلنا تذكيرًا إلى {name}.',
  'circles.chat.settingsA11y': 'إعدادات {name} وأعضاؤها',
  'circles.chat.invited': '{count} مدعوين',
  'circles.chat.muted': 'مكتومة',
  'circles.chat.openVote': 'تصويت مفتوح',
  'circles.chat.pinnedPlan': 'خطة مثبّتة',
  'circles.chat.voted': '{q} · صوّت {n} من {total}',
  'circles.chat.startsHere': 'هنا تبدأ {name}.',
  'circles.chat.startsBody': 'كل تصويت وخطة وتقسيم تعملونه معًا يبقى هنا، بالترتيب.',
  'circles.chat.dmTitle': 'سلّم على {name}.',
  'circles.chat.dmBody': 'أنتما الاثنان فقط. سلام، أو مكان حفظته، أو خطة للويكند.',
  'circles.chat.ideasA11y': 'أفكار',
  'circles.chat.idea.salam': 'السلام عليكم',
  'circles.chat.idea.free': 'فاضي هالويكند؟',
  'circles.chat.gone': 'هذه المجموعة لم تعد موجودة.',
  'circles.chat.goneBody': 'غادرتها، أو حذفها المشرف. حجوزاتك باقية في «الرحلات».',
  'circles.chat.startedVote': 'بدأ {who} تصويتًا',
  'circles.chat.splitCost': 'قسّم {who} تكلفة',
  'circles.chat.sharedPlan': 'شارك {who} خطة',
  'circles.chat.sharedPlace': 'شارك {who} مكانًا',
  'circles.chat.invitePeople': 'ادعُ أشخاصًا',
  'circles.chat.startVote': 'ابدأ تصويتًا',
  'circles.chat.split': 'قسّم تكلفة',
  'circles.chat.seen': 'شوهدت',
  'circles.chat.seenBy': 'شاهدها {names}',
  'circles.chat.madaTyping': 'مادا تبحث في الأمر',
  'circles.chat.tools': 'أدوات المجموعة: تصويت، تقسيم، مشاركة، اسأل مادا',
  'circles.chat.input': 'راسل المجموعة',
  'circles.chat.placeholder': 'رسالة، أو @Mada',
  'circles.chat.placeholderDm': 'راسل {name}',
  'circles.chat.send': 'أرسل',
  'circles.chat.older': 'رسائل أقدم',
  'circles.chat.notSent': 'لم تُرسل. اضغط إرسال لتحاول مرة أخرى.',
  'circles.tools.title': 'أضف إلى المجموعة',
  'circles.tools.voteSub': 'تواريخ، أماكن، أي شيء. كل واحد يضغط مرة.',
  'circles.tools.splitSub': 'من دفع ومن عليه. ادفع حصتك هنا.',
  'circles.tools.splitSubAlone': 'يعمل حين ينضم أحد.',
  'circles.tools.share': 'شارك خطة أو مكانًا',
  'circles.tools.shareSub': 'من خططنا ومحفوظاتك.',
  'circles.tools.askSub': 'أفكار وطيران وإقامة وتأشيرات لـ {dest}.',
  'circles.tools.askSubAny': 'أفكار وطيران وإقامة وتأشيرات.',
  'circles.vote.closedWon': 'انتهى · فاز {label}',
  'circles.vote.closedTie': 'انتهى · تعادل',
  'circles.vote.count': 'صوّت {n} من {total}',
  'circles.vote.youPicked': 'اخترت {label}',
  'circles.vote.close': 'أنهِ التصويت',
  'circles.vote.opt.one': '{label}، صوت واحد',
  'circles.vote.opt.two': '{label}، صوتان',
  'circles.vote.opt.few': '{label}، {count} أصوات',
  'circles.vote.opt.other': '{label}، {count} صوتًا',
  'circles.split.paidBy': 'دفعها {who} · {mode}',
  'circles.split.modeFamily': 'مقسّمة حسب العائلة',
  'circles.split.modeCustom': 'مبالغ مخصّصة',
  'circles.split.modeEqual': 'مقسّمة بالتساوي',
  'circles.split.settled': 'مسدّدة',
  'circles.split.paidBill': 'دفع الفاتورة',
  'circles.split.paid': 'دفع',
  'circles.split.yourShare': 'حصتك',
  'circles.split.owes': 'عليه لـ {who}',
  'circles.split.markPaid': 'علّمها مدفوعة',
  'circles.split.payMine': 'ادفع حصتي · {amount}',
  'circles.split.cash': 'دفعت نقدًا',
  'circles.split.reminded': 'ذُكّر اليوم',
  'circles.split.remind': 'ذكّر {names}',
  'circles.split.allPaid': 'الكل دفع. لا شيء متبقٍ.',
  'circles.split.remindToast': 'أرسلنا تذكيرًا إلى {names}.',
  'circles.split.yourFamily': 'عائلتك',
  'circles.split.family': 'عائلة {name}',
  'circles.share.plan': 'خطة · {days} أيام',
  'circles.share.pin': 'ثبّت',
  'circles.share.yourTip': 'نصيحتك',
  'circles.share.tipOf': 'نصيحة {name}',
  'circles.voteSheet.q': 'السؤال',
  'circles.voteSheet.qPlaces': 'وين نروح؟',
  'circles.voteSheet.qDates': 'أي مساء للعشاء؟',
  'circles.voteSheet.qAny': 'نحجز الفان؟',
  'circles.voteSheet.dates': 'تواريخ',
  'circles.voteSheet.places': 'أماكن',
  'circles.voteSheet.any': 'أي شيء',
  'circles.voteSheet.kindA11y': 'نوع التصويت',
  'circles.voteSheet.choice': 'الخيار {n}',
  'circles.voteSheet.removeChoice': 'أزل الخيار {n}',
  'circles.voteSheet.add': 'أضف خيارًا',
  'circles.voteSheet.quick': 'خيارات سريعة',
  'circles.voteSheet.yes': 'نعم',
  'circles.voteSheet.no': 'لا',
  'circles.voteSheet.maybe': 'ربما',
  'circles.voteSheet.needQ': 'أضف سؤالًا.',
  'circles.voteSheet.dup': 'خياران متطابقان.',
  'circles.voteSheet.need2': 'أضف خيارين على الأقل.',
  'circles.voteSheet.post': 'انشر التصويت',
  'circles.splitSheet.what': 'مقابل ماذا',
  'circles.splitSheet.whatHint': 'عشاء على البوسفور',
  'circles.splitSheet.dinner': 'عشاء',
  'circles.splitSheet.hotel': 'فندق',
  'circles.splitSheet.van': 'فان المطار',
  'circles.splitSheet.tickets': 'تذاكر',
  'circles.splitSheet.total': 'المجموع',
  'circles.splitSheet.totalHint': '1,200',
  'circles.splitSheet.paidBy': 'دفعها',
  'circles.splitSheet.between': 'بين',
  'circles.splitSheet.how': 'طريقة التقسيم',
  'circles.splitSheet.equally': 'بالتساوي',
  'circles.splitSheet.byFamily': 'حسب العائلة',
  'circles.splitSheet.custom': 'مخصّص',
  'circles.splitSheet.shareA11y': 'حصة {name}',
  'circles.splitSheet.addsUp': 'المجموع {amount}.',
  'circles.splitSheet.left': 'باقي {amount} للتوزيع.',
  'circles.splitSheet.over': '{amount} أكثر من المجموع.',
  'circles.splitSheet.pick2': 'اختر شخصين على الأقل.',
  'circles.splitSheet.go': 'قسّم {amount}',
  'circles.splitSheet.idle': 'قسّمها',
  'circles.shareSheet.plans': 'خطط عملناها',
  'circles.shareSheet.planSub': '{days} أيام · {city}',
  'circles.shareSheet.pin': 'ثبّت الخطة أعلى المجموعة',
  'circles.shareSheet.saves': 'أماكنك المحفوظة',
  'circles.shareSheet.none': 'لا شيء محفوظ بعد. احفظ نصيحة في «اكتشف» وتقدر تشاركها هنا.',
  'circles.shareSheet.from': '{city} · من {name}',
  'circles.mada.where': 'وين تفكرون؟ قولوا لنا مكانًا ونجيب أفكارًا لكم {n}.',
  'circles.mada.where.one': 'وين تفكر؟ قل لنا مكانًا ونجيب لك أفكارًا.',
  'circles.mada.you': 'لك',
  'circles.mada.all': 'لكم {n}',
  'circles.mada.planIt': 'خطّط لها',
  'circles.mada.planAsk': 'خطّط لرحلة إلى {dest} لـ {n}',
  'circles.mada.unknown': 'ليس لدينا أفكار جاهزة لـ {dest} بعد. نقدر نخطط لها معكم من الصفر، {who}.',
  'circles.mada.visaCheck': 'نتحقق من كل جواز في المجموعة قبل أي حجز.',
  'circles.mada.flights': '{dest} على بعد {fly}. الطيران من {from} للشخص. نقدر نحجز مقاعد {who}، معًا.',
  'circles.mada.findFlights': 'ابحث عن رحلات',
  'circles.mada.flightsAsk': 'رحلات إلى {dest} لـ {n}',
  'circles.mada.home': '{dest} هي بلدكم. لا حاجة للطيران.',
  'circles.mada.stay': 'أين تقيم في {dest}: {stay}',
  'circles.mada.seeStays': 'اعرض الإقامات',
  'circles.mada.staysAsk': 'مكان للإقامة في {dest} لـ {n}',
  'circles.mada.when': 'أفضل وقت لـ {dest}: {when}',
  'circles.mada.onePerson': 'شخص واحد',
  'circles.mada.people': '{n} أشخاص',
  'circles.mada.cost': 'لـ {people}، أربع ليالٍ في {dest} عادةً بين {lo} و{hi} مع الطيران والفندق. نحسبها بدقة حين تطلب.',
  'circles.mada.ideas': 'ثلاث أفكار لـ {dest}، {who}:',
  'circles.mada.ideasFoot': '{fly}، من {from} للشخص.',
  'circles.mada.seePlan': 'اعرض خطتنا',
  'circles.mada.result': 'اتفقنا على {phrase}. نحجزها لكم؟',
  'circles.mada.bookIt': 'احجزها',
  'circles.mada.notNow': 'ليس الآن',
  'circles.mada.tie': 'تعادل بين {options}. اختاروا واحدًا ونتولى الباقي.',
  'circles.mada.welcomeOthers': 'هذه {name}. خطّطوا هنا، وصوّتوا على الخيارات، وقسّموا التكاليف. اكتبوا @Mada لتسألونا أي شيء. وموظفكم في مادا يؤكد كل ما تحجزونه.',
  'circles.mada.welcomeInvited.one': 'هذه {name}. دعونا {names}. ابدأوا التخطيط حتى ينضم.',
  'circles.mada.welcomeInvited.other': 'هذه {name}. دعونا {names}. ابدأوا التخطيط حتى ينضموا.',
  'circles.mada.welcomeAlone': 'هذه {name}. أنت فقط حتى الآن. شارك الرابط وينضم من يفتحه.',
  'circles.mada.ideasFor': 'أفكار لـ {dest}',
  'circles.mada.aTrip': 'رحلة',
  'circles.mada.ideasMsg': '@Mada أفكار لـ {dest}',
  'circles.mada.fallback': 'نجيب عن هذا في «اسأل». أرسله إلى مادا من هناك.',
  'circles.sys.created.you': 'أنشأت المجموعة',
  'circles.sys.created': 'أنشأ {name} المجموعة',
  'circles.sys.invited.you': 'دعوت {names}',
  'circles.sys.invited': 'دعا {name} {names}',
  'circles.sys.joined.you': 'انضممت',
  'circles.sys.joined': 'انضم {name}',
  'circles.sys.joinedByLink.you': 'انضممت عبر رابط {name}',
  'circles.sys.joinedByLink': 'انضم {name} عبر رابط',
  'circles.sys.left.you': 'غادرت المجموعة',
  'circles.sys.left': 'غادر {name} المجموعة',
  'circles.sys.removed.you': 'أزلت {names}',
  'circles.sys.removed': 'أزال {name} {names}',
  'circles.sys.renamed.you': 'غيّرت اسم المجموعة إلى {text}',
  'circles.sys.renamed': 'غيّر {name} اسم المجموعة إلى {text}',
  'circles.sys.admin.you': 'أنت المشرف الآن',
  'circles.sys.admin': '{names} المشرف الآن',
  'circles.sys.pinned.you': 'ثبّت {text}',
  'circles.sys.pinned': 'ثبّت {name} {text}',
  'circles.sys.cancelledInvite.you': 'ألغيت دعوة {names}',
  'circles.sys.cancelledInvite': 'ألغى {name} دعوة',
  'circles.sys.paid.you': 'دفعت حصتك · {amount}',
  'circles.sys.paid': 'دفع {name} حصته · {amount}',
  'circles.sys.markedPaid.self': 'علّمت حصتك مدفوعة · {amount}',
  'circles.sys.markedPaid.you': 'علّمت {names} كمدفوع',
  'circles.sys.markedPaid.theirs': 'علّم {name} حصته مدفوعة · {amount}',
  'circles.sys.markedPaid': 'علّم {name} {names} كمدفوع',
  'circles.sys.reminded.you': 'ذكّرت {names}',
  'circles.sys.reminded': 'أرسل {name} تذكيرًا إلى {names}',
  'circles.sys.dm': 'الرسائل مع {name} تبقى بينكما.',
  'circles.last.nothing': 'لا شيء بعد',
  'circles.last.vote': 'تصويت: {q}',
  'circles.last.voteClosed': 'انتهى التصويت: {q}',
  'circles.last.split': 'تقسيم: {what}',
  'circles.last.settled': 'سُدّد: {what}',
  'circles.last.shared': 'شارك {who} {what}',
  'circles.last.line': '{who}: {text}',
  'circles.settings.label': 'إعدادات المجموعة',
  'circles.settings.rename': 'غيّر الاسم',
  'circles.settings.adminYou': 'أنت المشرف',
  'circles.settings.admin': '{name} هو المشرف',
  'circles.settings.roleAdmin': 'المشرف',
  'circles.settings.roleFamily': 'العائلة',
  'circles.settings.invitedPill': 'مدعو',
  'circles.settings.invitedA11y': '{name}، مدعو',
  'circles.settings.sent': 'أُرسلت {ago}',
  'circles.settings.remindedTag': 'ذُكّر',
  'circles.settings.noAnswer': 'لم يرد بعد',
  'circles.settings.remind': 'ذكّر',
  'circles.settings.reminded': 'ذُكّر',
  'circles.settings.cancelInvite': 'ألغِ الدعوة',
  'circles.settings.addPeople': 'أضف أشخاصًا',
  'circles.settings.mute': 'كتم',
  'circles.settings.muteSub': 'الحجوزات والتصويت تصلك كما هي.',
  'circles.settings.muteA11y': 'اكتم هذه المجموعة',
  'circles.settings.mutedToast': 'كُتمت.',
  'circles.settings.unmutedToast': 'أُلغي الكتم.',
  'circles.settings.leave': 'غادر المجموعة',
  'circles.settings.delete': 'احذف المجموعة',
  'circles.settings.deleteAll': 'احذفها عند الجميع',
  'circles.rename.title': 'غيّر اسم المجموعة',
  'circles.rename.a11y': 'اسم المجموعة',
  'circles.rename.note': 'كل من في المجموعة يرى الاسم الجديد.',
  'circles.rename.done': 'تغيّر الاسم.',
  'circles.add.title': 'ادعُ أشخاصًا',
  'circles.add.none': 'كل من تعرفهم على مادا موجودون هنا أو مدعوون. ادعُ غيرهم برابط.',
  'circles.add.go': 'ادعُ {count}',
  'circles.add.idle': 'ادعُ',
  'circles.add.sent': 'أرسلنا الدعوة إلى {names}.',
  'circles.member.member': 'عضو',
  'circles.member.makeAdmin': 'اجعل {name} المشرف',
  'circles.member.makeAdminSub': 'تبقى في المجموعة.',
  'circles.member.adminDone': '{name} المشرف الآن.',
  'circles.member.remove': 'أزله من المجموعة',
  'circles.member.removeSub': 'رسائله تبقى. ويفقد الوصول إلى الخطط المشتركة.',
  'circles.member.removed': '{name} خارج المجموعة الآن.',
  'circles.member.onlyAdmin': 'المشرف وحده، {name}، يضيف الأعضاء أو يزيلهم.',
  'circles.member.profile': 'اعرض الملف',
  'circles.leave.title': 'تغادر {name}؟',
  'circles.leave.deleteTitle': 'تحذف {name}؟',
  'circles.leave.bodyAdmin': 'يصبح {name} المشرف. حجوزاتك تبقى لك.',
  'circles.leave.body': 'لن ترى الرسائل الجديدة. حجوزاتك تبقى لك.',
  'circles.leave.bodyInvited': 'لم ينضم أحد بعد، لذلك نحذف المجموعة ودعواتها.',
  'circles.leave.bodyAlone': 'أنت الوحيد هنا، لذلك نحذف المجموعة.',
  'circles.leave.leave': 'غادر',
  'circles.leave.delete': 'احذف',
  'circles.leave.stay': 'ابقَ',
  'circles.leave.left': 'غادرت {name}.',
  'circles.leave.deleted': 'حُذفت {name}.',
  'circles.deleteAll.title': 'تحذفها عند الجميع؟',
  'circles.deleteAll.body': 'الرسائل والتصويتات والخطط المشتركة تُحذف عند الـ {count} كلهم. والحجوزات تبقى لمن عملها.',
  'circles.people.title': 'ناسك',
  'circles.people.tabsA11y': 'الأشخاص',
  'circles.people.friends': 'الأصدقاء',
  'circles.people.following': 'تتابعهم',
  'circles.people.invited': 'المدعوون',
  'circles.people.requests': 'الطلبات',
  'circles.people.going': 'مسافر إلى {going}',
  'circles.people.explored': '{count} أماكن زارها',
  'circles.people.friendsEmptyTitle': 'لا أصدقاء هنا بعد.',
  'circles.people.friendsEmptyBody': 'أضف من تسافر معهم. هم وحدهم يرون رحلاتك ونصائحك وخططك.',
  'circles.people.followingSub': '{count} رحلات · نصائح عامة',
  'circles.people.followingEmptyTitle': 'لا تتابع أحدًا بعد.',
  'circles.people.followingEmptyBody': 'تابع من تثق بذوقهم. نصائحهم العامة تظهر أولًا في «اكتشف».',
  'circles.people.followingEmptyAction': 'ابحث عن أشخاص في «اكتشف»',
  'circles.people.joined': 'انضم',
  'circles.people.expired': 'انتهى الرابط',
  'circles.people.notYet': 'ليس بعد',
  'circles.people.sentBy': 'أُرسلت عبر {channel} · {when}',
  'circles.people.remindedToday': 'ذُكّر اليوم',
  'circles.people.channel.link': 'رابط',
  'circles.people.channel.sms': 'رسالة نصية',
  'circles.people.channel.whatsapp': 'واتساب',
  'circles.people.remindToast': 'أرسلنا تذكيرًا إلى {name} عبر {channel}.',
  'circles.people.cancelToast': 'أُلغيت الدعوة. الرابط لم يعد يعمل.',
  'circles.people.see': 'اعرض {name}',
  'circles.people.invitedEmptyTitle': 'لم تدعُ أحدًا بعد.',
  'circles.people.invitedEmptyBody': 'أرسل رابطك على واتساب. يبقى 14 يومًا، وترى هنا لحظة انضمام أحد.',
  'circles.people.shareLink': 'شارك رابط دعوتك',
  'circles.people.requestSub': '{trips} رحلات · {mutual} أصدقاء مشتركين',
  'circles.people.accept': 'اقبل',
  'circles.people.decline': 'ارفض',
  'circles.people.block': 'احظر',
  'circles.people.friendsNow': 'أنت و{name} أصدقاء الآن.',
  'circles.people.declined': 'رفضت. لن نخبر {name}.',
  'circles.people.blocked': 'حُظر. لا يقدر {name} يجدك أو يراسلك.',
  'circles.people.requestsEmptyTitle': 'لا طلبات.',
  'circles.people.requestsEmptyBody': 'حين يطلب أحد صداقتك، يظهر هنا. القرار لك، ولا نخبره إن رفضت.',
  'circles.addFriends.title': 'أضف أصدقاء',
  'circles.addFriends.contacts': 'من جهات اتصالك',
  'circles.addFriends.contactsSub': 'اعرف من على مادا. لا نرفع جهات اتصالك.',
  'circles.addFriends.byPhone': 'برقم الجوال',
  'circles.addFriends.phoneHint': '5X XXX XXXX',
  'circles.addFriends.phoneBad': 'أرقام الجوال السعودية تبدأ بـ 5 ومن 9 أرقام.',
  'circles.addFriends.already': '{name} صديقك أصلًا.',
  'circles.addFriends.onMada': 'على مادا',
  'circles.addFriends.add': 'أضف',
  'circles.addFriends.sent': 'أُرسل',
  'circles.addFriends.requestSent': 'أرسلنا الطلب.',
  'circles.addFriends.notOnMada': 'ليس على مادا بعد.',
  'circles.addFriends.inviteSms': 'ادعُه برسالة نصية',
  'circles.addFriends.smsSent': 'أرسلنا الدعوة برسالة نصية.',
  'circles.contacts.askLabel': 'الوصول إلى جهات الاتصال',
  'circles.contacts.askTitle': 'تعرف من جهات اتصالك على مادا؟',
  'circles.contacts.askBody': 'لنعرض من على مادا. نطابق الأرقام على هذا الجوال ولا نحفظها أبدًا.',
  'circles.contacts.allow': 'اسمح',
  'circles.contacts.deny': 'لا تسمح',
  'circles.contacts.deniedLabel': 'بلا جهات اتصال',
  'circles.contacts.deniedTitle': 'لا بأس.',
  'circles.contacts.deniedBody': 'أضف أصدقاءك برقم الجوال أو أرسل رابطك. وتقدر تسمح بجهات الاتصال لاحقًا من الإعدادات.',
  'circles.contacts.foundLabel': 'جهات اتصال على مادا',
  'circles.contacts.foundTitle': 'من جهات اتصالك على مادا',
  'circles.contacts.mutual': '{count} أصدقاء مشتركين',
  'circles.contacts.allFriends': 'كل جهات اتصالك على مادا أصدقاؤك أصلًا.',
  'circles.contacts.none': 'لا أحد من جهات اتصالك على مادا بعد. أرسل لهم رابطك.',
  'circles.friend.gone': 'هذا الشخص لم يعد على مادا.',
  'circles.friend.more': 'خيارات أخرى لـ {name}',
  'circles.friend.since': 'أصدقاء منذ {year}',
  'circles.friend.sinceToday': 'أصدقاء منذ اليوم',
  'circles.friend.youFollow': 'تتابعه',
  'circles.friend.tripsWith': '{count} رحلات مع مادا',
  'circles.friend.stats': '{lead} · {places} أماكن · {followers} متابعين',
  'circles.friend.inCity': 'في {city} في نفس وقتك',
  'circles.friend.inCitySub': '{dates} · شاركها {name} معك',
  'circles.friend.message': 'راسله',
  'circles.friend.follow': 'تابع',
  'circles.friend.following': 'تتابعه',
  'circles.friend.followToast': 'تتابع {name}. نصائحه العامة تظهر في صفحتك.',
  'circles.friend.unfollowToast': 'ألغيت متابعة {name}.',
  'circles.friend.acceptRequest': 'اقبل طلب الصداقة',
  'circles.friend.add': 'أضف صديقًا',
  'circles.friend.asked': 'طلبت',
  'circles.friend.askedToast': 'طلبت صداقة {name}. الأصدقاء يرون رحلات بعضهم ونصائحهم الخاصة.',
  'circles.friend.planTogether': 'خطّطوا لرحلة معًا',
  'circles.friend.followNote': 'المتابعة تعرض لك نصائح {name} العامة. الأصدقاء وحدهم يرون رحلات بعضهم وأماكنهم.',
  'circles.friend.circlesTogether': 'مجموعات مشتركة',
  'circles.friend.tips': 'نصائح {name}',
  'circles.friend.noTips': 'لم ينشر {name} نصيحة بعد.',
  'circles.friend.hideAround': 'أخفِه من «من حولك»',
  'circles.friend.hideAroundSub': 'لن نخبره.',
  'circles.friend.hideAroundToast': 'لن ترى {name} في «من حولك». ولن نخبره.',
  'circles.friend.remove': 'أزل الصديق',
  'circles.friend.removeSub': 'تبقى في المجموعات المشتركة.',
  'circles.friend.reportBlock': 'بلّغ أو احظر',
  'circles.friend.reportBlockSub': 'يراجع شخص كل بلاغ خلال 24 ساعة.',
  'circles.friend.removeTitle': 'تزيل {name}؟',
  'circles.friend.removeBody': 'لن يرى نصائحك ولا مكانك. ولن نخبره.',
  'circles.friend.removed': 'أزلت {name}.',
  'circles.friend.blockedTitle': 'حظرت {name}.',
  'circles.friend.blockedBody': 'لا يقدر يجدك أو يراسلك. ألغِ الحظر لترى صفحته من جديد.',
  'circles.friend.unblock': 'ألغِ الحظر',
  'circles.friend.unblocked': 'ألغيت حظر {name}.',
  'circles.savedScreen.inCity': 'محفوظ في {city}',
  'circles.savedScreen.emptyBody': 'اضغط علامة الحفظ على أي نصيحة أو خطة. تظهر هنا، مرتبة حسب المدينة، جاهزة للتخطيط أو للمشاركة مع مجموعة.',
  'circles.savedScreen.dayFrom': 'خطّط ليوم منها',
  'circles.savedScreen.dayAsk': 'خطّط ليوم في {city} حول {places}',
  'circles.savedScreen.share': 'شارك',
  'circles.savedScreen.from': 'من {name} · {kind}',
  'circles.savedScreen.map': 'الخريطة',
  'circles.savedScreen.plans': 'الخطط المحفوظة',
  'circles.join.expiredTitle': 'انتهت صلاحية هذه الدعوة.',
  'circles.join.expiredBody': 'روابط الدعوة تبقى 14 يومًا. اطلب من {name} رابطًا جديدًا. يأخذ منه ضغطتين.',
  'circles.join.cancelledTitle': 'هذه الدعوة لم تعد تعمل.',
  'circles.join.cancelledBody': 'ألغاها {name}. اطلب منه رابطًا جديدًا إن كنت لا تزال تريد الانضمام.',
  'circles.join.askOnWhatsApp': 'اسأل {name} على واتساب',
  'circles.join.backToMada': 'ارجع إلى مادا',
  'circles.join.lookAround': 'تجوّل في مادا',
  'circles.join.invitedYou': '{name} دعاك',
  'circles.join.areIn': '{names} موجودون',
  'circles.join.isIn': '{names} موجود',
  'circles.join.theySee': 'إن انضممت، يرون',
  'circles.join.theySeeBody': 'اسمك وصورتك وما تنشره في المجموعة. لا جوازك ولا مدفوعاتك ولا مكانك أبدًا.',
  'circles.join.join': 'انضم إلى المجموعة',
  'circles.join.joinWithMada': 'انضم عبر مادا',
  'circles.join.takesAMinute': 'تأخذ دقيقة. وجوازك يقدر ينتظر.',
  'circles.join.joined': 'انضممت. يقدر {name} يرى أنك انضممت.',
  'circles.join.already': 'أنت في {name} أصلًا.',
  'circles.join.madaTitle': 'سافر مع {name}.',
  'circles.join.madaBody': 'خطّطوا للرحلات معًا، وصوّتوا على التواريخ، وقسّموا التكاليف. الأصدقاء وحدهم يرون رحلاتك.',
  'circles.join.addFriend': 'أضف {name} صديقًا',
  'circles.join.notFound': 'لم نجد هذه الدعوة.',
  'circles.err.notMember': 'لست في هذه المجموعة.',
  'circles.err.adminOnly': 'المشرف وحده يقدر يعمل ذلك.',
  'circles.err.blocked': 'لا يمكنك التواصل مع هذا الشخص على مادا.',
  'circles.err.inviteExpired': 'انتهت صلاحية هذه الدعوة.',
  'circles.err.voteClosed': 'هذا التصويت انتهى.',
  'circles.err.splitSum': 'الحصص لا تساوي المجموع.',
  'circles.err.self': 'هذا أنت.',
  'circles.err.alreadyReminded': 'أرسلت تذكيرًا اليوم.',
  'circles.err.dupeName': 'لديك مجموعة بهذا الاسم.',
  'sms.circles.invite': '{name} دعاك إلى مادا للرحلات: {url}',
  'sms.circles.remind': '{name} ينتظرك على مادا للرحلات: {url}',
  'notify.circles.invite.title': '{name} دعاك',
  'notify.circles.invite.body': '{circle}. تنضم حين توافق.',
  'notify.circles.share.title': 'حصة بانتظار السداد',
  'notify.circles.share.body': 'ذكّرك {name}: {what}، {amount}.',
  'notify.circles.friend.title': '{name} يطلب صداقتك',
  'notify.circles.friend.body': 'اقبل أو ارفض من المجموعات. لا نخبره إن رفضت.',
  'notify.circles.thanks.title': '{name} شكرك',
  'notify.circles.thanks.body': 'على نصيحتك عن {place}.',
  'notify.circles.hello.title': '{name} يسلّم عليك',
  'notify.circles.hello.body': 'أنتما الاثنان في {city}.',
};
