/**
 * Arabic: Shared words, presence, onboarding, Today, Trips, Wallet and Circles headers, errors, SMS and notifications (en.ts).
 * A first draft in warm, plain Modern Standard Arabic for the native Saudi writer to transcreate (COPY.md §7.4).
 * Same keys as the English; Arabic's extra plural forms are `.two`, `.few` and `.zero`. The brand is مادا.
 * Generated once from the translation sheet; edit here from now on.
 */
import type { en } from '../en';
import type { ArSection } from './types';

export const arCommon: ArSection<typeof en> = {
  'common.back': 'رجوع',
  'common.cancel': 'إلغاء',
  'common.skip': 'تخطٍّ',
  'common.later': 'لاحقًا',
  'common.notNow': 'ليس الآن',
  'common.okay': 'تمام',
  'common.continue': 'متابعة',
  'common.tryAgain': 'حاول مرة أخرى',
  'common.offline.banner': 'أنت غير متصل. كل ما يخص رحلاتك محفوظ على هذا الجوال.',
  'common.agentName': 'فيصل',
  'action.talk': 'تحدّث مع مادا',
  'action.ask': 'اسأل مادا',
  'action.send': 'أرسل إلى مادا',
  'action.call': 'اتصل بمادا',
  'presence.title': 'مادا',
  'presence.online': '{agent} متصل الآن',
  'presence.typing': '{agent} يكتب…',
  'presence.replies': 'يرد عادةً خلال {minutes} د',
  'presence.covering': '{agent} بدلًا من {usual} الليلة، وعلى اطلاع برحلتك كاملة.',
  'presence.away': 'نرد خلال 10 دقائق، في أي ساعة',
  'presence.offline': 'أنت غير متصل. سيرى {agent} رسائلك حين تعود',
  'actor.confirmed': 'أكّدها {agent} من مادا',
  'actor.replied': 'ردّ {agent}',
  'actor.intro': '{agent}، موظفك في مادا',
  'notify.sender': 'مادا',
  'tabs.today': 'اليوم',
  'tabs.trips': 'الرحلات',
  'tabs.ask': 'اسأل مادا',
  'tabs.circles': 'المجموعات',
  'tabs.wallet': 'المحفظة',
  'welcome.title': 'علينا الباقي.',
  'welcome.body': 'قل لنا وجهتك. نجدها ونحجزها ونبقى معك حتى تعود إلى بيتك.',
  'welcome.start': 'ابدأ',
  'welcome.track': 'تتبّع رحلة طيران فقط',
  'welcomeBack.titleNamed': 'أهلًا بعودتك يا {name}.',
  'welcomeBack.title': 'أهلًا بعودتك.',
  'welcomeBack.line': 'كل شيء كما تركته.',
  'welcomeBack.open': 'افتح مادا',
  'welcomeBack.notMe': 'لست أنا',
  'signin.badge': 'أكّدها فيصل من مادا',
  'signin.title': 'سجّل دخولك لتحجز وتحفظ رحلاتك.',
  'signin.body': 'رحلاتك ووثائقك وعائلتك تبقى على هذا الجوال وفي حسابك.',
  'signin.apple': 'المتابعة مع Apple',
  'signin.google': 'المتابعة مع Google',
  'signin.phone': 'استخدم رقم جوالي',
  'signin.note': 'حجوزاتك خاصة. لا نبيع بياناتك أبدًا.',
  'signin.sheet.title': 'المتابعة مع {provider}؟',
  'signin.sheet.shareEmail': 'شارك بريدي',
  'signin.sheet.shareEmailSub': 'البريد المرتبط بحساب Apple',
  'signin.sheet.hideEmail': 'أخفِ بريدي',
  'signin.sheet.hideEmailSub': 'عنوان خاص يحوّل الرسائل إليك',
  'signin.sheet.google': 'تشارك Google اسمك وبريدك الإلكتروني فقط. لا شيء غير ذلك.',
  'signin.cancelled': 'ألغيت تسجيل الدخول. لم نأخذ أي معلومة.',
  'signin.offline.title': 'أنت غير متصل.',
  'signin.offline.body': 'تسجيل الدخول يحتاج إلى اتصال. يعمل رقم جوالك بالطريقة نفسها حين يعود الاتصال.',
  'phone.title': 'رقم جوالك',
  'phone.titleSocial': 'شيء أخير: رقم جوالك',
  'phone.body': 'نرسل لك رمزًا من 6 أرقام. نستخدمه لتسجيل الدخول وتحديثات الرحلة العاجلة فقط.',
  'phone.bodySocial': 'سجّلت دخولك عبر {provider}. تغييرات البوابة ورسائل فيصل تصلك برسالة نصية وواتساب، لذلك نحتاج رقمًا يكون معك.',
  'phone.label': 'رقم الجوال',
  'phone.placeholder': '5X XXX XXXX',
  'phone.problem.prefix': 'أرقام الجوال السعودية تبدأ بـ 5 بعد \u2066+966\u2069.',
  'phone.problem.short': 'الرقم يبدو ناقصًا. يحتاج إلى 9 أرقام بعد \u2066+966\u2069 (لديك {count}).',
  'phone.problem.long': 'الرقم يبدو أطول من اللازم. يحتاج إلى 9 أرقام بعد \u2066+966\u2069.',
  'phone.problem.empty': 'اكتب رقم جوالك هنا. يبدأ بـ 5.',
  'phone.offline': 'أنت غير متصل. نرسل الرمز حين يعود الاتصال.',
  'phone.send': 'أرسلوا لي رمزًا',
  'phone.demo': 'للتجربة: الرقم 50 000 4127 لديه حساب.',
  'otp.title': 'أدخل الرمز',
  'otp.sentTo': 'أرسلناه إلى {phone}.',
  'otp.sentToFallback': 'أرسلناه إلى جوالك.',
  'otp.change': 'غيّر الرقم',
  'otp.label': 'رمز من 6 أرقام',
  'otp.wrong.one': 'الرمز غير مطابق. بقيت محاولة واحدة.',
  'otp.wrong.two': 'الرمز غير مطابق. بقيت محاولتان.',
  'otp.wrong.few': 'الرمز غير مطابق. بقيت {count} محاولات.',
  'otp.wrong.other': 'الرمز غير مطابق. بقيت {count} محاولة.',
  'otp.locked': 'محاولات كثيرة. اطلب رمزًا جديدًا لتكمل.',
  'otp.expired': 'انتهت صلاحية الرمز. اطلب رمزًا جديدًا لتكمل.',
  'otp.resendIn': 'رمز جديد بعد 0:{seconds}',
  'otp.resend': 'أرسل رمزًا جديدًا',
  'otp.resent': 'أرسلنا رمزًا جديدًا.',
  'otp.demo': 'رمز التجربة: 123456',
  'name.title': 'بماذا نناديك؟',
  'name.body': 'الاسم الأول يكفي. يستخدمه فيصل حين يراسلك.',
  'name.label': 'الاسم الأول',
  'name.go': 'يلّا نبدأ',
  'name.goNamed': 'يلّا نبدأ يا {name}',
  'alerts.title': 'لن نزعجك إلا حين يهم الأمر.',
  'alerts.body': 'تغيّر البوابة. التأخير. لحظة وصول سائقك. ولا عروض أبدًا.',
  'alerts.allow': 'اسمح بالتنبيهات',
  'alerts.later': 'ليس الآن',
  'alerts.preview.day': 'الثلاثاء 9 مارس',
  'alerts.preview.time': '07:12',
  'alerts.preview.driver.body': 'خالد عند بابك في سيارة لكزس رمادية.',
  'alerts.preview.leave.body': 'الزحام يزداد في الطريق إلى مطار الملك خالد.',
  'today.nothing.title': 'لا وجهة بعد.',
  'today.eid.weeks': 'العيد بعد {count} أسابيع.',
  'today.eid.weeks.one': 'العيد بعد أسبوع.',
  'today.eid.weeks.two': 'العيد بعد أسبوعين.',
  'today.eid.weeks.few': 'العيد بعد {count} أسابيع.',
  'today.eid.weeks.other': 'العيد بعد {count} أسبوعًا.',
  'today.eid.days': 'العيد بعد {count} أيام.',
  'today.eid.days.one': 'العيد غدًا.',
  'today.eid.days.two': 'العيد بعد يومين.',
  'today.eid.days.few': 'العيد بعد {count} أيام.',
  'today.eid.days.other': 'العيد بعد {count} يومًا.',
  'today.eid.soon': 'عيد الفطر على الأبواب.',
  'today.composer.title': 'إلى أين بعدها؟',
  'today.composer.body': 'مكان، تاريخ، ومن معك. اكتبها كما تحب.',
  'today.service.flight': 'طيران',
  'today.service.stay': 'إقامة',
  'today.service.visa': 'تأشيرات',
  'today.service.umrah': 'عمرة',
  'today.service.car': 'سيارات',
  'today.service.food': 'مطاعم',
  'today.service.todo': 'أنشطة',
  'today.passport.title': 'أضف جواز سفرك',
  'today.passport.body': 'مسحة واحدة ونعبّئه في كل حجز.',
  'today.tile.alula.title': 'العُلا',
  'today.tile.alula.body': 'يومان، خطّطناهما لك. ساعة و20 دقيقة من الرياض.',
  'today.tile.istanbul.title': 'إسطنبول',
  'today.tile.istanbul.body': '4 ساعات و15 دقيقة من الرياض',
  'today.tile.family.title': 'أضف عائلتك',
  'today.tile.family.body': 'احجز للجميع دفعة واحدة',
  'today.a11y.notifications': 'الإشعارات',
  'today.a11y.profile': 'الملف الشخصي والإعدادات',
  'trips.title': 'الرحلات',
  'trips.tab.upcoming': 'القادمة',
  'trips.tab.requests': 'الطلبات',
  'trips.tab.past': 'السابقة',
  'trips.empty.title': 'اسمك ليس على اللوحة بعد.',
  'trips.empty.body': 'اضغط على مدينة لتراها، أو قل لنا وجهتك. يحجزها فيصل ويبقى معك حتى تعود.',
  'trips.empty.action': 'إلى أين؟',
  'trips.empty.board': 'المغادرة · {city}',
  'trips.ideas.title': 'قريبة منك هذا الشتاء',
  'trips.idea.istanbul.title': 'إسطنبول',
  'trips.idea.istanbul.sub': '4 س · أجواء باردة ودافئة',
  'trips.idea.alula.title': 'العُلا',
  'trips.idea.alula.sub': 'ساعة و20 د · نجوم وصخور',
  'trips.idea.season.title': 'موسم الرياض',
  'trips.idea.season.sub': 'بلا طيران',
  'trips.requests.idea.visa': 'تأشيرة شنغن',
  'trips.requests.idea.table': 'طاولة لليلة',
  'trips.requests.idea.car': 'سيارة مع سائق',
  'trips.requests.idea.umrah': 'عمرة في رمضان',
  'trips.past.page': 'التأشيرات · الأختام',
  'trips.past.first': 'أول رحلة',
  'trips.requests.empty.title': 'لا شيء ينتظر فيصل.',
  'trips.requests.empty.body': 'أرسل له أي طلب: تأشيرة، طاولة الليلة، سيارة ليوم كامل. يصل هنا وتتابع تقدّمه.',
  'trips.requests.empty.action': 'أرسل طلبًا إلى مادا',
  'trips.past.empty.title': 'كل رحلة تترك ختمًا.',
  'trips.past.empty.body': 'ختمك الأول مكانه هنا. تبقى رحلاتك هنا مع كل إيصال، فتأخذ الرحلة التالية دقيقة.',
  'trips.past.empty.action': 'احصل على أول ختم',
  'wallet.title': 'المحفظة',
  'wallet.locked': 'مقفلة بـ Face ID · تعمل دون اتصال',
  'wallet.you': 'أنت',
  'wallet.passport.eyebrow': 'جواز السفر',
  'wallet.passport.country': 'المملكة العربية السعودية',
  'wallet.passport.notAdded': 'لم يُضف بعد',
  'wallet.passport.emptyTitle': 'جواز سفرك ليس هنا بعد.',
  'wallet.passport.emptyBody': 'مسحة واحدة على هذا الجوال. ونطابقه مع كل رحلة.',
  'wallet.passport.scan': 'امسحه الآن',
  'wallet.docs.eyebrow': 'وثائقك الأخرى',
  'wallet.docs.emptyTitle': 'لا وثائق أخرى بعد',
  'wallet.docs.emptyBody': 'تأشيرة، أو هوية وطنية، أو تأمين سفر. ونراقب التواريخ عنك.',
  'wallet.passes.eyebrow': 'لهذه الرحلة',
  'wallet.passes.emptyTitle': 'لا بطاقات صعود بعد',
  'wallet.passes.emptyBody': 'التذاكر والقسائم تصل هنا لحظة تأكيد فيصل للرحلة. وتعمل دون اتصال.',
  'wallet.passes.plan': 'خطّط لرحلة',
  'circles.tab.discover': 'اكتشف',
  'circles.tab.circles': 'المجموعات',
  'circles.yours': 'مجموعاتك',
  'circles.empty.title': 'ناسك، في مكان واحد.',
  'circles.empty.body': 'أنشئ مجموعة لمن تسافر معهم. خطّطوا معًا، وصوّتوا على التواريخ، وتقاسموا التكاليف.',
  'circles.empty.action': 'أنشئ أول مجموعة',
  'circles.idea.family': 'العائلة',
  'circles.idea.eid': 'رحلة العيد',
  'circles.idea.weekend': 'شلّة الويكند',
  'circles.idea.cousins': 'عيال العم',
  'circles.friends': 'الأصدقاء',
  'circles.friends.emptyTitle': 'اجمع ناسك.',
  'circles.friends.emptyBody': 'أضف الأصدقاء الذين تسافر معهم. هم وحدهم يرون رحلاتك ونصائحك.',
  'circles.friends.add': 'أضف أصدقاء',
  'ask.placeholder': 'إلى أين؟',
  'ask.placeholderTrip': 'أي شيء في {city}؟',
  'ask.disclosure': 'إجابات فورية من مادا. ويؤكد شخص من فريق مادا كل ما تحجزه.',
  'ask.soon': '«اسأل» يصل في الإصدار القادم. تحدّث مع مادا في أي شيء حتى ذلك الحين.',
  'error.internal': 'لم ينجح الأمر، والتقصير منا. جرّب مرة أخرى، أو تحدّث مع مادا.',
  'error.validation': 'أحد التفاصيل يحتاج نظرة أخرى.',
  'error.unauthorized': 'سجّل دخولك لتكمل.',
  'error.sessionExpired': 'سجّل دخولك مرة أخرى لتكمل.',
  'error.forbidden': 'هذا يخص حسابًا آخر.',
  'error.notFound': 'لم نجد ذلك.',
  'error.rateLimited': 'محاولات كثيرة. انتظر {seconds} ثانية ثم حاول مرة أخرى.',
  'error.otpRateLimited': 'رموز كثيرة لرقم واحد. حاول مرة أخرى بعد {minutes} د.',
  'error.otpCooldown': 'الرمز في الطريق. تقدر تطلب رمزًا جديدًا بعد {seconds} ثانية.',
  'error.phoneInvalid': 'هذا لا يبدو رقم جوال سعوديًا. يحتاج إلى 9 أرقام بعد \u2066+966\u2069، ويبدأ بـ 5.',
  'error.phoneTaken': 'هذا الرقم مسجّل في حساب آخر.',
  'error.notConfigured': 'هذه الخدمة لم تُفعّل بعد. تحدّث مع مادا ونتولاها يدويًا.',
  'error.offline': 'أنت غير متصل.',
  'sms.otp': '{code} رمزك في مادا للرحلات. صالح لمدة 10 دقائق. لا تشاركه مع أحد.',
  'notify.gateChange.title': 'تغيّرت البوابة إلى {gate}',
  'notify.gateChange.body': 'الصعود إلى {flight} الآن من {gate}. المشي إليها {minutes} دقائق.',
  'notify.leave.title': 'انطلق بعد {minutes} دقيقة',
  'notify.leave.body': 'الزحام يزداد إلى مطار الملك خالد. الطريق {drive} د.',
  'notify.driver.title': 'سائقك وصل',
  'notify.driver.body': '{driver} عند {door} ومعه لوحة باسمك.',
  'notify.confirmed.title': 'رحلتك إلى {city} مؤكدة',
  'notify.confirmed.body': 'أكّدها {agent}. رمز الحجز {ref}.',
  'notify.connectionRisk.title': 'رحلتك الموصلة في خطر',
  'notify.connectionRisk.body': '{flight} متأخرة {hours} ساعات. نحجز لك طريقتين للوصول.',
  'notify.refund.title': 'أُرسل المبلغ المسترد',
  'notify.refund.body': '{amount} في طريقه إلى {card}.',
  'notify.digest.title': 'غدًا',
  'notify.digest.body': 'الاستقبال {pickup} · يُغلق تسجيل السفر {checkin} · \u2066{temp}°\u2069 في {city}',
};
