/**
 * Arabic: Places: city search, city pages, Plan it with Mada (places.ts).
 * A first draft in warm, plain Modern Standard Arabic for the native Saudi writer to transcreate (COPY.md §7.4).
 * Same keys as the English; Arabic's extra plural forms are `.two`, `.few` and `.zero`. The brand is مادا.
 * Generated once from the translation sheet; edit here from now on.
 */
import type { placesCopy } from '../places';
import type { ArSection } from './types';

export const arPlaces: ArSection<typeof placesCopy> = {
  'places.search.title': 'إلى أين؟',
  'places.search.placeholder': 'مدينة أو رمز مطار',
  'places.search.label': 'ابحث عن مدن ومطارات',
  'places.search.recent': 'الأخيرة',
  'places.search.near': 'قريبة منك',
  'places.search.popular': 'وجهات الناس',
  'places.search.clearRecent': 'امسح',
  'places.search.clear': 'امسح البحث',
  'places.search.none': 'لا مدينة باسم «{q}».',
  'places.search.noneBody': 'جرّب اسم مدينة أو رمز مطار.',
  'places.search.closest': 'أقرب ما نعرفه',
  'places.search.offline': 'أنت غير متصل. البحث يعود لحظة عودة الاتصال.',
  'places.search.retry': 'ابحث مرة أخرى',
  'places.hit.alsoCalled': 'تُعرف أيضًا بـ {name}',
  'places.hit.airport': '{label}',
  'places.city.timeThere': '{time} هناك',
  'places.city.sameTime': 'نفس توقيتك',
  'places.city.ahead': 'متقدمة عنك {hours}',
  'places.city.behind': 'متأخرة عنك {hours}',
  'places.city.hour.one': 'ساعة واحدة',
  'places.city.hour.two': 'ساعتان',
  'places.city.hour.few': '{count} ساعات',
  'places.city.hour.other': '{count} ساعة',
  'places.city.weather': 'تظهر توقعات الطقس هنا قبل سفرك بـ 10 أيام.',
  'places.city.airports': 'المطارات',
  'places.city.airportKm': '{km} كم من المركز',
  'places.city.money': 'العملة',
  'places.city.guide': 'الدليل',
  'places.city.readOn': 'اقرأ المزيد في Wikivoyage',
  'places.city.wikipedia': 'اقرأ المزيد في ويكيبيديا',
  'places.city.sources': 'المصادر',
  'places.city.section.understand': 'تعرّف عليها',
  'places.city.section.getIn': 'الوصول',
  'places.city.section.see': 'معالم',
  'places.city.section.do': 'أنشطة',
  'places.city.section.eat': 'مطاعم',
  'places.city.section.staySafe': 'السلامة',
  'places.city.trimmed': 'مختصر من الأصل.',
  'places.city.plan': 'خطّط لها مع مادا',
  'places.city.planServed': 'الطيران والغرف لـ {city} متاحة هنا. قل لنا من مسافر ومتى.',
  'places.city.localTime': 'التوقيت المحلي',
  'places.city.nearest': 'أقرب مطار',
  'places.city.planByHandAway': 'نجهّزها يدويًا. ترد مادا هنا خلال 10 دقائق، في أي ساعة.',
  'places.city.planByHand': 'نجهّزها يدويًا. يرد {agent} هنا، عادةً خلال 20 دقيقة.',
  'places.city.notFound': 'لم نجد هذه المدينة.',
  'places.city.notFoundBody': 'ابحث مرة أخرى باسمها أو برمز مطارها.',
  'places.city.search': 'ابحث عن مدن',
  'places.city.loadingGuide': 'نفتح الدليل…',
  'places.city.a11yHero': '{city}، {country}',
  'places.plan.title': 'خطّط لـ {city} مع مادا',
  'places.plan.who': 'كم عددكم',
  'places.plan.when': 'متى',
  'places.plan.month': 'اختر شهرًا',
  'places.plan.undecided': 'لم نقرر بعد',
  'places.plan.message': 'رسالتك',
  'places.plan.send': 'أرسل إلى مادا',
  'places.plan.sending': 'نرسل…',
  'places.plan.offline': 'أنت غير متصل. تُرسل لحظة عودة الاتصال.',
  'places.request.title': 'رحلة إلى {city}',
  'places.request.detail': '{city}، {country}',
};
