/**
 * Arabic: When things go wrong: offline, slow, busy, maintenance, updates (resilience.ts).
 * A first draft in warm, plain Modern Standard Arabic for the native Saudi writer to transcreate (COPY.md §7.4).
 * Same keys as the English; Arabic's extra plural forms are `.two`, `.few` and `.zero`. The brand is مادا.
 * Generated once from the translation sheet; edit here from now on.
 */
import type { resilienceCopy } from '../resilience';
import type { ArSection } from './types';

export const arResilience: ArSection<typeof resilienceCopy> = {
  'net.offline.title': 'أنت غير متصل.',
  'net.offline.body': 'هذا يحتاج إلى اتصال. كل ما يخص رحلاتك موجود على هذا الجوال.',
  'net.offline.retryOnline': 'نحمّله لحظة عودة الاتصال.',
  'net.offline.queued': 'أنت غير متصل. نرسله لحظة عودة الاتصال.',
  'net.back': 'عاد الاتصال.',
  'net.back.sending.one': 'عاد الاتصال. أرسلنا شيئًا واحدًا عملته دون اتصال.',
  'net.back.sending.two': 'عاد الاتصال. أرسلنا شيئين عملتهما دون اتصال.',
  'net.back.sending.few': 'عاد الاتصال. أرسلنا {count} أشياء عملتها دون اتصال.',
  'net.back.sending.other': 'عاد الاتصال. أرسلنا {count} شيئًا عملته دون اتصال.',
  'net.weak': 'اتصالك بطيء الآن.',
  'fresh.justNow': 'حُدّث الآن',
  'fresh.minutes': 'حُدّث قبل {minutes} د',
  'fresh.hours': 'حُدّث قبل {hours} س',
  'fresh.date': 'حُدّث {date}',
  'fresh.offline': 'محفوظ على هذا الجوال · حُدّث {when}',
  'fresh.last': 'آخر تحديث {when}',
  'slow.title': 'ما زلنا نعمل… أبطأ من المعتاد',
  'slow.body': 'لم يضع شيء مما عملته.',
  'slow.bodyWeak': 'اتصالك ضعيف. لم يضع شيء مما عملته.',
  'slow.cancel': 'إلغاء',
  'timeout.title': 'هذا يأخذ وقتًا طويلًا.',
  'timeout.body': 'ربما الاتصال ضعيف. لم يضع شيء مما عملته.',
  'busy.wait': 'لدينا ضغط الآن. نحاول مرة أخرى بعد {seconds} ثانية.',
  'busy.title': 'لنأخذ استراحة قصيرة.',
  'busy.body': 'كانت هناك محاولات كثيرة متتالية. نحاول مرة أخرى بعد {seconds} ثانية. لا شيء مقفل.',
  'problem.inline': 'لم يُحمَّل هذا.',
  'problem.title': 'لم ينجح الأمر، والتقصير منا.',
  'problem.body': 'رحلاتك ووثائقك بأمان على هذا الجوال. جرّب مرة أخرى، أو تحدّث مع مادا.',
  'problem.ref': 'المرجع {ref}',
  'problem.partial.title': 'جزء من هذا لم يُحمَّل.',
  'problem.partial.body': 'تحديث مادا يحل الأمر عادةً. وكل شيء آخر يعمل كالمعتاد.',
  'crash.eyebrow': 'دورة انتظار',
  'crash.title': 'نحلّق قليلًا ريثما نعود. رحلاتك بأمان.',
  'crash.body': 'توقّف شيء من جهتنا. حجوزاتك ومدفوعاتك ومستنداتك كما هي تمامًا. أعد التشغيل وستعود إلى صفحة اليوم.',
  'crash.note': 'فريقنا على علم بالفعل. لم تُرسَل أي بيانات شخصية.',
  'crash.restart': 'أعد تشغيل مادا',
  'supplierDown.title': 'نظام {supplier} لا يستجيب.',
  'supplierDown.body': 'نحاول مرة أخرى كل دقيقة. تحدّث مع مادا ونحجزها يدويًا.',
  'supplierDown.bodyBooking': '{agent} يحجزها يدويًا. لا شيء مطلوب منك.',
  'supplierDown.generic': 'شركة الطيران',
  'supplierDown.status': '{supplier} بطيء في الاستجابة الآن.',
  'supplier.flights': 'شركة الطيران',
  'supplier.hotels': 'الفندق',
  'supplier.payments': 'البنك',
  'supplier.sms': 'خدمة الرسائل النصية',
  'supplier.whatsapp': 'واتساب',
  'supplier.email': 'خدمة البريد الإلكتروني',
  'supplier.flightStatus': 'متتبّع الرحلات',
  'supplier.flightPositions': 'خريطة الرحلات',
  'supplier.ai': 'خدمة الإجابات الفورية',
  'supplier.identity': 'Apple أو Google',
  'session.expired.title': 'سجّل دخولك مرة أخرى لتكمل.',
  'session.expired.body': 'أخرجناك من حسابك حفاظًا على أمانه. ما كتبته باقٍ هنا.',
  'session.expired.action': 'سجّل الدخول',
  'session.expired.to': 'نرسل رمزًا إلى {phone}.',
  'update.title': 'حدّث مادا لتكمل الحجز.',
  'update.body': 'هذا الإصدار لم يعد يصل إلى الحجوزات. رحلاتك ووثائقك بأمان، وكلها هنا بعد التحديث.',
  'update.note': 'عادةً أقل من دقيقة على الواي فاي.',
  'update.action': 'حدّث مادا',
  'update.offline': 'افتح رحلاتي',
  'update.soft': 'إصدار جديد من مادا جاهز.',
  'update.softAction': 'حدّث',
  'maintenance.title': 'نحدّث مادا الآن.',
  'maintenance.titleUntil': 'نحدّث مادا حتى {time}.',
  'maintenance.body': 'الحجز والتغيير والدفع متوقفة مؤقتًا. التحديث مجدول، ولا يتأثر شيء مما حجزته.',
  'maintenance.bodyUntil': 'الحجز والتغيير والدفع متوقفة حتى {time} بتوقيت الرياض. التحديث مجدول، ولا يتأثر شيء مما حجزته.',
  'maintenance.works': 'رحلاتك ومحفظتك تعمل دون اتصال، مع بطاقات الصعود وعنوان الفندق.',
  'maintenance.call': 'تحدّث مع مادا هاتفيًا',
  'maintenance.note': 'الفريق يرد في أي ساعة على {phone}.',
  'maintenance.until': 'نعود بحلول {time}.',
  'maintenance.banner': 'صيانة · الحجز متوقف',
  'maintenance.bannerUntil': 'صيانة حتى {time} · الحجز متوقف',
  'maintenance.trips': 'افتح رحلاتي',
  'maintenance.retry': 'تحقق مرة أخرى',
  'net.pay.offlineTitle': 'أنت غير متصل، فتوقفنا قبل الدفع.',
  'pay.dropped.title': 'انقطع الاتصال أثناء الدفع.',
  'net.pay.held': 'لم يُخصم شيء. سعرك محجوز لمدة {minutes} دقيقة أخرى.',
  'pay.already': 'الدفع جارٍ. لن يُخصم منك إلا مرة واحدة.',
  'net.pay.offlineBody': 'لم يُخصم شيء. نكمل من حيث توقفت.',
  'pay.offline.resume': 'أكمل',
  'pay.unknown.title': 'نتحقق مع بنكك.',
  'pay.unknown.body': 'لن يُخصم منك مرتين. نعرض لك النتيجة هنا.',
  'order.resumed': 'حجز {place} ما زال لدى {agent}.',
  'outbox.queued': 'في الانتظار',
  'outbox.queuedLine': 'يُرسل حين تتصل',
  'outbox.sending': 'نرسل',
  'outbox.stuck': 'لم يُرسل',
  'outbox.why': 'لم يصل إلى مادا. لم يضع شيء.',
  'outbox.retry': 'أرسل مرة أخرى',
  'outbox.discard': 'تجاهل',
  'outbox.discarded': 'تجاهلناه. لم يُرسل شيء.',
  'outbox.empty': 'لا شيء ينتظر الإرسال',
  'outbox.offline': 'أنت غير متصل. تُرسل هذه لحظة عودة الاتصال.',
  'outbox.down': 'مادا لا تستجيب الآن. تُرسل هذه لحظة استجابتها.',
  'outbox.allSent': 'كل ما عملته وصل إلى مادا.',
  'outbox.works': 'يعمل دون اتصال',
  'outbox.worksBody': 'الرحلات والمحفظة وبطاقات الصعود وبرنامج رحلتك وعنوان الفندق باللغة المحلية.',
  'outbox.call': 'اتصل بمادا · {phone}',
  'pill.offline': 'غير متصل · رحلاتك على هذا الجوال',
  'pill.offlineWaiting': 'غير متصل · {count} بانتظار الإرسال',
  'pill.down': 'لا نصل إلى مادا الآن',
  'pill.downWaiting': 'لا نصل إلى مادا · {count} بالانتظار',
  'pill.weak': 'اتصال ضعيف · التحميل بطيء',
  'pill.sending.one': 'نرسل شيئًا واحدًا…',
  'pill.sending.two': 'نرسل شيئين…',
  'pill.sending.few': 'نرسل {count} أشياء…',
  'pill.sending.other': 'نرسل {count} شيئًا…',
  'pill.held': '{count} لم تُرسل · افتح صندوق الإرسال',
  'pill.a11y': '{text}. افتح صندوق الإرسال.',
  'outbox.title': 'بانتظار الإرسال',
  'gone.title': 'هذا الرابط لم يعد يؤدي إلى شيء.',
  'gone.body': 'ما كان يشير إليه حُذف، أو شورك مع شخص آخر. لم يتغير شيء يخصك.',
  'gone.trips': 'اعرض رحلاتك',
  'gone.home': 'اذهب إلى اليوم',
  'gone.inviteTitle': 'انتهت صلاحية هذه الدعوة.',
  'gone.inviteBody': 'الدعوات تبقى 7 أيام. اطلب رابطًا جديدًا ممن أرسلها.',
  'storage.full.title': 'ذاكرة جوالك شبه ممتلئة.',
  'storage.full.body': 'لم نتمكن من حفظ رحلاتك للاستخدام دون اتصال. وفّر بعض المساحة ونحاول مرة أخرى.',
  'perm.settings': 'افتح الإعدادات',
  'perm.camera.title': 'الكاميرا مغلقة لمادا.',
  'perm.camera.body': 'نستخدمها لقراءة الجوازات والوثائق. لا نحفظ شيئًا حتى تراجعه. فعّلها من الإعدادات › مادا، أو أكمل بدونها.',
  'perm.camera.manual': 'ارفع صورة بدلًا منها',
  'perm.contacts.title': 'جهات الاتصال مغلقة لمادا.',
  'perm.contacts.body': 'نطابق الأرقام على هذا الجوال لنعرض من على مادا. لا نرفعها أبدًا. فعّلها من الإعدادات › مادا، أو أكمل بدونها.',
  'perm.contacts.manual': 'شارك رابط دعوتك',
  'perm.location.title': 'الموقع مغلق لمادا.',
  'perm.location.body': 'نستخدم مدينتك، لا شارعك، ليرى الأصدقاء الذين اخترتهم أنك قريب. فعّله من الإعدادات › مادا، أو أكمل بدونه.',
  'perm.location.manual': 'اختر مدينتك بدلًا منه',
  'perm.notifications.title': 'التنبيهات مغلقة لمادا.',
  'perm.notifications.body': 'تغيّر البوابة، التأخير، ووصول سائقك. ولا عروض أبدًا. فعّلها من الإعدادات › مادا، أو أكمل بدونها.',
  'perm.notifications.manual': 'استلمها برسائل نصية بدلًا منها',
  'perm.photos.title': 'الصور مغلقة لمادا.',
  'perm.photos.body': 'نستخدمها لإضافة وثيقة من صورك. فعّلها من الإعدادات › مادا، أو أكمل بدونها.',
  'perm.photos.manual': 'اختر ملفًا بدلًا منها',
  'error.supplierDown': 'هذا المزوّد لا يستجيب. تحدّث مع مادا ونتولاها يدويًا.',
  'error.maintenance': 'الحجز متوقف لدقائق ونحن نحسّن مادا.',
  'error.upgradeRequired': 'هذا الإصدار من مادا يحتاج تحديثًا.',
  'error.idempotencyConflict': 'أُرسل هذا من قبل ببيانات مختلفة. راجعه وأرسله مرة أخرى.',
  'error.inProgress': 'ما زلنا على المحاولة الأولى. انتظر ثواني.',
  'error.timeout': 'هذا يأخذ وقتًا طويلًا. لم يضع شيء مما عملته.',
};
