/**
 * Arabic: Today in every phase of a trip (en-trips-today.ts).
 * A first draft in warm, plain Modern Standard Arabic for the native Saudi writer to transcreate (COPY.md §7.4).
 * Same keys as the English; Arabic's extra plural forms are `.two`, `.few` and `.zero`. The brand is مادا.
 * Generated once from the translation sheet; edit here from now on.
 */
import type { enTripsToday } from '../en-trips-today';
import type { ArSection } from './types';

export const arTripsToday: ArSection<typeof enTripsToday> = {
  'trip.direct': 'مباشرة',
  'td.justYou': 'أنت فقط',
  'td.travellers': '{n} مسافرين',
  'td.openTrip': 'افتح الرحلة',
  'td.lastTrip': '{when}، سافر {you} إلى {city}.',
  'td.lastTime': 'المرة الماضية',
  'td.tile.circle': 'أنشئ مجموعة',
  'td.tile.circleBody': 'خطّطوا للرحلة القادمة معًا',
  'td.banner.now': 'الآن',
  'td.when.tomorrow': 'غدًا',
  'td.when.tomorrowAt': 'غدًا · {time}',
  'td.when.today': 'اليوم',
  'td.when.todayAt': 'اليوم · {time}',
  'td.when.thisWeek': 'هذا الأسبوع',
  'td.when.inDays': 'بعد {n} أيام',
  'td.when.inWeeks': 'بعد {n} أسابيع',
  'td.demo.title': 'اعرض لحظة من الرحلة',
  'td.demo.body': 'لنسخ المراجعة. ينتقل وقت الرحلة إليها، ولا يتغير شيء حقيقي.',
  'td.demo.real': 'الوقت الحقيقي',
  'td.demo.offline': 'دون اتصال',
  'td.demo.showing': 'المعروض: {phase}',
  'td.demo.phase.none': 'لا خطط',
  'td.demo.phase.booked': 'قبلها بأسابيع',
  'td.demo.phase.daybefore': 'اليوم السابق',
  'td.demo.phase.travelday': 'يوم السفر',
  'td.demo.phase.delayed': 'تأخير متوقع',
  'td.demo.phase.cancelled': 'أُلغيت الرحلة',
  'td.demo.phase.inair': 'في الجو',
  'td.demo.phase.landed': 'بعد الهبوط',
  'td.demo.phase.home': 'بعد العودة',
  'td.req.answer': 'لدى مادا رد على {what}',
  'td.req.working': 'مادا تعمل على {what}',
  'td.req.tap': 'اضغط لتراه',
  'td.req.queued': 'يُرسل حين يعود اتصالك',
  'td.req.usually': 'عادةً خلال ساعتين',
  'td.guest.title': 'تتبّع أي رحلة.',
  'td.guest.emptyTitle': 'لا شيء متتبَّع بعد.',
  'td.guest.emptyBody': 'أضف رقم رحلة ونراقب لك البوابة والموعد. لا حاجة لحساب.',
  'td.guest.cardTitle': 'تريدنا نحجز ونتابع الرحلة كلها؟',
  'td.guest.cardBody': 'سجّل دخولك لتحجز الطيران والإقامة والتأشيرات، وخلف كل حجز موظف باسمه.',
  'td.guest.comeWith': 'رحلاتك المتتبَّعة تنتقل معك.',
  'td.guest.signIn': 'سجّل الدخول',
  'td.track.label': 'رقم الرحلة',
  'td.track.when': 'متى موعدها؟',
  'td.track.today': 'اليوم',
  'td.track.tomorrow': 'غدًا',
  'td.track.pick': 'اختر تاريخًا',
  'td.track.date': 'تاريخ الرحلة',
  'td.track.pickDay': 'اختر يوم الرحلة.',
  'td.track.submit': 'تتبّعها',
  'td.track.errNumber': 'أضف الرقم بعد رمز شركة الطيران، مثل SV263.',
  'td.track.errAirline': 'ابدأ برمز شركة الطيران من حرفين، مثل SV أو EK.',
  'td.track.errShape': 'حرفان أو حرف ورقم، ثم حتى 4 أرقام. مثل SV263 أو F3101.',
  'td.track.askTitle': 'تريد تنبيهًا إن تغيّرت {code}؟',
  'td.track.askBody': 'تغيّر البوابة والتأخير والإلغاء لهذه الرحلة. لا شيء غير ذلك. جوالك يسألك بعدها.',
  'td.track.allow': 'نعم، نبّهني',
  'td.track.tracking': 'نتتبّع {code}.',
  'td.track.trackingAlerts': 'نتتبّع {code}. وننبهك إن تغيّرت.',
  'td.track.saved': 'حُفظت. نجد {code} حين تكون في الجو.',
  'td.track.onTime': 'في الموعد',
  'td.track.late': 'متأخرة',
  'td.track.waiting': 'بالانتظار',
  'td.track.unknown': 'نجدها حين تكون في الجو. أغلب شركات الطيران تنشر مسار الرحلة قبلها بيوم.',
  'td.track.alerts': 'ننبهك إن تغيّرت',
  'td.track.alertsOff': 'التنبيهات مغلقة على هذا الجوال',
  'td.track.noAlerts': 'لا تنبيهات لهذه',
  'td.track.fromTo': 'من {from} إلى {to}',
  'td.track.stop': 'أوقف',
  'td.track.stopped': 'أوقفنا تتبّع {code}.',
  'td.ready.count': '{done} من {total} جاهزة',
  'td.ready.allSet': 'كل شيء جاهز.',
  'td.ready.last': '{k} هو آخر شيء.',
  'td.ready.left': 'باقي {n} أشياء. كل واحد يأخذ دقيقة.',
  'td.ready.nothing': 'لا شيء يحتاجك حتى اليوم السابق.',
  'td.ready.doneList': '{n} جاهزة: {list}',
  'td.ready.flight': 'الرحلة',
  'td.ready.flights': 'الرحلات',
  'td.ready.seatsTogether': 'المقاعد {seats}، متجاورة',
  'td.ready.seat': 'المقعد {seat}',
  'td.ready.noFlights': 'لا رحلات طيران بعد',
  'td.ready.noFlightsBody': 'الإقامة محجوزة. أضف الطيران حين تجهز.',
  'td.ready.findFlights': 'ابحث عن رحلات',
  'td.ready.noStay': 'لا إقامة بعد',
  'td.ready.staysCancelled': 'أُلغيت الغرف. نقدر نجد غيرها.',
  'td.ready.noStayBody': 'تريد غرفًا لنفس التواريخ؟ نقدر نحجز بعضها.',
  'td.ready.findStay': 'ابحث عن إقامة',
  'td.ready.whereStaying': 'مكان إقامتك',
  'td.ready.stay': 'الإقامة',
  'td.ready.stayV': '{name} · {nights} ليالٍ',
  'td.ready.ppOf': 'جواز {name}',
  'td.ready.fixPp': 'أصلح مسألة جواز {name}',
  'td.ready.passport': 'الجواز',
  'td.ready.passports': 'الجوازات',
  'td.ready.ppMissing': 'ليست في المحفظة بعد: {names}',
  'td.ready.addPp': 'أضفه',
  'td.ready.ppValid': 'صالح لـ {country}',
  'td.ready.ppValidAll': 'الـ {n} كلها صالحة لـ {country}',
  'td.ready.entry': 'شروط الدخول',
  'td.ready.entryV': 'راجعناها لك',
  'td.ready.entryAll': 'راجعناها للـ {n} كلهم',
  'td.ready.data': 'إرسال الجوال عند الهبوط',
  'td.ready.dataOne': 'جوالك يعمل لحظة هبوطك. {price}.',
  'td.ready.dataMany': 'الجوالات تعمل لحظة الهبوط. {price} للواحد.',
  'td.ready.setUp': 'جهّزها',
  'td.ready.esimDone': 'شريحة eSIM لـ {n} · تُثبّت قبل سفرك',
  'td.ready.esimWaiting': 'لدى مادا. ادفع حين يجهز السعر.',
  'td.ready.esimPay': 'اعرضها',
  'td.ready.pickups': 'الاستقبال من المطار',
  'td.ready.bothWays': 'ذهابًا وعودة · ينتظر السائق {wait}',
  'td.ready.oneWay': 'عند الوصول · ينتظر السائق {wait}',
  'td.ready.noPickup': 'بلا استقبال من المطار',
  'td.ready.noPickupBody': 'سائق في صالة الوصول يحمل اسمك.',
  'td.ready.addPickup': 'أضف استقبالًا',
  'td.esim.sheetTitle': 'إرسال الجوال في {country}',
  'td.esim.sheetBody': '10 جيجابايت لكل شخص لمدة 7 أيام. تُثبّت قبل السفر وتعمل حين تهبط. قابلة للاسترداد حتى تثبيتها.',
  'td.esim.send': 'أرسل إلى مادا · {price}',
  'td.esim.sent': 'وصل إلى مادا. تدفع حين تجهز الشرائح.',
  'td.esim.offline': 'اتصل لترسلها. وكل شيء آخر محفوظ.',
  'td.offline.title': 'أنت غير متصل.',
  'td.rel.self': 'أنت',
  'td.rel.spouse': 'الزوج أو الزوجة',
  'td.rel.child': 'ابن أو ابنة',
  'td.rel.parent': 'أحد الوالدين',
  'td.rel.sibling': 'أخ أو أخت',
  'td.rel.helper': 'عاملة منزلية',
  'td.rel.other': 'العائلة',
  'td.next.title': 'التالي في {city}',
  'td.next.cruise': 'عشاء على قارب في البوسفور',
  'td.next.cruiseMany': 'عشاء على الماء لـ {n}. من رصيف كاباتاش.',
  'td.next.cruiseOne': 'عشاء على الماء. من رصيف كاباتاش.',
  'td.next.anyEvening': 'أي مساء',
  'td.next.kids': 'ثلاثة أيام سهلة مع الأطفال',
  'td.next.kidsNote': 'قصور، وعبّارات، وأطيب كنافة.',
  'td.next.plan': 'خطة لك',
  'td.next.walk': 'من غلطة إلى كاراكوي مشيًا',
  'td.next.walkNote': 'قهوة، والبرج، والماء. صباح على مهل.',
  'td.next.walkAsk': 'مشي من غلطة إلى كاراكوي',
  'td.next.half': 'نصف يوم',
  'td.next.table': 'طاولة في كاراكوي',
  'td.next.tableFamily': 'حلال، جلسات عائلية، على الماء.',
  'td.next.tableHalal': 'حلال، على الماء.',
  'td.next.anyNight': 'أي ليلة',
  'td.circleTips': 'نصائح من أشخاص زاروها',
  'td.circleTipsBody': 'شاهد ما حفظه المسافرون في {city}، في المجموعات.',
  'td.db.allSet': 'كل شيء جاهز لغد.',
  'td.db.oncePacked': 'كل شيء جاهز، بعد تجهيز الشنط.',
  'td.db.checkedIn': 'تم تسجيل السفر',
  'td.db.seat': 'المقعد',
  'td.db.seats': 'المقاعد',
  'td.db.bags': '{bags} لكل مسافر',
  'td.db.pass': 'بطاقة صعود واحدة',
  'td.db.passes': '{n} بطاقات صعود',
  'td.db.offline': 'جاهزة دون اتصال',
  'td.db.openPass': 'افتح البطاقة',
  'td.db.openPasses': 'افتح البطاقات',
  'td.plan.title': 'الخطة',
  'td.plan.tonight': 'الليلة',
  'td.plan.pack': 'جهّز الشنط',
  'td.plan.packed': 'جاهزة',
  'td.plan.packSub': '{n} من {total} تم',
  'td.plan.packedSub': 'كل شيء فيها. لا شيء للصباح.',
  'td.plan.seeList': 'اعرض القائمة',
  'td.plan.lights': 'النوم',
  'td.plan.lightsSub': '{n} ساعات قبل المنبّه',
  'td.plan.wake': 'نوقظ جوالك',
  'td.plan.wakeSub': 'منبّه هادئ، مع الطقس ومدة الطريق',
  'td.plan.atDoor': '{driver} عند بابك',
  'td.plan.atDoorSub': '{car} · ينتظر {waits}',
  'td.plan.changePickup': 'غيّر موعد الاستقبال',
  'td.plan.leave': 'انطلق إلى المطار',
  'td.plan.leaveSub': '31 د إلى {airport}. لا سيارة محجوزة.',
  'td.plan.airportSub': 'تسليم الحقائب يُغلق {time}. أنت مسجّل مسبقًا.',
  'td.plan.boarding': 'الصعود، البوابة {gate}',
  'td.plan.seats': 'المقاعد {seats}، متجاورة',
  'td.plan.seat': 'المقعد {seat}',
  'td.plan.fly': '{code} إلى {city}',
  'td.plan.flySub': 'تهبط {time} بالتوقيت المحلي',
  'td.plan.tomorrow': 'غدًا، {day}',
  'td.weather.onLanding': '{city} عند الهبوط',
  'td.weather.a11y': '{city} حين تهبط: {temp} درجة. {summary}',
  'td.pack.title': 'جهّز الشنط الليلة',
  'td.pack.done': 'الشنط جاهزة. نومًا هنيئًا.',
  'td.pack.doneBody': 'كل شيء فيها. والصباح علينا.',
  'td.pack.count': '{n} من {total} في الشنط. علامات الصح تبقى على هذا الجوال.',
  'td.pack.passport': 'جوازك',
  'td.pack.passports': 'الجوازات ×{n}',
  'td.pack.ppFix': 'جواز {name} يحتاج إصلاحًا أولًا.',
  'td.pack.ppOk': 'صالح لـ {country}. طابقناه مع المحفظة.',
  'td.pack.ppOkAll': 'الـ {n} كلها صالحة لـ {country}. طابقناها مع المحفظة.',
  'td.pack.chargers': 'الشواحن وباور بانك',
  'td.pack.chargersSub': 'الباور بانك يكون في حقيبة اليد.',
  'td.pack.adapter': 'محوّل كهرباء، {plug}',
  'td.pack.adapterSub': 'القوابس في {country} دائرية بسنّين، 230 فولت.',
  'td.pack.umbrella': 'مظلة',
  'td.pack.umbrellaSub': 'مطر خفيف عند هبوطك.',
  'td.pack.layer': 'لبس دافئ',
  'td.pack.layerEach': 'لبس دافئ لكل واحد',
  'td.pack.layerSub': '{temp}° في {city}. وهنا حوالي 28°.',
  'td.pack.mat': 'سجادة صلاة',
  'td.pack.matHotel': 'الفندق على بعد دقيقتين من مسجد.',
  'td.pack.matCity': 'المساجد قريبة دائمًا في {city}.',
  'td.pack.snacks': 'سناكات لـ {names}',
  'td.pack.snacksSub': '{dur} في الجو.',
  'td.pack.meds': 'الأدوية',
  'td.pack.medsSub': 'في حقيبة اليد، مع الوصفات.',
  'td.pack.yours': 'أضفتها أنت',
  'td.pack.add': 'أضف شيئًا للشنط',
  'td.pack.addBtn': 'أضف',
  'td.pack.remove': 'أزل {what}',
  'td.pickup.label': 'غيّر موعد الاستقبال',
  'td.pickup.when': 'متى يجي {driver}؟',
  'td.pickup.body': '31 د إلى {airport} في تلك الساعة. تسليم الحقائب لرحلة {code} يُغلق الساعة {time}.',
  'td.pickup.atBy': 'الساعة {t}، قبل {time}',
  'td.pickup.spare': 'متسع {n} د',
  'td.pickup.tight': '{n} د فقط قبل إغلاق تسليم الحقائب',
  'td.pickup.suggest': 'ما نقترحه',
  'td.pickup.wake': 'نوقظ جوالك الساعة {time}.',
  'td.pickup.stays': 'الاستقبال يبقى الساعة {time}',
  'td.pickup.move': 'انقل الاستقبال إلى {time}',
  'td.pickup.told': 'أخبرنا {driver}. الاستقبال الساعة {time}.',
  'td.pickup.tightNote': 'الوقت ضيق صباح يوم عمل. نقترح أبكر.',
  'td.tv.allSet': 'كل شيء جاهز.',
  'td.tv.oneThing': 'شيء واحد يحتاج نظرة.',
  'td.tv.newFlight': 'كل شيء جاهز على الرحلة الجديدة.',
  'td.tv.driverWaits': '{car}. ينتظرك عند بابك.',
  'td.tv.leaveBy': 'انطلق قبل {time}',
  'td.tv.driveTo': '31 د إلى {airport}، {terminal}.',
  'td.tv.passes': 'بطاقات الصعود',
  'td.leave.in': 'انطلق من البيت بعد',
  'td.leave.min': 'د',
  'td.leave.driver': '{driver} الساعة {time}',
  'td.leave.noCar': 'لا سيارة محجوزة',
  'td.leave.drive': '31 د إلى {airport}',
  'td.fc.onTime': 'في الموعد',
  'td.fc.mayBeLate': 'قد تتأخر',
  'td.fc.late': 'متأخرة {n} د',
  'td.fc.gate': 'البوابة',
  'td.fc.boards': 'الصعود',
  'td.fc.seat': 'المقعد',
  'td.fc.seats': 'المقاعد',
  'td.fc.live': 'مباشر من شركة الطيران · حُدّث الآن',
  'td.fc.offline': 'دون اتصال · آخر تحديث من شركة الطيران الساعة {time}',
  'td.fc.gateChanged': 'تغيّرت البوابة إلى {gate} · {min} د مشيًا · مباشر من شركة الطيران',
  'td.fc.inbound': 'الطائرة القادمة من القاهرة متأخرة.',
  'td.fc.predicted': 'تتوقع مادا تأخيرًا. لم تعلن {airline} بعد.',
  'td.fc.seePlan': 'اعرض الخطة',
  'td.dw.title': 'ما يحدث بعد ذلك',
  'td.dw.held': 'مقاعد محجوزة على رحلة 10:25',
  'td.dw.heldAll': 'للـ {n} كلهم، متجاورة. الحجز المؤقت بلا تكلفة.',
  'td.dw.heldOne': 'مقعد لك. الحجز المؤقت بلا تكلفة.',
  'td.dw.watching': 'نراقب الطائرة القادمة من القاهرة',
  'td.dw.watchingSub': 'يُفترض أن تهبط في الرياض قبل 08:30. نتحقق كل 5 دقائق.',
  'td.dw.driver': 'نبلغ {driver} أولًا بأول',
  'td.dw.driverSub': 'إن غيّرت الرحلة، يجي لاحقًا. ابقَ في البيت حتى ذلك الوقت.',
  'td.cx.title': 'ألغت {airline} رحلتك.',
  'td.cx.bodyAll': 'يحق لكم استرداد كامل. ونحجز الآن مقاعد على الرحلة التالية لكم الـ {n} كلكم.',
  'td.cx.bodyOne': 'يحق لك استرداد كامل. ونحجز لك الآن مقعدًا على الرحلة التالية.',
  'td.cx.options': 'اعرض خياراتك',
  'td.cx.taken': 'تولّيناه مسبقًا',
  'td.cx.hotel': 'الفندق على علم',
  'td.cx.hotelRoom': '{name}: غرفتك محجوزة، حتى لو وصلت متأخرًا.',
  'td.cx.hotelRooms': '{name}: غرفكم محجوزة، حتى لو وصلتم متأخرين.',
  'td.cx.pickups': 'الاستقبال ينتقل معك',
  'td.cx.pickupsSub': '{a} و{b} يتبعان الرحلة التي تختارها.',
  'td.cx.money': 'أو استرد مالك',
  'td.cx.moneySub': '{amount} مقابل {what}، إلى بطاقتك خلال 7 أيام تقريبًا.',
  'td.cx.flight': 'الرحلة',
  'td.cx.flights': 'الرحلات',
  'td.talk.today': '{agent} معك اليوم.',
  'td.talk.tonight': '{agent} مناوب الليلة.',
  'td.talk.watching': '{agent} يراقب الطائرة القادمة من القاهرة.',
  'td.talk.onPhone': '{agent} على الهاتف مع {airline} الآن.',
  'td.talk.wifi': 'واي فاي في الطائرة؟ {agent} يقدر يتواصل معك.',
  'td.talk.arrival': '{agent} يتابع وصولك.',
  'td.air.estimated': 'في الجو · تقديري، بلا حاجة لإشارة',
  'td.air.live': 'في الجو · {alt} قدم، رُصدت الآن',
  'td.air.to': 'إلى {city}',
  'td.air.lookLeft': 'انظر يسارًا بعد 40 دقيقة تقريبًا: جبال طوروس.',
  'td.deck.title': 'خطّط لأول أمسية',
  'td.deck.body': 'اسحب يمينًا على ما يعجبك. نحجزه حين تهبط.',
  'td.deck.of': '{i} من {n}',
  'td.deck.yes': 'نعم، احجزه',
  'td.deck.yesA11y': 'نعم، احجزه حين أهبط',
  'td.deck.skip': 'تخطٍّ',
  'td.deck.picks.one': 'أول أمسية: اختيار واحد.',
  'td.deck.picks.two': 'أول أمسية: اختياران.',
  'td.deck.picks.few': 'أول أمسية: {n} اختيارات.',
  'td.deck.picks.other': 'أول أمسية: {n} اختيارًا.',
  'td.deck.free': 'أمسية حرة إذن.',
  'td.deck.saved': 'حُفظت. نحجزها لحظة هبوطك ووصول الإشارة.',
  'td.deck.nothing': 'لا شيء محجوز. تقدر تسأل حين تصل.',
  'td.deck.again': 'ابدأ من جديد',
  'td.words.title': 'خمس كلمات لـ {city}',
  'td.words.body': 'للتاكسي والمقهى والأطفال.',
  'td.words.in': 'بـ{lang}',
  'td.words.english': 'بالإنجليزية',
  'td.words.say': 'تُنطق «{say}»',
  'td.words.tapFlip': 'اضغط للقلب',
  'td.words.tap': 'اضغط لتراها باللغة المحلية',
  'td.words.next': 'الكلمة التالية',
  'td.words.again': 'ابدأ من جديد',
  'td.land.title': 'حين تهبط',
  'td.land.passport': 'الجوازات، ثم الحقائب',
  'td.land.carousel': 'رقم سير الحقائب يظهر هنا عند هبوطك',
  'td.land.driver': '{driver} يستقبلك عند {door} وبيده اسمك',
  'td.land.noCar': 'لا سيارة محجوزة بعد. خياراتك في الأسفل.',
  'td.land.where': 'أين تقيم؟',
  'td.land.forDriver': 'العنوان للسائق',
  'td.land.gettingThere': 'الوصول',
  'td.arr.landed': 'هبطت {time} · {to}',
  'td.arr.sameTime': 'نفس توقيت الرياض',
  'td.arr.welcome': 'أهلًا بك في {city}.',
  'td.arr.weather': '{temp}° و{summary}.',
  'td.arr.booking.one': 'نحجز اختيارك لليلة',
  'td.arr.booking.two': 'نحجز اختياريك لليلة',
  'td.arr.booking.few': 'نحجز اختياراتك الـ {n} لليلة',
  'td.arr.booking.other': 'نحجز اختياراتك الـ {n} لليلة',
  'td.arr.bookingSub': 'التي اخترتها في الجو. التأكيد خلال 5 دقائق تقريبًا.',
  'td.arr.now': 'الآن',
  'td.arr.through': 'خرجت.',
  'td.arr.count': '{n} من {total}',
  'td.arr.phone': 'شغّل جوالك',
  'td.arr.phoneSub': 'واي فاي مجاني في المطار لمدة ساعة. فعّل التجوال فقط إن احتجته.',
  'td.arr.passport': 'الجوازات',
  'td.arr.passportMany': 'مسار الجوازات الأجنبية. ابقوا الـ {n} معًا.',
  'td.arr.passportOne': 'مسار الجوازات الأجنبية. حوالي 20 دقيقة.',
  'td.arr.kids': 'الأطفال يبقون معك.',
  'td.arr.bags': 'الحقائب على {carousel}',
  'td.arr.theCarousel': 'سير الحقائب',
  'td.arr.bagsSub': 'حوالي 20 دقيقة بعد الهبوط.',
  'td.arr.bagMissing': 'بلّغنا عن حقيبة مفقودة',
  'td.arr.bagRef': 'المرجع {ref}. {agent} يتابعها مع {airline}.',
  'td.arr.money': 'المال',
  'td.arr.moneySub': 'البطاقات تعمل في كل مكان تقريبًا. وللنقد القليل، {atm}.',
  'td.arr.moneyGeneric': 'البطاقات تعمل في كل مكان تقريبًا. وللنقد القليل، استخدم الصراف الآلي لا مكتب الصرافة.',
  'td.arr.driverAt': '{driver} عند {door}',
  'td.arr.toHotel': 'الوصول إلى الفندق',
  'td.arr.gettingThere': 'الوصول',
  'td.arr.sign': 'اللوحة تحمل اسم {name}. ينتظر {waits} مجانًا.',
  'td.arr.tellUs': 'قل لنا أين تقيم.',
  'td.arr.noCar': 'لا سيارة محجوزة. استقبال، أو تاكسي، أو المترو.',
  'td.arr.room': 'الغرفة جاهزة الساعة 14:00',
  'td.arr.rooms': 'الغرف جاهزة الساعة 14:00',
  'td.arr.roomSub': '{name}. الطريق {drive}.',
  'td.arr.toYours': 'إلى مكان إقامتك',
  'td.arr.noHotel': 'لا فندق محجوز. أخبرنا، ليعرف السائق ومادا.',
  'td.arr.hotelAddress': 'عنوان الفندق',
  'td.arr.theAddress': 'العنوان',
  'td.arr.gotBags': 'استلمت الحقائب',
  'td.arr.bagDidnt': 'حقيبة لم تصل',
  'td.arr.withDriver': 'مع السائق',
  'td.arr.atHotel': 'في الفندق',
  'td.arr.there': 'وصلت',
  'td.arr.done': 'تم',
  'td.arr.rest': 'ارتح أولًا. وحين تريد العشاء، اسألنا.',
  'td.arr.restPicks': 'ارتح أولًا. نحجز اختياراتك لليلة.',
  'td.arr.again': 'ابدأ القائمة من جديد',
  'td.bag.label': 'حقيبة مفقودة',
  'td.bag.title': 'قبل أن تغادر صالة الأمتعة',
  'td.bag.s1': 'توجّه إلى مكتب أمتعة {airline} بجانب {carousel}.',
  'td.bag.s2': 'اعرض ملصق حقيبتك (موجود على بطاقة الصعود في المحفظة).',
  'td.bag.s3': 'يعطونك مرجعًا مثل ISTSV12345. اكتبه في الأسفل.',
  'td.bag.ref': 'المرجع من المكتب',
  'td.bag.err': '5 حروف ثم 5 أرقام، مثل ISTSV12345.',
  'td.bag.chase': 'خلّ مادا تتابعها',
  'td.bag.toast': '{agent} يتابعها مع {airline}. احتفظ بإيصالات الضروريات، حتى 375 ر.س في اليوم.',
  'td.bag.foot': 'الحقائب تصل عادةً خلال 48 ساعة. وتدفع {airline} ثمن الضروريات أثناء الانتظار.',
  'as.whereTitle': 'لا فندق محجوز. أين تقيم؟',
  'as.driverNeeds': '{driver} يحتاج عنوانًا بعد المطار.',
  'as.soMada': 'لتعرف مادا أين تصل إليك.',
  'as.address': 'العنوان',
  'as.hotelInstead': 'تفضّل فندقًا؟ اطلب من مادا غرفًا لليلة.',
  'as.hotelAddress': 'عنوان الفندق',
  'as.theAddress': 'العنوان',
  'as.checkIn': 'تسجيل الدخول من 14:00',
  'as.with': 'مع {label}',
  'as.youGave': 'العنوان الذي أعطيتنا إياه',
  'as.fullScreen': 'اعرض العنوان بملء الشاشة',
  'as.tapFull': 'اضغط لتعرضه بملء الشاشة للسائق',
  'as.google': 'خرائط Google',
  'as.apple': 'خرائط Apple',
  'as.copy': 'انسخ',
  'as.copied': 'نُسخ العنوان.',
  'as.holdCopy': 'اضغط مطولًا على العنوان لتنسخه.',
  'as.callHotel': 'اتصل بالفندق',
  'as.cantOpen': 'لم يُفتح على هذا الجوال.',
  'as.meeting': '{driver} يستقبلك',
  'as.meetingBody': '{door}، صالة الوصول، بلوحة مكتوب عليها {sign}. {car}. ينتظر {waits} بعد هبوطك، مجانًا.',
  'as.call': 'اتصل بـ {driver}',
  'as.message': 'راسله',
  'as.noCar': 'لا سيارة محجوزة. ثلاث طرق للوصول',
  'as.opt.pickup': 'استقبال من مادا',
  'as.opt.pickupSub': '220 ر.س {all}· ينتظر السائق 60 د',
  'as.forAll': 'لكم كلكم',
  'as.opt.taxi': 'تاكسي من الموقف',
  'as.opt.taxiGeneric': 'من الموقف الرسمي خارج صالة الوصول. اطلب تشغيل العدّاد.',
  'as.opt.metro': 'المترو',
  'as.opt.metroGeneric': 'الأرخص، وصعب مع الحقائب الكبيرة.',
  'as.bookPickup': 'اطلب الاستقبال من مادا · 220 ر.س',
  'as.pickupAsked': 'وصل إلى مادا. تدفع حين يتأكد السائق.',
  'as.taxiTip': 'خذ التاكسي من الموقف فقط. إن رفض السائق تشغيل العدّاد، خذ الذي بعده. واعرض عليه العنوان في الأعلى.',
  'as.directions': 'الاتجاهات في خرائط Google',
  'as.offline': 'محفوظ على هذا الجوال. يعمل بلا إشارة.',
  'as.forDriver': 'العنوان للسائق',
  'as.takeMe': 'أرجو إيصالي إلى هنا',
  'as.tapClose': 'اضغط في أي مكان للإغلاق',
  'as.pickupTitle': 'استقبال من المطار عند الوصول',
  'as.pickupShort': 'الاستقبال',
  'as.pickupDetail': '{airport} · سائق في صالة الوصول يحمل اسمك',
  'as.pickupQuote': 'سائق في صالة الوصول يحمل اسمك، وينتظر 60 دقيقة. {price}.',
  'mv.both': 'فندقك والاستقبال',
  'mv.hotel': 'فندقك',
  'mv.pickup': 'الاستقبال',
  'mv.stillOn': '{what} ما زالا يوم {day}.',
  'mv.flightNow': 'رحلتك الآن يوم {day}.',
  'mv.moveThem': 'انقلهما إلى {day}',
  'mv.moveIt': 'انقله إلى {day}',
  'mv.titleBoth': 'ننقل الفندق والاستقبال إلى {day} أيضًا؟',
  'mv.titleHotel': 'ننقل الفندق إلى {day} أيضًا؟',
  'mv.titlePickup': 'ننقل الاستقبال إلى {day} أيضًا؟',
  'mv.flightIs': 'رحلتك الآن يوم {day} الساعة {time}.',
  'mv.checkIn': 'تسجيل الدخول {from} → {to} · {n} ليالٍ',
  'mv.atDoor': '{driver} عند بابك',
  'mv.noCost': 'بلا تكلفة',
  'mv.nothingBack': 'لا يُسترد شيء',
  'mv.keepsNight': 'بعد مهلة الإلغاء المجاني يحتفظ الفندق بثمن الليلة التي تلغيها.',
  'mv.extraNight': 'الفندق يحتاج أن يوافق على الليلة الإضافية. تدفع حين يوافق.',
  'mv.both.btn': 'انقلهما',
  'mv.it.btn': 'انقله',
  'mv.back': 'يُسترد {amount}',
  'mv.keep': 'أبقِهما كما هما',
  'mv.familyFriends': 'الأهل أو الأصدقاء',
  'mv.whereStaying': 'أين تقيم؟',
  'mv.addrPh': 'الشارع، الحي، المدينة',
  'mv.addrErr': 'أضف الشارع والحي.',
  'mv.saveAddr': 'احفظ العنوان',
  'mv.saved': 'حُفظ. العنوان لدى السائق.',
  'mv.findHotel': 'ابحث عن فندق',
  'mv.sameDates': 'لنفس التواريخ',
  'mv.withFamily': 'عند الأهل أو الأصدقاء',
  'mv.addAddr': 'أضف العنوان للسائق',
  'mv.later': 'قرّر لاحقًا',
  'td.home.title': 'حمدًا لله على السلامة.',
  'td.home.noLag': '{city} على توقيت الرياض، فلا إرهاق من فرق التوقيت. ارتح الليلة. لا شيء يحتاجك.',
  'td.home.rest': 'ارتح الليلة. لا شيء يحتاجك.',
  'td.home.oneWay': 'سافرت ذهابًا فقط، فلا رحلة عودة في هذه الرحلة. أخبر مادا إن أردت واحدة.',
  'td.home.stampA11y': 'ختم جديد في الجواز: {label} {day}',
  'td.home.night': 'ليلة واحدة في {city}',
  'td.home.nights': '{n} ليالٍ في {city}',
  'td.home.newStamp': 'ختم جديد: {country}.',
  'td.home.countries': '{n} دول الآن.',
  'td.home.first': 'رحلتك الأولى مع مادا.',
  'td.home.km': 'كم طرتها',
  'td.home.nightWord': 'ليلة',
  'td.home.nightsWord': 'ليالٍ',
  'td.home.traveller': 'مسافر',
  'td.home.ofYou': 'منكم',
  'td.home.whole': 'الرحلة كاملة',
  'td.home.noExtra': 'بلا رسوم إضافية',
  'td.home.flight': 'الرحلة',
  'td.home.flights': 'الرحلات',
  'td.home.stay': 'الإقامة',
  'td.home.pickups': 'الاستقبال',
  'td.home.refund': 'مبلغ مسترد في الطريق · {amount}',
  'td.home.refundAsked': 'طلبناه من {airline}',
  'td.home.refundApproved': 'تمت الموافقة. يُرسل إلى {card} بعدها.',
  'td.home.credit': '{amount} رصيد مادا',
  'td.home.creditSub': 'غير مستخدم. يُخصم من حجزك القادم تلقائيًا.',
  'td.home.receipts': 'الإيصالات في «الرحلات»',
  'td.home.planNext': 'خطّط للرحلة القادمة',
  'td.home.good.winter': 'مناسبة هذا الشتاء',
  'td.home.good.spring': 'مناسبة هذا الربيع',
  'td.home.good.summer': 'مناسبة هذا الصيف',
  'td.rate.how': 'كيف كانت',
  'td.rate.q.hotel': 'نفس الفندق المرة القادمة؟',
  'td.rate.q.driver': 'كيف كان السائقون؟',
  'td.rate.q.agent': 'و{agent}؟',
  'td.rate.agentWho': 'موظفك في هذه الرحلة',
  'td.rate.drivers': '{a} في الرياض، و{b} في {city}',
  'td.rate.yes': 'نعم، تذكّروه',
  'td.rate.no': 'ليس هذا',
  'td.rate.great': 'ممتاز',
  'td.rate.fine': 'لا بأس',
  'td.rate.poor': 'ليس جيدًا',
  'td.rate.hotelYes': 'حُفظ. نقترحه أولًا المرة القادمة.',
  'td.rate.hotelNo': 'فهمنا. لن نقترحه مرة أخرى.',
  'td.rate.anything': 'شيء يحتاج {agent} يعرفه؟',
  'td.rate.notePh': 'اختياري. الأطفال حبّوا العبّارة…',
  'td.rate.noteA11y': 'ملاحظة لـ {agent}',
  'td.rate.sent': 'وصل إلى مادا.',
  'td.rate.thanks': 'شكرًا لك. {agent} يقرأ كل ملاحظة.',
  'td.rate.noteWent': 'وصلت ملاحظتك معه.',
  'td.rate.change': 'غيّر إجاباتي',
  'td.mem.add': 'أضف 3 صور مفضلة',
  'td.mem.three': 'ثلاث صور تذكّرك بها.',
  'td.mem.go': 'تُضاف إلى بطاقة الرحلة، لتجدها لاحقًا.',
  'td.mem.goMany': 'تُضاف إلى بطاقة الرحلة، ليجدها {you}.',
  'td.mem.onTrip': 'صارت على بطاقة الرحلة.',
  'td.mem.onTripMany': 'صارت على الرحلة، لـ {you}.',
  'td.mem.added': 'أُضيفت إلى رحلة {city}.',
  'td.mem.cant': 'لم تُفتح هذه. جرّب صورة أخرى.',
  'td.mem.addOne': 'أضف صورة',
  'td.mem.remove': 'أزل الصورة {n}',
  'td.ideas.forUs': 'لنا الـ {n}',
  'td.ideas.forMe': 'لي',
  'td.ideas.alula': 'العُلا',
  'td.ideas.alulaWinter': 'ليالٍ باردة وأيام دافئة. على بعد ساعة و20 دقيقة.',
  'td.ideas.alulaSpring': 'آخر الأسابيع الباردة قبل الصيف.',
  'td.ideas.alulaAsk': 'يومان في العُلا',
  'td.ideas.alulaOct': 'العُلا في أكتوبر',
  'td.ideas.alulaOctNote': 'احجز الآن، الموسم يمتلئ بسرعة.',
  'td.ideas.season': 'موسم الرياض',
  'td.ideas.seasonNote': 'ويكند في البلد، على أصوله.',
  'td.ideas.seasonAsk': 'ويكند في موسم الرياض {us}',
  'td.ideas.snow': 'مكان فيه ثلج',
  'td.ideas.snowNote': 'غوداوري أو أرضروم، على بعد 4 ساعات.',
  'td.ideas.snowAsk': 'مكان فيه ثلج في يناير {us}',
  'td.ideas.abha': 'أبها',
  'td.ideas.abhaSpring': 'جبال خضراء، 20° في مايو.',
  'td.ideas.abhaSummer': 'اهرب من الحر، على بعد ساعة و40 دقيقة.',
  'td.ideas.abhaAsk': 'ويكند طويل في أبها',
  'td.ideas.riyadh': 'الرياض',
  'td.ideas.riyadhNote': 'إجازة في المدينة ما دام الجو معتدلًا.',
  'td.ideas.riyadhAsk': 'إجازة في الرياض',
  'td.ideas.baku': 'العودة إلى باكو',
  'td.ideas.bakuNote': 'أحببتها العيد الماضي. 24° في يوليو.',
  'td.ideas.bakuAsk': 'باكو مرة أخرى هذا الصيف {us}',
  'td.ideas.tbilisi': 'تبليسي',
  'td.ideas.tbilisiNote': '24° في يوليو. على بعد 3 ساعات ونصف.',
  'td.ideas.tbilisiAsk': 'تبليسي هذا الصيف {us}',
};
