/**
 * Arabic: Trip companion shared words, Trips, refunds, invoices, disruption, inbox (en-trips.ts).
 * A first draft in warm, plain Modern Standard Arabic for the native Saudi writer to transcreate (COPY.md §7.4).
 * Same keys as the English; Arabic's extra plural forms are `.two`, `.few` and `.zero`. The brand is مادا.
 * Generated once from the translation sheet; edit here from now on.
 */
import type { enTrips } from '../en-trips';
import type { ArSection } from './types';

export const arTrips: ArSection<typeof enTrips> = {
  'trip.and': 'و',
  'trip.ofYou.one': 'أنت',
  'trip.ofYou.two': 'أنتما الاثنان',
  'trip.ofYou.many': 'أنتم الـ {n}',
  'trip.oneWay': 'ذهاب فقط',
  'trip.yourDriver': 'سائقك',
  'trip.yourName': 'اسمك',
  'trip.theAirline': 'شركة الطيران',
  'trip.aRoom': 'غرفة',
  'trip.aRoomCap': 'الغرفة',
  'trip.connectingRooms': 'غرف متصلة',
  'trip.cabin.economy': 'السياحية',
  'trip.cabin.premium': 'السياحية المميزة',
  'trip.cabin.business': 'الأعمال',
  'trip.cabin.first': 'الأولى',
  'trip.with.airline': 'شركة الطيران',
  'trip.with.hotel': 'الفندق',
  'trip.with.faisal': 'مادا',
  'trip.legs.flight': 'الرحلة',
  'trip.legs.back': 'رحلة العودة',
  'trip.legs.both': 'الرحلتين',
  'trip.rule.flight.flown': 'تمت الرحلة.',
  'trip.rule.flights.flown': 'تمت الرحلتان.',
  'trip.rule.flight.nothingLeft': 'لم يبقَ شيء في التذاكر للاسترداد.',
  'trip.rule.airlineCancelled': 'ألغت {airline} هذه الرحلة.',
  'trip.rule.gaca': 'وفق أنظمة الهيئة العامة للطيران المدني يعود لك السعر كاملًا، مع الرسوم.',
  'trip.rule.refundable': 'سعر {airline}: استرداد بعد خصم {fee} ر.س للشخص.',
  'trip.rule.refundable.used': 'سعر {airline}: استرداد بعد خصم {fee} ر.س للشخص، عن رحلة العودة غير المستخدمة.',
  'trip.rule.refundable.why': 'الرسوم لـ {n}: {fee}. الاسترداد يشمل {legs}.',
  'trip.rule.refundable.usedWhy': 'سافرت ذهابًا. رحلة العودة لم تُستخدم، فيعود ذلك النصف بعد خصم الرسوم.',
  'trip.rule.taxesOnly': 'سعر {airline} هذا غير قابل للاسترداد. ضرائب المطار تُسترد: {tax} ر.س للشخص.',
  'trip.rule.taxesOnly.used': 'سعر {airline} هذا غير قابل للاسترداد. ضرائب المطار تُسترد: {tax} ر.س للشخص عن العودة.',
  'trip.rule.taxesOnly.why': 'شركة الطيران لا تدفع تلك الضرائب إن لم تسافر، فتعود لك. أما السعر نفسه فلا.',
  'trip.rule.stay.over': 'انتهت إقامتك.',
  'trip.rule.stay.overWhy': 'استُخدمت كل الليالي.',
  'trip.rule.freeCancelled': 'مجانًا، لأن الرحلة أُلغيت.',
  'trip.rule.stay.waived': 'يتنازل الفندق عن قاعدته حين تلغي شركة الطيران. أبلغناهم مسبقًا.',
  'trip.rule.stay.used': 'الليلة مستخدمة. ويحتفظ الفندق بليلة أخرى كرسوم.',
  'trip.rule.stay.usedWhy': '{nights} ليالٍ غير مستخدمة، ناقص ليلة واحدة ({night}).',
  'trip.rule.stay.free': 'الإلغاء مجاني حتى {day}.',
  'trip.rule.stay.freeWhy': 'يعود كل ريال.',
  'trip.rule.stay.late': 'بعد {day} يحتفظ الفندق بالليلة الأولى، {night}.',
  'trip.rule.stay.lateWhy': 'الليالي الأخرى تعود.',
  'trip.rule.pickup.bothDone': 'تمت الرحلتان بالسيارة.',
  'trip.rule.pickup.allDone': 'تمت المشاوير الأربعة.',
  'trip.rule.pickup.half': 'مشاوير الذهاب تمت. ومشاوير العودة لا.',
  'trip.rule.pickup.halfWhy': 'يعود النصف.',
  'trip.rule.pickup.inside24': 'خلال 24 ساعة، يُدفع للسائق كاملًا.',
  'trip.rule.pickup.inside24Why': '{driver} محجوز للصباح. لكن مادا تقدر تسأل.',
  'trip.rule.pickup.free': 'الإلغاء مجاني حتى 24 ساعة قبل الموعد.',
  'trip.rule.extra.free': 'الإلغاء مجاني حتى 48 ساعة قبل الموعد.',
  'trip.rule.extra.inside48': 'خلال 48 ساعة لا يمكن استرداده.',
  'trip.rule.extra.inside48Why': 'المكان يحجزه لك. لكن مادا تقدر تسأل.',
  'trip.rule.change': 'رسوم تغيير الرحلة تُدفع لشركة الطيران ولا تُسترد.',
  'trip.change.backOn': 'العودة يوم {day}.',
  'trip.change.oneWay': 'ذهاب فقط.',
  'trip.change.dayEarlier': 'قبلها بيوم.',
  'trip.change.dayLater': 'بعدها بيوم.',
  'trip.change.noSeats': 'لا يوجد {n} مقاعد متبقية على هذه الرحلة.',
  'trip.change.flyOn': 'تسافر يوم {day}',
  'trip.change.onFlight': 'رحلتك {code} الساعة {time}',
  'trip.change.early': 'الأبكر، والأقل سعرًا. تصل في وقت الغداء.',
  'trip.change.evening': 'مسائية. صباح هادئ في البيت.',
  'trip.change.homeOn': 'تعود يوم {day}',
  'trip.change.homeAt': 'تعود الساعة {time} بدلًا من ذلك',
  'trip.change.sooner': 'أبكر بيوم. ويحتفظ الفندق بليلة كرسوم.',
  'trip.change.longer': 'أطول بيوم. أضف ليلة في الفندق أيضًا.',
  'trip.change.later': 'نفس اليوم، لاحقًا. تهبط 01:50.',
  'trip.change.oneSooner': 'أبكر بيوم.',
  'trip.change.twoSooner': 'أبكر بيومين.',
  'rq.queued': 'بانتظار الاتصال',
  'rq.sent': 'وصل إلى مادا',
  'rq.onIt': '{agent} يتولاه',
  'rq.asking': '{agent} يسأل {who}',
  'rq.needsAnswer': 'لدى مادا سؤال',
  'rq.priceReady': 'السعر جاهز',
  'rq.confirmedBy': 'أكّده {who}',
  'rq.done': 'تم',
  'rq.cant': 'غير ممكن',
  'rq.cancelled': 'ملغى',
  'sr.everyone': 'الجميع',
  'sr.bothFlights': 'الرحلتان',
  'sr.theFlight': 'الرحلة',
  'sr.hotel': 'الفندق',
  'sr.noFlights': 'لا رحلات طيران في هذه الرحلة، فلا شيء نطلبه من {airline}.',
  'sr.wheelchair.title.gate': 'كرسي متحرك حتى البوابة',
  'sr.wheelchair.title.seat': 'كرسي متحرك حتى المقعد',
  'sr.wheelchair.title.own': 'كرسي متحرك (خاص)',
  'sr.wheelchair.short': 'كرسي متحرك · {who}',
  'sr.meal.child': 'وجبة أطفال',
  'sr.meal.veg': 'وجبة نباتية',
  'sr.meal.diabetic': 'وجبة لمرضى السكري',
  'sr.meal.gluten': 'وجبة خالية من الغلوتين',
  'sr.meal.childOnly': 'وجبات الأطفال للأطفال دون 12 فقط.',
  'sr.bassinet.none': 'سرير الأطفال للرضّع دون السنتين وأقل من 11 كجم. لا أحد في هذه الرحلة بهذا العمر.',
  'sr.bassinet.title': 'مقعد بسرير أطفال',
  'sr.bassinet.short': 'سرير أطفال',
  'sr.bassinet.alt': 'صف سرير الأطفال محجوز في الذهاب. نقلكم فيصل إلى الصف 14 مع مقعد فارغ بجانبكم بدلًا منه.',
  'sr.seats.keep': 'مقاعد متجاورة',
  'sr.seats.keepBoth': 'مقاعد متجاورة، ذهابًا وعودة',
  'sr.seats.kids': 'الأطفال بجانب أحد الوالدين',
  'sr.seats.short': 'مقاعد متجاورة',
  'sr.seats.alt': 'طيران ناس لا يضمن المقاعد المتجاورة إلا باختيار مقاعد مدفوع، 35 ر.س للمقعد. تقدر مادا تضيفه.',
  'sr.celebration.birthday': 'عيد ميلاد',
  'sr.celebration.anniversary': 'ذكرى زواج',
  'sr.celebration.else': 'شيء آخر',
  'sr.celebration.note': 'رسالة للفندق',
  'sr.prayer.title': 'سجادات صلاة واتجاه القبلة في الغرفة',
  'sr.prayer.short': 'سجادات صلاة',
  'sr.bags.title.one': 'حقيبة إضافية واحدة',
  'sr.bags.title.two': 'حقيبتان إضافيتان',
  'sr.bags.title.few': '{count} حقائب إضافية',
  'sr.bags.title.other': '{count} حقيبة إضافية',
  'sr.bags.bothWays': 'ذهابًا وعودة',
  'sr.bags.short': 'حقائب إضافية',
  'sr.bags.quote.one': 'أضافت {airline} حقيبة إضافية واحدة بوزن {kg} كجم{both}. {price}.',
  'sr.bags.quote.two': 'أضافت {airline} حقيبتين إضافيتين بوزن {kg} كجم{both}. {price}.',
  'sr.bags.quote.few': 'أضافت {airline} {count} حقائب إضافية بوزن {kg} كجم{both}. {price}.',
  'sr.bags.quote.other': 'أضافت {airline} {count} حقيبة إضافية بوزن {kg} كجم{both}. {price}.',
  'sr.sports.golf': 'مضارب غولف',
  'sr.sports.bike': 'دراجة',
  'sr.sports.ski': 'زلاجات',
  'sr.sports.short.golf': 'مضارب غولف',
  'sr.sports.short.bike': 'صندوق دراجة',
  'sr.sports.short.ski': 'زلاجات',
  'sr.sports.alt': 'صندوق الدراجة أطول من عنبر {airline} في هذه الطائرة. تقدر مادا ترسلها شحنًا جويًا بـ 410 ر.س، وتصل قبلك بيوم.',
  'sr.pet.no': 'الحيوانات الأليفة لا تسافر معك على {airline}، لا في المقصورة ولا في العنبر، ولا تستطيع مادا حجز سفر الحيوانات.',
  'ho.none': 'لا فندق في هذه الرحلة.',
  'ho.pickRoom': 'اختر غرفة',
  'ho.room.family': 'جناح عائلي',
  'ho.room.view': 'غرف بإطلالة على البوسفور',
  'ho.room.two': 'غرفتان عاديتان',
  'ho.room.familySub': 'غرفة كبيرة واحدة، بحمّامين',
  'ho.room.viewSub': 'غرفتان متجاورتان، الطابق السابع',
  'ho.room.twoSub': 'غير متصلتين، في نفس الطابق',
  'ho.instead': '{title} بدلًا منها',
  'ho.nightsAt': '{name} · {nights} ليالٍ',
  'ho.room.quote': 'لدى الفندق {room} لكل الليالي الـ {nights}. زيادة {price}. ادفع ونبدّلها.',
  'ho.backOnce': 'يعود {amount} بعد التأكيد',
  'ho.refundOnWay': '{amount} مسترد في الطريق',
  'ho.nights.addTitle': 'ليلة إضافية، حتى {day}',
  'ho.nights.quote': 'يقدر الفندق يُبقي غرفكم ليلة إضافية، حتى {day}. نفس الغرف، {price}.',
  'ho.nights.cutHere': 'تقصير الإقامة يتم من «خيارات الفندق».',
  'ho.short.room': 'تغيير الغرفة',
  'ho.short.night': 'ليلة إضافية',
  'ho.short.early': 'دخول مبكر',
  'ho.short.late': 'مغادرة متأخرة {time}',
  'ho.short.bed': 'سرير إضافي',
  'ho.times.earlyFree': 'دخول مبكر، إن كانت الغرفة جاهزة',
  'ho.times.earlyPaid': 'دخول مبكر الساعة 10:00، مضمون',
  'ho.times.lateFree': 'مغادرة متأخرة حتى 14:00',
  'ho.times.latePaid': 'مغادرة متأخرة حتى 18:00',
  'ho.times.earlyNo': 'الغرف ممتلئة الليلة السابقة. اترك حقائبك في الاستقبال، وفي الفندق صالة عائلية فيها مصلى.',
  'ho.times.quote': 'الفندق وافق: {what}. {price}.',
  'ho.bed.cot': 'سرير أطفال',
  'ho.bed.cotShort': 'سرير أطفال في الغرفة',
  'ho.bed.extra': 'سرير إضافي',
  'ho.bed.noBaby': 'للرضّع دون السنتين. لا أحد في هذه الرحلة بهذا العمر.',
  'ho.bed.quote': 'يجهّز الفندق سريرًا إضافيًا في الغرفة الثانية. {price} لـ {nights} ليالٍ.',
  'ho.connecting': 'غرف متصلة',
  'cf.callTitle': 'اتصلوا بي بخصوص تغيير رحلة',
  'cf.callShort': 'اتصال بخصوص تغيير',
  'cf.callDetail': '{code} · باقي أقل من يوم',
  'cf.callYes': 'مادا تتصل بك',
  'cf.widerTitle': 'ابحث عن رحلة أخرى',
  'cf.widerShort': 'بحث أوسع',
  'cf.widerDetail': '{code} · أي يوم قريب من {day}',
  'cf.widerYes': 'أرسلنا خيارين إلى محادثتك',
  'itin.pickupHome': '{driver} يستقبلك من البيت',
  'itin.flight': '{from} → {to} · {code}',
  'itin.flightSub': '{airline} · {from} {terminal} · تهبط {arr} في {to}',
  'itin.flightBackSub': '{airline} · تهبط {arr} في {to}',
  'itin.fact.seats': 'المقاعد',
  'itin.fact.bags': 'الحقائب',
  'itin.fact.bagsEach': '{bags} لكل مسافر',
  'itin.fact.boarding': 'الصعود',
  'itin.meets': '{driver} يستقبلك عند {door}',
  'itin.meetsSub': '{airport} · لوحة باسمك · {drive} إلى {place}',
  'itin.meetsSubNoStay': '{airport} · لوحة باسمك · أخبرنا أين تقيم',
  'itin.theHotel': 'الفندق',
  'itin.yourPlace': 'مكان إقامتك',
  'itin.noStay': 'لا فندق محجوز. أين تقيم؟',
  'itin.noStaySub': 'أخبرنا، ليعرف السائق ومادا أين أنت.',
  'itin.own': 'الإقامة عند {label}',
  'itin.checkIn': 'تسجيل الدخول · {name}',
  'itin.checkInSub': '{room} · {nights} ليالٍ',
  'itin.earlyCheckIn': '· دخول مبكر',
  'itin.checkOut': 'المغادرة',
  'itin.checkOutSub': 'اترك الحقائب في الاستقبال إن أردت التجول',
  'itin.lateCheckout': 'مغادرة متأخرة، مؤكدة',
  'itin.toAirport': '{driver} يوصلك إلى المطار',
  'itin.toAirportSub': 'من {place} · {drive}',
  'itin.aboutHour': 'حوالي ساعة',
  'itin.drivesHome': '{driver} يوصلك إلى البيت',
  'itin.drivesHomeSub': 'يستقبلك في صالة الوصول، البوابة 2',
  'itin.pickPending': 'نحجزه حين تهبط',
  'itin.heldPay': 'محجوز مؤقتًا · ادفع للتأكيد',
  'itin.celebrationSub': 'الفندق على علم. لمسة بسيطة في الغرفة.',
  'itin.kidsFish': 'الأطفال يحبون الأسماك.',
  'itin.packTonight': 'جهّز الشنط الليلة',
  'itin.packTonightPickup': '{driver} يستقبلك الساعة {time} غدًا.',
  'itin.packTonightCheckout': 'المغادرة الساعة 12:00 غدًا.',
  'itin.day.fly': 'تسافر إلى {city}',
  'itin.day.home': 'العودة',
  'itin.day.free': 'يوم حر',
  'itin.day.in': 'في {city}',
  'itin.docs.passport.one': 'جوازك',
  'itin.docs.passport.two': 'جوازا السفر للاثنين',
  'itin.docs.passport.few': 'جوازات الـ {n} كلهم',
  'itin.docs.passport.other': 'جوازات الـ {n} كلهم',
  'itin.docs.passes': 'بطاقات الصعود، في محفظتك',
  'itin.docs.hotel': 'حجز الفندق، يُعرض عند تسجيل الدخول',
  'itin.docs.copies': 'نسخ الجوازات في محفظتك. والأصول تبقى في خزنة الغرفة.',
  'itin.warn.pickupOld': 'ما زال محجوزًا يوم {day}. ورحلتك {flight}.',
  'itin.warn.noStay': 'لا فندق محجوز. أين تقيم؟',
  'itin.warn.emptyNight': 'تهبط يوم {day}. هذه الليلة مدفوعة لكنها فارغة.',
  'itin.warn.noRoom.one': 'رحلة عودتك يوم {day}. لا غرفة لليلة الأخيرة.',
  'itin.warn.noRoom.two': 'رحلة عودتك يوم {day}. لا غرفة لليلتين الأخيرتين.',
  'itin.warn.noRoom.few': 'رحلة عودتك يوم {day}. لا غرفة لآخر {count} ليالٍ.',
  'itin.warn.noRoom.other': 'رحلة عودتك يوم {day}. لا غرفة لآخر {count} ليلة.',
  'itin.share.head': '{city}، {dates}. الخطة، من مادا للرحلات.',
  'itin.share.hotel': 'الإقامة في {name}، {address}',
  'itin.share.foot': 'الأوقات محلية.',
  'inv.kind.simplified': 'فاتورة ضريبية مبسطة',
  'inv.kind.tax': 'فاتورة ضريبية',
  'inv.kind.credit_note': 'إشعار دائن',
  'inv.kindAr.simplified': 'فاتورة ضريبية مبسطة',
  'inv.kindAr.tax': 'فاتورة ضريبية',
  'inv.kindAr.credit_note': 'إشعار دائن',
  'inv.draft': 'مسودة',
  'inv.vatNo': 'الرقم الضريبي',
  'inv.no': 'رقم الفاتورة',
  'inv.cnNo': 'رقم الإشعار الدائن',
  'inv.against': 'مقابل الفاتورة',
  'inv.buyer': 'المشتري:',
  'inv.customer': 'العميل:',
  'inv.traveller': 'المسافر:',
  'inv.paidWith': 'طريقة الدفع',
  'inv.col.item': 'البند',
  'inv.col.rate': 'نسبة الضريبة',
  'inv.col.net': 'الصافي',
  'inv.col.vat': 'الضريبة',
  'inv.col.total': 'الإجمالي',
  'inv.beforeVat': 'الإجمالي قبل الضريبة',
  'inv.vat15': 'ضريبة القيمة المضافة 15%',
  'inv.total': 'الإجمالي',
  'inv.foot': 'الأسعار شاملة الضريبة. الرحلات الدولية خاضعة لنسبة صفر.',
  'inv.line.tickets': 'تذاكر طيران {from}–{to} {ways}، {cabin}{n} × {each}',
  'inv.return': 'ذهاب وعودة',
  'inv.oneWay': 'ذهاب فقط',
  'inv.zeroRated': 'نقل دولي، نسبة صفر',
  'inv.line.fee': 'رسوم خدمة مادا',
  'inv.line.discount': 'خصم',
  'inv.discountNote': 'مخصوم من السعر',
  'inv.line.room': '{room}، {nights} ليالٍ × {each}',
  'inv.line.transfer.one': 'توصيل خاص، مشوار واحد',
  'inv.line.transfer.two': 'توصيل خاص، مشواران',
  'inv.line.transfer.few': 'توصيل خاص، {count} مشاوير',
  'inv.line.transfer.other': 'توصيل خاص، {count} مشوارًا',
  'inv.changeNote': 'فرق السعر ورسوم التغيير',
  'inv.reissueTitle': 'أعد إصدار الفاتورة الضريبية',
  'inv.reissueShort': 'أُعيد إصدار الفاتورة',
  'inv.reissueYes': 'فاتورة ضريبية جديدة في المدفوعات',
  'dz.opt.direct': '{airline} {code} · مباشرة',
  'dz.opt.tomorrow': '{airline} {code} · غدًا',
  'dz.opt.times': 'تقلع {dep} · تهبط {arr} في {airport}',
  'dz.opt.stay': 'ابقَ على {code}',
  'dz.opt.stayTimes': 'يُرجّح إقلاعها {dep} · تهبط {arr}',
  'dz.opt.refund': 'استرد المبلغ بدلًا من ذلك',
  'dz.opt.home': 'ارجع إلى البيت واسترد المبلغ',
  'dz.opt.refundTimes': 'يعود {amount} إلى بطاقتك',
  'dz.opt.refundNote': 'وتُلغى الإقامة والاستقبال مجانًا أيضًا.',
  'dz.opt.homeNote': 'وتُلغى الإقامة والاستقبال مجانًا أيضًا. وتدفع شركة الطيران التاكسي إلى البيت.',
  'dz.opt.morningNote': 'أول رحلة تقلع. نفس المقاعد متجاورة. وفندق قرب المطار الليلة، على حساب شركة الطيران.',
  'dz.opt.xyNightNote': 'نوم أطول. نفس الفندق الليلة. والاستقبال ينتقل معك.',
  'dz.opt.nextNote': 'نفس المقاعد متجاورة. بلا تكلفة إضافية.',
  'dz.opt.xyEarlierNote': 'أبكر. بلا تكلفة إضافية عليك. والاستقبال ينتقل معك.',
  'dz.opt.xyNote': 'بلا تكلفة إضافية عليك. والاستقبال ينتقل معك.',
  'dz.opt.stayNote': 'نفس المقاعد، نفس المطار. تهبط بعد 3 ساعات من الموعد.',
  'td.pp.blocking': 'جواز {name} ينتهي في {date}. تطلب {country} صلاحية {days} يومًا بعد الوصول، فيجب أن يكون ساريًا حتى {need}.',
  'td.pp.fine': 'يصلح لـ {city}: تطلب {country} صلاحية {days} يومًا بعد الوصول، ولدى {name} {left}.',
  'td.esim.title': 'شريحة eSIM لـ {country}',
  'td.esim.short.one': 'شريحة eSIM لشخص',
  'td.esim.short': 'شرائح eSIM لـ {count}',
  'td.esim.detail': '10 جيجابايت لكل شخص لمدة 7 أيام',
  'td.esim.quote': 'شرائح eSIM لـ {count}، 10 جيجابايت لكل شخص لمدة 7 أيام. {price}. تُثبّت قبل سفرك.',
  'dz.you': 'أنت',
  'dz.allOf': 'لكم الـ {n} كلكم',
  'dz.delay.headline': 'يُرجّح أن تتأخر {code} 3 ساعات.',
  'dz.delay.sub': 'الطائرة القادمة من القاهرة هبطت متأخرة. لم تعلن {airline} بعد. نحجز مقاعد لـ {everyone} على رحلة أبكر.',
  'dz.delay.source': 'توقّع من الطائرة القادمة الساعة 08:02',
  'dz.cancel.headline': 'ألغت {airline} رحلة {code}.',
  'dz.cancel.sub': 'يحق لك استرداد كامل. ونحجز مقاعد لـ {everyone} على رحلتين أخريين اليوم.',
  'dz.cancel.source': 'أكّدت {airline} الإلغاء الساعة 06:12',
  'dz.night.headline': 'ألغت {airline} رحلة {code} الساعة 23:40.',
  'dz.night.sub': 'لا تحتاج ترتّب الليلة بنفسك. حجزنا غرفة قرب المطار ومقاعد لـ {everyone} على أول رحلة غدًا.',
  'dz.night.source': 'أكّدت {airline} الإلغاء الساعة 23:40',
  'dz.night.hotel': 'فندق قرب المطار الليلة',
  'dz.night.hotelBody': 'على حساب شركة الطيران. القسيمة تصل إلى محفظتك. حافلة من البوابة 4 كل 20 دقيقة.',
  'dz.night.meals': 'قسائم الوجبات',
  'dz.night.mealsBody': '75 ر.س لكل واحد لـ {everyone}، في أي مقهى في الصالة أو في الفندق.',
  'dz.night.next': 'الرحلة التالية {time}',
  'dz.night.nextBody': '{airline} {code}، مقاعد متجاورة محجوزة. أو اختر غيرها في الأسفل.',
  'dz.agent.day': '{agent} من مادا معك في هذا.',
  'dz.agent.night': '{agent} من الفريق الليلي معك في هذا.',
  'dz.refundTitle': 'أُلغيت {code} · الرحلات والإقامة والاستقبال',
  'dz.done.refund': 'المبلغ المسترد في الطريق: {amount}.',
  'dz.done.refundBody': 'عادةً من 7 إلى 14 يومًا حتى يعود إلى {card}. تابعه في الرحلات ← الطلبات.',
  'dz.done.refundBodyNight': 'عادةً من 7 إلى 14 يومًا حتى يعود إلى {card}. تابعه في الرحلات ← الطلبات. تدفع {airline} التاكسي إلى البيت: احتفظ بالإيصال.',
  'dz.done.refundLine': '«طلبت الاسترداد من {airline} وألغيت الباقي. أخبرك حين يُرسل.»',
  'dz.done.stay': 'تم. تبقى على {code}.',
  'dz.done.stayBody': 'نواصل مراقبة الطائرة. إن تأخرت أكثر، يكون لدينا بديل جاهز قبل أن تعلن {airline}.',
  'dz.done.rebook.one': 'تم. حجزك الآن على {flight}.',
  'dz.done.rebook.two': 'تم. أنتما الاثنان على {flight}.',
  'dz.done.rebook.few': 'تم. أنتم الـ {n} كلكم على {flight}.',
  'dz.done.rebook.other': 'تم. أنتم الـ {n} كلكم على {flight}.',
  'dz.done.rebookBody': '{driver} يستقبلك الآن الساعة {time}. والاستقبال في الطرف الآخر ينتقل أيضًا. بطاقات الصعود الجديدة في محفظتك.',
  'dz.done.rebookBodyNoCar': 'بطاقات الصعود الجديدة في محفظتك.',
  'dz.done.nightBody': 'غرفتك محجوزة في فندق المطار، 8 دقائق بالحافلة من البوابة 4. قسائم الفندق والوجبات في محفظتك. نراسلك الساعة {time} لتستيقظ.',
  'dz.done.line': '«نقلت كل شيء. رحلة سعيدة.»',
  'dz.done.nightLine': '«نقلت تذاكركم وحجزت الغرفة. ارتاحوا شوي.»',
  'dz.voucher.hotel': 'فندق الليلة · فندق المطار',
  'dz.voucher.hotelBody': 'على حساب {airline}. حافلة من البوابة 4 كل 20 دقيقة.',
  'dz.voucher.meal': 'قسائم وجبات · 75 ر.س × {n}',
  'dz.voucher.mealBody': 'أي مقهى في الصالة أو في الفندق. صالحة حتى 10:00.',
  'notify.trip.price.title': 'سعر من مادا',
  'notify.trip.price.body': '{what}: {amount}. ادفع في «الرحلات» للتأكيد.',
  'notify.trip.credit.title': 'المبلغ المسترد في رصيد مادا',
  'notify.trip.credit.body': '{amount} جاهز للاستخدام الآن، في أي حجز.',
  'notify.trip.rebooked.title': 'حُجزت رحلتك الجديدة',
  'notify.trip.rebooked.body': '{agent}: حجزك على {what} الساعة {time}. والاستقبال انتقل أيضًا.',
  'notify.trip.cancelled.title': 'أُلغيت {flight}',
  'notify.trip.cancelled.body': 'نحجز مقاعد على رحلات أخرى. اضغط لتختار.',
  'notify.trip.delayed.title': '{flight} متأخرة',
  'notify.trip.delayed.body': 'متأخرة حوالي {minutes} دقيقة. نحجز لك خيارًا أبكر.',
};
