/**
 * Arabic: Trip management screens, part two (en-trips-ui2.ts).
 * A first draft in warm, plain Modern Standard Arabic for the native Saudi writer to transcreate (COPY.md §7.4).
 * Same keys as the English; Arabic's extra plural forms are `.two`, `.few` and `.zero`. The brand is مادا.
 * Generated once from the translation sheet; edit here from now on.
 */
import type { enTripsUi2 } from '../en-trips-ui2';
import type { ArSection } from './types';

export const arTripsUi2: ArSection<typeof enTripsUi2> = {
  'ho.title': 'خيارات الفندق',
  'ho.cancelled': 'أُلغيت الإقامة.',
  'ho.ownPlace': 'إقامتك في {address}.',
  'ho.sameDates': 'غرف قرب وسط المدينة، لنفس التواريخ؟',
  'ho.free': 'التغيير مجاني حتى {day}.',
  'ho.r.room': 'غيّر الغرفة',
  'ho.r.roomSub': 'جناح، أو إطلالة، أو غرفتان',
  'ho.r.nights': 'أضف ليالي أو أنقصها',
  'ho.r.nightsSub': 'الآن {n} ليالٍ، والمغادرة يوم {day}',
  'ho.r.times': 'تسجيل الدخول والمغادرة',
  'ho.r.timesSub': 'دخول مبكر، مغادرة متأخرة',
  'ho.r.bed': 'سرير أطفال أو سرير إضافي',
  'ho.r.bedSub': 'لرضيع، أو لشخص إضافي',
  'ho.r.inBooking': 'ضمن حجزك',
  'ho.r.askHotel': 'اسأل الفندق',
  'ho.r.switch': 'فندق آخر',
  'ho.r.switchSub': 'تجد مادا واحدًا لنفس التواريخ',
  'ho.switchAsk': 'فندق آخر في {city}، {dates}',
  'ho.aNight': 'الليلة',
  'ho.room.more': '{amount} زيادة لـ {n} ليالٍ. تدفع حين يوافق الفندق.',
  'ho.room.less': 'يعود {amount} إلى بطاقتك حين يؤكد الفندق.',
  'ho.askPrice': 'اسأل الفندق · +{amount} ر.س',
  'ho.ask': 'اسأل الفندق',
  'ho.pickOne': 'اختر واحدًا',
  'ho.n.until': 'أقم حتى {day}',
  'ho.n.oneMore': 'ليلة إضافية · {amount}',
  'ho.n.leave': 'غادر يوم {day}',
  'ho.n.lessFree': 'ليلة أقل · التقصير مجاني حتى {day}',
  'ho.n.lessKept': 'بعد {day} يحتفظ الفندق بثمن الليلة التي تلغيها',
  'ho.n.flightStill': 'رحلة عودتك ما زالت يوم {day}. غيّرها من «غيّر الرحلة».',
  'ho.n.needPlace': 'رحلة عودتك يوم {day}، فستحتاج مكانًا لتلك الليلة.',
  'ho.n.cutBtn': 'غادر قبلها بليلة',
  'ho.t.earlyFreeSub': 'مجانًا. الفندق يقرر صباح اليوم نفسه.',
  'ho.t.lateFreeSub': 'مجانًا، إن توفرت مساحة لدى الفندق',
  'ho.t.half': 'نصف ليلة، {amount}',
  'ho.t.free': 'مجانًا',
  'ho.t.intro': 'تهبط الساعة {arr} وتصل الفندق حوالي {reach}.',
  'ho.t.mayNot': 'تسجيل الدخول الساعة 14:00، فقد لا تحتاجه.',
  'ho.t.foot': 'حسب توفر الغرف لدى الفندق. لا تدفع إلا إن وافقوا.',
  'ho.b.cotSub': 'مجانًا، يُجهّز قبل وصولك',
  'ho.b.bedSub': '150 ر.س لليلة · {n} ليالٍ',
  'ho.c.has': 'موجود في حجزك. أكّد الفندق غرفتين متصلتين.',
  'ho.c.not': 'غرفكم ليست متصلة الآن. يقدر الفندق يحاول، والأمر يعتمد على من يغادر قبلكم.',
  'ho.c.good': 'ممتاز',
  'sr.title': 'طلبات خاصة',
  'sr.anything': 'تحتاج شيئًا؟',
  'sr.intro': 'تطلب مادا من {airline} والفندق نيابة عنك، وتتابع تقدّم كل طلب.',
  'sr.everyoneCap': 'الجميع',
  'sr.emptyTitle': 'لا رحلة للطلب لها.',
  'sr.emptyBody': 'الطلبات الخاصة تُفتح بعد حجز رحلة.',
  'sr.t.wheelchair': 'كرسي متحرك',
  'sr.t.meal': 'وجبة خاصة',
  'sr.t.bassinet': 'سرير أطفال',
  'sr.t.seats': 'مقاعد متجاورة',
  'sr.t.celebration': 'مناسبة',
  'sr.t.prayer': 'سجادة صلاة واتجاه القبلة في الغرفة',
  'sr.t.bags': 'حقائب إضافية',
  'sr.t.sports': 'معدات رياضية',
  'sr.t.pet': 'السفر مع حيوان أليف',
  'sr.s.wheelchair': 'حتى البوابة، أو حتى المقعد',
  'sr.s.meal': 'حلال في كل رحلة. للأطفال، ونباتية، ولمرضى السكري.',
  'sr.s.bassinet': 'لرضيع دون السنتين',
  'sr.s.seats': 'العائلة جنبًا إلى جنب',
  'sr.s.celebration': 'عيد ميلاد أو ذكرى زواج، مع رسالة للفندق',
  'sr.s.prayer': 'مع أوقات الصلاة في المدينة',
  'sr.s.bags': 'أرخص الآن منها في المطار',
  'sr.s.sports': 'غولف، دراجات، تزلج',
  'sr.s.pet': 'ما المسموح',
  'sr.asked': 'طلبات حتى الآن',
  'sr.else': 'شيء آخر؟ تحدّث مع مادا',
  'sr.close': 'أغلق',
  'sr.queued': 'محفوظ على هذا الجوال. يُرسل حين يعود اتصالك.',
  'sr.sentToast': 'وصل إلى مادا. تابعه في «الرحلات»، ضمن الطلبات.',
  'sr.bags.toast': 'وصل إلى مادا. السعر في «الرحلات»، ضمن الطلبات.',
  'sr.w.intro': 'لـ {who}. تستقبلك {airline} عند مكتب تسجيل السفر وترافقك.',
  'sr.w.gate': 'حتى البوابة',
  'sr.w.gateSub': 'تقدر تمشي حتى المقعد',
  'sr.w.seat': 'حتى المقعد',
  'sr.w.seatSub': 'مساعدة في صعود الدرج وحتى المقعد',
  'sr.w.own': 'كرسي متحرك خاص',
  'sr.w.ownSub': 'يُشحن مجانًا في عنبر الطائرة',
  'sr.m.intro': 'كل الوجبات على {airline} حلال. وجبة خاصة لـ {who}:',
  'sr.m.for': 'لـ {names}',
  'sr.m.vegSub': 'بلا لحوم ولا أسماك',
  'sr.m.diabeticSub': 'قليلة السكر، بكربوهيدرات محسوبة',
  'sr.m.glutenSub': 'بلا قمح ولا شعير ولا جاودار',
  'sr.m.childSub': 'للأطفال دون 12',
  'sr.m.foot': 'مجانًا. تُطلب قبل الرحلة بـ 24 ساعة.',
  'sr.b.intro': 'سرير الأطفال يُثبّت على الجدار أمام الصف الأول. للرضّع أقل من 11 كجم. مجاني، لكن عدده قليل في كل طائرة.',
  'sr.b.addBaby': 'مسافر مع رضيع في النهاية؟ أضفه في المحفظة أولًا، ثم ارجع.',
  'sr.se.intro': 'مقاعدك الآن {out}.',
  'sr.se.introBack': 'مقاعدك الآن {out}، و{back} في العودة.',
  'sr.se.side': 'جنبًا إلى جنب',
  'sr.se.keep': 'مقاعد متجاورة',
  'sr.se.keepSub': 'الجميع في صف واحد، أو صفين متتاليين',
  'sr.se.kids': 'الأطفال بجانب أحد الوالدين',
  'sr.se.kidsSub': 'بالغ واحد على الأقل بجانب كل طفل',
  'sr.c.intro': 'يجهّز الفندق لمسة بسيطة في الغرفة. والتفاصيل يقررها هو.',
  'sr.c.note': 'رسالة للفندق (اختيارية)',
  'sr.c.notePh': 'لمن، وبأي مناسبة',
  'sr.c.notePhOne': '{name} يكمل …',
  'sr.p.times': 'أوقات الصلاة في {city}: {times}.',
  'sr.p.qibla': 'يحدد الفندق اتجاه القبلة في الغرفة.',
  'sr.bg.intro': 'سعرك يشمل {bags}. كل حقيبة إضافية على {airline} حتى {kg} كجم، بـ {fee} لكل اتجاه.',
  'sr.bg.fewer': 'حقيبة أقل',
  'sr.bg.more': 'حقيبة إضافية',
  'sr.bg.total': 'حقائب إضافية',
  'sr.bg.for': 'حقائب إضافية لـ {who}',
  'sr.bg.twoFlights': 'رحلتان',
  'sr.bg.ask': 'اطلبها · {amount}',
  'sr.sp.intro': 'الحقائب الرياضية تُحسب حقيبة واحدة حتى {kg} كجم. تتحقق مادا من الحجم مع شركة الطيران.',
  'sr.sp.golf': 'مضارب غولف',
  'sr.sp.golfSub': 'عادةً من 15 إلى 20 كجم',
  'sr.sp.bike': 'دراجة في صندوق',
  'sr.sp.bikeSub': 'عادةً من 25 إلى 32 كجم',
  'sr.sp.ski': 'زلاجات أو لوح تزلج',
  'sr.sp.skiSub': 'عادةً من 8 إلى 12 كجم',
  'sr.pet.guide': 'كلاب الإرشاد والمساعدة استثناء. تسافر مجانًا في المقصورة بالأوراق المطلوبة. أخبر مادا ونرتّبها.',
  'itin.title': 'البرنامج',
  'itin.heading': '{city}، يومًا بيوم',
  'itin.offTitle': 'البرنامج ليس على هذا الجوال بعد.',
  'itin.offBody': 'افتحه مرة واحدة مع وجود إشارة ويبقى هنا طوال الرحلة.',
  'itin.retry': 'حاول مرة أخرى',
  'itin.eyebrow': '{dates} · {n} أيام',
  'itin.saved': 'محفوظ على هذا الجوال. يعمل بلا إشارة.',
  'itin.lastUpdated': 'دون اتصال · آخر تحديث الساعة {time}',
  'itin.addCal': 'أضف إلى التقويم',
  'itin.share': 'شارك',
  'itin.sameTime': 'الأوقات محلية. {city} على نفس توقيت الرياض.',
  'itin.localTimes': 'الأوقات بتوقيت المكان الذي تكون فيه ذلك اليوم.',
  'itin.cancelledAirline': 'ألغتها شركة الطيران',
  'itin.carry': 'احمل معك:',
  'itin.askedFor': 'طلبنا: {what}.',
  'itin.checkInNote': 'تسجيل السفر يُفتح قبل الرحلة بـ 24 ساعة. نعمله لك وتظهر بطاقات الصعود في محفظتك.',
  'itin.changeFlight': 'غيّر هذه الرحلة',
  'itin.special': 'طلبات خاصة',
  'itin.passes': 'بطاقات الصعود',
  'itin.theDriver': 'السائق',
  'itin.driverWaits': '{driver} يتابع رحلتك. إن تأخرت، ينتظر مجانًا.',
  'itin.callDriver': 'اتصل بـ {driver}',
  'itin.yourName': 'اسمك',
  'itin.hotelTimes': 'تسجيل الدخول من 14:00، والمغادرة قبل 12:00. الحجز باسم {name}.',
  'itin.hotelOptions': 'خيارات الفندق',
  'itin.heldNote': '{what}. تحجزه مادا حتى ذلك الحين.',
  'itin.bookedNote': 'محجوز. التأكيد في محفظتك.',
  'itin.payConfirm': 'ادفع للتأكيد',
  'itin.ideaNote': 'مجرد فكرة. لا شيء محجوز.',
  'itin.askBook': 'اطلب من مادا حجزها',
  'itin.leaveFree': 'اترك اليوم حرًا',
  'itin.close': 'أغلق',
  'itin.shareTitle': 'شارك البرنامج',
  'itin.shareBody': 'أرسل الخطة كرسالة. تُظهر الأوقات والأماكن، ولا شيء خاص.',
  'itin.theySee': 'ما يرونه',
  'itin.theyDont': 'ما لا يرونه',
  'itin.sees.flights': 'مواعيد الرحلات وأرقامها',
  'itin.sees.hotel': 'اسم الفندق وعنوانه',
  'itin.sees.drivers': 'أسماء السائقين ومواعيد الاستقبال',
  'itin.sees.tables': 'الطاولات والجولات المحجوزة',
  'itin.hidden.passports': 'أرقام الجوازات',
  'itin.hidden.paid': 'ما دفعته، وكيف',
  'itin.hidden.code': 'رمز حجزك',
  'itin.shareBtn': 'شارك الخطة',
  'itin.copied': 'نُسخت. الصقها في واتساب.',
  'itin.cantShare': 'لم تتم المشاركة من هنا. حاول مرة أخرى.',
  'itin.calTitle': 'أضف إلى تقويمك',
  'itin.calBody': 'اللحظات الـ {n} المهمة. وأفكار الأيام الحرة لا تُضاف.',
  'itin.add': 'أضف',
  'itin.added': 'أُضيف',
  'itin.allFile': 'أضفها كلها كملف',
  'itin.fileSaved': 'حُفظ. افتحه ويضيف تقويمك الـ {n} كلها.',
  'itin.fileFailed': 'تطبيق التقويم لا يقبل ملفًا هنا. أضفها واحدة واحدة في الأعلى.',
  'dz.call': 'اتصل',
  'dz.callA11y': 'اتصل بفريق مادا على {phone}',
  'dz.callNumber': 'اتصل بفريق مادا على {phone}.',
  'dz.callDesk': 'اتصل بالفريق',
  'dz.offTitle': 'لا إشارة لتحميل الخيارات.',
  'dz.offBody': 'اتصل بالفريق ونرتّبها بالهاتف. {phone}، في أي ساعة.',
  'dz.working': 'مادا تتولاها.',
  'dz.step.held': 'حُجزت المقاعد',
  'dz.step.refund': 'نطلب الاسترداد من {airline}',
  'dz.theAirline': 'شركة الطيران',
  'dz.step.tickets': 'ننقل تذاكرك',
  'dz.step.vouchers': 'نحجز الفندق وقسائم الوجبات',
  'dz.step.pickup': 'ننقل الاستقبال',
  'dz.chooseAgain': 'اختر من جديد',
  'dz.q.title': 'محفوظ على جوالك. يُرسل حين يعود اتصالك.',
  'dz.q.body': 'اختيارك: {choice}. لم يصلنا شيء بعد. لحظة عودة اتصال جوالك، يصل إلى {who} ونجري التغيير. المقاعد محجوزة حتى {until}.',
  'dz.q.nightDesk': 'الفريق الليلي',
  'dz.q.waiting': 'بانتظار الاتصال',
  'dz.q.hurry': 'تحتاجه أسرع؟ اتصل بالفريق ونعمله بالهاتف. {phone}، في أي ساعة.',
  'dz.backToday': 'ارجع إلى اليوم',
  'dz.sentTitle': 'أُرسل. أجرت مادا التغيير.',
  'dz.sentBody': 'وصلنا اختيارك حين عاد اتصالك. والرحلة تعرض الخطة الجديدة.',
  'dz.today': 'اليوم',
  'dz.tonight': 'الليلة',
  'dz.chooseA11y': 'اختر ما تريد',
  'dz.rights.title': 'ما تمنحك إياه الأنظمة',
  'dz.rights.sub': 'أنظمة الطيران السعودية (الهيئة العامة للطيران المدني)، بكلمات بسيطة',
  'dz.rights.care': 'رعاية أثناء الانتظار.',
  'dz.rights.careBody': 'وجبات ومشروبات، وغرفة فندق إن امتد الانتظار إلى الليل، والتوصيل ذهابًا وإيابًا. على حساب شركة الطيران.',
  'dz.rights.choice': 'لك الخيار بين الرحلة التالية أو استرداد مالك.',
  'dz.rights.choiceBody': 'استرداد كامل، حتى لو كان السعر غير قابل للاسترداد.',
  'dz.rights.comp': 'وتعويض إضافي',
  'dz.rights.compBody': 'حين تلغي شركة الطيران قبل أقل من 14 يومًا. نطالب به نيابة عنك. لا تحتاج تعبئة أي شيء.',
  'dz.rather': 'تفضّل الكلام؟ اتصل على {phone}',
  'dz.offlineNote': 'أنت غير متصل. نحفظ اختيارك ونرسله لحظة عودة الاتصال.',
  'dz.getRefund': 'استرد المبلغ',
  'dz.stayOn': 'ابقَ على {code}',
  'dz.take': 'خذ رحلة {time}',
};
