/**
 * Arabic: Trip management screens (en-trips-ui.ts).
 * A first draft in warm, plain Modern Standard Arabic for the native Saudi writer to transcreate (COPY.md §7.4).
 * Same keys as the English; Arabic's extra plural forms are `.two`, `.few` and `.zero`. The brand is مادا.
 * Generated once from the translation sheet; edit here from now on.
 */
import type { enTripsUi } from '../en-trips-ui';
import type { ArSection } from './types';

export const arTripsUi: ArSection<typeof enTripsUi> = {
  'tm.detail.gone': 'انتهت هذه الرحلة.',
  'tm.detail.booking': 'الحجز {ref}',
  'tm.detail.going': 'الذهاب',
  'tm.detail.oneWay': 'ذهاب فقط',
  'tm.detail.back': 'العودة',
  'tm.detail.refunded': 'مُسترد',
  'tm.detail.change': 'غيّر',
  'tm.detail.noHome': 'لا رحلة عودة محجوزة. يقدر {agent} يضيف واحدة في أي وقت.',
  'tm.detail.nights': '{n} ليالٍ',
  'tm.detail.cancelled': 'ملغاة',
  'tm.detail.stayed': 'أقمتم',
  'tm.detail.refundOnWay': 'المبلغ المسترد في الطريق. تابعه في «الرحلات»، ضمن الطلبات.',
  'tm.detail.stayingWith': 'الإقامة عند {label}',
  'tm.detail.takesYou': '{driver} يوصلك إلى هناك.',
  'tm.detail.tellUs': 'أخبرنا',
  'tm.detail.pickBoth': 'استقبال من المطار وتوصيل إليه',
  'tm.detail.pickThere': 'استقبال من المطار عند الذهاب',
  'tm.detail.pickArrival': 'استقبال من المطار عند الوصول',
  'tm.detail.inCity': '{driver} في {city}',
  'tm.detail.needsAddr': 'يحتاج عنوانك',
  'tm.detail.manage': 'إدارة',
  'tm.detail.travellers': 'المسافرون',
  'tm.detail.you': '{name} (أنت)',
  'tm.detail.open.one': 'طلب واحد لدى مادا. شاهد أين وصل.',
  'tm.detail.open.two': 'طلبان لدى مادا. شاهد أين وصل كل واحد.',
  'tm.detail.open.few': '{n} طلبات لدى مادا. شاهد أين وصل كل واحد.',
  'tm.detail.open.other': '{n} طلبًا لدى مادا. شاهد أين وصل كل واحد.',
  'tm.m.itinerary': 'برنامج الرحلة كاملًا',
  'tm.m.itinerarySub': 'يومًا بيوم، بالأوقات والوثائق',
  'tm.m.payments': 'المدفوعات والفواتير',
  'tm.m.paymentsSub': 'فواتير ضريبية لكل دفعة',
  'tm.m.nextPayment': 'الدفعة التالية {amount} يوم {day}',
  'tm.m.change': 'غيّر الرحلة',
  'tm.m.changeSub': 'التاريخ، الوقت، العودة، تهجئة اسم',
  'tm.m.changeCall': 'باقي أقل من يوم: {agent} يتصل بك',
  'tm.m.hotel': 'خيارات الفندق',
  'tm.m.hotelSub': 'الغرفة، الليالي، تسجيل الدخول والمغادرة',
  'tm.m.hotelFind': 'ابحث عن مكان للإقامة',
  'tm.m.special': 'طلبات خاصة',
  'tm.m.specialSub': 'كرسي متحرك، وجبات، حقائب، مناسبة',
  'tm.m.refund': 'اطلب استردادًا',
  'tm.m.refundSub': 'شاهد بالضبط ما يعود لك أولًا',
  'tm.cancel.title': 'تلغي الإقامة؟',
  'tm.cancel.body': 'يعود لك {amount}.',
  'tm.cancel.flightsStay': 'رحلاتك تبقى كما هي.',
  'tm.cancel.instalments': 'هذا ما دفعته حتى الآن عبر {provider}. الدفعات المتبقية ({n}، بقيمة {amount}) تُلغى.',
  'tm.cancel.paid': 'دفعت {amount}.',
  'tm.cancel.confirm': 'ألغِ الإقامة',
  'tm.cancel.keep': 'أبقِها',
  'tm.cancel.done': 'أُلغيت. المبلغ المسترد في الطريق.',
  'tm.nostay.body': '{driver} يستقبلك في المطار يوم {day}. أخبرنا إلى أين يوصلك.',
  'tr.tripA11y': 'رحلة {city}',
  'tr.justYou': 'أنت فقط',
  'tr.booked': 'محجوزة',
  'tr.itinerary': 'البرنامج',
  'tr.payments': 'المدفوعات',
  'tr.tracking': 'رحلات تتتبّعها',
  'tr.import.title': 'حجزت من مكان آخر؟',
  'tr.import.body': 'ارفع ملف PDF ونتابعها مثل أي رحلة مع مادا.',
  'tr.import.upload': 'ارفع حجزًا',
  'tr.req.send': 'أرسل طلبًا إلى مادا',
  'tr.req.pay': 'ادفع {amount}',
  'tr.req.confirmedToday': 'تأكد اليوم',
  'tr.req.cantDefault': 'لا يستطيعون تنفيذه. تحدّث مع مادا ونجد طريقة أخرى.',
  'tr.req.queuedChoice': 'اختيارك للرحلة',
  'tr.req.savedPhone': 'محفوظ على هذا الجوال. يُرسل حين يعود اتصالك.',
  'tr.refund': 'استرداد · {amount}',
  'tr.ref.notApproved': 'لم تتم الموافقة',
  'tr.ref.withMada': 'لدى مادا',
  'tr.ref.inCredit': 'في رصيدك',
  'tr.ref.sent': 'أُرسل',
  'tr.ref.onWay': 'في الطريق',
  'tr.sameAgain': 'نفسها مرة أخرى',
  'tr.sameAgainAsk': '{city} مرة أخرى، مثل {when}',
  'rq.tr.savedPhone': 'محفوظ على هذا الجوال',
  'rq.tr.withinHour': 'عادةً خلال ساعة',
  'pay.title': 'المدفوعات',
  'pay.emptyTitle': 'لم يُدفع شيء بعد.',
  'pay.emptyBody': 'كل دفعة في هذه الرحلة تظهر هنا مع فاتورتها الضريبية.',
  'pay.plan': 'خطّط لرحلة',
  'pay.eyebrow': '{city} · الحجز {ref}',
  'pay.total': 'إجمالي الرحلة. اضغط أي دفعة لترى فاتورتها الضريبية.',
  'pay.totalRefunded': 'إجمالي الرحلة، واسترددت منه {amount}. اضغط أي دفعة لترى فاتورتها الضريبية.',
  'pay.next': 'الدفعة التالية: {amount} يوم {day}',
  'pay.nextBody': '{what}. باقي {n}، تُخصم من {card}. بلا فوائد ولا رسوم.',
  'pay.a11y': '{title}، {amount}، افتح الفاتورة',
  'pay.andCredit': 'و{amount} رصيد مادا',
  'pay.credited': 'أُضيف {amount} · إشعار دائن',
  'pay.ofPaid': 'دُفع {n} من {total}',
  'pay.invoice': 'الفاتورة',
  'pay.plan.title': 'خطة الدفع',
  'pay.atBooking': 'عند الحجز',
  'pay.payment': 'الدفعة {n}',
  'pay.paid': 'مدفوعة',
  'pay.due': 'مستحقة',
  'pay.plan.foot': 'إن ألغيت، تُلغى الدفعات المتبقية أيضًا. لا يُخصم شيء آخر.',
  'pay.tabby4': 'تابي · 4 دفعات',
  'pay.tamara3': 'تمارا · 3 دفعات',
  'inv.title': 'الفاتورة',
  'inv.gone': 'هذه الدفعة لم تعد ضمن الرحلة.',
  'inv.goneBody': 'تقدر مادا ترسل لك نسخة من أي فاتورة.',
  'inv.tab.invoice': 'فاتورة',
  'inv.tab.tax': 'فاتورة ضريبية',
  'inv.tab.credit': 'إشعار دائن',
  'inv.draft.title': 'مسودة. راجع بيانات الشركة.',
  'inv.draft.body': 'بعد إصدارها لا يمكن تعديلها. ولا يعيد إصدارها إلا {agent}.',
  'inv.qr': 'رمز QR من هيئة الزكاة والضريبة',
  'inv.f.seller': 'البائع',
  'inv.f.vat': 'الرقم الضريبي',
  'inv.f.no': 'رقم الفاتورة',
  'inv.f.cnNo': 'رقم الإشعار الدائن',
  'inv.f.onIssue': 'عند الإصدار',
  'inv.f.date': 'التاريخ',
  'inv.f.buyer': 'المشتري',
  'inv.f.buyerVat': 'الرقم الضريبي للمشتري · السجل التجاري',
  'inv.f.traveller': 'المسافر',
  'inv.f.customer': 'العميل',
  'inv.f.against': 'مقابل الفاتورة',
  'inv.f.paidWith': 'طريقة الدفع',
  'inv.vatRate': 'ضريبة القيمة المضافة {rate}%',
  'inv.seeCredit': 'اعرض الإشعار الدائن للاسترداد',
  'inv.co.title': 'فاتورة باسم شركة',
  'inv.co.row': 'فاتورة ضريبية كاملة بالرقم الضريبي لشركتك',
  'inv.co.body': 'نصدر فاتورة ضريبية كاملة ببيانات شركتك، لكل دفعة في هذه الرحلة. راجعها قبل الإصدار.',
  'inv.co.name': 'اسم الشركة',
  'inv.co.namePh': 'كما في السجل التجاري',
  'inv.co.vat': 'الرقم الضريبي',
  'inv.co.cr': 'رقم السجل التجاري',
  'inv.co.crPh': '10 أرقام',
  'inv.co.address': 'العنوان',
  'inv.co.addressPh': 'الشارع، الحي، المدينة',
  'inv.co.save': 'احفظ بيانات الشركة',
  'inv.co.saved': 'حُفظت. راجعها، ثم أصدر الفاتورة الضريبية.',
  'inv.co.errName': 'أضف اسم الشركة كما هو مسجّل.',
  'inv.co.errVat': 'أضف الرقم الضريبي للشركة.',
  'inv.co.errVatLen': 'الرقم الضريبي السعودي من 15 رقمًا (هذا فيه {n}).',
  'inv.co.errVat3': 'يبدأ بـ 3 وينتهي بـ 3، مثل 300000000000003.',
  'inv.co.errCr': 'أضف رقم السجل التجاري.',
  'inv.co.errCrLen': 'رقم السجل التجاري من 10 أرقام (هذا فيه {n}).',
  'inv.co.errAddr': 'أضف الشارع والحي والمدينة.',
  'inv.issue': 'أصدر الفاتورة الضريبية',
  'inv.issued': 'صدرت. الفاتورة الضريبية نهائية الآن.',
  'inv.editCo': 'عدّل بيانات الشركة',
  'inv.share': 'شارك PDF',
  'inv.saved': 'حُفظت. اختر «حفظ كـ PDF» لتحتفظ بنسخة.',
  'inv.cantShare': 'لم نتمكن من مشاركتها هنا. اطلب من مادا إرسالها بالبريد.',
  'inv.issuedTo': 'صدرت باسم {name}، {day}',
  'inv.cantEdit': 'لا يمكن تعديل الفاتورة الضريبية بعد إصدارها. يقدر {agent} يلغيها بإشعار دائن ويصدر فاتورة جديدة.',
  'inv.askReissue': 'اطلب من مادا إعادة الإصدار',
  'inv.reissueSent': 'وصل إلى مادا. اكتب ما تريد تغييره في المحادثة.',
  'rf.title': 'الاسترداد',
  'rf.askTitle': 'اطلب استردادًا',
  'rf.emptyTitle': 'لا شيء للاسترداد بعد.',
  'rf.emptyBody': 'حين تدفع لرحلة، ترى هنا بالضبط ما يمكن أن يعود لك.',
  'rf.seeTrips': 'اعرضها في «الرحلات»',
  'rf.done': 'تم',
  'rf.sent.anyway': 'وصل إلى مادا.',
  'rf.sent.credit': '{amount} في رصيد مادا.',
  'rf.sent.card': '{amount} في طريقه إليك.',
  'rf.sent.anywayBody': 'القاعدة تقول لا يُسترد شيء، لكن {agent} سيسأل. تصلك الإجابة خلال يوم.',
  'rf.sent.creditBody': 'جاهز للاستخدام الآن، في أي حجز. ولا ينتهي.',
  'rf.sent.tabbyBody': 'نبلغ {provider} اليوم. ما دفعته يعود إلى بطاقتك، والدفعات المتبقية تُلغى.',
  'rf.sent.cardBody': 'يعود إلى {card}، عادةً خلال 5 إلى 10 أيام عمل.',
  'rf.sent.line': '«أتابعه حتى يصل إلى حسابك.»',
  'rf.sent.lineAnyway': '«أسأل، وأخبرك بالنتيجة في الحالتين.»',
  'rf.sent.lineCredit': '«تم. صار عندك الآن.»',
  'rf.doneTitle': 'انتهت رحلتك.',
  'rf.doneBody': 'استُخدمت كل رحلة وكل ليلة، فلا شيء متبقٍ للاسترداد. إن خيّب أملك شيء في الرحلة، أخبر {agent}. سيتابعه مع شركة الطيران أو الفندق.',
  'rf.slide.pick': 'اختر ما تريد استرداده',
  'rf.slide.reason': 'اختر سببًا',
  'rf.slide.anyway': 'اسحب لتسأل مادا على أي حال',
  'rf.slide.ask': 'اسحب لتطلب {amount}',
  'rf.what': 'ماذا نسترد؟',
  'rf.cancelled': 'ألغت {airline} رحلة {code}.',
  'rf.cancelledBody': 'وفق أنظمة الهيئة العامة للطيران المدني يعود لك سعر الرحلات كاملًا، مع الرسوم. وإلغاء الإقامة والاستقبال مجاني أيضًا.',
  'rf.used': 'جزء من الرحلة مُستخدم.',
  'rf.usedBody': 'يعود فقط ما لم تستخدمه بعد.',
  'rf.already': 'استُرد مسبقًا',
  'rf.refunded': 'مُسترد',
  'rf.paymentsStop': 'تتوقف الدفعات',
  'rf.nothingBack': 'لا يُسترد شيء',
  'rf.youPaid': 'دفعت {amount}.',
  'rf.instNote': 'دفعت {paid} حتى الآن، ويعود لك. ودفعات {provider} المتبقية ({n}، بقيمة {left}) تُلغى.',
  'rf.owe': 'تخصم {provider} {amount} مقابل رسوم الفندق.',
  'rf.why': 'لماذا؟',
  'rf.reason.plans': 'تغيّرت الخطط',
  'rf.reason.ill': 'أحدنا مريض',
  'rf.reason.docs': 'مشكلة في التأشيرة أو الجواز',
  'rf.reason.airline': 'شركة الطيران غيّرتها',
  'rf.reason.else': 'وجدت بديلًا',
  'rf.reason.other': 'سبب آخر',
  'rf.illNote': 'أرسل لمادا تقريرًا طبيًا. بعض شركات الطيران تعفي من الرسوم به، وسنطلب ذلك.',
  'rf.airlineNote': 'إن غيّرت {airline} موعد رحلتك أكثر من 3 ساعات، تمنحك أنظمة الهيئة العامة للطيران المدني استردادًا كاملًا. تراجع مادا الجدول.',
  'rf.where': 'إلى أين يذهب؟',
  'rf.backThrough': 'يعود عبر {provider}',
  'rf.backThroughBody': 'دفعت بالتقسيط، فيعود المبلغ بنفس الطريقة: ما دفعته حتى الآن إلى بطاقتك، والدفعات المتبقية تُلغى.',
  'rf.toCard': 'إلى {card}',
  'rf.toCardSub': 'من 5 إلى 10 أيام عمل',
  'rf.toCredit': 'رصيد مادا',
  'rf.toCreditSub': 'فوري · نفس المبلغ · لأي حجز، ولا ينتهي',
  'rf.mixed': 'الجزء المدفوع عبر {provider} يعود عبرها، والدفعات المتبقية تُلغى.',
  'rf.sumAnyway': 'القواعد تقول لا يُسترد شيء. لكن {agent} يقدر يسأل.',
  'rf.youGet': 'يعود لك',
  'rf.sumInst': 'و{left} دفعات لن تدفعها. {all} إجمالًا.',
  'rf.tr.requested': 'طُلب',
  'rf.tr.today': 'اليوم',
  'rf.tr.asking': '{agent} يسأل',
  'rf.tr.couldnt': 'لم يتمكن {agent} من الحصول على الموافقة',
  'rf.tr.withinDay': 'عادةً خلال يوم',
  'rf.tr.approvedBy': 'وافق {agent}',
  'rf.tr.approvedByAirline': 'وافقت {airline}',
  'rf.tr.inCredit': 'أُضيف إلى رصيد مادا · {amount}',
  'rf.tr.readyNow': 'جاهز للاستخدام الآن',
  'rf.tr.days13': 'عادةً من يوم إلى 3 أيام',
  'rf.tr.sentProvider': 'أُرسل إلى {provider}',
  'rf.tr.sentCard': 'أُرسل إلى {card}',
  'rf.tr.cancelledLeft': 'أُلغيت الدفعات المتبقية ({n})',
  'rf.tr.law': 'خلال 7 أيام، بحكم النظام',
  'rf.tr.days714': 'عادةً من 7 إلى 14 يومًا',
  'rf.tr.backOnCard': 'عاد إلى بطاقتك',
  'rf.tr.inBank': 'في بنكك',
  'rf.tr.arrived': 'وصل',
  'rf.tr.afterSent': 'من 5 إلى 10 أيام عمل بعد إرساله، بالريال',
  'cf.title': 'غيّر الرحلة',
  'cf.noFlights': 'لا رحلات طيران في هذه الرحلة.',
  'cf.noFlightsBody': 'تقدر مادا تضيف رحلات في أي وقت.',
  'cf.cancelledBody': 'لا تدفع شيئًا مقابل التغيير. ونحجز مقاعد على رحلتين أخريين لكم الـ {n} كلكم.',
  'cf.flownBody': 'حمدًا لله على السلامة. لا شيء متبقٍ للتغيير.',
  'cf.flown': 'تمت الرحلتان.',
  'cf.flownOne': 'سافرت على هذه مسبقًا.',
  'cf.callMe': 'اطلب من مادا الاتصال بي',
  'cf.within24': 'باقي أقل من يوم.',
  'cf.within24Body': 'خلال 24 ساعة، لا تغيّر {airline} التذاكر إلا بالهاتف. يتصل بك {agent}، ثم يتصل بهم، ويبقى على الخط حتى ينتهي الأمر.',
  'cf.rulesApply': 'القواعد ما زالت تنطبق',
  'cf.rulesBody': 'رسوم التغيير {fee}، مع أي فرق في السعر. ترى السعر قبل أي تغيير.',
  'cf.feePp': '{fee} ر.س للشخص',
  'cf.feePpShort': '{fee} ر.س للفرد',
  'cf.free': 'مجانًا',
  'cf.minusPp': 'ناقص {fee} ر.س للفرد',
  'cf.taxesOnly': 'الضرائب فقط',
  'cf.r.fee': 'رسوم التغيير',
  'cf.r.refund': 'الاسترداد',
  'cf.r.bags': 'الحقائب',
  'cf.working': '{agent} يغيّرها الآن.',
  'cf.step.held': 'حجزنا المقاعد الجديدة',
  'cf.step.changing': 'نغيّر التذاكر مع {airline}',
  'cf.step.pickups': 'ننقل مواعيد الاستقبال',
  'cf.backToTrip': 'ارجع إلى الرحلة',
  'cf.done': 'تم. {say}.',
  'cf.doneCredit': 'السعر أقل، فأُضيف {amount} إلى رصيد مادا الآن.',
  'cf.doneNoCost': 'بلا تكلفة عليك.',
  'cf.donePasses': 'بطاقات الصعود الجديدة تصل إلى محفظتك حين يُفتح تسجيل السفر.',
  'cf.doneLine': '«غيّرناها مع {airline}. {seats}»',
  'cf.sameSeats': 'نفس المقاعد متجاورة.',
  'cf.sameSeat': 'نفس المقعد.',
  'cf.backLine': 'العودة {code} · {day} · {time}',
  'cf.oneWayLine': 'ذهاب فقط',
  'cf.travellers.one': 'مسافر واحد',
  'cf.travellers.two': 'مسافران',
  'cf.travellers.few': '{n} مسافرين',
  'cf.travellers.other': '{n} مسافرًا',
  'cf.whatChange': 'ماذا تريد أن تغيّر؟',
  'cf.k.date': 'يوم آخر',
  'cf.k.dateSub': 'نفس شركة الطيران. ومقاعدك تنتقل معك.',
  'cf.k.time': 'وقت آخر، نفس اليوم',
  'cf.k.timeSub': 'أبكر أو أبطأ يوم {day}.',
  'cf.k.return': 'العودة فقط',
  'cf.k.returnSub': 'أطِل إقامتك، أو ارجع أبكر.',
  'cf.k.one': 'مسافر واحد فقط',
  'cf.k.oneSub': 'أحدكم يعود في يوم آخر.',
  'cf.k.airline': 'شركة طيران أخرى',
  'cf.k.airlineSub': 'تذكرة جديدة، لا تغيير.',
  'cf.k.name': 'صحّح تهجئة اسم',
  'cf.k.nameSub': 'تصحيحات صغيرة، لتطابق التذكرة الجواز.',
  'cf.onlyHome': 'أنت في {city}، فلا يتغير إلا طريق العودة.',
  'cf.else': 'شيء آخر',
  'cf.whoHome': 'من يعود في يوم آخر؟',
  'cf.under12': 'عمر {name} أقل من 12.',
  'cf.escort': 'الأطفال دون 12 لا يسافرون وحدهم إلا مع مرافق من {airline} يبقى معهم من الباب إلى الباب. 350 ر.س، محسوبة في الأسفل.',
  'cf.pickHome': 'اختر رحلة العودة',
  'cf.pickNew': 'اختر الرحلة الجديدة',
  'cf.noSeats': 'لا مقاعد لـ {who} على تلك الرحلات.',
  'cf.one': 'شخص واحد',
  'cf.allN': 'الـ {n} كلهم',
  'cf.wider': 'يقدر {agent} يبحث أوسع: مطارات أخرى، أو قائمة انتظار في اليوم الذي تريده.',
  'cf.askWider': 'اطلب من مادا البحث أوسع',
  'cf.full': 'ممتلئة',
  'cf.b.fee': 'رسوم التغيير',
  'cf.b.freeFare': 'مجانًا في هذا السعر',
  'cf.b.escort': 'مرافق لـ {name}، من الباب إلى الباب',
  'cf.b.diff': 'فرق السعر',
  'cf.b.same': 'نفس السعر',
  'cf.b.pay': 'تدفع',
  'cf.b.back': 'يعود لك',
  'cf.b.total': 'المجموع',
  'cf.b.creditNote': 'السعر أقل من الرسوم، فيعود الفرق رصيدًا في مادا، فورًا.',
  'cf.b.nextMove': 'بعدها نسألك إن كان الفندق والاستقبال ينتقلان أيضًا.',
  'cf.b.oneMore': 'تحتاج ليلة إضافية. أضفها من خيارات الفندق.',
  'cf.b.rules': 'التذاكر الجديدة بنفس القواعد. ويؤكد {agent} مع {airline}.',
  'cf.review': 'راجع · {amount}',
  'cf.pickFlight': 'اختر رحلة',
  'cf.slideBack': 'اسحب للتغيير · يعود لك {amount}',
  'cf.slideFree': 'اسحب للتغيير · بلا تكلفة',
  'cf.quoted': 'وصل إلى مادا. السعر في «الرحلات»، ضمن الطلبات.',
  'cf.sent': 'وصل إلى مادا. تابعه في «الرحلات»، ضمن الطلبات.',
  'cf.sw.cant': 'لا يمكن نقل التذاكر إلى شركة طيران أخرى.',
  'cf.sw.body': 'نسترد تذاكرك في {airline} وفق قواعدها ونشتري تذاكر جديدة.',
  'cf.sw.back': 'يعود لك {amount}.',
  'cf.sw.taxes': 'هذا السعر غير قابل للاسترداد، فلا تعود إلا الضرائب: {amount}. وتغيير اليوم في {airline} أرخص: {fee} ر.س للشخص.',
  'cf.sw.foot': 'السعر بعد الاسترداد، للـ {n} كلهم. يتحقق {agent} من المقاعد قبل أن تدفع شيئًا.',
  'cf.sw.ask': 'اطلب من مادا التبديل',
  'cf.n.whose': 'اسم من؟',
  'cf.n.now': 'على التذكرة الآن',
  'cf.n.given': 'الاسم الأول والأسماء الأخرى',
  'cf.n.sur': 'اسم العائلة',
  'cf.n.same': 'اكتبه تمامًا كما في الجواز. شركات الطيران تسمح بتصحيحات صغيرة فقط: حتى 3 أحرف.',
  'cf.n.ok.one': 'تصحيح بسيط (حرف واحد). تعمله {airline} مجانًا. وترسله مادا مع صورة صفحة الجواز.',
  'cf.n.ok.two': 'تصحيح بسيط (حرفان). تعمله {airline} مجانًا. وترسله مادا مع صورة صفحة الجواز.',
  'cf.n.ok.few': 'تصحيح بسيط ({n} أحرف). تعمله {airline} مجانًا. وترسله مادا مع صورة صفحة الجواز.',
  'cf.n.ok.other': 'تصحيح بسيط ({n} حرفًا). تعمله {airline} مجانًا. وترسله مادا مع صورة صفحة الجواز.',
  'cf.n.too': 'هذا أكثر من تصحيح تهجئة. تسمح شركات الطيران بتغيير 3 أحرف كحد أقصى. الاسم المختلف يعني تذكرة جديدة، فتنطبق قواعد السعر.',
  'cf.n.askCost': 'اسأل مادا كم يكلف',
};
