/**
 * Arabic: Wallet, passports, account, Help and support (wallet.ts).
 * A first draft in warm, plain Modern Standard Arabic for the native Saudi writer to transcreate (COPY.md §7.4).
 * Same keys as the English; Arabic's extra plural forms are `.two`, `.few` and `.zero`. The brand is مادا.
 * Generated once from the translation sheet; edit here from now on.
 */
import type { walletCopy } from '../wallet';
import type { ArSection } from './types';

export const arWallet: ArSection<typeof walletCopy> = {
  'wallet.lock.title': 'المحفظة مقفلة',
  'wallet.lock.body': 'جوازات العائلة كلها وتأشيراتها. محفوظة ومشفّرة، وتعمل دون اتصال.',
  'wallet.lock.checking': 'نتحقق من Face ID',
  'wallet.lock.open': 'افتح بـ Face ID',
  'wallet.lock.failed': 'لم يتعرّف Face ID عليك. استخدم رمز المرور.',
  'wallet.lock.passcode': 'رمز المرور',
  'wallet.lock.usePasscode': 'استخدم رمز المرور',
  'wallet.lock.openWallet': 'افتح المحفظة',
  'wallet.lock.wrong.one': 'رمز المرور غير مطابق. بقيت محاولة واحدة.',
  'wallet.lock.wrong.two': 'رمز المرور غير مطابق. بقيت محاولتان.',
  'wallet.lock.wrong.few': 'رمز المرور غير مطابق. بقيت {count} محاولات.',
  'wallet.lock.wrong.other': 'رمز المرور غير مطابق. بقيت {count} محاولة.',
  'wallet.lock.lockedOut': 'محاولات كثيرة. حاول بعد {minutes} د، أو افتحها بـ Face ID.',
  'wallet.lock.demo': 'رمز المرور للتجربة: 123456',
  'wallet.lock.prompt': 'افتح محفظتك',
  'wallet.lock.lockedWith': 'مقفلة بـ Face ID · تعمل دون اتصال',
  'wallet.lock.notLocked': 'تُفتح دون Face ID · تعمل دون اتصال',
  'wallet.add': 'أضف وثيقة',
  'wallet.whose': 'وثائق من؟',
  'wallet.signedOut.title': 'أضف جوازًا ونتابعه عنك.',
  'wallet.signedOut.body': 'تواريخ الانتهاء والتأشيرات وشروط الدخول، نطابقها مع كل رحلة.',
  'wallet.signedOut.action': 'سجّل دخولك لتضيفه',
  'wallet.passport.waitingOther': 'جواز {name} ليس هنا بعد.',
  'wallet.passport.number': 'الرقم',
  'wallet.passport.born': 'تاريخ الميلاد',
  'wallet.passport.expires': 'ينتهي',
  'wallet.passport.issuedBy': 'صادر من {country}',
  'wallet.chip.valid': 'ساري',
  'wallet.chip.ready': 'جاهز لـ {city}',
  'wallet.chip.spare': 'جاهز · يتبقى {days} يومًا إضافيًا',
  'wallet.chip.notValid': 'لا يصلح لـ {city}',
  'wallet.chip.expired': 'منتهي',
  'wallet.validity.validUntil': 'ساري حتى {date}.',
  'wallet.validity.validUntilBody': 'نطابقه مع كل رحلة تخطط لها.',
  'wallet.validity.expired': 'انتهى هذا الجواز في {date}.',
  'wallet.validity.expiredBody': 'لا يمكن السفر به. تقدر مادا تساعدك في تجديده.',
  'wallet.validity.ready': 'جاهز لـ {city}.',
  'wallet.validity.readyBody': 'صلاحيته تتجاوز بكثير الـ {days} يومًا التي تطلبها {country} بعد الوصول.',
  'wallet.validity.spare': 'يصلح لـ {city}، ويتبقى {days} يومًا إضافيًا.',
  'wallet.validity.spareBody': 'يصلح لـ {city}: تطلب {country} صلاحية {need} يومًا بعد الوصول، ولدى {name} {left}.',
  'wallet.validity.blockedYou': 'لا يمكنك السفر إلى {city} بهذا الجواز.',
  'wallet.validity.blocked': 'لا يمكن لـ {name} السفر إلى {city} بهذا الجواز.',
  'wallet.validity.blockedBody': 'جواز {name} ينتهي في {date}. تطلب {country} صلاحية {need} يومًا بعد الوصول، فيجب أن يكون ساريًا حتى {until}.',
  'wallet.validity.notOnTrip': '{name} ليس ضمن رحلة {city}.',
  'wallet.validity.trip': 'الرحلة · {date}',
  'wallet.validity.until': 'مطلوب حتى {date}',
  'wallet.renew': 'احجز موعد تجديد',
  'wallet.renew.message': 'أرجو حجز موعد تجديد جواز لـ {name} قبل الرحلة القادمة.',
  'wallet.renew.sent': 'وصل إلى مادا. نبحث عن أقرب موعد تجديد لـ {name}.',
  'wallet.copyNumber': 'انسخ الرقم',
  'wallet.copyNumber.done': 'نُسخ الرقم.',
  'wallet.copyNumber.masked': 'نحفظ آخر الأرقام فقط على هذا الجوال: {number}. الرقم الكامل لدى مادا، مشفّرًا.',
  'wallet.docs.eyebrowOther': 'وثائق {name} الأخرى',
  'wallet.docs.emptyTitleOther': 'لا وثائق أخرى بعد',
  'wallet.docs.emptyBodyOther': 'تأشيرة، أو هوية وطنية، أو تأمين سفر لـ {name}. ونراقب التواريخ.',
  'wallet.docs.addFor': 'أضف وثيقة لـ {name}',
  'wallet.docs.iqama': 'الإقامة',
  'wallet.docs.exitVisa': 'تأشيرة خروج وعودة',
  'wallet.docs.notAdded': 'لم تُضف',
  'wallet.docs.exitNeeded': 'مطلوبة قبل كل سفر للخارج',
  'wallet.docs.addIt': 'أضفها',
  'wallet.docs.replace': 'استبدلها بأحدث',
  'wallet.docs.replaceBody': 'امسحها أو ارفعها. نحذف القديمة حين نحفظ الجديدة.',
  'wallet.docs.share': 'شاركها مع مادا',
  'wallet.docs.shareBody': 'لتأشيرة أو حجز. يراها فيصل حتى نهاية الرحلة.',
  'wallet.docs.shared': 'مشاركة مع مادا لهذه الرحلة فقط. يراها فيصل ولا يستطيع تنزيلها.',
  'wallet.docs.sharedUntil': 'يراها فيصل حتى {date}.',
  'wallet.docs.stopSharing': 'أوقف المشاركة',
  'wallet.docs.stopped': 'لم يعد فيصل يراها.',
  'wallet.docs.view': 'اعرض الملف',
  'wallet.docs.delete': 'احذف',
  'wallet.docs.deleted': 'حُذفت من هذا الجوال ومن مادا.',
  'wallet.docs.setup': 'أُضيفت حين جهّزت مادا. لحذفها، تحدّث مع مادا.',
  'wallet.docs.added': 'أُضيفت الآن',
  'wallet.docs.validUntil': 'سارية حتى {date}',
  'wallet.docs.expiresOn': '{number} · تنتهي {date}',
  'wallet.passes.title': 'بطاقات الصعود',
  'wallet.passes.row': '{flight} · {count} بطاقات صعود',
  'wallet.passes.rowOne': '{flight} · بطاقة صعود واحدة',
  'wallet.passes.rowSub': '{date} · {terminal} · المقاعد {seats}',
  'wallet.passes.rowSubOne': '{date} · {terminal} · المقعد {seats}',
  'wallet.passes.notYet': 'لرحلة {flight} يوم {date}. تُفتح مع تسجيل السفر، قبل الإقلاع بـ 24 ساعة.',
  'wallet.passes.noFlights': 'لا رحلات طيران في هذه الرحلة.',
  'wallet.pass.seat': 'المقعد {seat}',
  'wallet.pass.terminal': 'الصالة',
  'wallet.pass.gate': 'البوابة',
  'wallet.pass.boards': 'الصعود',
  'wallet.pass.previous': 'السابقة',
  'wallet.pass.next': 'التالية',
  'wallet.pass.of': '{n} من {count}',
  'wallet.pass.code': 'رمز بطاقة الصعود',
  'wallet.pass.bright': 'ارفع سطوع الشاشة عند البوابة.',
  'wallet.pass.appleWallet': 'أضف إلى Apple Wallet',
  'wallet.vouchers': 'قسائم شركة الطيران',
  'money.eyebrow': 'المال',
  'money.credit': 'رصيد مادا',
  'money.credit.used': 'يُستخدم أولًا عند الدفع. لا ينتهي أبدًا.',
  'money.credit.zero': 'يمكن أن تصل المبالغ المستردة هنا فورًا بدل انتظار البنك.',
  'money.credit.title': 'رصيد مادا · {amount}',
  'money.credit.body': 'مال تحفظه مادا لك. مصدره مبالغ مستردة اخترت أخذها رصيدًا، ويُستخدم أولًا كلما دفعت. لا ينتهي أبدًا، وتقدر تحوّله إلى بطاقتك متى شئت.',
  'money.credit.emptyTitle': 'لم يتحرك شيء بعد.',
  'money.credit.emptyBody': 'المبالغ المستردة التي تأخذها رصيدًا تظهر هنا مع التاريخ. وتُخصم من حجزك القادم أولًا.',
  'money.credit.move': 'حوّله إلى بطاقتي',
  'money.credit.moved': '{amount} في طريقه إلى {card}. من 5 إلى 10 أيام عمل.',
  'money.credit.movedTo': 'حُوّل إلى {card}',
  'money.credit.refund': 'استرداد كرصيد',
  'money.credit.goodwill': 'من مادا',
  'money.credit.spend': 'استُخدم في حجز',
  'money.credit.adjustment': 'تسوية',
  'money.credit.expiry': 'منتهٍ',
  'money.credit.notEnough': 'رصيد مادا لا يكفي. رصيدك {amount}.',
  'money.credit.nothing': 'لا يوجد رصيد مادا لتحويله.',
  'money.cards': 'البطاقات وApple Pay',
  'money.cards.sub': '{count} محفوظة · الافتراضية {label}',
  'money.cards.subOne': 'واحدة محفوظة · الافتراضية {label}',
  'money.cards.none': 'لا بطاقات بعد · Apple Pay جاهز على هذا الجوال',
  'cards.title': 'ادفع بـ',
  'cards.creditNote': 'لديك {amount} رصيد مادا. يُستخدم أولًا.',
  'cards.expires': 'تنتهي {exp}',
  'cards.applePay': 'Apple Pay',
  'cards.add': 'أضف بطاقة',
  'cards.number': 'رقم البطاقة',
  'cards.expiry': 'تاريخ الانتهاء',
  'cards.cvv': 'رمز الأمان',
  'cards.cvvHint': '3 أرقام',
  'cards.name': 'الاسم على البطاقة',
  'cards.save': 'احفظ البطاقة للمرة القادمة',
  'cards.note': 'بيانات البطاقة تذهب مباشرة إلى مزوّد الدفع. لا ترى مادا الرقم الكامل أبدًا.',
  'cards.test': 'بطاقة تجربة: 4242 4242 4242 4242.',
  'cards.use': 'استخدم هذه البطاقة',
  'cards.problem.amex': 'لا نقبل American Express بعد. استخدم Visa أو Mastercard أو مدى.',
  'cards.problem.luhn': 'الرقم لا يبدو صحيحًا. راجع كل رقم.',
  'cards.problem.short': 'رقم البطاقة من 16 رقمًا.',
  'cards.problem.brand': 'نقبل Visa وMastercard ومدى.',
  'cards.problem.expired': 'انتهت صلاحية هذه البطاقة.',
  'cards.problem.format': 'اكتبه بصيغة MM/YY، مثل 08/28.',
  'cards.label': '{brand} المنتهية بـ {last}',
  'cards.default.applePay': 'Apple Pay هو وسيلتك الافتراضية.',
  'cards.default.changed': '{label} هي الافتراضية الآن.',
  'cards.default.same': 'هذه هي الافتراضية أصلًا.',
  'cards.default.updated': 'تحدّثت البطاقة الافتراضية.',
  'cards.default': 'الافتراضية',
  'cards.remove': 'احذف',
  'cards.removeLabel': 'احذف {label}',
  'cards.removed': 'حُذفت البطاقة.',
  'cards.removedApplePay': 'حُذفت البطاقة. Apple Pay هو الافتراضي الآن.',
  'cards.removeDefault.title': 'هذه بطاقتك الافتراضية.',
  'cards.removeDefault.body': 'اختر ما تستخدمه من الآن، ثم نحذفها.',
  'cards.removeDefault.use': 'استخدم {label}',
  'cards.removeLast.title': 'تحذف بطاقتك الوحيدة؟',
  'cards.removeLast.body': 'تقدر تدفع بـ Apple Pay. وأضف بطاقة متى شئت عند الحجز.',
  'cards.removeLast.confirm': 'احذف البطاقة',
  'cards.keep': 'أبقِها',
  'cards.pickDefault': 'اختر البطاقة الافتراضية الجديدة أولًا.',
  'docs.add.title': 'ماذا تضيف؟',
  'docs.kind.passport': 'جواز سفر',
  'docs.kind.visa': 'تأشيرة',
  'docs.kind.id': 'هوية وطنية أو إقامة',
  'docs.kind.insurance': 'تأمين سفر',
  'docs.kind.other': 'شيء آخر',
  'docs.title.passport': 'جواز السفر',
  'docs.title.visa': 'التأشيرة',
  'docs.title.national_id': 'الهوية الوطنية',
  'docs.title.iqama': 'الإقامة',
  'docs.title.exit_reentry': 'تأشيرة خروج وعودة',
  'docs.title.insurance': 'تأمين السفر',
  'docs.title.other': 'وثيقة',
  'docs.upload.for': 'أضف {what} لـ {name}',
  'docs.upload.aDocument': 'وثيقة',
  'docs.upload.scan': 'امسح بالكاميرا',
  'docs.upload.scanSub': 'الأفضل للجوازات والتأشيرات المطبوعة',
  'docs.upload.photo': 'صوّر صفحة الصورة',
  'docs.upload.photoSub': 'نقرأ السطرين في أسفلها',
  'docs.upload.file': 'ارفع صورة أو PDF',
  'docs.upload.fileSub': 'من ملفاتك أو صورك · حتى 10 ميجابايت',
  'docs.upload.choosePhoto': 'اختر صورة',
  'docs.upload.choosePhotoSub': 'من صورك · حتى 10 ميجابايت',
  'docs.upload.reading': 'نقرأ {name}…',
  'docs.upload.readingPage': 'نقرأ الصفحة…',
  'docs.upload.failed': 'لم نتمكن من قراءتها.',
  'docs.upload.failedBody': 'جرّب صورة أوضح، مسطّحة وبلا لمعان، أو ملف PDF من الجهة المُصدِرة مباشرة.',
  'docs.upload.failedPassport': 'ضعه مسطّحًا على طاولة بعيدًا عن اللمعان، وصفحة الصورة كاملة في اللقطة، ومعها السطران في الأسفل.',
  'docs.upload.found': 'وجدنا هذا. راجعه قبل الحفظ.',
  'docs.upload.foundPhoto': 'قرأناه من صورتك. راجع كل حرف قبل الحفظ.',
  'docs.upload.checkThis': 'راجع هذا',
  'docs.upload.save': 'احفظ',
  'docs.upload.wrong': 'في شيء غير صحيح',
  'docs.upload.saved': 'حُفظت في المحفظة.',
  'docs.upload.sending': 'نحفظها مشفّرة…',
  'docs.field.type': 'النوع',
  'docs.field.valid': 'سارية',
  'docs.field.name': 'الاسم',
  'docs.field.insurer': 'شركة التأمين',
  'docs.field.covers': 'التغطية',
  'docs.field.policy': 'الوثيقة',
  'docs.field.document': 'الوثيقة',
  'docs.field.number': 'الرقم',
  'docs.field.expires': 'تنتهي',
  'docs.field.photo': 'صورة',
  'docs.field.pdf': 'PDF',
  'docs.field.validUntil': 'سارية حتى (DD/MM/YYYY)',
  'docs.field.validUntilHint': 'لنذكّرك قبل انتهائها.',
  'wallet.upload.wrongType': 'نوع الملف لا يصلح. استخدم صورة أو PDF.',
  'wallet.upload.tooBig': 'الملف أكبر من 10 ميجابايت. جرّب صورة للصفحة بدلًا منه.',
  'wallet.upload.photoOnly': 'نقرأ الجوازات من صورة، لا من PDF. صوّر صفحة الصورة بدلًا منه.',
  'passport.later': 'لاحقًا',
  'passport.title': 'امسحه مرة واحدة. ولا تكتبه بعدها أبدًا.',
  'passport.body': 'كل رحلة طيران وفندق وتأشيرة تتعبّأ تلقائيًا من الآن، لك ولكل من يسافر معك.',
  'passport.lock': 'مشفّر، ولا يُفتح إلا حين تحجز لك مادا.',
  'passport.titleFor': 'امسح جواز {name} مرة واحدة.',
  'passport.scan': 'امسح الجواز',
  'passport.byHand': 'أدخله يدويًا',
  'passport.demo.head': 'المملكة العربية السعودية',
  'passport.demo.type': 'جواز سفر · P',
  'passport.demo.surname': 'اسم العائلة',
  'passport.demo.given': 'الاسم الأول',
  'passport.demo.no': 'الرقم',
  'passport.demo.expires': 'ينتهي',
  'passport.demo.form': 'السعودية · المسافر 1',
  'passport.demo.filled': 'عُبّئ من المسح',
  'passport.demo.nameOnTicket': 'الاسم على التذكرة',
  'passport.demo.passport': 'جواز السفر',
  'passport.demo.valid': 'صالح لهذه الرحلة',
  'passport.camera.title': 'يطلب «مادا» استخدام الكاميرا',
  'passport.camera.body': 'لقراءة جوازك. لا نرفع شيئًا حتى تراجع البيانات.',
  'passport.camera.allow': 'اسمح',
  'passport.camera.deny': 'لا تسمح',
  'passport.camera.deniedTitle': 'بلا كاميرا، ولا مشكلة.',
  'passport.camera.deniedBody': 'أدخل البيانات يدويًا الآن. وتقدر تسمح بالكاميرا لاحقًا من الإعدادات.',
  'passport.camera.doLater': 'لاحقًا',
  'passport.camera.settings': 'افتح الإعدادات',
  'passport.camera.cancel': 'إلغاء',
  'passport.camera.hold': 'صوّر صفحة الصورة',
  'passport.camera.holdBody': 'مسطّحًا على طاولة، بلا لمعان، والسطران في الأسفل داخل اللقطة.',
  'passport.camera.take': 'التقط صورة',
  'passport.camera.choose': 'اختر صورة',
  'passport.camera.useDemo': 'استخدم جواز التجربة',
  'passport.camera.private': 'نقرؤه على هذا الجوال. لا نرفع الصورة ولا نحتفظ بها.',
  'passport.camera.demoTitle': 'ضع صفحة الصورة داخل الإطار',
  'passport.camera.demoBody': 'نقرأ السطرين في الأسفل…',
  'passport.camera.reading': 'نقرأ جوازك…',
  'passport.camera.warming': 'نجهّز القارئ. المسح الأول يأخذ ثواني أكثر.',
  'passport.camera.looking': 'نبحث عن السطرين في الأسفل.',
  'passport.camera.failed': 'لم نتمكن من قراءته.',
  'passport.camera.tip1': 'ضع الجواز مسطّحًا على طاولة.',
  'passport.camera.tip2': 'بلا لمعان. ابتعد عن المصابيح والنوافذ.',
  'passport.camera.tip3': 'أدخل صفحة الصورة كاملة، ومعها السطران في الأسفل.',
  'passport.camera.readerMissing': 'لم يُحمَّل قارئ الجواز. تأكد من اتصالك وحاول مرة أخرى.',
  'passport.camera.notPhoto': 'هذه ليست صورة. اختر صورة JPG أو PNG لصفحة الصورة.',
  'passport.camera.tooBig': 'الصورة أكبر من 10 ميجابايت. جرّب صورة أصغر، أو التقط صورة جديدة.',
  'passport.camera.cantOpen': 'تعذّر فتح الصورة. جرّب JPG أو PNG.',
  'passport.confirm.title': 'هل هذا صحيح؟',
  'passport.confirm.titleManual': 'تمامًا كما في صفحة الصورة.',
  'passport.confirm.bar': 'بيانات الجواز',
  'passport.confirm.body': 'تشترط شركات الطيران أن تطابق الأسماء الجواز حرفًا بحرف، بما فيها كل الأسماء.',
  'passport.confirm.fromPhoto': 'قرأناه من صورتك. راجع كل حرف.',
  'passport.confirm.doubt.one': 'قد لا نكون قرأنا تفصيلًا واحدًا بدقة.',
  'passport.confirm.doubt.two': 'قد لا نكون قرأنا تفصيلين بدقة.',
  'passport.confirm.doubt.few': 'قد لا نكون قرأنا {count} تفاصيل بدقة.',
  'passport.confirm.doubt.other': 'قد لا نكون قرأنا {count} تفصيلًا بدقة.',
  'passport.field.given': 'الاسم الأول والأسماء الأخرى',
  'passport.field.surname': 'اسم العائلة',
  'passport.field.number': 'رقم الجواز',
  'passport.field.nationality': 'الجنسية',
  'passport.field.dob': 'تاريخ الميلاد (DD/MM/YYYY)',
  'passport.field.expiry': 'تاريخ الانتهاء (DD/MM/YYYY)',
  'passport.field.check': 'راجع هذا. قد لا نكون قرأناه بدقة.',
  'passport.field.badDate': 'اكتبه بصيغة DD/MM/YYYY، مثل 22/06/2031.',
  'passport.field.badNumber': 'حروف وأرقام فقط، كما في صفحة الصورة.',
  'passport.field.badCountry': 'اكتب الدولة كما في الجواز، مثل Saudi Arabia.',
  'passport.expired.title': 'انتهت صلاحية هذا الجواز.',
  'passport.expired.body': 'سنحفظه، لكن لا يمكن السفر به. تقدر مادا تساعدك في تجديده.',
  'passport.fillMore.one': 'بقي حقل واحد',
  'passport.fillMore.two': 'بقي حقلان',
  'passport.fillMore.few': 'بقيت {count} حقول',
  'passport.fillMore.other': 'بقي {count} حقلًا',
  'passport.save': 'احفظ الجواز',
  'passport.saveScanned': 'نعم، احفظه',
  'passport.saved': 'حُفظ الجواز. يعبّئ كل حجز من الآن.',
  'passport.savedFor': 'حُفظ جواز {name}.',
  'profile.guest.title': 'أنت تتابع رحلة طيران.',
  'profile.guest.body': 'سجّل دخولك لتحجز، وتحفظ رحلاتك، وتضيف جوازات عائلتك.',
  'profile.guest.signIn': 'سجّل الدخول',
  'profile.yourAccount': 'حسابك',
  'profile.addPhone': 'أضف رقم جوال',
  'profile.addPassport': 'أضف جوازك ليظهر اسمك',
  'profile.details': 'بياناتك',
  'profile.detailsSub': 'الاسم، البريد، الجوال، مطارك الأساسي',
  'profile.account': 'الحساب',
  'profile.signin': 'طرق تسجيل الدخول',
  'profile.signinNone': 'لا شيء',
  'profile.prefs': 'تفضيلات السفر',
  'profile.prefsNoLoyalty': 'لا أرقام عضوية بعد',
  'profile.prefsLoyalty.one': 'رقم عضوية واحد',
  'profile.prefsLoyalty.two': 'رقما عضوية',
  'profile.prefsLoyalty.few': '{count} أرقام عضوية',
  'profile.prefsLoyalty.other': '{count} رقم عضوية',
  'profile.household': 'العائلة',
  'profile.justYou': 'أنت فقط',
  'profile.household.youNoPassport': 'جوازك لم يُمسح بعد · أضف عائلتك',
  'profile.household.addFamily': 'أضف عائلتك لتحجز للجميع',
  'profile.household.needs.one': 'جواز واحد يحتاج نظرة',
  'profile.household.needs.two': 'جوازان يحتاجان نظرة',
  'profile.household.needs.few': '{count} جوازات تحتاج نظرة',
  'profile.household.needs.other': '{count} جوازًا يحتاج نظرة',
  'profile.household.allGood': 'جوازات الجميع ممسوحة',
  'profile.paying': 'الدفع',
  'profile.noCards': 'لا بطاقات محفوظة',
  'profile.noCardsSub': 'أضف بطاقة عند الحجز، أو الآن.',
  'profile.noCardsApplePay': 'لا بطاقات محفوظة. Apple Pay يعمل على هذا الجوال.',
  'profile.credit': '{amount} رصيد مادا',
  'profile.creditSub': 'يُستخدم أولًا في حجزك القادم.',
  'profile.changeCard': 'غيّر الافتراضية أو أضف بطاقة',
  'profile.addCard': 'أضف بطاقة',
  'profile.alerts': 'التنبيهات',
  'profile.alerts.quiet': 'هادئة',
  'profile.alerts.everything': 'كل شيء',
  'profile.alerts.label': 'كم مرة ننبهك',
  'profile.alerts.quietBody': 'فقط حين يلزمك فعل شيء: تغيّر البوابة، التأخير، وقت الانطلاق، الوثائق. والباقي ينتظر ملخص المساء.',
  'profile.alerts.everythingBody': 'كل تحديث عن رحلاتك لحظة حدوثه. ولا عروض أبدًا.',
  'profile.alerts.off': 'تنبيهات مادا مغلقة على هذا الجوال. فعّلها من الإعدادات لتصلك تغييرات البوابة.',
  'profile.app': 'التطبيق',
  'profile.language': 'اللغة',
  'profile.languageSub': 'English · العربية',
  'profile.languageSubNotify': 'English · العربية',
  'profile.security': 'الأمان',
  'profile.securitySub.one': '{face} · جهاز واحد',
  'profile.securitySub.two': '{face} · جهازان',
  'profile.securitySub.few': '{face} · {count} أجهزة',
  'profile.securitySub.other': '{face} · {count} جهازًا',
  'profile.faceOn': 'Face ID مفعّل',
  'profile.faceOff': 'Face ID مغلق',
  'profile.privacy': 'الخصوصية',
  'profile.privacySub': 'التنزيل، الحذف، وما نحتفظ به',
  'profile.privacySubPending': 'نسختك في الطريق إلى بريدك',
  'profile.help': 'المساعدة',
  'profile.helpSub': 'أسئلة، تحدّث مع مادا، الشروط',
  'profile.inbox': 'التحديثات',
  'profile.inboxSub.zero': 'لا جديد',
  'profile.inboxSub.one': 'تحديث جديد',
  'profile.inboxSub.two': 'تحديثان جديدان',
  'profile.inboxSub.few': '{count} تحديثات جديدة',
  'profile.inboxSub.other': '{count} تحديثًا جديدًا',
  'profile.signOut': 'سجّل الخروج',
  'profile.version': 'مادا للرحلات {version}',
  'profile.photoChange': 'غيّر الصورة',
  'profile.photoAdd': 'أضف صورة',
  'account.title': 'بياناتك',
  'account.intro': 'كل تفصيل يوضّح مصدره. تستخدمها مادا في كل حجز.',
  'account.name': 'الاسم',
  'account.passportName': 'الاسم في جوازك',
  'account.notScanned': 'لم يُمسح بعد',
  'account.calledYou': 'الاسم الذي تناديك به مادا',
  'account.addName': 'أضف اسمًا',
  'account.nameWait': 'سنستخدم اسمك الأول حين نضيف جوازك',
  'account.contact': 'التواصل',
  'account.email': 'البريد الإلكتروني',
  'account.notAdded': 'لم يُضف',
  'account.emailWarn': 'أضفه لتصلك التذاكر والإيصالات',
  'account.mobile': 'الجوال',
  'account.mobileWarn': 'أضفه لتصلك تغييرات البوابة ورسائل فيصل',
  'account.fromPassport': 'من جوازك',
  'account.dob': 'تاريخ الميلاد',
  'account.nationality': 'الجنسية',
  'account.forBookings': 'للحجوزات',
  'account.home': 'مطارك الأساسي',
  'account.language': 'اللغة',
  'account.currency': 'عرض الأسعار بـ',
  'account.src.passport': 'من مسح جوازك',
  'account.src.typed': 'كتبته بنفسك',
  'account.src.apple': 'من تسجيل الدخول عبر Apple',
  'account.src.google': 'من تسجيل الدخول عبر Google',
  'account.src.signup': 'تحققنا منه برسالة نصية عند التسجيل',
  'account.src.verified': 'موثّق',
  'account.src.verifiedOn': 'وُثّق في {date}',
  'account.src.default': 'الإعداد الافتراضي في مادا',
  'account.src.none': 'لم يُمسح بعد',
  'account.src.added': 'حُدد حين أضفتهم',
  'account.locked.nameTitle': 'يأتي من جوازك.',
  'account.locked.fieldTitle': 'مقروء من جوازك.',
  'account.locked.nameBody': 'تشترطه شركات الطيران حرفًا بحرف. لتغييره، امسح جوازًا جديدًا.',
  'account.locked.fieldBody': 'يطابق جوازك دائمًا. لتغييره، امسح جوازًا جديدًا.',
  'account.locked.notYet': 'لم تمسح جوازك بعد.',
  'account.locked.scanNew': 'امسح جوازًا جديدًا',
  'account.locked.scanMine': 'امسح جوازي',
  'account.preferred.title': 'بماذا نناديك؟',
  'account.preferred.body': 'نستخدمه في رسائل مادا وفيصل. التذاكر تحمل دائمًا الاسم الذي في جوازك.',
  'account.preferred.empty': 'أضف الاسم الذي تحب أن نناديك به.',
  'account.preferred.long': 'أقل من 30 حرفًا.',
  'account.preferred.letters': 'حروف فقط.',
  'account.preferred.save': 'احفظ الاسم',
  'account.preferred.saved': 'سنناديك {name}.',
  'account.preferred.usePassport': 'استخدم الاسم الذي في جوازي',
  'account.preferred.reset': 'سنستخدم الاسم الذي في جوازك.',
  'account.email.yours': 'بريدك',
  'account.email.new': 'البريد الجديد',
  'account.email.add': 'أضف بريدك',
  'account.email.body': 'التذاكر والإيصالات وخطابات التأشيرة تصل هنا. نرسل رمزًا لنتأكد أنه بريدك.',
  'account.email.bad': 'هذا لا يبدو بريدًا إلكترونيًا. تأكد من وجود @ ونقطة.',
  'account.email.same': 'هذا بريدك الحالي.',
  'account.email.send': 'أرسلوا لي رمزًا',
  'account.email.relayTitle': 'عنوان خاص من Apple',
  'account.email.relayBody': 'اخترت «إخفاء بريدي» عند تسجيل الدخول. ما نرسله إلى هذا العنوان يُحوَّل إلى بريد Apple ID. تقدر تبقيه، أو تستخدم بريدك.',
  'account.email.useOwn': 'استخدم بريدي',
  'account.email.change': 'غيّر البريد',
  'account.email.keep': 'أبقِ هذا',
  'account.email.verified': 'تحققنا من بريدك. التذاكر والإيصالات تصل إليه من الآن.',
  'account.code.title': 'أدخل الرمز',
  'account.code.sentTo': 'أرسلناه إلى {to}.',
  'account.code.change': 'غيّر',
  'account.code.label': 'رمز من 6 أرقام',
  'account.code.wrong.one': 'الرمز غير مطابق. بقيت محاولة واحدة.',
  'account.code.wrong.two': 'الرمز غير مطابق. بقيت محاولتان.',
  'account.code.wrong.few': 'الرمز غير مطابق. بقيت {count} محاولات.',
  'account.code.wrong.other': 'الرمز غير مطابق. بقيت {count} محاولة.',
  'account.code.locked': 'محاولات كثيرة. اطلب رمزًا جديدًا لتكمل.',
  'account.code.newIn': 'رمز جديد بعد 0:{seconds}',
  'account.code.resend': 'أرسل رمزًا جديدًا',
  'account.code.resent': 'أرسلنا رمزًا جديدًا.',
  'account.code.offline': 'أنت غير متصل. نرسله حين يعود الاتصال.',
  'account.code.demo': 'رمز التجربة: 123456',
  'account.phone.change': 'غيّر رقمك',
  'account.phone.add': 'أضف رقمك',
  'account.phone.now': 'الرقم الحالي {phone}.',
  'account.phone.body': 'نرسل رمزًا إلى الرقم الجديد لنتأكد أنه رقمك.',
  'account.phone.label': 'رقم الجوال الجديد',
  'account.phone.same': 'هذا رقمك الحالي.',
  'account.phone.taken': 'هذا الرقم مسجّل في حساب آخر في مادا. سجّل الدخول به هناك، أو اطلب من مادا نقله إلى هذا الحساب.',
  'account.phone.switchTo': 'تنتقل إلى {phone}؟',
  'account.phone.use': 'تستخدم {phone}؟',
  'account.phone.stops': 'يتوقف',
  'account.phone.fromNow': 'من الآن',
  'account.phone.confirmBody': 'رقمك القديم يتوقف عن تسجيل الدخول فورًا. رسائل الرحلة ومكالمات فيصل تذهب إلى الجديد. وتصله شركات الطيران في الرحلات المحجوزة أيضًا.',
  'account.phone.useNew': 'استخدم الرقم الجديد',
  'account.phone.keepOld': 'أبقِ رقمي القديم',
  'account.phone.changed': 'تغيّر الرقم. استخدمه في تسجيل الدخول القادم.',
  'account.phone.added': 'أُضيف. تقدر تسجّل الدخول به أيضًا.',
  'account.offline': 'أنت غير متصل. نرسل الرمز حين يعود الاتصال.',
  'account.home.title': 'من أين تسافر عادةً؟',
  'account.home.main': 'المطارات الرئيسية',
  'account.home.other': 'مطار آخر',
  'account.home.placeholder': 'المدينة أو الرمز من 3 أحرف',
  'account.home.none': 'لا يوجد مطار سعودي يطابق «{q}». جرّب اسم المدينة أو الرمز من 3 أحرف. للمطارات في الخارج، اسأل مادا.',
  'account.home.saved': 'تبدأ رحلاتك من {code} ما لم تقل غير ذلك.',
  'account.language.title': 'اللغة',
  'account.language.arabicSub': 'كتبها كاتب سعودي، لا ترجمة آلية.',
  'account.language.next': 'التالي',
  'account.language.notify': 'أخبرني حين تجهز العربية',
  'account.language.notifySub': 'تنبيه واحد، ثم لا شيء.',
  'account.language.notifyOn': 'نخبرك حين تجهز العربية.',
  'account.language.done': 'تم',
  'account.currency.title': 'اعرض الأسعار بـ',
  'account.currency.note': 'الدفع دائمًا بالريال السعودي. العملات الأخرى تقريبية، بسعر اليوم.',
  'account.currency.sar': 'الأسعار بالريال السعودي.',
  'account.currency.other': 'الأسعار تظهر بـ {code} أيضًا. والدفع يبقى بالريال السعودي.',
  'account.photo.title': 'صورتك',
  'account.photo.added': 'أُضيفت في {date}. يراها فيصل ومجموعاتك.',
  'account.photo.body': 'يراها فيصل ومجموعاتك. ولا تظهر في أي حجز.',
  'account.photo.take': 'التقط صورة',
  'account.photo.choose': 'اختر صورة',
  'account.photo.remove': 'احذف الصورة',
  'account.photo.removed': 'حُذفت الصورة.',
  'account.photo.updated': 'تحدّثت الصورة.',
  'account.photo.rules': 'JPEG أو PNG، حتى 10 ميجابايت.',
  'account.photo.notPhoto': 'هذا الملف ليس صورة. اختر JPEG أو PNG.',
  'account.photo.tooBig': 'الصورة أكبر من 10 ميجابايت. اختر صورة أصغر.',
  'signinMethods.title': 'طرق تسجيل الدخول',
  'signinMethods.body': 'طرق الدخول إلى حسابك. احتفظ باثنتين على الأقل، حتى لا يقفل ضياع واحدة الباب عليك.',
  'signinMethods.apple': 'Apple',
  'signinMethods.appleSub': 'Face ID أو كلمة مرور Apple',
  'signinMethods.google': 'Google',
  'signinMethods.googleSub': 'حسابك في Google',
  'signinMethods.phone': 'رقم الجوال',
  'signinMethods.phoneSub': 'رمز برسالة نصية',
  'signinMethods.hideOn': '«إخفاء بريدي» مفعّل',
  'signinMethods.notLinked': 'غير مربوط',
  'signinMethods.linked': 'مربوط',
  'signinMethods.add': 'أضف',
  'signinMethods.onlyOne': 'طريقة دخول واحدة فقط.',
  'signinMethods.onlyOneBody': 'أضف طريقة أخرى لتبقى قادرًا على الدخول إن فقدت هذه.',
  'signinMethods.hideTitle': 'عن «إخفاء بريدي»',
  'signinMethods.hideBody': 'حين تسجّل الدخول عبر Apple تقدر تخفي عنوانك الحقيقي. تعطينا Apple عنوانًا خاصًا يحوّل الرسائل إليك. وتقدر توقفه متى شئت من إعدادات الآيفون، ضمن Apple ID، ثم «تسجيل الدخول باستخدام Apple».',
  'signinMethods.addTitle': 'تضيف {name} كطريقة دخول؟',
  'signinMethods.addApple': 'تشارك Apple اسمك وبريدًا إلكترونيًا. وتقدر تخفي عنوانك الحقيقي.',
  'signinMethods.addGoogle': 'تشارك Google اسمك وبريدك الإلكتروني فقط. لا شيء غير ذلك.',
  'signinMethods.continue': 'المتابعة مع {name}',
  'signinMethods.offline': 'أنت غير متصل. اتصل لتضيف طريقة دخول.',
  'signinMethods.added': 'أُضيف {name}. تقدر تسجّل الدخول به الآن.',
  'signinMethods.phoneManage': 'تسجّل الدخول برمز يُرسل إلى {phone}. لاستخدام رقم آخر، غيّره من «بياناتك».',
  'signinMethods.canSignIn': 'تقدر تسجّل الدخول عبر {name}.',
  'signinMethods.onlyWay': 'هذه طريقتك الوحيدة للدخول.',
  'signinMethods.onlyWayBody': 'أضف طريقة أخرى قبل أن تحذف هذه.',
  'signinMethods.relayNote': 'بريدك هو العنوان الخاص من Apple. الرسائل تصلك عليه، لكن نقترح إضافة بريدك الشخصي في «بياناتك».',
  'signinMethods.remove': 'احذف {name}',
  'signinMethods.removed': 'حُذف {name}. لم يعد بإمكانك الدخول به.',
  'signinMethods.keep': 'أبقِه',
  'signinMethods.taken': 'حساب {name} هذا مرتبط بحساب آخر في مادا.',
  'prefs.title': 'تفضيلات السفر',
  'prefs.body': 'يستخدمها فيصل في كل حجز لك. غيّرها متى شئت. والرحلات المحجوزة تبقى على ما طُلب لها.',
  'prefs.seats': 'المقاعد',
  'prefs.seat.window': 'نافذة',
  'prefs.seat.aisle': 'ممر',
  'prefs.seat.any': 'بلا تفضيل',
  'prefs.seat.anyShort': 'أي مقعد',
  'prefs.together': 'أجلسنا مع العائلة معًا',
  'prefs.togetherSub': 'ندفع رسوم اختيار المقاعد حين تفرضها شركة الطيران، ونخبرك قبلها.',
  'prefs.meal': 'الوجبة',
  'prefs.meal.halal': 'حلال',
  'prefs.meal.veg': 'نباتية',
  'prefs.meal.vegan': 'نباتية صرفة',
  'prefs.meal.child': 'وجبة أطفال',
  'prefs.meal.diabetic': 'لمرضى السكري',
  'prefs.meal.gluten': 'خالية من الغلوتين',
  'prefs.meal.lowsalt': 'قليلة الملح',
  'prefs.meal.halalNote': 'كل الوجبات على الخطوط السعودية حلال. وفي الشركات الأخرى نطلبها لك.',
  'prefs.meal.childNote': 'وجبات الأطفال من عمر 2 إلى 11. وللكبار نطلب وجبة خفيفة.',
  'prefs.meal.otherNote': 'نطلبها عند الحجز. تحتاجها شركات الطيران قبل الرحلة بـ 24 ساعة.',
  'prefs.assist': 'مساعدة في المطار',
  'prefs.assist.wchr': 'كرسي متحرك حتى البوابة',
  'prefs.assist.wchrSub': 'تقدر تمشي مسافات قصيرة وتصعد الدرج.',
  'prefs.assist.wchc': 'كرسي متحرك حتى المقعد',
  'prefs.assist.wchcSub': 'مساعدة كاملة حتى مقعدك في الطائرة.',
  'prefs.assist.infant': 'مسافر مع رضيع',
  'prefs.assist.infantSub': 'دون السنتين، في الحضن. تحتاج شركات الطيران أن تعرف عند الحجز.',
  'prefs.assist.bassinet': 'سرير أطفال',
  'prefs.assist.bassinetSub': 'سرير مثبّت على الجدار أمامك. عدده محدود، لذلك نطلبه مبكرًا.',
  'prefs.assist.bassinetOff': 'فعّل «مسافر مع رضيع» أولًا.',
  'prefs.loyalty': 'أرقام العضوية',
  'prefs.loyalty.emptyTitle': 'لا أرقام عضوية بعد',
  'prefs.loyalty.emptyBody': 'أضف الفرسان أو برنامج فندق، وكل حجز نعمله يكسبك نقاطًا.',
  'prefs.loyalty.add': 'أضف رقم عضوية',
  'prefs.loyalty.edit': 'عدّل {name}',
  'prefs.loyalty.airlines': 'شركات الطيران',
  'prefs.loyalty.hotels': 'الفنادق',
  'prefs.loyalty.number': 'رقم العضوية',
  'prefs.loyalty.dup': 'لديك رقم {name} مسبقًا. عدّله بدلًا من إضافة جديد.',
  'prefs.loyalty.bad': 'هذا لا يبدو رقم {name}. شكله {hint}.',
  'prefs.loyalty.save': 'احفظ الرقم',
  'prefs.loyalty.saved': 'حُفظ {name}. نضيفه إلى كل حجز يكسب نقاطًا.',
  'prefs.loyalty.remove': 'احذف',
  'prefs.loyalty.removedAirline': 'حُذف {name}. النقاط المكتسبة تبقى لدى شركة الطيران.',
  'prefs.loyalty.removedHotel': 'حُذف {name}. النقاط المكتسبة تبقى لدى الفندق.',
  'prefs.notes': 'ملاحظات لفيصل',
  'prefs.notesHint': 'أي شيء يساعد، مثل «حصة تفضّل الرحلات الصباحية» أو «أحمد يتعب من السفر».',
  'prefs.notesSaved': 'حُفظت لفيصل.',
  'household.title': 'العائلة',
  'household.body': 'كل من تحجز لهم. جوازاتهم وتفضيلاتهم تعبّئ كل رحلة.',
  'household.you': '{name} (أنت)',
  'household.youPlain': 'أنت',
  'household.holder': 'صاحب الحساب',
  'household.emptyTitle': 'أنت فقط حتى الآن.',
  'household.emptyBody': 'أضف من تحجز لهم. أسماؤهم وجوازاتهم تعبّئ كل رحلة، فلا يكتبها أحد مرتين.',
  'household.note': 'الجوازات تُمسح في المحفظة وتبقى مشفّرة.',
  'household.add': 'أضف شخصًا',
  'household.status.none': 'لم يُمسح',
  'household.status.problem': 'يحتاج تجديدًا',
  'household.status.expired': 'منتهٍ',
  'household.status.soon': 'على وشك الانتهاء',
  'household.status.ok': 'ممسوح',
  'household.status.expiredText': 'انتهى في {date}. لا يمكن السفر به.',
  'household.status.soonText': 'ينتهي في {date}. دول كثيرة تشترط 6 أشهر صلاحية عند الوصول.',
  'household.age.infant': 'رضيع · دون السنتين',
  'household.age.child': 'طفل · {age}',
  'household.age.teen': 'مراهق · {age}',
  'household.age.adult': 'بالغ · {age}',
  'household.age.infantNote': 'يسافر في الحضن أو في سرير أطفال. يحتاج جوازًا خاصًا به.',
  'household.age.childNote': 'سعر طفل في أغلب شركات الطيران، من 2 إلى 11.',
  'household.age.teenNote': 'سعر بالغ من 12. لكنه قاصر في التأشيرات وخطابات الموافقة.',
  'household.gone': 'لم يعد ضمن عائلتك.',
  'household.youHolder': 'أنت · صاحب الحساب',
  'household.passport': 'جواز السفر',
  'household.notScannedYou': 'جوازك لم يُمسح بعد.',
  'household.notScanned': 'جواز {name} لم يُمسح بعد.',
  'household.expiresLine': '{number} · ينتهي {date}',
  'household.scanMine': 'امسح جوازي',
  'household.scanTheirs': 'امسح جوازه',
  'household.scanNew': 'امسح الجواز الجديد',
  'household.details': 'التفاصيل',
  'household.relation': 'صلة القرابة',
  'household.yourDetails': 'بياناتك وتفضيلاتك',
  'household.yourDetailsSub': 'الاسم، التواصل، المقاعد، الوجبات',
  'household.residency': 'الإقامة',
  'household.iqama': 'رقم الإقامة',
  'household.iqamaLength': 'رقم الإقامة من 10 أرقام (هذا فيه {count}).',
  'household.iqamaPrefix': 'أرقام الإقامة تبدأ بـ 2. وأرقام الهوية الوطنية تبدأ بـ 1.',
  'household.iqamaSaved': 'حُفظ رقم الإقامة.',
  'household.exit': 'تأشيرة خروج وعودة',
  'household.exit.none': 'لا يوجد بعد',
  'household.exit.single': 'مفردة',
  'household.exit.multiple': 'متعددة',
  'household.exit.useBy': 'تُستخدم قبل (DD/MM/YYYY)',
  'household.exit.needed': 'مطلوبة قبل سفر {name} للخارج. تصدرها من أبشر بصفتك الكفيل.',
  'household.exit.addDate': 'أضف آخر موعد لاستخدامها.',
  'household.exit.expired': 'انتهت في {date}. أصدر تأشيرة جديدة من أبشر قبل أي رحلة.',
  'household.exit.valid': 'سارية حتى {date} · باقي {days} يومًا.',
  'household.remove': 'أزل {name} من العائلة',
  'household.remove.title': 'تزيل {name}؟',
  'household.remove.body': 'نحذف جواز {name} وتفضيلاته. الحجوزات السابقة تبقى كما هي. وتقدر تضيفه من جديد متى شئت.',
  'household.remove.confirm': 'أزل {name}',
  'household.remove.keep': 'أبقِ {name}',
  'household.removed': 'أُزيل {name} من عائلتك.',
  'household.relation.title': '{name} بالنسبة لك…',
  'household.relation.note': 'بعض التأشيرات وخطابات الموافقة تسأل عن صلة القرابة.',
  'household.saved': 'حُفظ.',
  'household.addTitle': 'أضف شخصًا',
  'household.addBody': 'الأسماء كما في الجواز تمامًا. وتقدر تمسحه لاحقًا من المحفظة.',
  'household.addGiven': 'الاسم الأول والأسماء الأخرى',
  'household.addSurname': 'اسم العائلة',
  'household.addHelperNote': 'نطلب رقم الإقامة وتأشيرة الخروج والعودة قبل أي سفر للخارج.',
  'household.addButton': 'أضف {name}',
  'household.addThem': 'أضفه',
  'household.added': 'أُضيف {name}. امسح جوازه من المحفظة حين تتمكن.',
  'household.relation.Spouse': 'الزوج أو الزوجة',
  'household.relation.Son': 'ابن',
  'household.relation.Daughter': 'ابنة',
  'household.relation.Parent': 'أحد الوالدين',
  'household.relation.Sibling': 'أخ أو أخت',
  'household.relation.Relative': 'قريب',
  'household.relation.Friend': 'صديق',
  'household.relation.Helper': 'عاملة منزلية',
  'household.relation.Colleague': 'زميل',
  'household.relation.Family': 'العائلة',
  'security.title': 'الأمان',
  'security.wallet': 'المحفظة',
  'security.faceId': 'Face ID للمحفظة',
  'security.checking': 'نتحقق من Face ID…',
  'security.on': 'الجوازات لا تُفتح إلا بعد Face ID أو رمز المرور.',
  'security.off': 'مغلق. أي شخص معه جوالك مفتوحًا يقدر يفتح الجوازات.',
  'security.faceFailed': 'لم يتعرّف Face ID عليك. حاول مرة أخرى، أو جهّزه من إعدادات الآيفون.',
  'security.faceOnToast': 'المحفظة تُقفل بـ Face ID.',
  'security.signedInOn': 'مسجّل الدخول على',
  'security.thisPhone': 'هذا الجوال',
  'security.signOut': 'سجّل الخروج',
  'security.onlyThis': 'هذا الجوال وحده مسجّل الدخول.',
  'security.onlyThisBody': 'إن سجّلت الدخول من آيباد أو من الويب، يظهر هنا، وتقدر تُخرجه من هذا الجوال.',
  'security.unknown': 'جهاز لا تعرفه؟ أخرجه، ثم أخبر مادا.',
  'security.everywhere': 'سجّل الخروج من كل الأجهزة',
  'security.faceOff.title': 'تُغلق Face ID للمحفظة؟',
  'security.faceOff.body': 'ستُفتح الجوازات والتأشيرات دون تحقق. أي شخص معه جوالك مفتوحًا يقدر يراها.',
  'security.faceOff.confirm': 'أغلقه',
  'security.faceOff.keep': 'أبقِ Face ID',
  'security.faceOff.done': 'أُغلق Face ID للمحفظة.',
  'security.device.title': 'تُخرج {name}؟',
  'security.device.body': 'سيحتاج Apple أو Google أو رمزًا ليعود. وما حُفظ على ذلك الجهاز وحده يُحذف منه.',
  'security.device.confirm': 'أخرج {name}',
  'security.device.offline': 'أنت غير متصل. اتصل لتُخرج جهازًا آخر.',
  'security.device.done': 'خرجنا من {name}.',
  'security.device.sub': '{platform} · {when}',
  'security.device.now': 'الآن',
  'security.device.web': 'madatrips.sa على الويب',
  'security.device.unknown': 'جوال',
  'signout.title': 'تسجّل الخروج؟',
  'signout.titleEverywhere': 'تسجّل الخروج من كل الأجهزة؟',
  'signout.body': 'رحلاتك تبقى في حسابك في الحالتين. ماذا يبقى على هذا الجوال؟',
  'signout.bodyEverywhere': 'كل الأجهزة، ومنها هذا الجوال. رحلاتك تبقى في حسابك في الحالتين. ماذا يبقى على هذا الجوال؟',
  'signout.keep': 'أبقِ رحلاتي على هذا الجوال',
  'signout.keepBody': 'أسرع حين تعود. جوازك يبقى مشفّرًا ومقفلًا حتى تسجّل الدخول.',
  'signout.keepBodyFamily.one': 'أسرع حين تعود. جوازك وجواز شخص آخر تبقى مشفّرة ومقفلة حتى تسجّل الدخول.',
  'signout.keepBodyFamily.two': 'أسرع حين تعود. جوازك وجوازا شخصين آخرين تبقى مشفّرة ومقفلة حتى تسجّل الدخول.',
  'signout.keepBodyFamily.few': 'أسرع حين تعود. جوازك وجوازات {count} آخرين تبقى مشفّرة ومقفلة حتى تسجّل الدخول.',
  'signout.keepBodyFamily.other': 'أسرع حين تعود. جوازك وجوازات {count} آخرين تبقى مشفّرة ومقفلة حتى تسجّل الدخول.',
  'signout.remove': 'احذف كل شيء من هذا الجوال',
  'signout.removeBody': 'لجوال مشترك أو مستعار. نمسح منه الرحلات والجوازات والبطاقات والصور. سجّل الدخول مرة أخرى لتستعيدها.',
  'privacy.title': 'الخصوصية',
  'privacy.yours': 'نسختك',
  'privacy.export': 'نزّل كل شيء',
  'privacy.exportSub': 'الرحلات والوثائق والمدفوعات والرسائل، في ملف واحد.',
  'privacy.exportPending': 'النسخة في الطريق',
  'privacy.exportPendingSub': 'طلبتها في {date} الساعة {time}. يصل رابط إلى {email} خلال 24 ساعة.',
  'privacy.pending': 'قيد التنفيذ',
  'privacy.keep': 'ما نحتفظ به، ولماذا',
  'privacy.keep.passports': 'الجوازات والهويات',
  'privacy.keep.passportsWhy': 'لحجز الطيران والفنادق والتأشيرات. مشفّرة. ولا تُرسل إلا لشركة الطيران أو الفندق أو السفارة عند الحجز.',
  'privacy.keep.contact': 'الاسم والجوال والبريد',
  'privacy.keep.contactWhy': 'لتسجيل دخولك والتواصل معك بشأن رحلاتك.',
  'privacy.keep.trips': 'الرحلات والمدفوعات',
  'privacy.keep.tripsWhy': 'لتراها وتغيّرها. أرقام البطاقات يحفظها مزوّد الدفع، لا مادا.',
  'privacy.keep.prefs': 'التفضيلات',
  'privacy.keep.prefsWhy': 'المقاعد والوجبات وأرقام العضوية، لتعبئة الحجوزات.',
  'privacy.keep.location': 'الموقع',
  'privacy.keep.locationWhy': 'في أيام السفر فقط، لنحسب وقت طريقك. وفي «من حولك» حين تفعّله.',
  'privacy.keep.usage': 'استخدام التطبيق',
  'privacy.keep.usageWhy': 'إن سمحت. لنعرف ما هو بطيء. لا نبيعه، ولا نستخدمه للإعلانات.',
  'privacy.choose': 'أنت تختار',
  'privacy.marketing': 'عروض بالبريد',
  'privacy.marketingSub': 'مغلقة إلا إن طلبتها. رسالة واحدة في الشهر على الأكثر.',
  'privacy.analytics': 'ساعدنا في تحسين التطبيق',
  'privacy.analyticsSub': 'استخدام مجهول الهوية، مثل الشاشات البطيئة.',
  'privacy.delete': 'احذف حسابي',
  'privacy.footer': 'لا نبيع أبدًا ما تشاركه معنا. أرسل أسئلتك إلى privacy@madatrips.sa.',
  'privacy.export.title': 'تريد نسخة من كل شيء؟',
  'privacy.export.body': 'نرسل لك رابط تنزيل بالبريد خلال 24 ساعة. يعمل الرابط 7 أيام.',
  'privacy.export.bodyTo': 'نرسل رابط تنزيل إلى {email} خلال 24 ساعة. يعمل الرابط 7 أيام.',
  'privacy.export.needEmail': 'أضف بريدًا في «بياناتك» أولًا، ليكون لدينا مكان نرسلها إليه.',
  'privacy.export.confirm': 'أرسلوا نسختي بالبريد',
  'privacy.export.offline': 'أنت غير متصل. اطلبها حين يعود الاتصال.',
  'privacy.export.done': 'وصل طلبك. نرسل الرابط بالبريد خلال 24 ساعة.',
  'privacy.delete.title': 'تحذف حسابك؟',
  'privacy.delete.body': 'بعد 30 يومًا نحذف رحلاتك ووثائقك وعائلتك وتفضيلاتك. وحتى ذلك الحين تقدر تغيّر رأيك.',
  'privacy.delete.bookings': 'الحجوزات السابقة تبقى لدى شركة الطيران والفندق.',
  'privacy.delete.bookingsTrip': 'الحجوزات السابقة تبقى لدى شركة الطيران والفندق، ومنها {city} في {date}.',
  'privacy.delete.refunds': 'المبالغ المستردة الجارية تصل إلى بطاقتك كما هي.',
  'privacy.delete.receipts': 'نحتفظ بالإيصالات 5 سنوات، لأن النظام يطلب ذلك.',
  'privacy.delete.type': 'اكتب DELETE للتأكيد',
  'privacy.delete.typeWord': 'اكتب كلمة DELETE.',
  'privacy.delete.confirm': 'احذف بعد 30 يومًا',
  'privacy.delete.keep': 'أبقِ حسابي',
  'privacy.delete.scheduled': 'مجدول في {date}.',
  'privacy.banner.title': 'الحذف مجدول في {date}.',
  'privacy.banner.body': 'كل شيء يبقى حتى ذلك اليوم. والحجوزات تبقى لدى شركات الطيران.',
  'privacy.banner.cancel': 'ألغِ الحذف',
  'privacy.banner.cancelled': 'أُلغي الحذف. حسابك باقٍ.',
  'privacy.exportEmail.subject': 'نسختك من مادا للرحلات',
  'privacy.exportEmail.body': 'هذه كل ما تحتفظ به مادا للرحلات لك، كما طلبت. الرابط يعمل 7 أيام: {link}',
  'help.title': 'المساعدة',
  'help.talk': 'تحدّث مع مادا',
  'help.talkBody': 'يرد عليك شخص، ليلًا ونهارًا. عادةً خلال 5 دقائق.',
  'help.whatsapp': 'واتساب',
  'help.call': 'اتصال',
  'help.faq': 'أسئلة متكررة',
  'help.q1': 'من يحجز رحلتي؟',
  'help.a1': 'شخص من فريق مادا، غالبًا فيصل. كل حجز يُراجع ويُؤكَّد يدويًا، وترى اسم من أكّده.',
  'help.q2': 'هل أقدر أغيّر حجزًا أو ألغيه؟',
  'help.a2': 'نعم. افتح الرحلة واضغط «تغيير». نعرض رسوم شركة الطيران قبل أي خطوة، ولا يتغير شيء حتى توافق.',
  'help.q3': 'متى يصل المبلغ المسترد إلى بطاقتي؟',
  'help.a3': 'نرسله في اليوم الذي تفرج عنه شركة الطيران أو الفندق. ثم تحتاج البنوك من 5 إلى 14 يومًا لإظهاره. وتتابع كل خطوة في «الرحلات».',
  'help.q4': 'هل جوازي آمن في التطبيق؟',
  'help.a4': 'مشفّر ومقفل بـ Face ID. لا نفتحه إلا لنحجز لك، ولا نبيعه أبدًا.',
  'help.q5': 'هل أقدر أحجز لعائلتي وللعاملة المنزلية؟',
  'help.a5': 'نعم. أضفهم إلى عائلتك مرة واحدة. جوازاتهم تعبّئ كل حجز، وللعاملة المنزلية نتحقق أولًا من الإقامة وتأشيرة الخروج والعودة.',
  'help.q6': 'ماذا يحدث إن تأخرت رحلتي أو أُلغيت؟',
  'help.a6': 'نراقب كل رحلة. إن تغيّرت، نحجز مقاعد على رحلات أخرى ونعرض عليك الخيارات. فيصل والفريق موجودون ليلًا ونهارًا.',
  'help.legal': 'الشروط والسياسات',
  'help.terms': 'شروط الاستخدام',
  'help.privacy': 'سياسة الخصوصية',
  'help.version': 'مادا للرحلات {version}',
  'help.callTitle': 'اتصل بمادا',
  'help.callBody': '{phone}. ليلًا ونهارًا، بالعربية أو الإنجليزية. جهّز رمز الحجز إن كان الأمر عن رحلة.',
  'help.callNow': 'اتصل الآن',
  'help.opening': 'نفتح واتساب: {phone}',
  'legal.updated': 'حُدّثت في 1 أكتوبر 2026',
  'legal.terms.1h': 'من نحن',
  'legal.terms.1b': 'تديرها مادا للسفر والسياحة، وكالة سفر مرخّصة في الرياض. كل رحلة يحجزها أشخاص من فريق مادا.',
  'legal.terms.2h': 'الحجوزات',
  'legal.terms.2b': 'حين تؤكد، نحجز باسمك لدى شركة الطيران أو الفندق أو المزوّد. وتنطبق قواعد أسعارهم، ونعرضها قبل أن تدفع.',
  'legal.terms.3h': 'الدفع',
  'legal.terms.3b': 'الأسعار بالريال السعودي وتشمل كل رسم نعرفه. إن تغيّر سعر قبل الحجز، نسألك أولًا.',
  'legal.terms.4h': 'التغيير والاسترداد',
  'legal.terms.4b': 'ننقل رسوم المزوّد كما هي، ولا نضيف رسومًا من عندنا على التغييرات التي تعملها في التطبيق.',
  'legal.terms.5h': 'حسابك',
  'legal.terms.5b': 'احتفظ ببيانات دخولك لنفسك. أنت مسؤول عن الحجوزات التي تتم من حسابك.',
  'legal.privacy.1h': 'ما نجمعه',
  'legal.privacy.1b': 'بياناتك، وجوازات عائلتك، ورحلاتك ومدفوعاتك، وموقعك في أيام السفر إن سمحت.',
  'legal.privacy.2h': 'لماذا',
  'legal.privacy.2b': 'لنحجز رحلاتك ونرعاها. لا شيء غير ذلك.',
  'legal.privacy.3h': 'من يراها',
  'legal.privacy.3b': 'أشخاص من فريق مادا يعملون على رحلاتك، وشركات الطيران والفنادق والسفارات التي نحجز معها. لا نبيعها أبدًا.',
  'legal.privacy.4h': 'أين تُحفظ',
  'legal.privacy.4b': 'الجوازات مشفّرة. وكل شيء محفوظ في المملكة العربية السعودية، وفق نظام حماية البيانات الشخصية.',
  'legal.privacy.5h': 'حقوقك',
  'legal.privacy.5b': 'نزّلها أو صحّحها أو احذفها متى شئت، من «الخصوصية» في التطبيق.',
  'support.presenceLine': '{presence} · {replies}',
  'support.pronoun.she': 'وهي',
  'support.pronoun.he': 'وهو',
  'support.about': 'بخصوص: {about}',
  'support.aboutAccount': 'حسابك',
  'support.aboutTrip': 'رحلة {city}',
  'support.disclosure': 'إجابات فورية من مادا. ويؤكد فيصل والفريق كل ما تحجزه.',
  'support.hiNamed': 'أهلًا {name}. {what} أمامنا الآن. كيف نخدمك؟',
  'support.hi': 'أهلًا. {what} أمامنا الآن. كيف نخدمك؟',
  'support.account': 'حسابك',
  'support.topics': 'المواضيع',
  'support.topic.change': 'تغيير حجزي',
  'support.topic.refund': 'استرداد مبلغ',
  'support.topic.bag': 'حقيبة مفقودة',
  'support.topic.docs': 'الوثائق أو التأشيرة',
  'support.topic.airport': 'مساعدة في المطار',
  'support.topic.other': 'شيء آخر',
  'support.placeholder': 'اكتب إلى مادا',
  'support.send': 'أرسل',
  'support.attach': 'أرسل صورة',
  'support.call': 'اتصل بمادا على {phone}',
  'support.whatsapp': 'راسل مادا على واتساب',
  'support.callDesk': 'اتصل بالفريق الآن',
  'support.read': 'قُرئت',
  'support.notSent': 'لم تُرسل',
  'support.sendAgain': 'أرسل مرة أخرى',
  'support.remove': 'احذف',
  'support.uploadFailed': 'لم تُرسل. تأكد من اتصالك وحاول مرة أخرى.',
  'support.typingMada': 'مادا تكتب…',
  'support.queued': 'تُرسل حين تتصل',
  'support.sending': 'تُرسل',
  'support.typingLabel': 'يكتب',
  'support.photoAlt': 'صورة أرسلتها',
  'support.pdf': 'PDF · {name}',
  'support.tooBig': 'الملف أكبر من 10 ميجابايت. أرسل صورة أصغر، أو لقطة شاشة للصفحة.',
  'support.offline.title': 'أنت غير متصل.',
  'support.offline.queued.one': 'رسالتك تُرسل لحظة عودة الاتصال.',
  'support.offline.queued.two': 'رسالتاك تُرسلان لحظة عودة الاتصال.',
  'support.offline.queued.few': 'رسائلك الـ {count} تُرسل لحظة عودة الاتصال.',
  'support.offline.queued.other': 'رسائلك الـ {count} تُرسل لحظة عودة الاتصال.',
  'support.offline.none': 'ما تكتبه الآن يُرسل لحظة عودة الاتصال.',
  'support.offline.desk': 'تحتاجنا الآن؟ الفريق يرد في أي ساعة.',
  'support.offline.call': 'اتصل بالفريق',
  'support.offline.sms': 'أرسل رسالة نصية',
  'support.offline.smsBody': 'مرحبًا فيصل، أحتاج مساعدة في رحلتي.',
  'support.rate.title': 'هل انحلّت المشكلة؟',
  'support.rate.yes': 'نعم، شكرًا',
  'support.rate.no': 'ليس بعد',
  'support.rate.yesSaid': 'نعم، شكرًا.',
  'support.rate.noSaid': 'ليس بعد.',
  'support.bag.ref': 'رقم ملصق الحقيبة أو مرجع مكتب الأمتعة',
  'support.bag.refHint': 'SV 482913 أو RUHSV12345',
  'support.bag.what': 'كيف شكلها؟',
  'support.bag.black': 'حقيبة سوداء',
  'support.bag.coloured': 'حقيبة ملوّنة',
  'support.bag.box': 'شنطة أو صندوق',
  'support.bag.to': 'سلّمها إلى',
  'support.bag.hotel': 'فندقنا',
  'support.bag.home': 'البيت',
  'support.bag.none': 'ليس لدي رقم مرجعي بعد',
  'support.bag.summary': '{ref} · {kind} · التسليم إلى {to}',
  'support.refund.sent': 'أُرسل',
  'support.refund.withFaisal': 'لدى فيصل',
  'support.refund.onWay': 'في الطريق',
  'support.refund.to': 'إلى {card}.',
  'support.refund.stage.requested': 'طلبناه من شركة الطيران. ترد عادةً خلال 3 أيام',
  'support.refund.stage.approved': 'تمت الموافقة. نرسله إلى بطاقتك',
  'support.refund.stage.sent': 'أُرسل. تحتاج البنوك حتى 5 أيام عمل لإظهاره',
  'support.refund.stage.rejected': 'فيصل يراجعه مع شركة الطيران',
  'support.reply.urgent': 'اتصل بالفريق الآن: {phone}. يرد شخص في أي ساعة، عادةً خلال دقيقة. إن أصيب أحد، اتصل بـ 997 للإسعاف في السعودية، أو 112 في الخارج.',
  'support.reply.airport': 'الاتصال أسرع في المطار. اضغط «اتصال» وتصل إلى الفريق مباشرة، في أي ساعة.',
  'support.reply.bag': 'نأسف على الحقيبة. خلّنا نلقاها. أرسل لنا رقم ملصق الحقيبة الموجود على بطاقة صعودك، أو المرجع الذي أعطاك إياه مكتب الأمتعة.',
  'support.reply.missedTrip': 'نحن عليها. نحجز لك مقاعد على رحلتين اليوم. أيهما تفضّل؟',
  'support.reply.missed': 'نحن عليها. أرسل لنا رقم الرحلة أو صورة للحجز، ونعيد حجزك على أقرب رحلة فيها مقاعد.',
  'support.reply.refundTwice': 'نرى دفعة واحدة. الخصم الثاني غالبًا تعليق مؤقت من البنك يختفي خلال 3 أيام. أرسل لنا لقطة من كشف الحساب ونراجعها اليوم.',
  'support.reply.refundTwiceRef': 'نرى دفعة واحدة للحجز {ref}. الخصم الثاني غالبًا تعليق مؤقت من البنك يختفي خلال 3 أيام. أرسل لنا لقطة من كشف الحساب ونراجعها اليوم.',
  'support.reply.refundLatest': 'هنا وصل استردادك.',
  'support.reply.refundNone': 'لا استرداد جاريًا. اختر ما تريد استرداده وترى بالضبط ما يعود لك قبل أي خطوة.',
  'support.reply.refundStart': 'ابدأ الاسترداد',
  'support.reply.refundAnother': 'ابدأ استردادًا آخر',
  'support.reply.seatNoTrip': 'بعد الحجز نجلسكم معًا. لا شيء يحتاج تغييرًا الآن.',
  'support.reply.seat': 'طلبنا من {airline} {seat}{next}، في الرحلتين. نؤكد لك هنا، ويظهر المقعد على بطاقة الصعود في محفظتك.',
  'support.reply.seatWindow': 'مقعدًا بجانب النافذة',
  'support.reply.seatAisle': 'مقعدًا على الممر',
  'support.reply.seatNext': '، بجانب {name}',
  'support.reply.change': 'ماذا تريد أن تغيّر: الرحلة، أو الفندق، أو المسافرين؟ وتقدر تعملها بنفسك ونؤكدها لك.',
  'support.reply.changeFlight': 'غيّر الرحلة',
  'support.reply.docs': 'أرسل لنا صورة الوثيقة، أو قل لنا الدولة. ونتحقق مما يحتاجه كل واحد منكم.',
  'support.reply.other': 'تفضّل. نحن هنا.',
  'support.reply.photo': 'وصلت. نراجعها ونرد هنا خلال 5 دقائق.',
  'support.reply.free': 'نراجعها ونرد هنا خلال 5 دقائق.',
  'support.reply.picked': 'نحجز لك {flight} الآن. يؤكدها فيصل مع شركة الطيران، وتصل بطاقات الصعود الجديدة إلى محفظتك.',
  'support.reply.pickedRefund': 'نُلغي حجز مقاعدك ويعود السعر كاملًا. اختر ما تريد استرداده وترى المبلغ أولًا.',
  'support.reply.bagFiled': 'شكرًا. نسجّلها لدى شركة الطيران تحت {ref} الآن. وهذا ما يحدث بعدها.',
  'support.reply.bagStep1': 'يبحثون عنها الآن. أغلب الحقائب تظهر خلال 24 ساعة.',
  'support.reply.bagStep2Hotel': 'حين يجدونها، تُسلَّم إلى فندقك مجانًا. ونخبرك هنا.',
  'support.reply.bagStep2Home': 'حين يجدونها، تُسلَّم إلى بيتك مجانًا. ونخبرك هنا.',
  'support.reply.bagStep3': 'حتى ذلك الحين، اشترِ ما تحتاجه. تعوّض شركة الطيران التكاليف المعقولة: احتفظ بالإيصالات وأرسل صورها هنا.',
  'support.reply.bagStep4': 'إن لم يجدوها خلال 21 يومًا، نطالب لك بقيمتها كاملة.',
  'support.reply.bagNone': 'لا بأس. قبل أن تغادر المطار، توجّه إلى مكتب الأمتعة في صالة الوصول وبلّغ عنها. يعطونك رقمًا مرجعيًا على نموذج. أرسل لنا صورته ونتولى الباقي.',
  'support.reply.bagNoneSaid': 'ليس لدي رقم مرجعي بعد.',
  'support.reply.leaveLater': 'استرداد بدلًا من ذلك',
  'notify.supportReply.title': 'مادا',
  'notify.supportReply.body': '{name}: {text}',
  'inbox.title': 'التحديثات',
  'inbox.markRead': 'علّم الكل كمقروء',
  'inbox.filter': 'صفّ التحديثات',
  'inbox.all': 'الكل',
  'inbox.trips': 'الرحلات',
  'inbox.money': 'المال',
  'inbox.circles': 'المجموعات',
  'inbox.empty.title': 'كل شيء هادئ.',
  'inbox.empty.money': 'المدفوعات والمبالغ المستردة ورصيد مادا تظهر هنا لحظة تحرّكها.',
  'inbox.empty.circles': 'التصويت والتقسيم والأعضاء الجدد في مجموعاتك يظهرون هنا.',
  'inbox.empty.watching': 'نراقب رحلاتك. لحظة تغيّر بوابة أو وقت أو وصول رد، يظهر هنا.',
  'inbox.empty.body': 'تغيّر البوابات وردود فيصل والمبالغ المستردة وأخبار المجموعات تظهر هنا، فلا يضيع شيء.',
  'inbox.empty.plan': 'خطّط لرحلة',
  'inbox.justNow': 'الآن',
  'inbox.minAgo': 'قبل {n} د',
  'inbox.hAgo': 'قبل {n} س',
  'inbox.unread': 'غير مقروء',
  'error.documentType': 'نوع الملف لا يصلح. استخدم صورة أو PDF.',
  'error.documentSize': 'الملف أكبر من 10 ميجابايت. جرّب صورة للصفحة بدلًا منه.',
  'error.lastMethod': 'هذه طريقتك الوحيدة للدخول. أضف طريقة أخرى قبل أن تحذف هذه.',
  'error.emailNeeded': 'أضف بريدًا في «بياناتك» أولًا، ليكون لدينا مكان نرسلها إليه.',
  'error.emailCodeWrong.one': 'الرمز غير مطابق. بقيت محاولة واحدة.',
  'error.emailCodeWrong.two': 'الرمز غير مطابق. بقيت محاولتان.',
  'error.emailCodeWrong.few': 'الرمز غير مطابق. بقيت {count} محاولات.',
  'error.emailCodeWrong.other': 'الرمز غير مطابق. بقيت {count} محاولة.',
  'error.defaultCard': 'هذه بطاقتك الافتراضية. اختر ما تستخدمه من الآن، ثم نحذفها.',
  'error.creditShort': 'رصيد مادا لا يكفي. رصيدك {amount}.',
  'error.storageMissing': 'لا يمكن حفظ الوثائق على هذا الخادم بعد. يقدر فيصل يستلمها يدويًا.',
};
