// Arabic for the agent desk in Mada Ops. The English string is the key, as in src/lib/i18n/ar.ts (merged there).
export const AR_DESK: Record<string, string> = {
  "Destination": "وجهة",
  "City guide": "دليل المدينة",
  "Nearest airports": "أقرب المطارات",
  "Plan it with Mada: the team plans and books it by hand.": "خطّطها مع مدى: يخطط الفريق الرحلة ويحجزها يدويًا.",
  "Order timeline": "مسار الطلب", "Booking": "الحجز", "Order placed": "قُدّم الطلب", "Card authorised": "فُوّضت البطاقة", "Seats held": "حُجزت المقاعد", "PNR recorded": "سُجّل رقم الحجز",
  "Fare confirmed": "تأكد السعر", "Question sent": "أُرسل سؤال", "Traveller answered": "أجاب المسافر", "New fare sent": "أُرسل سعر جديد", "Issuing": "قيد الإصدار",
  "Ticket numbers entered": "أُدخلت أرقام التذاكر", "Card captured": "خُصم المبلغ", "Card hold released": "أُلغي الحجز على البطاقة", "Ticketing failed": "تعذّر الإصدار", "Call me": "اتصل بي",
  "A lower price is good news: confirm at the price they agreed": "السعر الأقل خبر جيد: أكّد بالسعر الذي وافقوا عليه",
  // navigation and headers
  "App desk": "مكتب التطبيق",
  "App desk · 24/7": "مكتب التطبيق · على مدار الساعة",
  "Desk inbox": "صندوق المكتب",
  "Inbox": "الوارد",
  "Orders": "الطلبات المدفوعة",
  "Requests": "الطلبات",
  "Chats": "المحادثات",
  "Refunds": "الاستردادات",
  "Disruptions": "اضطرابات الرحلات",
  "Moderation": "الإشراف",
  "Team": "الفريق",
  "Team & rota": "الفريق والمناوبات",
  "Team and rota": "الفريق والمناوبات",
  "Refunds and changes": "الاستردادات والتغييرات",
  "Everything travellers are waiting on, most urgent first. Orders are confirmed within 4 minutes, chats answered within 10.": "كل ما ينتظره المسافرون، الأكثر إلحاحًا أولًا. تُؤكَّد الطلبات خلال 4 دقائق، ويُرَد على المحادثات خلال 10.",
  "Bookings from the app. Confirm and hold within 4 minutes, then issue: the card is only captured when tickets are issued.": "حجوزات من التطبيق. أكّد واحجز المقاعد خلال 4 دقائق ثم أصدر التذاكر: لا يُخصم المبلغ من البطاقة إلا عند الإصدار.",
  "Visas, Umrah, cars, tables and anything else travellers ask Mada to arrange. Quote within the promised time.": "التأشيرات والعمرة والسيارات وحجوزات المطاعم وكل ما يطلبه المسافرون من مدى. أرسل التسعيرة خلال الوقت الموعود.",
  "Travellers write to Mada. You answer as yourself, by first name. First reply within 10 minutes, any hour.": "يكتب المسافرون إلى مدى، وترد أنت باسمك الأول. أول رد خلال 10 دقائق، في أي ساعة.",
  "Approve to the card it came from or to Mada credit, which is instant. A declined refund shows the traveller your reason.": "اعتمد الاسترداد إلى البطاقة الأصلية أو إلى رصيد مدى الفوري. عند الرفض يرى المسافر سببك.",
  "Today's flights with Mada travellers on board. Status from the airline feed, positions from open ADS-B. Travellers on a disrupted flight hear the plan within 10 minutes.": "رحلات اليوم التي على متنها مسافرو مدى. الحالة من شركة الطيران، والمواقع من بيانات ADS-B المفتوحة. يصل المسافرين على رحلة متأثرة الخطةُ خلال 10 دقائق.",
  "Tips travellers share in Circles, and what people report. Decide with a reason; the author reads it.": "النصائح التي يشاركها المسافرون في الدوائر، والبلاغات. قرّر مع ذكر السبب؛ صاحب المنشور يقرؤه.",
  "The people travellers talk to. Each traveller has their own agent; when that agent is off, whoever covers for them answers, then the shared queue.": "الأشخاص الذين يتحدث إليهم المسافرون. لكل مسافر موظفه الخاص؛ وعند غيابه يرد من يغطي عنه، ثم الطابور المشترك.",

  // status pill and presence
  "You're {name} to travellers": "أنت {name} عند المسافرين",
  "On shift": "في المناوبة",
  "Not on shift": "خارج المناوبة",
  "Off shift": "خارج المناوبة",
  "Online": "متصل",
  "Away": "بعيد",
  "Off": "خارج",
  "Signed off": "أنهى المناوبة",
  "You": "أنت",
  "On the desk now": "على المكتب الآن",
  "Rota": "المناوبات",
  "Covering for {names}": "يغطي عن {names}",
  "Covering for {name}": "يغطي عن {name}",
  "covering for {name}": "يغطي عن {name}",
  "Nobody is on shift. Travellers see “Replies within 10 minutes, any hour”.": "لا أحد في المناوبة. يرى المسافرون «الرد خلال 10 دقائق، في أي ساعة».",
  "{n} past their promised time": "{n} تجاوزت الوقت الموعود",
  "See escalations": "عرض التصعيدات",
  "Traveller sees": "يرى المسافر",
  "What the traveller sees under Mada": "ما يراه المسافر تحت اسم مدى",

  // inbox
  "Waiting on the desk": "بانتظار المكتب",
  "Late": "متأخر",
  "Mine": "لي",
  "Unassigned": "دون إسناد",
  "Whole team": "كل الفريق",
  "Escalations": "التصعيدات",
  "Shortcuts": "الاختصارات",
  "Keyboard shortcuts": "اختصارات لوحة المفاتيح",
  "Next / previous": "التالي / السابق",
  "Open": "المفتوحة",
  "Open it": "افتحه",
  "Take it": "استلمه",
  "Mine · Team · Unassigned · Escalated": "لي · الفريق · دون إسناد · مصعّد",
  "Show or hide this": "إظهار أو إخفاء هذه القائمة",
  "Close": "إغلاق",
  "Escalated": "مصعّد",
  "Shared queue": "الطابور المشترك",
  "Covering": "يغطي",
  "Assigned": "مُسند",
  "Their agent": "موظفه",
  "Nothing waiting on you": "لا شيء بانتظارك",
  "Nothing here": "لا شيء هنا",
  "New work for your travellers lands here first.": "أي عمل جديد لمسافريك يصل هنا أولًا.",
  "When travellers need the desk, it shows up here.": "عندما يحتاج المسافرون المكتب يظهر هنا.",
  "Order": "طلب حجز",
  "Ticketing": "الإصدار",
  "Chat": "محادثة",
  "Request": "طلب",
  "Refund": "استرداد",
  "Disruption": "اضطراب",
  "Confirm the order": "أكّد الطلب",
  "Issue tickets": "أصدر التذاكر",
  "Payment capture didn't go through": "لم يكتمل خصم المبلغ",
  "Needs a quote": "يحتاج تسعيرة",
  "Paid, finish it": "مدفوع، أكمله",
  "Waiting for a reply": "بانتظار الرد",
  "Refund to decide": "استرداد بانتظار القرار",
  "Delayed": "متأخرة",
  "Cancelled": "ملغاة",
  "Diverted": "محوّلة",
  "Tip to review": "نصيحة للمراجعة",
  "Unsafe report": "بلاغ عن خطر",
  "Report to review": "بلاغ للمراجعة",
  "Photo": "صورة",
  "Support": "الدعم",

  // SLA
  "Due": "مستحق",
  "{m} min": "{m} د",
  "{h}h": "{h} س",
  "{h}h {m}m": "{h} س {m} د",
  "{span} late": "متأخر {span}",
  "{span} left": "متبقٍّ {span}",
  "Answered in time": "رُدّ في الوقت",
  "Answered late": "رُدّ متأخرًا",
  "Promise": "الوعد",

  // statuses
  "Waiting to confirm": "بانتظار التأكيد",
  "Held · issue tickets": "محجوز · أصدر التذاكر",
  "Waiting on traveller": "بانتظار المسافر",
  "New price sent": "أُرسل سعر جديد",
  "Issued": "صادر",
  "Not issued": "لم يصدر",
  "In progress": "قيد التنفيذ",
  "Queued": "في الانتظار",
  "New": "جديد",
  "Reviewing": "قيد المراجعة",
  "Quote sent": "أُرسلت التسعيرة",
  "Waiting for payment": "بانتظار الدفع",
  "Paid · with us": "مدفوع · لدينا",
  "Confirmed": "مؤكد",
  "Done": "تم",
  "Started": "بدأ",
  "Bank check pending": "بانتظار تحقق البنك",
  "Authorised · not captured": "مفوَّض · لم يُخصم",
  "Captured": "تم الخصم",
  "Hold released": "أُلغي الحجز على البطاقة",
  "Declined": "مرفوض",
  "Capture didn't go through": "لم يكتمل الخصم",
  "Refunded": "مسترد",
  "Partly refunded": "مسترد جزئيًا",

  // orders
  "To confirm": "للتأكيد",
  "To issue": "للإصدار",
  "All": "الكل",
  "No orders here": "لا طلبات هنا",
  "Orders from the app appear the moment a traveller slides to book.": "تظهر الطلبات هنا لحظة سحب المسافر لتأكيد الحجز.",
  "Traveller": "المسافر",
  "Card": "البطاقة",
  "Total": "الإجمالي",
  "Named agent: {name}": "الموظف المسمّى: {name}",
  "Trip": "الرحلة",
  "Return": "العودة",
  "Outbound": "الذهاب",
  "Economy": "سياحية",
  "Business": "أعمال",
  "First": "أولى",
  "No flight details on this order": "لا توجد تفاصيل رحلة في هذا الطلب",
  "Travellers": "المسافرون",
  "Full passport numbers open for 30 seconds, and every look is logged.": "يظهر رقم الجواز كاملًا لمدة 30 ثانية، وكل اطلاع يُسجَّل.",
  "Passport numbers are masked. Issuing rights show them in full.": "أرقام الجوازات مخفية جزئيًا. صلاحية الإصدار تظهرها كاملة.",
  "Name": "الاسم",
  "Born": "تاريخ الميلاد",
  "Nationality": "الجنسية",
  "Passport": "الجواز",
  "Expires": "ينتهي",
  "Account holder": "صاحب الحساب",
  "Spouse": "الزوج/الزوجة",
  "Child": "ابن/ابنة",
  "Helper": "عاملة منزلية",
  "Sibling": "أخ/أخت",
  "Parent": "أحد الوالدين",
  "Missing": "غير موجود",
  "under 6 months": "أقل من 6 أشهر",
  "No travellers on this order": "لا مسافرين في هذا الطلب",
  "Show full number": "إظهار الرقم كاملًا",
  "Show full number (logged)": "إظهار الرقم كاملًا (يُسجَّل)",
  "Hide": "إخفاء",
  "Price and payment": "السعر والدفع",
  "{n} payments": "{n} دفعات",
  "All-in total": "الإجمالي الشامل",
  "New price sent: SAR {from} → SAR {to}": "أُرسل سعر جديد: {from} ر.س ← {to} ر.س",
  "Instalments: captured in full from the provider when tickets are issued. Releasing the hold cancels the plan.": "الدفع بالتقسيط: يُحصَّل كاملًا من مزود الخدمة عند إصدار التذاكر، وإلغاء الحجز يلغي الخطة.",
  "Conversation": "المحادثة",
  "What the traveller sees in the order's thread. Notes stay with the team.": "ما يراه المسافر في محادثة الطلب. الملاحظات تبقى للفريق.",
  "Confirmed by {name} at Mada": "أكّده {name} في مدى",
  "Ticket": "تذكرة",
  "Not issued · card hold released": "لم يصدر · أُلغي الحجز على البطاقة",
  "Waiting on the traveller": "بانتظار المسافر",
  "Asked {ago}": "سُئل {ago}",
  "Next step": "الخطوة التالية",
  "Check names against passports, then hold the seats.": "طابق الأسماء مع الجوازات ثم احجز المقاعد.",
  "Seats are held. Issue to capture the card.": "المقاعد محجوزة. أصدر التذاكر ليُخصم المبلغ.",
  "Waiting on the traveller. You can still act.": "بانتظار المسافر، ويمكنك المتابعة.",
  "PNR from the GDS (optional)": "رقم الحجز PNR من النظام (اختياري)",
  "Confirm and hold": "أكّد واحجز المقاعد",
  "PNR": "رقم الحجز PNR",
  "Ticket for {name}": "تذكرة {name}",
  "Issue and capture SAR {amount}?": "إصدار التذاكر وخصم {amount} ر.س؟",
  "Issue tickets and capture": "أصدر التذاكر واخصم المبلغ",
  "Issuing needs the desk issuing right. Hold the seats and hand it to someone who has it.": "الإصدار يحتاج صلاحية الإصدار في المكتب. احجز المقاعد وسلّم الطلب لمن يملكها.",
  "Ask the traveller": "اسأل المسافر",
  "Is the name on Ahmed's ticket AHMED ALHARBI, as on his passport?": "هل الاسم على تذكرة أحمد AHMED ALHARBI كما في جوازه؟",
  "Yes": "نعم",
  "No": "لا",
  "Answer {n}": "إجابة {n}",
  "Answer 1": "إجابة 1",
  "Answer 2": "إجابة 2",
  "Another answer": "إجابة أخرى",
  "It appears on their waiting screen with these one-tap answers.": "يظهر السؤال على شاشة الانتظار مع هذه الإجابات بلمسة واحدة.",
  "Send the question": "أرسل السؤال",
  "Price changed": "تغيّر السعر",
  "New all-in total (SAR)": "الإجمالي الشامل الجديد (ر.س)",
  "Why, for the team (optional)": "السبب، للفريق (اختياري)",
  "The current card hold is released. The traveller takes the new price or picks again.": "يُلغى الحجز الحالي على البطاقة، ويقبل المسافر السعر الجديد أو يختار من جديد.",
  "Send the new price": "أرسل السعر الجديد",
  "What happened, for the team": "ما الذي حدث، للفريق",
  "Releases the card hold and tells the traveller nothing was charged.": "يلغي الحجز على البطاقة ويبلغ المسافر بأنه لم يُخصم شيء.",
  "Release the card hold and close this order?": "إلغاء الحجز على البطاقة وإغلاق هذا الطلب؟",
  "Release the hold and close": "ألغِ الحجز وأغلق الطلب",
  "Card hold": "الحجز على البطاقة",
  "Method": "طريقة الدفع",
  "Amount": "المبلغ",
  "Status": "الحالة",
  "Provider ref": "مرجع مزود الدفع",
  "Authorised": "تاريخ التفويض",
  "Desk log": "سجل المكتب",
  "{n} entries": "{n} إدخالات",
  "Nothing yet": "لا شيء بعد",
  "System": "النظام",

  // assign
  "Who has it": "من يتولاه",
  "{name} is this traveller's agent": "{name} هو موظف هذا المسافر",
  "No agent chosen for this traveller yet": "لم يُحدَّد موظف لهذا المسافر بعد",
  "Their agent, on shift": "موظفه، في المناوبة",
  "Covering tonight": "يغطي الليلة",
  "Assigned by hand": "أُسند يدويًا",
  "First free hand takes it": "يستلمه أول موظف متاح",
  "Give it to": "سلّمه إلى",
  "Follow the rota": "حسب المناوبات",
  "Hand on": "سلّم",
  "Clear escalation": "إلغاء التصعيد",
  "What's needed?": "ما المطلوب؟",
  "Escalate": "صعّد",

  // requests
  "Closed": "مغلق",
  "No requests here": "لا طلبات هنا",
  "Requests sent from the app land here with what the traveller asked for.": "تصل هنا الطلبات المرسلة من التطبيق مع ما طلبه المسافر.",
  "Type": "النوع",
  "Agent": "الموظف",
  "Visa": "تأشيرة",
  "Umrah": "عمرة",
  "Car": "سيارة",
  "Restaurant": "مطعم",
  "Things to do": "أنشطة",
  "Change": "تغيير",
  "Cancel": "إلغاء",
  "General": "عام",
  "What they asked for": "ما طلبه المسافر",
  "Every traveller needs their own Nusuk permit.": "يحتاج كل مسافر تصريح نسك خاصًا به.",
  "Replies go out in your agent name. Notes stay with the team.": "تُرسل الردود باسمك كموظف. الملاحظات تبقى للفريق.",
  "held until {time}": "محجوز حتى {time}",
  "Accepted": "مقبول",
  "Expired": "منتهي",
  "Send a new quote": "أرسل تسعيرة جديدة",
  "Build the quote": "جهّز التسعيرة",
  "A line for each person, so everyone sees their share.": "سطر لكل شخص، ليرى كلٌّ حصته.",
  "Umrah checklist": "قائمة متطلبات العمرة",
  "Visa checklist": "قائمة متطلبات التأشيرة",
  "Checklist": "قائمة المتطلبات",
  "{done} of {n} ready": "{done} من {n} جاهز",
  "Add an item": "أضف عنصرًا",
  "Save": "حفظ",
  "Ask or finish": "اسأل أو أنهِ",
  "Which date suits you for the VFS appointment?": "أي موعد يناسبك لمقابلة VFS؟",
  "Mark this request done? The traveller is told.": "تحديد الطلب كمكتمل؟ سيُبلَّغ المسافر.",
  "Mark done": "تحديده كمكتمل",
  "Umrah package": "باقة عمرة",
  "Service": "خدمة",
  "What it's for": "البند",
  "Line": "السطر",
  "Amount (SAR)": "المبلغ (ر.س)",
  "Remove": "إزالة",
  "Add a line": "أضف سطرًا",
  "Cancellation rule the traveller sees": "سياسة الإلغاء التي يراها المسافر",
  "Price held for": "مدة تثبيت السعر",
  "No hold": "دون تثبيت",
  "Hold 2 hours": "تثبيت ساعتين",
  "Hold 24 hours": "تثبيت 24 ساعة",
  "Hold 3 days": "تثبيت 3 أيام",
  "Send the quote": "أرسل التسعيرة",
  "Flight": "طيران",
  "Stay": "إقامة",
  "Pickup": "توصيل",
  "Discount": "خصم",
  "Other": "أخرى",
  "Passport valid 6 months past return": "جواز صالح 6 أشهر بعد العودة",
  "Passport photo, white background": "صورة شخصية بخلفية بيضاء",
  "Bank statement, last 3 months": "كشف حساب بنكي لآخر 3 أشهر",
  "Employment letter or iqama": "خطاب تعريف بالراتب أو الإقامة",
  "Flight and hotel booking": "حجز الطيران والفندق",
  "Travel insurance": "تأمين السفر",
  "Nusuk permit for each traveller": "تصريح نسك لكل مسافر",
  "Passport valid 6 months": "جواز صالح 6 أشهر",
  "Meningitis vaccination certificate": "شهادة تطعيم الحمى الشوكية",
  "Hotel in Makkah booked": "حجز فندق في مكة",
  "Transport Jeddah to Makkah": "النقل من جدة إلى مكة",
  "Ihram for each man": "إحرام لكل رجل",

  // chat
  "Waiting": "بانتظار الرد",
  "No conversations": "لا محادثات",
  "When a traveller writes to Mada, it shows up here.": "عندما يكتب مسافر إلى مدى تظهر المحادثة هنا.",
  "Back": "رجوع",
  "Support chat": "محادثة الدعم",
  "Choose a conversation": "اختر محادثة",
  "Waiting travellers are at the top of the list.": "المسافرون المنتظرون في أعلى القائمة.",
  "Reply as {name}": "رد باسم {name}",
  "Note for the team": "ملاحظة للفريق",
  "Saved replies": "الردود المحفوظة",
  "Only the team sees this": "لا يراها إلا الفريق",
  "Write to the traveller…": "اكتب للمسافر…",
  "Attach": "إرفاق",
  "Add note": "أضف ملاحظة",
  "Send": "إرسال",
  "as {name}": "باسم {name}",
  "Nothing in this thread yet": "لا شيء في هذه المحادثة بعد",

  // refunds
  "To decide": "بانتظار القرار",
  "Approved · on its way": "معتمد · في الطريق",
  "Sent": "أُرسل",
  "No refunds waiting": "لا استردادات بانتظار القرار",
  "Cancellations and refund requests from the app show up here.": "تظهر هنا الإلغاءات وطلبات الاسترداد من التطبيق.",
  "Open the order": "افتح الطلب",
  "Paid with": "طريقة الدفع",
  "Paid": "المدفوع",
  "Reason given": "السبب المذكور",
  "Paid with {provider}. Refunding to the card cancels the remaining payments with {provider}, and what was paid goes back to their card. Mada credit is instant instead.": "مدفوع عبر {provider}. الاسترداد إلى البطاقة يلغي الدفعات المتبقية مع {provider}، ويعود المدفوع إلى بطاقة المسافر. رصيد مدى فوري بدلًا من ذلك.",
  "Traveller reads:": "يقرأ المسافر:",
  "To Mada credit": "إلى رصيد مدى",
  "To {card}": "إلى {card}",
  "the card": "البطاقة",
  "expected by {date}": "متوقع بحلول {date}",
  "Mada credit": "رصيد مدى",
  "Approve refund": "اعتمد الاسترداد",
  "Why not, in words the traveller will read": "لماذا لا، بكلمات سيقرؤها المسافر",
  "Decline with reason": "ارفض مع ذكر السبب",
  "Refund decisions need the desk refund right.": "قرارات الاسترداد تحتاج صلاحية الاسترداد في المكتب.",

  // disruptions
  "Flights today": "رحلات اليوم",
  "Travellers flying": "مسافرون في الجو اليوم",
  "Disrupted": "متأثرة",
  "In the air now": "في الجو الآن",
  "No Mada travellers fly today": "لا مسافرين من مدى اليوم",
  "Flights on booked trips appear here on the day.": "تظهر رحلات الحجوزات المؤكدة هنا في يومها.",
  "Scheduled": "مجدولة",
  "On time": "في الموعد",
  "Boarding": "صعود الطائرة",
  "Departed": "أقلعت",
  "In the air": "في الجو",
  "Landed": "هبطت",
  "Plan sent {ago}": "أُرسلت الخطة {ago}",
  "Gate {gate}": "البوابة {gate}",
  "{n} travellers on board": "{n} مسافرين على متنها",
  "Sent by {name}": "أرسلها {name}",
  "SAR {amount} credit each": "رصيد {amount} ر.س لكل حساب",
  "Send an update": "أرسل تحديثًا",
  "Send the rebooking plan": "أرسل خطة إعادة الحجز",
  "We've moved you to XY205 at 21:15. Same seats, and your pickup moves with you.": "نقلناك إلى XY205 الساعة 21:15. المقاعد نفسها، والتوصيل ينتقل معك.",
  "Your connection still works. We're holding the 21:15 in case it doesn't.": "رحلتك المتصلة ما زالت ممكنة، ونحجز لك رحلة 21:15 احتياطًا.",
  "Option {n}": "الخيار {n}",
  "What it means for them": "ماذا يعني لهم",
  "Voucher per account, as Mada credit (SAR, optional)": "قسيمة لكل حساب كرصيد مدى (ر.س، اختياري)",
  "Send to {n} accounts": "أرسل إلى {n} حسابات",
  "Send to 1 account": "أرسل إلى حساب واحد",
  "1 traveller on board": "مسافر واحد على متنها",
  "1 traveller": "مسافر واحد",
  "Altitude": "الارتفاع",
  "Speed": "السرعة",
  "Seen": "آخر رصد",
  "Not flying": "لن تطير",
  "Not in the air": "ليست في الجو",

  // moderation
  "To review": "للمراجعة",
  "Decided": "تم البت",
  "Blocked accounts": "الحسابات المحظورة",
  "No blocked accounts": "لا حسابات محظورة",
  "by {name}": "بواسطة {name}",
  "Lift this block?": "رفع هذا الحظر؟",
  "Lift block": "رفع الحظر",
  "Nothing to review": "لا شيء للمراجعة",
  "Nothing decided yet": "لم يُبت في شيء بعد",
  "New tips and reports from the app land here.": "تصل هنا النصائح والبلاغات الجديدة من التطبيق.",
  "Tip": "نصيحة",
  "Report": "بلاغ",
  "Unwanted contact": "تواصل غير مرغوب",
  "Pretending to be someone": "انتحال شخصية",
  "Unsafe": "خطر",
  "Something else": "أمر آخر",
  "Approved": "معتمد",
  "Rejected": "مرفوض",
  "Removed": "محذوف",
  "Dismissed": "مُغلق",
  "No text": "بلا نص",
  "Blocked": "محظور",
  "reported by {name}": "أبلغ عنه {name}",
  "Reason": "السبب",
  "Reason, if you reject it": "السبب، إن رفضتها",
  "Reason, if you remove it": "السبب، إن حذفته",
  "Approve": "اعتمد",
  "Reject": "ارفض",
  "Remove it": "احذفه",
  "Dismiss report": "أغلق البلاغ",
  "Also block {name}": "واحظر {name} أيضًا",
  "Moderation needs the desk moderation right.": "الإشراف يحتاج صلاحية الإشراف في المكتب.",

  // team
  "Agents": "الموظفون",
  "Travellers see the first name and photo, never the Ops account.": "يرى المسافرون الاسم الأول والصورة فقط، لا حساب العمليات.",
  "No agents yet": "لا موظفين بعد",
  "Add someone from the team below.": "أضف أحد أعضاء الفريق من الأسفل.",
  "Inactive": "غير نشط",
  "Active": "نشط",
  "{n} travellers": "{n} مسافرين",
  "Edit profile": "تعديل الملف",
  "Add someone to the desk": "أضف شخصًا إلى المكتب",
  "Times are Riyadh time. A shift can cover for someone: their travellers come to you while they're off.": "الأوقات بتوقيت الرياض. يمكن أن تغطي المناوبة عن زميل: يصلك مسافروه أثناء غيابه.",
  "Nothing on the rota for the next 7 days.": "لا مناوبات خلال الأيام السبعة القادمة.",
  "Now": "الآن",
  "Take this shift off the rota?": "حذف هذه المناوبة من الجدول؟",
  "Who": "من",
  "Covering for": "يغطي عن",
  "Nobody": "لا أحد",
  "Starts": "تبدأ",
  "Ends": "تنتهي",
  "Note (optional): night desk, Pakistan": "ملاحظة (اختياري): المكتب الليلي، باكستان",
  "Add to the rota": "أضف إلى المناوبات",
  "Travellers and their agent": "المسافرون وموظفوهم",
  "“Faisal, your Mada agent”. Changing it changes who they see.": "«فيصل، موظفك في مدى». تغييره يغيّر من يراه المسافر.",
  "Search name or phone…": "ابحث بالاسم أو الجوال…",
  "No travellers found": "لا مسافرين",
  "No name yet": "بلا اسم بعد",
  "No agent": "بلا موظف",
  "Choose an agent": "اختر موظفًا",
  "In both languages; the reply box picks the one for your screen.": "باللغتين؛ يختار مربع الرد لغة شاشتك.",
  "None yet": "لا شيء بعد",
  "Title, e.g. Bag tag photo": "العنوان، مثل: صورة ملصق الشنطة",
  "English": "الإنجليزية",
  "Arabic": "العربية",
  "Add saved reply": "أضف ردًا محفوظًا",
  "Team member": "عضو الفريق",
  "First name travellers see": "الاسم الأول الذي يراه المسافرون",
  "In Arabic": "بالعربية",
  "Languages": "اللغات",
  "Says": "العبارة",
  "He has your whole trip": "رحلتك كاملة عنده",
  "She has your whole trip": "رحلتك كاملة عندها",
  "Usual reply time (min)": "وقت الرد المعتاد (دقيقة)",
  "On the desk": "على المكتب",

  // results and refusals
  "You're online": "أنت متصل",
  "You're away": "أنت بعيد",
  "You're signed off": "أنهيت المناوبة",
  "Saved": "تم الحفظ",
  "Shift added": "أُضيفت المناوبة",
  "Reassigned": "أُعيد الإسناد",
  "Back on the rota": "عاد حسب المناوبات",
  "Escalation cleared": "أُلغي التصعيد",
  "Held. Tickets next": "تم الحجز. التذاكر التالية",
  "Sent to the traveller": "أُرسل إلى المسافر",
  "Issued. The traveller has their tickets": "صدرت التذاكر وهي لدى المسافر",
  "Card hold released. The traveller was told": "أُلغي الحجز على البطاقة وأُبلغ المسافر",
  "Checklist saved": "حُفظت القائمة",
  "Marked done": "تم التحديد كمكتمل",
  "Note added": "أُضيفت الملاحظة",
  "Saved reply added": "أُضيف الرد المحفوظ",
  "Refund approved": "اعتُمد الاسترداد",
  "Refund declined. The traveller sees why": "رُفض الاسترداد، ويرى المسافر السبب",
  "Plan sent to the travellers": "أُرسلت الخطة إلى المسافرين",
  "Tip approved": "اعتُمدت النصيحة",
  "Report dismissed": "أُغلق البلاغ",
  "Account blocked": "حُظر الحساب",
  "The payment capture didn't go through. The order is under ticketing problems: try again or mark it not issued.": "لم يكتمل خصم المبلغ. الطلب الآن ضمن مشكلات الإصدار: حاول مجددًا أو حدّده كغير صادر.",
  "You don't have access to do that on the desk": "لا تملك صلاحية هذا الإجراء في المكتب",
  "Not found": "غير موجود",
  "Check the amount": "تحقق من المبلغ",
  "Check each line's amount": "تحقق من مبلغ كل سطر",
  "Choose a start and end time": "اختر وقت البداية والنهاية",
  "A PNR is 5 to 8 letters and numbers": "رقم الحجز PNR من 5 إلى 8 أحرف وأرقام",
  "Ticket numbers are 13 digits": "رقم التذكرة 13 خانة",
  "The same ticket number appears twice": "رقم التذكرة نفسه مكرر",
  "There's no card hold on this order to capture": "لا يوجد حجز على البطاقة في هذا الطلب للخصم",
  "This order isn't ready to issue": "هذا الطلب غير جاهز للإصدار",
  "Someone else just changed this order": "عدّل شخص آخر هذا الطلب للتو",
  "This order isn't waiting for confirmation": "هذا الطلب لا ينتظر التأكيد",
  "Already held": "محجوز مسبقًا",
  "Write the question in 5 to 300 characters": "اكتب السؤال في 5 إلى 300 حرف",
  "Keep each answer under 40 characters": "اجعل كل إجابة أقل من 40 حرفًا",
  "This one is already closed": "هذا مغلق بالفعل",
  "Enter the new total": "أدخل الإجمالي الجديد",
  "That's the same price": "هذا هو السعر نفسه",
  "This order can't be repriced now": "لا يمكن تغيير سعر هذا الطلب الآن",
  "Say what happened, for the team": "اذكر ما حدث، للفريق",
  "This order is already closed": "هذا الطلب مغلق بالفعل",
  "Add at least one line": "أضف سطرًا واحدًا على الأقل",
  "Keep a quote to 20 lines": "لا تتجاوز 20 سطرًا في التسعيرة",
  "Check each line's name and amount": "تحقق من اسم ومبلغ كل سطر",
  "The total must be more than zero": "يجب أن يكون الإجمالي أكبر من صفر",
  "This request is already closed": "هذا الطلب مغلق بالفعل",
  "Already closed": "مغلق بالفعل",
  "Write a reply first": "اكتب الرد أولًا",
  "Keep a reply under 4,000 characters": "اجعل الرد أقل من 4,000 حرف",
  "Conversation not found": "المحادثة غير موجودة",
  "Write the note first": "اكتب الملاحظة أولًا",
  "Keep notes under 2,000 characters": "اجعل الملاحظات أقل من 2,000 حرف",
  "Refund not found": "الاسترداد غير موجود",
  "This refund has already been decided": "تم البت في هذا الاسترداد مسبقًا",
  "The card refund didn't go through. Try again, or refund to Mada credit": "لم يكتمل الاسترداد إلى البطاقة. حاول مجددًا أو استرد إلى رصيد مدى",
  "Give the traveller a clear reason, 10 to 300 characters": "اذكر للمسافر سببًا واضحًا، من 10 إلى 300 حرف",
  "Enter an amount": "أدخل مبلغًا",
  "Say why, so the author understands": "اذكر السبب ليفهمه صاحب المنشور",
  "Already decided": "تم البت مسبقًا",
  "Approve or reject a tip": "اعتمد النصيحة أو ارفضها",
  "Remove the content or dismiss the report": "احذف المحتوى أو أغلق البلاغ",
  "Say why the account is blocked": "اذكر سبب حظر الحساب",
  "Traveller not found": "المسافر غير موجود",
  "Already blocked": "محظور مسبقًا",
  "Not blocked": "غير محظور",
  "Write the plan in 10 to 400 characters": "اكتب الخطة في 10 إلى 400 حرف",
  "Unknown flight": "رحلة غير معروفة",
  "Vouchers are up to SAR 5,000": "القسيمة حتى 5,000 ر.س",
  "Nobody from Mada is on that flight": "لا أحد من مسافري مدى على هذه الرحلة",
  "Unknown item": "عنصر غير معروف",
  "Choose someone on the desk": "اختر شخصًا من المكتب",
  "Say what's needed, for whoever picks it up": "اذكر المطلوب لمن سيستلمه",
  "Agent not found": "الموظف غير موجود",
  "Use a first name between 2 and 30 letters": "استخدم اسمًا أول من 2 إلى 30 حرفًا",
  "Reply time is between 1 and 30 minutes": "وقت الرد بين 1 و30 دقيقة",
  "Choose at least one language": "اختر لغة واحدة على الأقل",
  "Team member not found": "عضو الفريق غير موجود",
  "A shift ends after it starts": "تنتهي المناوبة بعد بدايتها",
  "Keep a shift to 16 hours or less": "لا تتجاوز المناوبة 16 ساعة",
  "Someone can't cover for themselves": "لا يمكن للشخص أن يغطي عن نفسه",
  "That overlaps another shift for the same person": "تتداخل مع مناوبة أخرى للشخص نفسه",
  "Shift not found": "المناوبة غير موجودة",
  "Traveller or agent not found": "المسافر أو الموظف غير موجود",
  "Request not found": "الطلب غير موجود",
  "Order not found": "الطلب غير موجود",
  "Only orders can be held": "يمكن حجز طلبات الحجز فقط",
  "Only orders have a fare to change": "تغيير السعر لطلبات الحجز فقط",
  "Only orders have tickets": "التذاكر لطلبات الحجز فقط",
  "Only orders are ticketed": "الإصدار لطلبات الحجز فقط",
  "No passport on file": "لا يوجد جواز محفوظ",
  "That traveller isn't on this order": "هذا المسافر ليس في هذا الطلب",
  "Fill in the title and both languages": "املأ العنوان واللغتين",
  "Files must be under 6 MB": "يجب أن يكون الملف أقل من 6 ميجابايت",
  "Upload a PDF or an image": "ارفع ملف PDF أو صورة",
  "Something went wrong. Please try again.": "حدث خطأ. حاول مرة أخرى.",
};
